### ISSUE TITLE
Generate swagger (or similar) docs for the flux API

### ISSUE THREAD

**Issue by aaron7** [fluxcd/flux#1069]

**Comment by kingdonb** [comment]
I am completely ignorant about k8s apimachinery and swagger docs generation in Go.

Is this something that has already been handled in Flux v2?

If it would be nice-to-have then it will not be likely to make the cut for Flux v1 unfortunately, as maintenance mode means we will fix bugs and make security releases with priority, unless someone external to the FluxCD team was to contribute this, it is unlikely that any additional API documentation machinery would be added to Flux v1.

Closing for now, but as more docs are always nice, if anyone wanted to spearhead this effort it could certainly be reopened.
