### ISSUE TITLE
Automate consolidation of ConfigMap content

### ISSUE THREAD

**Issue by 2opremio** [fluxcd/flux#1083]
In order to create a k8s ConfigMap you need to provide the ConfigMap sources (a file or directory).

Currently, the creation and modification of ConfigMaps in flux is a manual process (it's the user's responsibility to maintain it).

However, flux could automate this process. Users could keep the sources of the ConfigMap in git as well and provide a way for flux to know the mapping of ConfigMaps and their content. Some options are:

 * An annotation in the config map with a path pointing to the content which should be part of the config map
 * A filenaming convention (e.g. a configmap in file `foo.yaml` should use the content from subdirectory `foo`)

In that way flux could update the ConfigMap as soon as it sees a change in the config map content without any user intervention.

**Comment by squaremo** [comment]
One knot here is that you can only `kubectl create` a configmap from a directory of content files, you can't `kubectl apply` one. So we'd probably have to assemble the configmap from the files ourselves, rather than delegating that to `kubectl`, which would be preferable.

**Comment by squaremo** [comment]
Might be useful to combine this with the pattern of having configmaps named for the commit hash, and updating their dependents to refer to the new commit (while avoiding cycles!).

**Comment by squaremo** [comment]
Side note: kustomize does something very like this https://github.com/kubernetes-sigs/kustomize/tree/master/examples/springboot#customize-configmap

**Comment by pdeveltere** [comment]
I think it would be great to maintain configmaps though flux. Something like:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo
  annotations:
    flux.weave.works/automated: "true"
data:
  ...
```

**Comment by demisx** [comment]
What's the recommended approach in the meantime? Currently, flux updates the configmap in a cluster with the latest in git, but the pods are still using the old values. Do I need to introduce [this configHash value](flux-86bd9fbbcb-drvvs) or will flux support this feature soon?

**Comment by kingdonb** [comment]
I think this is something that is available in Flux 2, via kyaml annotations you can update a string in a configmap using an image with tag or tag version only. You can also use kustomization substitution or patching to incorporate different types of values from an environment setting.
