### ISSUE TITLE
Return helpful errors from job status API

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1096]
We return helpful error messages when a release fails; but, because job status is serialised, the errors get squashed down to a string, losing the helpfulness.

For example, if a release runs into one of the ruamel bugs (using use-kubeyaml branch):

```
Error: loading resources after updates: parsing file at "/tmp/flux-working126624999/repo/config/helloworld/helloworld-deploy.yaml": parsing YAML doc from "config/helloworld/hel
loworld-deploy.yaml": yaml: line 19: mapping values are not allowed in this context
```

With the loss of context, this ends up being more mysterious than helpful.

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

Closing, as this was marked as an enhancement.
