### ISSUE TITLE
Spurious versioned image pushed for helm-operator

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1108]
We accidentally ended up with a helm-operator:1.3.1 image being pushed to that repo. The tag 1.3.1 is only supposed to apply to the flux image.

The cause was that I re-ran a master branch build; and since, in the meantime, the HEAD of master had been tagged, it assumed it should use the git tag for the image tag. This hasn't happened before, by coincidence, because we haven't re-run a build that's been git tagged in this way.

The solution is to make sure we only push master-* images when we're running the master build. We could adapt the `docker-tag` script so that it _only_ constructed tags of that kind, for example.

**Comment by stefanprodan** [comment]
Fixed by helm-op repo/CI split
