### ISSUE TITLE
Include known_hosts in secret to make it a bit easier to mount into container

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1113]
Either as the standard way of deploying it, or as an alternative means of overriding known_hosts (as in #724).

**Comment by squaremo** [comment]
Maybe a docker-config too? (e.g., as generated from sidecars, like the workaround posted in #539)

NB one thing to keep in mind: if you mount a secret or configmap using subPath, the files won't get updated when the resources do.

**Comment by hiddeco** [comment]
> NB one thing to keep in mind: if you mount a secret or configmap using subPath, the files won't get updated when the resources do.

You can get around this by specifying [`.configMap.items` in combination with a `mountPath`](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-specific-path-in-the-volume) as [mounted ConfigMaps are updated automatically](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically).

The downside of this approach is that it overwrites all the original data in the `mountPath` (if any).

You can however get around this (again) by creating a symlink to your `mountPath` (e.g. `/home/flux/.ssh/known_hosts` -> `/home/flux/config/known_hosts`).

**Comment by supra08** [comment]
@2opremio I would like to work on this issue.
