### ISSUE TITLE
"git repo not ready" error message not exactly useful

### ISSUE THREAD

**Issue by dholbach** [fluxcd/flux#1116]
Upon setting up Flux I mistyped the git repo URL (`github` instead of `github.com`) and read "git repo not ready" over and over again in the log. The error message in question is [declared here](https://github.com/weaveworks/flux/blob/8c0f7946d538a6cbdbcabc32773c478dd6e5d223/git/repo.go#L28).

My first hunch was that the deploy key was wrong or not set up - that's how I understood "ready". Maybe we could change the error message to `can't connect to git repo %s.` or some such? It'd be good to spell out exactly which git repo we're trying to connect with, so you get another chance to see your mistake in the logs.

**Comment by 2opremio** [comment]
Related #2657
