### ISSUE TITLE
Consider porting from kubeyaml to py-yamler or similar

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1120]
As of #976, we run YAML updates through kubeyaml, which is a vast improvement. But it's not very flexible -- kubeyaml has to understand each format we want to be able to update (e.g., `FluxHelmRelease`s), and each kind of update we want to do.

At the minute, we do _some_ analysis of manifests in Go code, and some in `kubeyaml`, and these have to line up. For example, both have to agree on how `FluxHelmRelease`s encode the image in use in the chart.

If we used a library that supported arbitrary changes to YAMLs, then we'd be able to do the analysis of what to change _only_ in fluxd (and have to change _only_ fluxd to support new formats or kinds of update).

**Comment by kingdonb** [comment]
In Flux v2, Kustomize's [kyaml setters](https://pkg.go.dev/sigs.k8s.io/kustomize/kyaml/setters) feature is used instead of manipulating YAML directly inside of Flux components.

Closing.
