### ISSUE TITLE
Better error message when flux fails to push commits

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1124]
If flux fails to push a commit, the user will see something like

    ERROR git push git@…: failed to push some refs to 'git@…'

.. indicating (most likely) that git couldn't fast-forward the branch on the remote. This will happen from time to time in normal operation, because inevitably other people or processes will push commits to the branch that flux hasn't seen yet.

The correct thing to do is just try again (and flux immediately fetches from upstream, to make this more likely to succeed). But we should better indicate that it's not unexpected, not a big problem, and easy to remedy. This may be blocked by #1096, since the commit is done as part of the job.

**Comment by kingdonb** [comment]
I think it's settled on the Flux maintainer team at least that Flux v1 cannot have any log style changes, or they would have to be considered breaking changes.

If there were an active report of failing to push the notes ref, or errors that get flux daemon into a stuck condition such that it does not resolve itself, that would be something to follow up, but this report does not have any of that. Closing this for now.
