### ISSUE TITLE
Be consistent with displaying revision SHA1s

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1135]
We sometimes shorten revision IDs and sometimes don't, and it'd be good to be consistent. This doesn't necessarily mean always showing a shortened SHA1 (or always a full SHA1) -- we should do something like showing the full hash when first mentioning it, then using the shortened one thereafter. Anyway, worth an audit.

**Comment by kingdonb** [comment]
Not a maintenance issue for Flux v1. Closing!
