### ISSUE TITLE
Run flux with read-only access to repository

### ISSUE THREAD

**Issue by jml** [fluxcd/flux#1139]
A few times I've spoken to flux users and potential flux users who really like the way flux keeps deployments in sync, but would rather not have flux actually edit their YAMLs.

They have a variety of reasons, include some or all of:
- general wariness about granting write access
- desire for all changes to be reviewed by a human
- desire for all changes to go through some automated CI process before being applied
- wanting to lock down which humans can trigger changes to the UI
- general desire for as few ways of doing a thing as possible (simplifies processes, training, etc. in larger orgs)

**Comment by jml** [comment]
Yup.

Yes re opening PR. @squaremo mentioned that when we spoke. His ideas
sounded fleshed out enough that I thought I’d leave it to him to speculate.

**Comment by squaremo** [comment]
> Flux could open a PR.

You can't open a PR if you can't write to the repo.

**Comment by squaremo** [comment]
The main technical difficulty with this is that flux currently assumes it can forcepush its "sync tag" to the upstream repo. This is largely a mechanism to prevent duplicate events, though it is tangled up in a few other places. To have properly read-only repos, we'd have to figure out another way to keep a high water mark or otherwise prevent duplicate events. (The event receiver should really be deduplicating _anyway_, but we shouldn't rely on that here.)

**Comment by stefanprodan** [comment]
We could store the checkpoint in an annotation on the SSH key secret that's under Flux control.

**Comment by ariep** [comment]
Potential flux user here. I would also be very interested in this feature for yet another reason: our use-case would consist of a single repository specifying a deployment, and many (small) clusters, that are not under our control, using flux to pull from the specification and update accordingly. We would not want to give the people controlling the clusters write access to our source repo.

**Comment by primeroz** [comment]
really interested in this. 

I need it to run CI Clusters where, due to an higher risk of leaking credentials, i really don't want to attach a RW ssh key 

is there any plan to work on this ?

**Comment by u24b6** [comment]
Is there any documentation for how to do this?

**Comment by 2opremio** [comment]
There is a flux flag for this `--git-readonly`

**Comment by 2opremio** [comment]
See https://docs.fluxcd.io/en/1.18.0/faq.html#can-i-run-flux-with-readonly-git-access
