### ISSUE TITLE
helm-op: export Prometheus metrics

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1159]
Off the top of my head:

 - count of releases (of different types? of different charts?)
 - gauge of releases "under management"
 - histogram of release duration (even if just for the counts)

**Comment by cristian-radu** [comment]
I would also like to suggest adding a queueLength gauge, similar to the flux daemon. 

https://github.com/weaveworks/flux/blob/335c768a3ba451419549e0f124697bfb8450bfd8/daemon/metrics.go#L41-L46

**Comment by stefanprodan** [comment]
Fixed in #2191
