### ISSUE TITLE
Avoid partial failures in release process

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1209]
At present, the release process is

 1. update the changelog (and examples, where they mention a version)
 2. create a release in github; this tags the git repo
 3. the tag triggers a CI build which makes the image and uploads fluxctl binaries

It's pretty convenient, when it works. It can fail in an annoying way, though -- if the CI build fails, it leaves a release without an accompanying image. This is a problem for Weave Cloud because it looks at the github releases to figure out which version of flux to give people.

**Comment by kingdonb** [comment]
I don't know if this really is a problem for Weave Cloud anymore,

I have a WC install that seems to be stuck on this image: `docker.io/fluxcd/flux:1.20.2`

We have the checkpoint-api where releases are manually catalogued after they've been verified successful, it is still internal at Weaveworks; the log output looks like this:

```
ts=2021-07-28T18:28:51.715085138Z caller=checkpoint.go:21 component=checkpoint msg="update available" latest=1.23.1 URL=https://github.com/fluxcd/flux/releases/tag/1.23.1
```

I think the innovation in our release process is more likely to land in Flux v2 from now on, (just wanted to add some documentation to this issue before closing.)
