### ISSUE TITLE
Cope gracefully when we can't get resources (in a namespace)

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1217]
It's desirable to be able to deploy fluxd with permissions restricted to certain namespaces or resources (usually namespaces, since this is a lost easier than alternatives).

At present though, unless you also tell it to only scan certain namespaces with `--k8s-namespace-whitelist`, it will respond to most API calls with an error, having failed to scan for workloads in a namespace for which it doesn't have permissions.

It'd be better to simply elide resources that we don't have the permissions to `get` (if we can tell).

**Comment by nmaupu** [comment]
Any news on that ? I am still getting bunch of error logs (e.g. `cannot get resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope`) when attempting to restrict flux to a specific namespace.
