### ISSUE TITLE
Feature proposal: only auto-deploy image when it's built from a more recent commit

### ISSUE THREAD

**Issue by errordeveloper** [fluxcd/flux#1241]
At the moment the following is entirely possible:

Two PRs get merged in app repo (PR1 and PR2, where PR2 becomes HEAD) and builds run for each of the merge commits. For some reason build for PR1 takes longer then the build for PR2, as a result of that Flux would see the image for PR2 first and deploy it, then image for PR1 appears and gets deployed.

We should be able to prevent this. I can see two ways right now (there maybe more). One way would be to resolve the revision in the source repo (but we don't have access to that), and the other way would be to use a convention image label that has a timestamp (perhaps one from the original commit).

**Comment by squaremo** [comment]
>  the other way would be to use a convention image label that has a timestamp (perhaps one from the original commit).

Yup. We can take the image creation time (for the purpose of sorting) from the labels, but it would still be up to the person configuring the CI build to make sure it was the correct time.

**Comment by kingdonb** [comment]
This is not strictly solved, but at least the problem has been fully externalized in Flux v2, which now explicitly depends on [sortable image tags](https://toolkit.fluxcd.io/guides/sortable-image-tags/) for image automation.

When strict ordering of builds is important, CI should ensure the timestamp used will be appropriately monotonically increasing or better yet, semver image ranges can be used which are unambiguous about which version is higher.

There is no remaining dependency on build metadata from OCI image layers in Flux v2, so the original issue is moot.

Closing.
