### ISSUE TITLE
Get git repo, and associated config, from file (ConfigMap)

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1259]
At present, you tell fluxd the git repo to look at with a command line argument. When running fluxd in Kubernetes (i.e., all the time), this means you have to change its deployment config and apply that to restart it, if you want to change its configuration. This is a problem for a couple of reasons:

 1. the user config cannot be adapted independently of the deployment; so, e.g., tooling like the weave launch agent has to interpret the deployment to be able to apply changes, which is brittle.
 2. similarly, you cannot store the user config and deployment config in different places, e.g., to put the user config in git, but let the deployment config be controlled by an operator or the like.

### what goes where

| flags | what to do with it them |
|--------|-------------------------------|
--connect string                        Connect to an upstream service e.g., Weave Cloud, at this base address | Leave as arg. This can be set on the deployment once.
--token string                          Authentication token for upstream service | Leave as arg. Put in secret; load as env variable in deploy config.
|----|----|
--git-branch string                     branch of git repo to use for Kubernetes manifests (default "master") |)
--git-ci-skip                           append "[ci skip]" to commit messages so that CI will skip builds |)
--git-ci-skip-message string            additional text for commit messages, useful for skipping builds in CI. Use this to supply specific text, or set --git-ci-skip |)
--git-email string                      email to use as git committer (default "support@weave.works") |)
--git-label string                      label to keep track of sync progress; overrides both --git-sync-tag and --git-notes-ref |)
--git-notes-ref string                  ref to use for keeping commit annotations in git notes (default "flux") |)
--git-path string                       path within git repo to locate Kubernetes manifests (relative path) |)
--git-set-author                        If set, the author of git commits will reflect the user who initiated the commit and will differ from the git committer. |)
--git-sync-tag string                   tag to use to mark sync progress for this cluster (default "flux-sync") |)
 --git-url string                        URL of git repo with Kubernetes manifests; e.g., git@github.com:weaveworks/flux-example |)
--git-user string                       username to use as git committer (default "Weave Flux") | ) Put these all in config. Maybe take the opportunity to deprecate `--git-sync-tag` and `--git-notes-ref`.To prepare a little for multiple repo support, separate into global and repo-specific args, and let the latter be given defaults at the top level.
|-----|-----|
--git-poll-interval duration            period at which to poll git repo for new commits (default 5m0s) |)
--sync-interval duration                apply config in git to cluster at least this often, even if there are no new commits (default 5m0s) | ) Leave as command-line arg; these is about the operation of the daemon, rather than the git repo itself. (An argument can be made for making either of them set per-repo, if and when there’s multiple repos; but, that can be added if and when).
|----|----|
--k8s-namespace-whitelist strings       Experimental, optional: restrict the view of the cluster to the namespaces listed. All namespaces are included if this is not set. | Undecided. Put in config.
|-----|-----|
--docker-config string                  path to a docker config to use for image registry credentials |)
--k8s-secret-data-key string            Data key holding the private SSH key within the k8s secret (default "identity") |)
--k8s-secret-name string                Name of the k8s secret used to store the private SSH key (default "flux-git-deploy") |)
--ssh-keygen-dir string                 directory, ideally on a tmpfs volume, in which to generate new SSH keys when necessary |)
--k8s-secret-volume-mount-path string   Mount location of the k8s secret storing the private SSH key (default "/etc/fluxd/ssh") | ) Leave as command-line args. These refer to files that will be mounted into the container, so it doesn’t make sense to have them specified elsewhere. (And in fact, most should just be left to default anyway).We’ll have to support multiple keys if and when we support multiple repos, so some of these might get deprecated (I’m thinking the key, which we could just name for the git URL).
|------|------|
--kubernetes-kubectl string             Optional, explicit path to kubectl tool |)
-l, --listen string                         Listen address where /metrics and API will be served (default ":3030") |)
--memcached-hostname string             Hostname for memcached service. (default "memcached") |)
--memcached-service string              SRV service used to discover memcache servers. (default "memcached") |)
--memcached-timeout duration            Maximum time to wait before giving up on memcached requests. (default 1s) |)
--registry-burst int                    maximum number of warmer connections to remote and memcache (default 125) |)
--registry-cache-expiry duration        Duration to keep cached image info. Must be < 1 month. (default 1h0m0s) | ) All operational stuff, leave as command-line args.
|-----|-----|
--registry-insecure-host strings        use HTTP for this image registry domain (e.g., registry.cluster.local), instead of HTTPS | Might be worth having this as a list value in config, since they relate to user data rather than operation.
|------|-----|
--registry-poll-interval duration       period at which to check for updated images (default 5m0s) |)
--registry-rps int                      maximum registry requests per second per host (default 200) |)
--registry-trace                        output trace of image registry requests to log | ) Leave as command-line args. Though there is an argument for making the rate-limiting tweakable per host (e.g., for GCR) -- maybe later.
|-----|-----|
--ssh-keygen-bits uint                  -b argument to ssh-keygen (default unspecified) |)
--ssh-keygen-type string                -t argument to ssh-keygen (default unspecified) | ) Leave as command-line args, all about key generation. Possibly the key bits and type could be per repository, but I don’t expect it would be that useful (?).
--version                               Get version number | Is really a subcommand; leave where it is.

### other considerations

We should make the git repo config a list, even if we accept only one element for now.

**Comment by kingdonb** [comment]
Maintenance mode means we won't change move or remove any of this stuff in Flux v1, these notes are historical at this point and have certainly been considered in the design of Flux v2. Closing.
