### ISSUE TITLE
Docs in master run ahead of releases

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1268]
Our docs tend to be updated either in PRs that make code changes, or shortly after, and merged to master.

Since we tend to point people at the docs from master (either explicitly by posting links in Slack or wherever, or implicitly by that being what you get when you come to https://github.com/weaveworks/flux), quite often people will see docs pertaining to changes that aren't in a release yet.

Some changes to docs are about new features of course, so it's not the case that all changes should be held back for the next release.

**Comment by stefanprodan** [comment]
We could use readthedocs.org 
It's free for open source projects and allows us to publish docs with each sem ver release.

**Comment by stefanprodan** [comment]
Fixed in 1.19.0
