### ISSUE TITLE
Handle errors encountered when parsing manifests' containers

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1269]
In cluster/kubernetes/resource/spec.go, we attempt to parse the image field of each container and initContainer, but discard any errors returned (and use an empty image.Ref).

It is not at all obvious how to handle any problems we encounter here, but we should figure it out at some stage, because it's bound to lead to problems.

**Comment by kingdonb** [comment]
Historical. Behavior in Flux v1 will not be changing in maintenance mode.
