### ISSUE TITLE
Helm docs need a review/rewrite

### ISSUE THREAD

**Issue by dholbach** [fluxcd/flux#1359]
In the review of #1357 it became clear that the Helm related docs need a rewrite (and/or possibly another review).

We currently have:

- [x] [chart/flux/README.md](https://github.com/weaveworks/flux/blob/master/chart/flux/README.md): likely in good shape
- [ ] [site/helm-get-started.md](https://github.com/weaveworks/flux/blob/master/site/helm-get-started.md): tutorial, relatively new, based on `flux-helm-test` (cf #1360 for the choice of example)
- [ ] [site/helm-operator.md](https://github.com/weaveworks/flux/blob/master/site/helm-operator.md): will need review/rewrite
- [ ] [site/helm-integration.md](https://github.com/weaveworks/flux/blob/master/site/helm-integration.md): will need review/rewrite, needs probably the most insight knowledge.

It'd be great if users of Flux+Helm could take a look at the docs above and see if they are up to date or things missing.

**Comment by stefanprodan** [comment]
The `chart/flux/README.md` looks good to me.

**Comment by stefanprodan** [comment]
Helm-op now has it's own docs section and Helm chart.
