### ISSUE TITLE
Release to branch

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1361]
To enable people to make a PR when e.g., releasing a new image, we could extend the API so that you can specify that a job should push commits to a branch other than the one given by `--git-branch`.

    fluxctl release --branch release-v1 ...

This could also apply to policy changes.

**Comment by kingdonb** [comment]
https://toolkit.fluxcd.io/guides/image-update/#push-updates-to-a-different-branch

This issue got a first-class treatment in Flux v2, it is now possible to configure image automation to push updates to a different branch and even accumulate them for application together through a pull request.

👍   🎉   🌮
