### ISSUE TITLE
Automated updates to a branch

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1362]
Similarly to #1361 (and yet not, read on ..), push commits from automation to a branch.

There is a big difference that makes this more complicated: automation happens unattended, and its updates are based on the current state. It's not enough to just change the branch that it pushes commits to, or to push each to a fresh branch -- if the branch hasn't been merged in the meantime, each subsequent automation run will end up pushing a commit including the same changes as the last.

So this needs to be thought through. A couple of alternative sketches:

 - Wait until the last branch is merged before running automation again
   - this could easily end up over-constraining the system, since in general updates can be done concurrently without waiting for the last
   - what if the branch is deleted? (would have to watch for that too)

 - Annotate resources as having an automated update outstanding, and don't include those in the automation run
   - could work neatly, but no doubt has corner cases (e.g., what if you lose state -- either the running resource or branch is deleted)

**Comment by kingdonb** [comment]
Same disposition as #1361, this is handled in Flux v2 now:

https://toolkit.fluxcd.io/guides/image-update/#push-updates-to-a-different-branch

fluxcd/image-automation-controller#121 made this feature possible in the latest Flux v2 releases.

🌮
