### ISSUE TITLE
Better status information for HelmRelease resources

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1413]
At present we just stick whatever Tiller says about the release state of the chart. But we could do better, and for example indicate when a release failed, and so on -- possibly as conditions (although, are they on the way out?).

The requirements need a bit of thinking through. As a start, I would posit

 - you should be able to tell from the FluxHelmRelease status whether the chart is released as specified
 - you should be able to tell ditto ditto if there's something stopping the chart from being updated, and what it is

**Comment by stefanprodan** [comment]
I think this is covered by the HelmRelease status conditions. @squaremo should we close this?

**Comment by stefanprodan** [comment]
This has been fixed in Helm Operator 1.0.0-rc.1, doing a `kubectl get hr` will output the release status and the install/upgrade error if the release failed.
