### ISSUE TITLE
Add additional "out_of_date" status for release

### ISSUE THREAD

**Issue by guyfedwards** [fluxcd/flux#1419]
Currently a release has either `'ready'` or `'updating'` status. 

This creates confusion when an update has been committed, but Kubernetes hasn't noticed yet and so any requests to the API will return `Status: "ready"` which is not incorrect, but is misleading as it is out of date. 

A possible solution would be to add a new status of `Status: "out_of_date"` or something alike to differentiate between the beginning and end of a release.

cc @squaremo

**Comment by kingdonb** [comment]
This feature would require eg. `fluxctl` or flux cli to poll the git repository directly, I think it's interesting. It could be done by simply running with the working directory in a local clone of the cluster repo.

Might be something to consider for the new flux ui that I understand is being developed. It could be a thing to run it as a process which carries with it, a clone of the cluster repo (or even on a developer workstation, where a clone is already there.)

 I don't know what this will shape up to be, as it is still new ideas. Hope you will follow us to Flux v2 and add any suggestions there, in the new [discussions](/fluxcd/flux2/discussions), or joining us on CNCF #flux slack.

As Flux contrib efforts have been focused on Flux v2, if you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/ - tl;dr: the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)
