### ISSUE TITLE
Tiller-less support in Flux Helm Operator

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux#1420]
The Helm Operator could work without Tiller by running `helm template` and `kubectl apply`. See https://jenkins-x.io/news/helm-without-tiller/

**Comment by stephenmoloney** [comment]
Seems like a good idea if it is optional, eg `--set helmOperator.tiller: false` and could serve as a good 
stepping stone to helm 3 migration.

**Comment by justinbarrick** [comment]
That’s one way to do that, another way is to just run tiller in the same pod as helm-operator and bind it to localhost. You still have to run tiller, but it makes it easier to operate (and it’s not going to use many resources on its own) and mitigates the security issues. You also still get to benefit from all of the features tiller gives you (garage collection, rollbacks, etc).

There’s a helm plugin that lets you do effectively this when running helm locally, but you don’t need it if you’re running them in a pod together: http://rimusz.net/tillerless-helm/

**Comment by alanjcastonguay** [comment]
>But the operator will also get those privileges, which will often be essentially cluster-admin.

If the HelmOperator pod is compromised today, the attacker has the certificate-auth secret material for connecting to tiller anyway. Giving a HelmOperator pod the k8s permission directly doesn't change the risk.

**Comment by timja** [comment]
Helm 3 has just had its first alpha release without tiller:
https://github.com/helm/helm/releases/tag/v3.0.0-alpha.1

It would be great to look at what changes would be required to run flux with helm 3

**Comment by jpds** [comment]
There's a Helm 3 tracking issue at #2069.

**Comment by stefanprodan** [comment]
This will be covered by Helm v3
