### ISSUE TITLE
Build flux container for Windows 

### ISSUE THREAD

**Issue by justinbarrick** [fluxcd/flux#1467]
Some users are running kubernetes clusters using windows machines which makes it harder for them to use Flux.

We should build a windows version of the image and tag it as a multi-platform image so that flux can run anywhere.

I expect this won’t be easy if flux makes assumptions about the filesystem or being on a Unix machine. Additionally, we’ll need to package git and kubectl for Windows.

We should do the same with the helm-operator while we’re at it.

**Comment by rparsonsbb** [comment]
Has there been any kind of movement on this?  Is it planned for Argo Flux?

**Comment by kingdonb** [comment]
Flux v1 is in maintenance mode now, and is not adding any new features unless they are critical.

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.

If you have a use case for Flux that isn't covered well, we want to hear about it.

If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/
