### ISSUE TITLE
Difficult to differentiate between error responses from /services and /images

### ISSUE THREAD

**Issue by foot** [fluxcd/flux#1500]
Different types of error responses:
1. 422: "context deadline exceeded" / "read error on port" -> retry request again
2. 422: "duplicate definition of yamls" -> show error to user and suggest how to fix

Might be opportunity to fix a feeling of slight inconsistency in the API:
- /services and /images respond successfully if the daemon is launched in a ReadOnly / unconfigured state
- /services and /images return errors if there is a problem w/ the contents of the git repo e.g. `422: duplicate definition of 'default:deployment/helloworld' (in hejworld-conf/helloworld-deploy.yaml and helloworld-conf/helloworld-deploy.yaml)`

Fixes?
1. The way I'm trying to use the API _right now_ it would be nicer to have class No. 2 of 422s over in `/status -> git.error` out of band and still let /services and /images potter along..
2. A different error code for class No. 2 of 422s.

**Comment by squaremo** [comment]
I see, the problem is that it's difficult to base any control flow on the errors you get back from the API.
(BTW, do you see the "rich" errors, which have JSON payloads? You may be able to get enough to dispatch on by asking for `application/json` responses.)

> The way I'm trying to use the API right now it would be nicer to have class No. 2 of 422s over in /status -> git.error out of band and still let /services and /images potter along..

Do you mean you'd want /services and /images to return a result, rather than an error, when they can't parse YAMLs or encounter duplicate definitions or whatever?

**Comment by foot** [comment]
That is really cool! TIL. 

```js

export const EXAMPLE_MANIFEST_DUPLICATION = {
  type: 'user',
  help: `Unable to parse files as manifests\n\nFlux was unable to parse the files in
    the git repo as manifests,\ngiving this error:\n\n    duplicate definition of
  'default:deployment/helloworld' (in hejworld-conf/helloworld-deploy.yaml and
    helloworld-conf/helloworld-deploy.yaml)\n\nCheck that any files mentioned are well-formed, and
  resources are not\ndefined more than once. It's also worth reviewing\n\n
  https://github.com/weaveworks/flux/blob/master/site/requirements.md\n\nto make sure you're not
  running into any corner cases.\n\nIf you think your files are all OK and you are still getting
  this\nmessage, please log an issue at\n\n    https://github.com/weaveworks/flux/issues\n\nand
  include the problematic file, if possible.\n`,
  error: `duplicate definition of 'default:deployment/helloworld' (in
    hejworld-conf/helloworld-deploy.yaml and helloworld-conf/helloworld-deploy.yaml)`,
};

export const EXAMPLE_CONTEXT_DEADLINE_EXCEEDED = {
  type: 'user',
  help: `Cannot contact flux daemon\n\nTo service this request, we need to ask the agent running in
  your\ncluster (fluxd) for some information. But we can't connect to it at\npresent.\n\nThis may
  be because it's not running at all, is temporarily\ndisconnected or has been firewalled.\n\nIf
  you are sure flux is running, you can simply wait a few seconds\nand try the operation
  again.\n\nOtherwise, please consult the installation instructions in our\ndocumentation:\n\n
  https://github.com/weaveworks/flux/blob/master/site/installing.md\n\nIf you are still stuck,
  please log an issue:\n\n    https://github.com/weaveworks/flux/issues\n\n`,
  error: 'context deadline exceeded',
};

export const EXAMPLE_IO_ERROR = {
  type: 'user',
  help: `Error: read tcp 10.244.229.8:3030-\u003e10.244.194.210:33114: i/o timeout\n\nWe don't have
  a specific help message for the error above.\n\nIt would help us remedy this if you log an issue
  at\n\n    https://github.com/weaveworks/flux/issues\n\nsaying what you were doing when you saw
  this, and quoting the message\nat the top.\n`,
  error: `read tcp 10.244.229.8:3030-\u003e10.244.194.210:33114: i/o timeout`,
};
```

**Comment by foot** [comment]
> Do you mean you'd want /services and /images to return a result, rather than an error, when they can't parse YAMLs or encounter duplicate definitions or whatever?

That was the above suggestion but I'm not sure about it anymore. If you're playing around w/ the config and haven't quite got it right maybe its better to fail fast and hard.
