### ISSUE TITLE
Error: user: Current not implemented on linux/amd64

### ISSUE THREAD

**Issue by montyz** [fluxcd/flux#1503]
```
$ fluxctl list-controllers
Error: user: Current not implemented on linux/amd64
Run 'fluxctl list-controllers --help' for usage.
```

Is this really not currently implemented for linux? Or does this error mean something else?

**Comment by squaremo** [comment]
Looks like some variety of this problem: https://github.com/golang/go/issues/14625. We don't use `user` directly, but it's likely to be dragged in by some Kubernetes-related library.

Did you compile the `fluxctl` binary yourself? If so, make sure you're using an up-to-date Go distribution to do so. If not, we'll have to review how the binaries are built in CI.

**Comment by montyz** [comment]
I installed it in a docker container from the github release binary:

```
RUN wget -q -O /usr/local/bin/fluxctl https://github.com/weaveworks/flux/releases/download/1.8.0/fluxctl_linux_amd64
RUN chmod +x /usr/local/bin/fluxctl
```

**Comment by squaremo** [comment]
What's the base image?

**Comment by montyz** [comment]
```
FROM jupyter/minimal-notebook
```
It's a debian based image of some sort.

**Comment by camilb** [comment]
Same issue here. 
@montyz 
Using this as workaround in kubernetes: 
`export USER=root FLUX_URL=http://flux.flux.svc.cluster.local:3030/api/flux && fluxctl list-controllers`

**Comment by seancfoley** [comment]
Same issue.  Compiled on ubuntu 16.04.  Run in docker image with base ubuntu 18.04.  Used the same env var workaround.

**Comment by kingdonb** [comment]
Flux v1 requires the root user, Flux v2 no longer does and can be used with standard Kubernetes best-practices including AIUI rootless containers.

I will close the issue for now as it is stale. Flux v1 remains in maintenance mode.

We can provide support to Flux v1 users especially with respect to migrating to the new Flux version, Flux v2, which has some breaking changes but is also a total rewrite and also brings many improvements. I'm closing the issue but you are most welcome to write back on this issue, or open another issue. Thanks for using Flux.
