### ISSUE TITLE
fluxd does not recognise `flux.weave.works/ignore: "true"`

### ISSUE THREAD

**Issue by endrec** [fluxcd/flux#1532]
Using `kubectl annotate fluxhelmrelease rrrr flux.weave.works/ignore=true` creates a string value for the annotation, but unfortunately fluxd does not really care.

Affected version: 1.8.0
See [slack thread](https://weave-community.slack.com/archives/C4U5ATZ9S/p1542639531978400)

**Comment by kingdonb** [comment]
I will close the issue for now as it is stale. Flux v1 remains in maintenance mode.

Flux v2 no longer uses annotations for this purpose, now any Flux resources which should be suspended can be patched with the `spec.suspend` field instead. So `kubectl annotate` limitations are not a problem anymore.

We can provide support to Flux v1 users especially with respect to migrating to the new Flux version, Flux v2, which has some breaking changes but is also a total rewrite and also brings many improvements. I'm closing the issue but you are most welcome to write back on this issue, or open another issue. Thanks for using Flux.
