### ISSUE TITLE
Instructions for known_hosts don't work when using flux chart

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1542]
The instructions for constructing a known_hosts in https://github.com/weaveworks/flux/blob/master/site/standalone-setup.md#using-a-private-git-host dodn't work with the flux chart, because it mounts a configmap even if it's empty. Doing so unconditionally is not unreasonable; so, we'll need to change the instructions.

**Comment by kingdonb** [comment]
These linked instructions are gone. Closing.
