### ISSUE TITLE
Update validation is sensitive to trailing `---`

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1600]
If you have a `---` at the _end_ of your yamel, fluxd may fail an update saying parsing YAML doc from \"env-name/sample1.yaml\": yaml: did not find expected node content`. Strictly speaking, you have made a wonky yamel, but it's forgivable, and fluxd could be more permissive.

**Comment by kingdonb** [comment]
Flux v2 may have already solved this.

I ran into this issue in another tool, Jsonnet balks at YAML files with too many `---` separators. This apparently common issue will not be getting fixed in Flux v1.
