### ISSUE TITLE
HELM_HOME mismatch with default in helm-operator chart yaml

### ISSUE THREAD

**Issue by stephenmoloney** [fluxcd/flux#1640]
What is the issue?

The HELM_HOME env var in the dockerfile seems to be a mismatch for the directory of the helm certs in the helm-deployment-operator.yaml.

Dockerfile - /var/fluxd/helm - https://github.com/weaveworks/flux/blob/8dd22bc52aa8dd4e54a0fe265a279d91c5a68029/docker/Dockerfile.helm-operator#L37

Helm chart - /etc/fluxd/helm/ - https://github.com/weaveworks/flux/blob/afc71f2a448056803105b5b94bc8814197f87f98/chart/flux/templates/helm-operator-deployment.yaml#L74

Would it make sense to synchronize them ?

**Comment by hiddeco** [comment]
We just [had a user on Slack](https://weave-community.slack.com/archives/C4U5ATZ9S/p1553079045751900) who reported `HelmRelease: chart download failed: Couldn't load repositories file (/var/fluxd/helm/repository/repositories.yaml)` errors after configuring the `configureRepositories` chart values.

The mountPath in the chart should be set to match the configured `HELM_HOME` environment variable.

**Comment by stefanprodan** [comment]
We will address the HELM_HOME issue in the Helm v3 port.
