### ISSUE TITLE
I'd like to manually deploy several images in one commit

### ISSUE THREAD

**Issue by paulbellamy** [fluxcd/flux#166]
Maybe something like this?

```
fluxctl release --update-image=weaveworks/scope:0.17.0 --update-image=nginx:1234 --all
```

**Comment by philwinder** [comment]
This will require a change to `ReleaseSpec` to allow multiple ImageSpecs. As a workaround:
`fluxctl release --update-image=weaveworks/scope:0.17.0 --all`
`fluxctl release --update-image=nginx:1234 --all`

But that will produce two commits.

Currently a nice-to-have.

**Comment by bastienbc** [comment]
Hi,

I am in this situation too:
My chart have to image: the actual app (pod), and a database migration tool (job as hook).
So I need to update both images in a single commit.

Since there is a single commit when it is automated and both images have changed, I thought I would have the same behavior in my CI.

Is my only option to directly calll the REST API?

**Comment by kingdonb** [comment]
In the new architecture of Flux v2, there are a number of solution for dependency order, but not any accommodation I'm aware of for automated update ordering. If you have not yet been able to upgrade to Flux v2, it is strongly recommended by the Flux developer team to consider upgrading now, or as soon as possible.

0.8 was released which marked the declaration of 100% feature parity, which means Flux v2 should be better for all use cases at this point. While Flux v2 is still pre-release, it is still possible to influence the design choices of image automation. I think you have a unique and interesting use case that Flux should support, without requiring you to choose to orchestrate your release to get this behavior via Helm charts. I'm not exactly sure how to solve it, but there should be something less drastic that you can do to get this behavior besides building a helm chart just to get these things synchronized.

Maybe if your images are maintained with version in sync, you could use the same ImageAutomationPolicy to drive both image tags in kustomize controller? That way as long as you're sure both image tags will always be published for every release, they could stay upgraded in sync with each other. This solution seems plausible and I think it could work in Flux v2 today, possibly without any changes.

I would encourage you read the new documentation at https://toolkit.fluxcd.io, try upgrading, see for sure if your use case is still in need of attention (or if it can be solved already), then perhaps consider opening up a new discussion on this issue at https://github.com/fluxcd/flux2/discussions over where there is currently a lot more attention now, than here in Flux v1 repo.

As for the feature request for Flux v1, now that we are in maintenance mode and Flux v2 is approaching a GA release, the likelihood of adding new features in Flux v1 has dropped significantly, we are in general not accepting new features unless they provide a very compelling argument, and mostly would decline them in favor of putting the effort into Flux v2.

Respecting you may have moved on already, I will go ahead and close out this issue for now.
