### ISSUE TITLE
Integration Helm operator with quay.io

### ISSUE THREAD

**Issue by fbarl** [fluxcd/flux#1666]
From Intercom:

> We are running kubernetes, and we wanted to use Helm App Registories on quay, as announced here:
> https://coreos.com/blog/quay-application-registry-for-kubernetes.html
> 
> So we pushed our helm chart to this repo:
> https://quay.io/application/[org]/[app]
> 
> However now we need to be able to download this chart.
>
> That leads to the questions:
> 
> 1. Where is the root of the App Repository?
> 2. How do we authentica (Should we use Robots?)
> 3. How do we set this up with Flux and the flux-helm-operator.
> 
> We’re trying to use HelmRelease CDR’s in our k8s cluster, that point to the Helm App Repo.
> However its not working, like the way we want:
> https://github.com/weaveworks/flux/blob/master/site/helm-integration.md#authentication
> 
> Currently we’re getting errors:
> 
> ```[flux-helm-operator-6cdbc96c5c-wfgft] ts=2019-01-15T15:06:13.596946245Z caller=chartsync.go:340 component=chartsync info=“chart download failed” releaseName=... resource=default:helmrelease/... err=“Looks like “https://quay.io/cnr/api/v1/packages/...” is not a valid chart repository or cannot be reached: Failed to fetch https://quay.io/cnr/api/v1/packages/.../index.yaml : 403 Forbidden”```

**Comment by fbarl** [comment]
@squaremo's note:

> Looks like quay.io requires a custom Helm plugin, though it's not clear whether it's doing authentication or not.

**Comment by stefanprodan** [comment]
If it works with curl then it should work with helm-op by mounting the repositories.yaml.

@fbarl can you ask if this works:

```
curl -u QUAY_USER:QUAY_PASS https://quay.io/cnr/api/v1/packages/[org]/[app]/index.yaml
```

**Comment by radityasurya** [comment]
but they are different, one is Charts API and Quay is App Registry

**Comment by squaremo** [comment]
App Registry does not appear to be very active or widespread: https://github.com/app-registry/spec (two maintainers, both from CoreOS; last commit Oct 2017).

**Comment by stefanprodan** [comment]
Helm v3 supports Docker Registry v2 for charts. We will be looking into support that instead of Quay App Registry.
