### ISSUE TITLE
Multi-arch Docker image manifests

### ISSUE THREAD

**Issue by jpds** [fluxcd/flux#1690]
I'd like to use Flux on arm32, however the default Docker images provided do not seem to have multiarch manifest support (support for this itself has been added in #1474).

**Comment by kingdonb** [comment]
Flux v2 does support multi-arch out of the box as of several weeks ago.

I think it is unlikely we will see this support added to Flux v1; I think I have seen some outside contributors providing this support already. I explained my position in #1761. I am in favor of ARM support, but I would also like users to migrate to Flux v2, so we can ultimately close the book on the earlier architecture of Flux which by comparison has many scaling and other supportability issues that are resolved in the new version.

I will close the issue for now as it is stale. Flux v1 remains in maintenance mode.

We can provide support to Flux v1 users especially with respect to migrating to the new Flux version, Flux v2, which has some breaking changes but is also a total rewrite and also brings many improvements. I'm closing the issue but you are most welcome to write back on this issue, or open another issue. Thanks for using Flux.
