### ISSUE TITLE
Rearrange deployment examples

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1691]
One complaint about the deployment examples is that it's not obvious, once you arrive there, what they are for or how to use them. We can make them a bit more self-contained by rearranging them and adding a README. This structure was suggested in Slack:

```
/setup
| README.md
-> /flux
    | README.md
    | flux-account.yaml
    | flux-deployment.yaml
    | flux-secret.yaml
    | memcache-dep.yaml
    | memcache-svc.yaml
    -> /helm-operator
        | README.md
        | flux-helm-release-crd.yaml
        | helm-operator-deployment.yaml
        | weave-cloud-helm-operator-deployment.yaml
```

**Comment by hiddeco** [comment]
I do not think that we should nest `helm-operator/` under `flux/` as `kubectl apply -f <directory>` will recursively apply manifests.

**Comment by dholbach** [comment]
Is this still relevant?
