### ISSUE TITLE
Update to nonexistent tag on change of repository

### ISSUE THREAD

**Issue by bboreham** [fluxcd/flux#1693]
I had a Kubernetes `Deployment` running from `quay.io/weaveworks/test-exporter:master-e4cc465`

Under `flux.weave.works/ignore: 'true'` annotation, I changed the image to `quay.io/cortexproject/test-exporter:master-f6627227` - different repository.

Flux made a commit:

```
Auto-release quay.io/weaveworks/test-exporter:master-a888416e
```

This tag is the second-newest  for the `cortexproject` image but does not exist for `weaveworks`.  

The version of Flux at the time was `quay.io/weaveworks/flux:master-ef8e102f`

**Comment by squaremo** [comment]
This is probably a consequence of fluxd looking at the state of the cluster when calculating image updates, but applying the updates to the files. As a sketch of the interleaving:

 1. fluxd applies the commit changing cortexproject/test-exporter to weaveworks/test-exporter
 2. while the rollout is underway, flux notes there is a new image for what's apparently running in the cluster, cortex/text-exporter, and starts an automated release
 3. the automated release is applied to git, changing the tag of the image used.

The obvious mitigation, once that's spelt out, is to verify that the name of each image has not been inadvertently changed, when updating manifests.

**Comment by stefanprodan** [comment]
I'm guessing Flux will not ignore a workload if it has both `flux.weave.works/ignore: 'true'` and `flux.weave.works/automated: 'true'`. This is different issue to the image mismatch.

**Comment by bboreham** [comment]
Note that I didn’t make a commit to kick this off; I did `kubectl apply` with the `ignore` annotation.

**Comment by squaremo** [comment]
> I did `kubectl apply` with the `ignore` annotation.

Oh OK, then it's easier to explain: since fluxd wasn't syncing it, the images would just differ indefinitely. No need for a particular interleaving. The conclusion is the same.

**Comment by 2opremio** [comment]
> This is probably a consequence of fluxd looking at the state of the cluster when calculating image updates but applying the updates to the files

Sorry if this is obvious, but, considering that git is considered the source of truth, why are we doing it this way?

**Comment by squaremo** [comment]
> Sorry if this is obvious, but, considering that the git repo is the source of truth, why are we doing it this way?

It's an early design decision that was never quite wrong enough to adapt to changing circumstances. In the early days, the model was to effect changes in the cluster then reflect them in git after the fact, rather than vice versa -- so the cluster was the first port of call.

Nowadays, we should look at what's in git. Either way, I think we should add the verification I mentioned above.
