### ISSUE TITLE
Artifactory chart repo url being changed

### ISSUE THREAD

**Issue by kevwil** [fluxcd/flux#1707]
We have an internal Artifactory server and have a Helm virtual repo on it. We've had no issues with it when using Helm directly, but we're having a URL rewriting issue when using HelmRelease.

For a given Chart repository at "https://our.server.com/artifactory/helm-virtual" and a chart "foo" version "1.0.0", we get the following error:

    Failed to fetch https://our.server.com/helm-virtual/foo-1.0.0.tgz : 404 Not Found

The "/artifactory" part of the URL is missing.

I have not yet been able to identify a cause for this, and have not found any work-around.

**Comment by squaremo** [comment]
I remember seeing something like this while debugging private repos support, and I .. cannot .. remember .. why. The interplay of the repositories.yaml file and relative paths is quite delicate, I do remember that.

Downloading the index for the chart repo may give us some clues -- it's that which has the paths to the tarballs.

**Comment by kevwil** [comment]
I checked the index file on our server and it appears that all the chart URLs have the correct full path.

**Comment by hiddeco** [comment]
I think this may be related to #1732 and thus should have been fixed with #1735.

**Comment by kingdonb** [comment]
Closing as I read this would have been fixed in Flux 1.10.1 🥳
