### ISSUE TITLE
Rollback failed Helm releases in git

### ISSUE THREAD

**Issue by gtseres** [fluxcd/flux#1742]
When pushing a new `HelmRelease` object, there is a case that when Flux tries to deploy it, the `helm` installation/upgrade command will fail to be executed. In that case, we have the `HelmRelease`  changed in git, but not actually deployed in the cluster (the previous version is still running). An idea would be for Flux to revert the `HelmRelease` change in git, so that the git repo and the cluster are kept in sync (do not deviate).

**Comment by hiddeco** [comment]
Flux sees git as the desired state, a failing release does not mean your desire changes; just that it was not possible to fulfill it.

If Flux would rollback the release to the old state, the automation would kick in again (e.g. to deploy the new detected image), and you and up in an infinite loop of unrolling a failure, rolling back, Flux changing the image, repeat...

However, the Helm operator might do a better job at exposing divergences, so you are able to either let a human take a look at it in time or write your own automated rollback logic once a divergence is detected.

**Comment by 2opremio** [comment]
After #1019 is merged, you will effectively be able roll the HelmRelease back by removing the from git repository.

**Comment by hiddeco** [comment]
> After #1442 is merged, you will effectively be able roll the HelmRelease back by removing the from git repository.

As the Helm operator purges a deleted `HelmRelease` this will not roll it back but undo the deployment as a whole. Which, I think, is not the desired effect.

**Comment by 2opremio** [comment]
> As the Helm operator purges a deleted `HelmRelease` this will not roll it back but undo the deployment as a whole. Which, I think, is not the desired effect.

Fair point

**Comment by kingdonb** [comment]
The relevant section from the Flux v2 docs:

https://toolkit.fluxcd.io/components/helm/helmreleases/#configuring-failure-remediation

This topic has evolved into the next generation of Flux! Closing, Flux v1 is in maintenance.
