### ISSUE TITLE
Provide arm/arm64 images

### ISSUE THREAD

**Issue by MansM** [fluxcd/flux#1761]
As a Flux end-user
I want to use flux on a raspberry
in order to flux at home 

I know travis-ci doesnt support it, but maybe weave can invest in some raspberries and use them with a gitlab.com ci runner:
https://about.gitlab.com/2018/03/22/gitlab-10-6-released/#gitlab-cicd-for-external-repos

**Comment by stefanprodan** [comment]
Flux bundles git, kubectl and helm binaries, having an ARM image implies more than just run docker build on an ARM machine.

**Comment by MansM** [comment]
Last time I build I just replaced amd64 with arm in the makefile and it did work...

**Comment by stefanprodan** [comment]
I wander how is that possible since the kubectl and helm checksums are different https://github.com/weaveworks/flux/blob/master/Makefile#L83

**Comment by MansM** [comment]
Didnt say I build it recently ;-)

**Comment by 2opremio** [comment]
Related: https://github.com/weaveworks/flux/issues/1690 

@MansM I doubt maintainers have the bandwidth to add support for other architectures. PRs are welcome though! (ideally with a commitment to maintain support for arm64)

**Comment by stefanprodan** [comment]
"weave can invest in some raspberries and use them with a gitlab.com ci runner"

I don't think this will happen any time soon.

**Comment by brezerk** [comment]
You don't really need to have an arm or arm64 board to build the images. The ARM images can be build using binfmt_misc.

Here you are some details: https://github.com/prometheus/prometheus/pull/5031

If you need any help let me know.

**Comment by brezerk** [comment]
one step closer: https://github.com/six8/pyinstaller-alpine/issues/5 :)
i'll work on kubeyaml now.

btw, I had a brief look into CircleCI configuration files for flux and do have some dumb questions:

I see you are using machine for build: is there any particular reason for this?
```
  build:
    working_directory: ~/flux
machine: true
```

also: you are puling Go instead of using circleci/golang image. probably this is b/c you are using machine... Any objections on moving build to circleci/golang docker instead?

**Comment by ybaruchel** [comment]
+ 1

**Comment by onedr0p** [comment]
I am looking to run flux in my k3s cluster, has anyone successfully built a Docker image and deployed it? I will take Dockerfiles and build myself. I'm am trying to do it from scratch but the build process isn't straight forward. fluxctl is fluxd?

**Comment by jonohill** [comment]
I've set up a Gitlab pipeline to build ARM images for my own use. A bit of a rabbit hole - I also had to mirror and build kubeyaml and kustomize. Feel free to use if you wish - but best to treat as experimental. https://gitlab.com/jonohill/flux/container_registry

**Comment by zlangbert** [comment]
I also wanted to run flux and the helm controller on a Raspberry Pi cluster, and took a quick stab at this. Using docker / [buildx](https://docs.docker.com/buildx/working-with-buildx/) with slightly modified Docerfiles this tuned out to be relatively easy. You can see what I did here:

Flux: https://github.com/zlangbert/flux/commit/250533124ee946e1577a20d063edaafeb5a7464f
Helm Operator: https://github.com/zlangbert/helm-operator/commit/29e73d7d656699325bce8c593411f90b305e8c9b

If anyone is interested in using these multiarch images you can get them here: 
https://hub.docker.com/r/zlangbert/flux/tags
https://hub.docker.com/r/zlangbert/flux-helm-operator/tags

Note these are built using the latest commit in `master` of flux and the latest of the `helm-v3-dev` branch of the helm operator.

**Comment by onedr0p** [comment]
Thanks for that multiarch image. What's the hold up of official support from weave? This seems rudimentary to add.

**Comment by ikaruswill** [comment]
I am running my own armv7 build of flux on a raspberry pi 3 7-node k3s cluster.

I've built my own image based on the work done by @onedr0p, following the official docker image as closely as possible.

https://hub.docker.com/r/ikaruswill/flux/tags

I'm expecting to keep this image up to date with drone-ci pipeline for as long as fluxcd doesn't have one for arm. Feel free to use them.

**Caveats:l**
- I have not built sops so sops will not work. Would be happy to integrate anyone's arm build of sops.

If anyone is keen on using, I also have a ci pipeline building kubeyaml regularly.

https://hub.docker.com/r/ikaruswill/kubeyaml/tags

**Comment by onedr0p** [comment]
@ikaruswill I have a repo and build multiarch container image for flux and helm-operator, and some others. I'm trying to stay up too date with releases since they aren't automated on my end.

https://gitlab.com/onedr0p/flux
https://hub.docker.com/r/onedr0p/flux/tags

https://gitlab.com/onedr0p/helm-operator
https://hub.docker.com/r/onedr0p/helm-operator/tags

**Comment by ikaruswill** [comment]
@onedr0p Awesome work, I see that you actually did build sops and helm-operator. I'll integrate them in my setup and image. Thanks for that.

**Comment by onedr0p** [comment]
The flux build is a bit crazy and I need to build sops, kustomize and flux concurrently or else the gitlab runners timeout because the build takes over an hour.

Here's what I mean: https://gitlab.com/onedr0p/flux/pipelines/113975458

**Comment by xUnholy** [comment]
Thanks for the work @onedr0p!

Would love for you to work on a project of mine, feel free to reach out - I'll shoot you an invite if you're interested.

**Comment by onedr0p** [comment]
@xUnholy a few of us already started an GitHub org and have a discord community growing.

https://github.com/k8s-at-home/

I hope we can combine efforts here.

**Comment by onedr0p** [comment]
My repos have been deleted, we've combined efforts here to provide ARM support:

https://github.com/raspbernetes/multi-arch-images

**Comment by kingdonb** [comment]
I am not sure what else is still needed to support Flux v1 on arm64, but I am willing to merge any changes in service of this idea. I have raspberry pi computers and I will test the changes on my local network. 👍

As for Flux v1, it is in maintenance mode and all new development currently takes place over on [fluxcd/flux2](/fluxcd/flux2) where there is full support for arm64 arch out of the box! 🎉

Closing, but with a note that I am enthusiastic about supporting Raspberry Pi owners who are Flux users and I am happy to see how much attention this issue has had!
