### ISSUE TITLE
Syncing does not necessarily have a consistent view of (kube)config

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1772]
It's possible that while syncing, a mounted `kubeconfig` file can be updated, meaning fluxd does not have a consistent view of the default namespace. One problem that might cause is that resources are applied with a namespace different to that expected, and afterwards incorrectly garbage collected.

To avoid this situation, we could "sandbox" syncs by taking a snapshot of the kubeconfig before starting, and making sure that it used by all processes that would consult kubeconfig.

**Comment by kingdonb** [comment]
This will not be able to get fixed in Flux v1.

Flux v2 likely does not suffer from this issue anymore (hopefully?) 🏭 

Closing.
