### ISSUE TITLE
Integration of flux into keptn

### ISSUE THREAD

**Issue by AloisReitbauer** [fluxcd/flux#1822]
Hey there,

creating this issue to coordinate on work regarding flux integration into keptn. The issue on our side (https://github.com/keptn/keptn/issues/147).

Our main goal is to provide a lightweight approach to drive our GitOps deployments. 

We need to investigate how to trigger the operator using keptn's cloud events.

**Comment by squaremo** [comment]
Hi! I'm keen to help this move along. I've had a look at the corresponding bug in keptn -- can we have a paraphrasing of the requirements here, in more general terms (e.g., what is a keptn cloud event)?

**Comment by kingdonb** [comment]
Closing in favor of https://github.com/fluxcd/flux2/issues/447
