### ISSUE TITLE
Release quits with Error when there are no changes

### ISSUE THREAD

**Issue by r-carsten** [fluxcd/flux#1882]
Running a 'fluxctl release --all --upcate-all-images --verbose'

result in a "Submitting release... Error: no changes made in repo" when there are no updates.

In my opinion, this should not be an error, better a normal process exit.

**Comment by ambis** [comment]
I just hit this as well.

I see no point in returning an error, when the system is already in the desired state.

**Comment by kingdonb** [comment]
Please let me know if you still need help with this. I apologize for the staleness of this reply, we are in the process of cleaning up stale issues from the Flux v1 repo now, this should be over soon.

Image automation has been totally rewritten in Flux v2 and the `fluxctl` command has been obsoleted with this new version in favor of the `flux` cli, which behaves a lot more like kubectl. I am not even sure it supports imperative-style updates like this anymore at all, everything is done through git.

I will close the issue for now as it is stale. Flux v1 remains in maintenance mode.

We can provide support to Flux v1 users especially with respect to migrating to the new Flux version, which has some breaking changes but is also a total rewrite and also brings many improvements. I'm closing the issue but you are most welcome to write back on this issue, or open another issue. Thanks for using Flux.
