### ISSUE TITLE
Document how to lock down flux through stricter RBAC rules

### ISSUE THREAD

**Issue by dholbach** [fluxcd/flux#1886]
Feedback of a Flux user 

> "[..] about the permissions given to Flux in the template you refer to in your installation guide:
> 
> https://github.com/weaveworks/flux/blob/master/deploy/flux-account.yaml#L17
> 
> It gives Flux all access to the cluster, including the possibility to modify roles and permissions. This means that anyone who gets hold of the Flux-operated git repository will able to take full control over the cluster and cut the owners away.
> 
> We preferred to explicitly list operations Flux is actually able to perform, e.g. managing pods, services, configurations, and limit that to absolute minimum.
> 
> Our suggestion here would be to add a comment on your template to make people aware of the fact that they are giving Flux full access to their infrastructure and would possibly want to tailor that."
> 
> 

It'd be great to link to the FAQ from a comment in the YAML bits above. Maybe we have an actual example or repo we can link to there.

**Comment by 2opremio** [comment]
We should also consider having stricter RBAC rules by default.

BTW, this repo is a great example of how to lock Flux down to a single namespace https://github.com/zeeZ/locked-down-flux (the rules can be extended to several namespaces)

**Comment by dholbach** [comment]
This is a long-standing issue apparently: #850 and #1085 ask for a rules review too. Is it hard to decide which rules we can tighten out of fear we'll break people's setup? Would broader integration tests help making a decision?

And thanks for pointing out the example @2opremio!

**Comment by stefanprodan** [comment]
Locking down Flux and the Helm Operator is now possible with `clusterRole.create=false`:

```bash
helm upgrade -i flux weaveworks/flux \
--namespace=myns \
--set helmOperator.create=true \
--set clusterRole.create=false
```

**Comment by stefanprodan** [comment]
When using `clusterRole.create=false` Flux will not be able to deploy namespaces or any other cluster level object. Flux and the Helm Operator will be able to apply objects only in the namespace where Flux is installed, this is enforce with RBAC and role bindings.

**Comment by nlamot** [comment]
Hi @stefanprodan, thanks for this great feature!
However, is it possible that it's not yet included in the latest Helm release of Weave flux (chart 0.10.2)?
When I check the date of that chart, it's 12 days old, while this change is 11 days old.

**Comment by stefanprodan** [comment]
Sorry I should've mention that this is scheduled for next release. Meanwhile you can use the chart from master branch.

**Comment by stefanprodan** [comment]
@nlamot you could also take a look at https://github.com/stefanprodan/fluxcd-multi-tenancy

**Comment by nlamot** [comment]
Hi @stefanprodan, thanks! This looks really awesome!
