### ISSUE TITLE
Refine docs about namespace visibility of Flux

### ISSUE THREAD

**Issue by dholbach** [fluxcd/flux#1887]
Feedback from a user about 

> "[..] limiting Flux's access to a particular namespace only. This is of course possible with the `--k8s-namespace-whitelist` startup switch, but it's not documented in the template.
> 
> Again we think that it would be a good idea to let users know that Flux has visibility of all namespaces by default and that it can be limited as needed."

Good starting points would be https://github.com/weaveworks/flux/blob/master/site/faq.md#can-i-restrict-the-namespaces-that-flux-can-see-or-operate-on and relevant discussion of startup switches (and daemon config?).

**Comment by kingdonb** [comment]
Closing. Flux v2 uses RBAC and `serviceAccountName` if you want to restrict your Kustomizations to a specific namespace or service account.

https://toolkit.fluxcd.io/components/kustomize/kustomization/#role-based-access-control

There is a similar configuration for HelmRelease and Helm Controller as well. Perhaps there should be some RBAC-related FAQ entries, but if so this will have to go on one of the new repos. Thanks for your contributions!
