### ISSUE TITLE
Support installing Istio with Weave Flux

### ISSUE THREAD

**Issue by 2opremio** [fluxcd/flux#1930]
There have been a few users with the need/desire of installing Istio with Flux.

However this is not possible right now since, for Istio to work, it needs to be deployed first-thing since for automatic sidecar injection to work properly. 

Flux doesn't allow you to set dependency rules it only uses the minimum creation ordering rules, see https://github.com/weaveworks/flux/blob/1.12.0/cluster/kubernetes/sync.go#L406-L428 .

**Comment by 2opremio** [comment]
According to a user:
> it turns out if you put istio dependencies in your chart for services then they wait for istio before being created. I can live with that.

**Comment by RoryShively** [comment]
+1

**Comment by stefanprodan** [comment]
Flux v2, based on the GitOps Toolkit, allows users to define the execution order. Using the `dependsOn` filed one can configure the reconciler to install Istio and verify that the injector is healthy before deploying any other workload on the cluster. https://toolkit.fluxcd.io/components/kustomize/kustomization/#kustomization-dependencies
