### ISSUE TITLE
Warn user about mismatching image filter annotations

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux#1936]
Annotating `HelmRelease` resources with image filters can be tricky due to the fact that there is a difference between annotating top- and sub-level images (`chart-image` should be used for the former, `<sub-level>` should be used for the latter).

We can guide people in this by logging a warning in case we find an annotation that does not match a key from the `values` in the `HelmRelease`.

In extend we can also do this for Kubernetes native resources (`Deployment`, `DaemonSet`, etc), and warn the user when an annotation does not match any of the `(init)Containers` names.

**Comment by kingdonb** [comment]
No further enhancements can land in Flux v1,

* #3320
