### ISSUE TITLE
Document formula for memcached `-m` and `-I` setting

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux#1939]
We recently increased the memory limits for memcached to `-m 512`, this is however still insufficient for some users[[1]][[2]].

As there is some sort of formula for determining the size of both arguments we should document this.

`-I = (amountOfTagsForImageWithMostTags * 1000) / 1000000`
`-m = amountOfImages * -I`

[1]: https://weave-community.slack.com/archives/C4U5ATZ9S/p1555349464176900
[2]: https://weave-community.slack.com/archives/C4U5ATZ9S/p1555349500177600

**Comment by UnwashedMeme** [comment]
The README on the chart still reports the max at 128: https://github.com/weaveworks/flux/blob/master/chart/flux/README.md

**Comment by kingdonb** [comment]
At this time, we hope you have already begun migration away from Flux v1 / legacy over to the [current version of Flux](https://github.com/fluxcd/flux2).

We hope you've been able to upgrade to Flux v2, and note that Flux v1 remains in maintenance mode. Bugs with Flux v1 can be addressed as long as it remains in maintenance, according to the plan laid out in the [Flux Migration Timetable](https://fluxcd.io/docs/migration/timetable/). 👍 

Thanks for using Flux.
