### ISSUE TITLE
Flux fails to provision objects longer than 262144 chars

### ISSUE THREAD

**Issue by aaron-trout** [fluxcd/flux#1962]
I am seeing an error where Flux will fail to create a ConfigMap, complaining about the length of annotations. This configmap has a very large `data` section, presumably Flux is using a `kubectl apply` like 3-way merge and storing the last applied config in the annotations which is causing the upset.

Can Flux fall back to a recreate or patch based on current and desired states only?

```
caller=loop.go:210 component=sync-loop err="default:configmap/node-exporter-dashboard: running kubectl: The ConfigMap \"node-exporter-dashboard\" is invalid: metadata.annotations: Too long: must have at most 262144 characters
```

**Comment by 2opremio** [comment]
Thanks for your report.

Yes, Flux is using `kubectl apply`. We could use a new annotation to indicate otherwise (similarly to what's suggested in #1816 )

**Comment by dmitri-lerko** [comment]
Experiencing the same issues around source controlled Grafana dashboards

**Comment by monotek** [comment]
Same grafana dashboard import issue here...

**Comment by Sayrus** [comment]
Same issue with Grafana dashboards and very big generated resources. 

This issue is not well referenced on Google so I'll link it to the relevant issue on:
-  kubernetes/kubectl#712

**Comment by kingdonb** [comment]
Can anyone on the current thread say whether this issue this issue would be continued on Flux v2? I haven't tried reproducing the issue yet, but if I understand `kubectl apply` is the source of the problem, if it is so central to standard kube API client libraries, it might also affect Flux v2 users.

I don't know enough about the implementation of kustomize controller or helm controller to say whether there is a similar issue or if it could still be a problem in the rewritten version.

**Comment by kingdonb** [comment]
I will close the issue for now as it is stale. Flux v1 remains in maintenance mode.

We can provide support to Flux v1 users especially with respect to migrating to the new Flux version, [Flux v2](/fluxcd/flux2), which has some breaking changes but is also a total rewrite and also brings many improvements. I'm closing the issue but you are most welcome to write back on this issue, or open another issue. Thanks for using Flux.
