### ISSUE TITLE
fluxctl release workloads shorthand

### ISSUE THREAD

**Issue by cdenneen** [fluxcd/flux#1981]
Allow `-w` flag to be passed vs currently requiring `--workload`

**Comment by cdenneen** [comment]
`-w` is for `watch` currently but is confusing as it doesn't match the other commands. Consider switching?

**Comment by kingdonb** [comment]
#3320 - Flux v1 is in maintenance mode, so changes that would be breaking existing behavior cannot be considered anymore.

Please check out Flux v2: https://toolkit.fluxcd.io

Closing
