### ISSUE TITLE
UI for Flux & Helm Operator

### ISSUE THREAD

**Issue by kahootali** [fluxcd/flux#2033]
A UI for Flux & Helm Operator, where it shows the HelmReleases it has deployed, and whether they are successful or not. And if Rollback is done (when that feature is implemented)

Currently, when a HelmRelease is deployed, HelmOperator deploys it and if it fails, it logs it and in future it might rollback when the [PR 2006](https://github.com/weaveworks/flux/pull/2006) is implemented. So a developer doesn't know whether his change has been deployed or not and if there was an error and Rollback was done. So there can be a UI where it shows that which HelmReleases are in failed state, which are in deployed and if there has been a Rollback.

**Comment by 2opremio** [comment]
We are not planning to implement a UI for now (and I doubt we would have the bandwidth to maintain a contributed one).

Since you are interested in failures and rollbacks, would monitoring metrics informing about them (e.g. Prometheus metrics) satisfy your needs?

**Comment by squaremo** [comment]
> So there can be a UI where it shows that which HelmReleases are in failed state

`fluxctl list-workloads` will show the release status of HelmReleases, so arguably there is a UI for this.

**Comment by runningman84** [comment]
A Prometheus metric would be a good first step!

**Comment by squaremo** [comment]
> `fluxctl list-workloads` will show the release status of HelmReleases

I am wrong about this -- it used to, but at least at the minute, the flux API doesn't include the Helm release status

**Comment by ysaakpr** [comment]
the need for a web UI can be debated, but to know the real status of the helm release if it failed is something very important to have. As of now, sometimes even though the HelmRelease is created, but helm was unable to install them and cause failure...but there is no way the developer to get know about it. We had to go through the logs.

**Comment by huapox** [comment]
> There is an UI for Flux in the making here https://github.com/flux-web/flux-web

Great!

**Comment by sureshamk** [comment]
check out this project  -> https://github.com/sureshamk/flux-ui 

<img width="512" alt="Home" src="https://raw.githubusercontent.com/sureshamk/flux-ui/master/docs/screen-shots/Home.png">

---
<img width="512" alt="Home" src="https://raw.githubusercontent.com/sureshamk/flux-ui/master/docs/screen-shots/detail.png">
---
<img width="512" alt="Home" src="https://raw.githubusercontent.com/sureshamk/flux-ui/master/docs/screen-shots/action.png">
---
<img width="512" alt="Home" src="https://raw.githubusercontent.com/sureshamk/flux-ui/master/docs/screen-shots/list-images.png">

**Comment by 2opremio** [comment]
Nice!!!

**Comment by kingdonb** [comment]
Flux v1 is in maintenance mode now, and is not adding any new features unless they are critical.

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2) – there is also a new project under development, [fluxcd/webui](https://github.com/fluxcd/webui) to bring a web UI to Flux v2.

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, I will go ahead and close out this issue for now.
