### ISSUE TITLE
Flux Kubernetes event-driven synchronization

### ISSUE THREAD

**Issue by bzon** [fluxcd/flux#2112]
**Describe the feature**
Make flux have the option to sync Kubernetes resources in Git in an event-driven fashion.

At the moment, when someone modified/deleted a resource that was **kubectl applied** by Flux, we have to wait for Flux to run the next git sync operation to restore the modified/deleted resource.

With this feature, Flux will sync manually tainted resources **immediately**. 

**What would the new user story look like?**
1. Users add labels to the Kubernetes resources in YAML files with **managed.by.flux=true**. Optionally, if feasible to do, Flux will automatically add this label to all the resources in YAML files.
2. During runtime, Flux periodically collects and reads all Kubernetes resources in YAML files with **managed.by.flux=true** label.
3. Flux starts watching the events for all the collected resources using label selectors.
4. Now, when someone deleted/modified a Kubernetes resource that belongs in the collected resources, Flux will run a read/compare/sync operation ONLY for the deleted/modified resource.

**Expected behavior**

When someone **manually** deleted/modified a resource that is managed in the Flux Git repository, Flux will reconcile immediately.

**Comment by bzon** [comment]
I can **maybe** submit a PR if this is validated. 😄 👍

**Comment by squaremo** [comment]
I understand the motivation for this. I think it'd be a significant investment of time to get a PR working -- but please do not let me dampen your enthusiasm! :grinning:

Some things that occur to me:

 - Flux already labels everything it syncs, for garbage collection purposes; I think it would be feasible to treat everything so labelled as under control of Flux, for this purpose too
 - This feature should respect the `flux.weave.works/ignore` annotation (meaning: don't sync!)
 - To reduce API connections and traffic, it may be necessary to coalesce watches; e.g., rather than have a watch for each resource under control, have one for the resource type and namespace (and label). This will require some careful bookkeeping.

**Comment by bzon** [comment]
@squaremo 

> * To reduce API connections and traffic, it may be necessary to coalesce watches; e.g., rather than have a watch for each resource under control, have one for the resource type and namespace (and label). This will require some careful bookkeeping.

This makes sense. The Kubernetes API resources are already built this way with each having a **Watch** method. 

```golang
        c := client.ExtensionsV1beta1().Ingresses(namespace)
	watch, _ := c.Watch(v1.ListOptions{
		LabelSelector: "flux-sample-label",
	})
	for event := range watch.ResultChan() {
		select event.Type {
                case event.Modified, event.Deleted:
                      // Do new flux feature sync logic
                }
	}
```

We can probably start applying it first starting with some of the most used resource types such as Namespace, Deployment, Ingresses, and Services.

> * Flux already labels everything it syncs, for garbage collection purposes; I think it would be feasible to treat everything so labelled as under control of Flux, for this purpose too
> * This feature should respect the `flux.weave.works/ignore` annotation (meaning: don't sync!)

Then these help this proposed feature get started right away.

**Comment by stefanprodan** [comment]
@bzon the watch example you posted will not work with custom resources. You'll have to discover the CRD installed in the cluster and use the dynamic client-go to watch for changes.

**Comment by bzon** [comment]
@stefanprodan I see. It can be really hacky to track CRDs then. Anyways, the resources that benefit the most from this feature are the standard k8s resources. Like I said in the previous comment, we can apply this feature gradually for resources that we know that we can track/watch/converge easily.

**Comment by kingdonb** [comment]
Please let me know if you still need help with this. I apologize for the staleness of this reply, we are in the process of cleaning up stale issues from the Flux v1 repo now, this should be over soon.

I will close the issue for now as it is stale. Flux v1 remains in maintenance mode. Although I can still review and accept some pull requests, there is little labor effort available to develop the Flux v1 codebase and are no new features being added to Flux v1 daemon and this is generally critical fixes only situation at this point.

We can provide support to Flux v1 users especially with respect to migrating to the new Flux version, [Flux v2](/fluxcd/flux2), which has some breaking changes but is also a total rewrite and also brings many improvements. I'm closing the issue but you are most welcome to write back on this issue, or open another issue. Thanks for using Flux.
