### ISSUE TITLE
Better gcloud git credential helper support

### ISSUE THREAD

**Issue by dmarkwat** [fluxcd/flux#2119]
Allow adding custom allowed env vars passed down to git. OR, simply add the Google gcloud sdk env vars, `CLOUDSDK_CONFIG` and `CLOUDSDK_PYTHON` to the allowed list, [here](https://github.com/weaveworks/flux/blob/master/git/operations.go#L28).

Further, in Helm it'd be possible to add a separate config block and templates to support GCSR in the same way AWS ECR is supported, for example. But given the requirement to add the google cloud SDK, I'd understand if this kind of change would be a reach.

**Explanation**

Google cloud source repositories support an awkward flow for using service accounts due to the lack of support for deploy keys and service account ssh keys. In lieu of these ssh keys, the Google Cloud SDK provides a git credential helper which can be wired like so when deploying flux with with Helm (see [gitconfig data section](https://github.com/weaveworks/flux/blob/master/chart/flux/values.yaml#L150)):
```
[credential "https://source.developers.google.com"]
    helper = /path/to/sdk/bin/git-credential-gcloud.sh
    username = <service account>@<project qualified name>
```

But, because flux limits the env vars passed down to the git clone/push/etc commands, this credentials helper must use a workaround or rely on the default credential location which requires complicated and possibly faulty volume mounting.

The workaround requires making a gitconfig change that should ideally be resolved using the pod env vars:
```
[credential "https://source.developers.google.com"]
    helper = !CLOUDSDK_CONFIG=/path/to/config /path/to/sdk/bin/git-credential-gcloud.sh
    username = <service account>@<project qualified name>
```

Ultimately, this change isn't required because of the workaround, but it would make using GCSR more k8s-idiomatic with less knowledge of flux and git guts required.

**What would the new user story look like?**
With the extra env var overrides:
- Start flux using a new arg, e.g., `--gitAllowedEnvVars CLOUDSDK_CONFIG,CLOUDSDK_PYTHON`
- Flux then passes those env vars down to `git`, enabling seamless operation with a GCSR git repo regardless of auth method
- Flux continues operation as normal

*It's assumed the requisite `gcloud auth activate-service-account --key-file=/path/to/key/file` was called in an `initContainer` and whose contents are referred to with `CLOUDSDK_CONFIG` and stored in a k8s volume. And it's also assumed the google cloud sdk is mounted with a volume or part of a custom, derived image of flux.*

**Expected behavior**
The extra env vars are allowed to pass down to `git` so tools like `gcloud` know where to obtain config and a proper python path.

**Comment by squaremo** [comment]
Thanks for this well-explained feature request :+1: 

I have no problem with allowing the extra env variables, either hard-wired or as an argument. It sounds like that would remove some pain.

**Comment by kingdonb** [comment]
This issue was referenced by a PR, I hope this addressed your issue.

Please let me know if you still need help with this. I apologize for the staleness of this reply, we are in the process of cleaning up stale issues from the Flux v1 repo now, this should be over soon.

I will close the issue for now as it is stale. Flux v1 remains in maintenance mode.

We can provide support to Flux v1 users especially with respect to migrating to the new Flux version, which has some breaking changes but is also a total rewrite and also brings many improvements. I'm closing the issue but you are most welcome to write back on this issue, or open another issue. Thanks for using Flux.
