### ISSUE TITLE
Configure the timeout through config

### ISSUE THREAD

**Issue by ysaakpr** [fluxcd/flux#2164]
**Describe the feature**
Frequently getting timeout error from `fluxctl sync`
00:01:27.763  Revision of master to apply is 9f4154b
00:01:27.763  Waiting for 9f4154b to be applied ...
00:02:35.601  Error: timeout
00:02:35.601  Run 'fluxctl sync --help' for usage.

Can we configure these timeout values from external

https://github.com/weaveworks/flux/blob/bbc08650bcff3304ca2083e5c46b6f2d2dc9a42d/cmd/fluxctl/await.go#L66

**Comment by hiddeco** [comment]
This is being worked on in #2056. I will see if I can perform some CPR on that PR...
