### ISSUE TITLE
Guidance on deploying multiple containers using Flux

### ISSUE THREAD

**Issue by atbe-crowe** [fluxcd/flux#2166]
Hi all,

I was able to successfully setup flux to deploy one of our applications to kubernetes using Helm. The app was a simple one container nginx application and the flux automation worked flawlessly.

This was my Flux repository setup at that stage:

```
C:\Data\Projects\git\AtfInsights-flux 
├── /charts                           
|  ├── /atf-insights-angular-app      
|  |  ├── Chart.yaml                  
|  |  ├── /charts                     
|  |  ├── /templates                  
|  |  └── values.yaml         
├── LICENSE                           
├── /namespaces                       
|  ├── dev.yaml                       
|  ├── prod.yaml                      
|  └── stg.yaml                       
├── README.md                         
└── /releases                         
   ├── /dev                           
   |  └── podinfo.yaml                
   ├── /prod                          
   |  └── podinfo.yaml                
   └── /stg                           
      └── podinfo.yaml
```

So now I had a *second* container that I wanted to add to the deployment, because our application is composed of several services.

The question is, **should I be using a second HelmRelease file with its own chart to deploy this second service**? That's what I tried, which brought me to this directory structure:

```
C:\Data\Projects\git\AtfInsights-flux
├── /charts
|  ├── /atf-insights-angular-app
|  |  ├── Chart.yaml
|  |  ├── /charts
|  |  ├── /templates
|  |  └── values.yaml
|  └── /atf-insights-report-service
|     ├── Chart.yaml
|     ├── /templates
|     └── values.yaml
├── LICENSE
├── /namespaces
|  ├── dev.yaml
|  ├── prod.yaml
|  └── stg.yaml
├── README.md
└── /releases
   ├── /dev
   |  ├── report-service.yaml
   |  └── webapp.yaml
   ├── /prod
   |  └── podinfo.yaml
   └── /stg
      └── podinfo.yaml
```

Notice now how there is `releases/dev/report-service.yaml` and `releases/dev/webapp.yaml`. Does Flux support multiple `HelmRelease` specs in the same folder for a release?

I pushed these changes to the master branch of my flux repo, and the `HelmRelease` object was indeed created successfully, but when I check on the object, this is the result:

```
kubectl get HelmRelease atf-insights-report-service -n atfinsights-dev -o yaml
>
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/sync-checksum: 9c46287c2e334ef2b646ffa4df11e1dbe5c75b3a
    flux.weave.works/tag.chart-image: glob:dev-*
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"flux.weave.works/v1beta1","kind":"HelmRelease","metadata":{"annotations":{"flux.weave.works/automated":"true","flux.weave.works/sync-checksum":"9c46287c2e334ef2b646ffa4df11e1dbe5c75b3a","flux.weave.works/tag.chart-image":"glob:dev-*"},"labels":{"flux.weave.works/sync-gc-mark":"sha256.QbO6MhoVWOuENawopmV6uyS8ZcoU5k8klI8fs3ba-Ks"},"name":"atf-insights-report-service","namespace":"atfinsights-dev"},"spec":{"chart":{"git":"attax@vs-ssh.visualstudio.com:v3/attax/TaxPlatform/AtfInsights-flux","path":"charts/atf-insights-report-service","ref":"master"},"releaseName":"atfinsights-dev-report-service","values":{"image":{"tag":"dev-25030187aaec7e354cea39dcfc5204e2b5aacc7e"},"replicaCount":1}}}
  creationTimestamp: 2019-06-18T15:08:37Z
  generation: 1
  labels:
    flux.weave.works/sync-gc-mark: sha256.QbO6MhoVWOuENawopmV6uyS8ZcoU5k8klI8fs3ba-Ks
  name: atf-insights-report-service
  namespace: atfinsights-dev
  resourceVersion: "2437822"
  selfLink: /apis/flux.weave.works/v1beta1/namespaces/atfinsights-dev/helmreleases/atf-insights-report-service
  uid: f2dfcd34-91da-11e9-85bf-02800a58bf57
spec:
  chart:
    git: attax@vs-ssh.visualstudio.com:v3/attax/TaxPlatform/AtfInsights-flux
    path: charts/atf-insights-report-service
    ref: master
  releaseName: atfinsights-dev-report-service
  values:
    image:
      tag: dev-25030187aaec7e354cea39dcfc5204e2b5aacc7e
    replicaCount: 1
status:
  conditions:
  - lastTransitionTime: 2019-06-18T15:10:52Z
    message: successfully cloned git repo
    reason: GitRepoCloned
    status: "True"
    type: ChartFetched
  - lastTransitionTime: 2019-06-18T15:10:53Z
    message: helm install succeeded
    reason: HelmSuccess
    status: "True"
    type: Released
  releaseName: ""
  releaseStatus: ""
  revision: 3381530cf3e32223ae49a4cbd7c5a69b208fbb77
```

Notice how the "HelmSuccess" is listed as type "Released" but the `releaseName` is empty.

When I run `helm ls` the `report-service` is not listed.

Is this the approach I should be taking to deploy an application composed of several Helm charts? If so, why is my `releaseName` empty?

If this is not the approach I should be taking, how should I go about deploying these two helm charts in tandem?

Thanks so much for any help anyone can provide.

**Comment by atbe-crowe** [comment]
**Followup**

It looks like my issue with the Helm release not getting created was an issue with the chart itself having some syntax issues (thanks Microsoft for the faulty chart :( )

I still would love an answer to this question:

"Which of the two deployment patterns is better for an application with multiple deployable charts?"

1. Create multiple `HelmRelease` objects each deploying an individual chart
2. Create a single `HelmRelease` object that uses an "umbrella" Helm chart that brings together all of the required Helm charts

From a deployment standpoint, I feel like option 2 is the better option because it will ensure that it's an all-or-nothing deployment. That is, if one of the subcharts fails to deploy, the whole deployment would be marked as a failure.

**Comment by kingdonb** [comment]
Please let me know if you still need help with this. I apologize for the staleness of this reply, we are in the process of cleaning up stale issues from the Flux v1 repo now, this should be over soon.

I will close the issue for now as it is stale. Flux v1 remains in maintenance mode.

We can provide support to Flux v1 users especially with respect to migrating to the new Flux version, [Flux v2](/fluxcd/flux2), which has some breaking changes but is also a total rewrite and also brings many improvements. I'm closing the issue but you are most welcome to write back on this issue, or open another issue. Thanks for using Flux.
