### ISSUE TITLE
Provide the reason for rollouts in the kubernetes.io/change-cause annotation

### ISSUE THREAD

**Issue by dlespiau** [fluxcd/flux#2173]
**Describe the feature**

Kubernetes can store the reasons for new Deployment rollouts in an `http://kubernetes.io/change-cause` annotation and `kubectl rollout history $mydeployment` will show the list of change reasons:

https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#checking-rollout-history-of-a-deployment

It'd be nice if flux could mirror (some of) the git history to that annotation so we can inspect the reasons that lead to new versions of a deployment through `kubectl` (or any other tooling that can talk to the api server, displaying the reason of cluster change in a UI for instance).

**What would the new user story look like?**

How would the new interaction with Flux look like? E.g.
1. User commits a new change with a commit message: "Update foo to 1.2.3"
1. *Somehow* this message makes its way to the annotation
1. `kubectl rollout history foo` shows "Update foo to 1.2.3" as the change reason.

**Expected behavior**

It's debatable what to do here but, for instance, we could copy the subject (first line) of the git commit message into that annotation (with a characters limit?).

**Comment by dlespiau** [comment]
flux currently discards that annotation when storing the deployment back to git. I'm not suggesting we should copy that annotation to git, seems fine to leave it in etcd. I'm more thinking of a git -> etcd path: the user (or a process like flux) commits a change, the first line of the commit message is stored in that annotation.

**Comment by squaremo** [comment]
The sequence of operations is this:

 - someone asks flux to release a new image
 - fluxd rewrites the manifest(s) in git and commits the change
 - ... another process sees there's a new commit, and `kubectl apply`s everything

fluxd does record which commits are image releases (using git notes); but it's not always the case that it's applying a single commit at a time. So, the link between changing a deployment, and that change being effected, is not straight-forward.

We could certainly use `--record` when applying manifests, which would give rollouts _something_ to put in that column in the output, though it would always be `kubectl apply -f -`.

**Comment by dlespiau** [comment]
Maybe recording which commit(s) have been applied would be a thing:

```
REVISION    CHANGE-CAUSE
1           flux apply git@github.com:user/flux.git master $hash
2           flux apply git@github.com:user/flux.git master $hash1..$hash2
```

**Comment by hbouissoumer** [comment]
Any updates on this feature? Thank you!

**Comment by netflash** [comment]
G’Day! 
I also like this feature to be implemented.

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
