### ISSUE TITLE
OCP4 - first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by mvazquezc** [fluxcd/flux#2174]
**Describe the bug**
When running flux on OpenShift 4, it fails to parse the image-registry url.

**To Reproduce**
Steps to reproduce the behaviour:

Deploy flux on OpenShift 4 following the steps documented [here](https://github.com/weaveworks/flux/blob/master/site/get-started.md)

Tail the flux logs.

**Expected behavior**
The image-registry url is parsed correctly.

**Logs**

172.31.76.157 corresponds to the image-registry service:

image-registry      ClusterIP      172.31.76.157   5000/TCP

ts=2019-06-20T10:15:25.794557659Z caller=images.go:106 resource=flux:deployment/flux err="parse 172.31.76.157:5000: first path segment in URL cannot contain colon"
ts=2019-06-20T10:15:25.802524618Z caller=images.go:106 resource=flux:deployment/memcached err="parse 172.31.76.157:5000: first path segment in URL cannot contain colon"
ts=2019-06-20T10:16:25.784916558Z caller=images.go:106 resource=flux:deployment/flux err="parse 172.31.76.157:5000: first path segment in URL cannot contain colon"
ts=2019-06-20T10:16:25.79297563Z caller=images.go:106 resource=flux:deployment/memcached err="parse 172.31.76.157:5000: first path segment in URL cannot contain colon"

**Additional context**

- Flux version: docker.io/weaveworks/flux:1.13.0
- Helm Operator version:  N/A
- Kubernetes version: v1.13.4
- Git provider: GitHub
- Container registry provider: OpenShift Image Registry

**Comment by hiddeco** [comment]
What does the full image ref look like?

**Comment by hiddeco** [comment]
This should have been resolved by #2248
