### ISSUE TITLE
Support git checkout over http proxy

### ISSUE THREAD

**Issue by davidkarlsen** [fluxcd/flux#2179]
**Describe the feature**
See https://gitolite.com/git-over-proxy.html
If socat could be included in the image then checkout against github would be supported for environments locked down behind a corporate proxy. This would also mean exposing an option to configure /root/.ssh/config via the helm-chart.

**What would the new user story look like?**
How would the new interaction with Flux look like? E.g.
0. install flux
1. configure ssh-config to use socat

Feel free to add a diagram if that helps explaining things.

**Expected behavior**
Checkouts would go via http-proxy

**Comment by davidkarlsen** [comment]
Another option would be to checkout over https as normally but support username + token as described in https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line

**Comment by hiddeco** [comment]
Besides to adding `socat`, the `GIT_PROXY_COMMAND` environment variable also needs to be whitelisted.

https://github.com/weaveworks/flux/blob/master/git/operations.go#L28
