### ISSUE TITLE
Make upstream its own component

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#2181]
To decouple Flux from Weave Cloud, the "upstream" part of the daemon should be moved into its own component (call it "weave cloud adapter"), and repo.

There are two functions to the upstream:

 1. connect a websocket to the service and convey RPC calls from the service to the daemon
 2. POST events to the service

The first can be done by the adapter making the websocket connection, and calling the flux API. Other than making sure the API is available to it (e.g., on localhost), that code can just be removed from the daemon, since it already serves the API.

The second has to be supported in the daemon, but could be made more general. The adapter would do the necessary authentication to weave cloud -- that's really the only thing that's particular to weave cloud.

The flux daemon would lose its `--connect` argument, and gain (say) a `--event-hook` argument, for the URL to which to post events.

One nice side-effect of this is that third party kit can _just_handle the events, and not have to support pointless websocket connections.

**Comment by squaremo** [comment]
weaveworks/flux-adapter is a sidecar that can be used to connect to Weave Cloud. At present, it will relay events _and_ accept websocket connections, so can be used with recent builds (after #2210) of flux, by setting the `--connect` argument to `https://localhost:3039` (the token argument is no longer necessary -- the adapter does that bit now).

We will need to have a window in which both kinds of deployment (connect directly to service vs use sidecar) are possible, to let people switch over.

**Comment by squaremo** [comment]
> The flux daemon would lose its `--connect` argument, and gain (say) a `--event-hook` argument, for the URL to which to post events.

Alternatively:

 - remove the upstream websocket connection
 - add an argument `--event-hook` for where to POST events
 - deprecate `--connect` but treat it as a synonym for `--event-hook` when supplied

**Comment by gled4er** [comment]
Hello @squaremo,

I wanted to ask you if the new `--event-hook` will give us the required capabilities as described in https://github.com/fluxcd/flux/issues/1128 or the context is different?

Thank you!

**Comment by squaremo** [comment]
The `--event-hook` described here is just for reporting events _out_ of the daemon -- it's an event sink. However: #2211 added the _incoming_ hooks to the HTTP API -- so, in master branch, they already exist, and an ingress or other service could ping them.

**Comment by gled4er** [comment]
This is very helpful! Thank you for the clarification @squaremo !

**Comment by gled4er** [comment]
@squaremo  may I ask you one more question? Will the typical use for `NotifyChange` is to inform Flux that there is change so it needs to update the state of cluster? If so, I think we are looking for a little bit different feature - when Flux is done applying certain change to the cluster it will send a payload to external system (in our case CI/CD). 

Thank you!

**Comment by jwenz723** [comment]
> > The flux daemon would lose its `--connect` argument, and gain (say) a `--event-hook` argument, for the URL to which to post events.
> 
> Alternatively:
> 
> * remove the upstream websocket connection
> * add an argument `--event-hook` for where to POST events
> * deprecate `--connect` but treat it as a synonym for `--event-hook` when supplied
> 
> This is still backward-_in_compatible, because you need the extra adapter in your configuration -- but it's a little gentler, since you don't have to change the arguments passed _and_ the version run _and_ the configuration at exactly the same time.

I think a generic style webhook with `--event-hook` would make the most sense. And then run the flux-adapter as an optional sidecar that receives those webhook events by setting `--event-hook=http://localhost:someport`. 

I would be open to helping to get this working. Any suggestions on where I would start?

**Comment by kingdonb** [comment]
I'm going to assume with the advent of `notification-controller` in Flux v2, the completion of this feature is no longer strategic or important for the future, and thus it can be closed.

🌴
