### ISSUE TITLE
Standardise authentication for fluxctl

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#2182]
fluxctl has an (optional) authentication scheme that is useless for anything but Weave Cloud. It'd be much better if it supported a standard authentication scheme, so it has a chance of working with third party kit.

Just supporting a [bearer token in a standard `Authorization` header](https://tools.ietf.org/html/rfc6750) would be enough to start with.

**Comment by kingdonb** [comment]
This issue describes a new feature, which is not destined to be included in Flux v1 at this point.

(Flux v1 is in maintenance, closing.)
