### ISSUE TITLE
Make default committer flags mandatory

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#2188]
At present, fluxd accepts flags `--git-user` and `--git-email` giving the committer name for git. The defaults give the name `Weave Flux <flux@weave.works>` when put together.

These should really have always been mandatory and not given defaults -- the only reason they have defaults is that Weaveworks was the first user and as such it was convenient.

Making them mandatory is a backward-incompatible change, as as such, we should lump it in with other such changes, as well as soften the impact by updating example configs, charts etc.

(NB they only need to be supplied _if_ git is configured and not read-only)

**Comment by kingdonb** [comment]
As a backward-incompatible change, this cannot be included in Flux v1 anymore before the maintenance period is at its end.

Closing.
