### ISSUE TITLE
Query regarding experimental status of syncGarbageCollection.dry and syncGarbageCollection.enabled  flags

### ISSUE THREAD

**Issue by maniSbindra** [fluxcd/flux#2214]
Hi,

We are planning to use either **syncGarbageCollection.dry**  or **syncGarbageCollection.enabled** flags in one of our implementations. I understand these flags are  currently in **experimental** state. Wanted to get a view regarding whether these flags are likely to be moved out of the experimental status soon? 

Thanks.

**Comment by kingdonb** [comment]
Please let me know if you still need help with this. I apologize for the staleness of this reply, we are in the process of cleaning up stale issues from the Flux v1 repo now, this should be over soon.

I will close the issue for now as it is stale. Flux v1 remains in maintenance mode.

We can provide support to Flux v1 users especially with respect to migrating to the new Flux version, [Flux v2](/fluxcd/flux2), which has some breaking changes but is also a total rewrite and also brings many improvements. I'm closing the issue but you are most welcome to write back on this issue, or open another issue. Thanks for using Flux.

**Comment by maniSbindra** [comment]
Thank you.
