### ISSUE TITLE
Flux+Kustomize integration doesn't seem to apply namespace specs

### ISSUE THREAD

**Issue by donreilly** [fluxcd/flux#2218]
When applying specs via kustomize, flux doesn't seem to apply any namespace spec in the overlay directory. Each overlay has its on unique namespace, which is generated and placed into the overlay directory like `quickstart/ns.yaml`. Flux attempts to apply everything else to no avail, obviously, since the namespace doesn't exist. Manually running `kustomize build .` in the overlay directory itself includes the namespace spec in the output, so if I manually apply this it works fine.

**To Reproduce**
The directory structure I'm using is something like:
```
├── base
└── overlays
    └── quickstart
        ├── configmaps
        │   ├── app1.yaml
        ├── kustomization.yaml
        └── ns.yaml
```
kustomization.yaml contains the namespace resource:

```
resources:
  - ns.yaml
```

**Expected behavior**
I would expect the namespace to get deployed alongside the other resources.

**Logs**
```flux-b46567b4f-mqmtl flux ts=2019-07-03T16:39:49.265563023Z caller=sync.go:546 method=Sync cmd="kubectl apply -f -" took=212.73122ms err="running kubectl: Error from server (NotFound): error when creating \"STDIN\": namespaces \"quickstart\" not found" output=```

**Comment by 2opremio** [comment]
Do you have a self-contained example (ideally a git repo) where this happens? (Including relevant flux flags, like the git paths).

**Comment by stefanprodan** [comment]
Works for me with Flux 1.13.1, I've tested it with https://github.com/stefanprodan/fluxcd-multi-tenancy/tree/master/cluster/team1

**Comment by 2opremio** [comment]
The `.flux.yaml` file is missing from your file-tree listing. Where is it placed and what are its contents?

(Ideally I would still prefer a fully-container example).

**Comment by gaffneyd4** [comment]
I found the issue we were experiencing, it was flux-unrelated user error.
This issue can be closed.
I'm leaving the problem and solution here in case someone else runs into something similar:

Example directory structure:
```
├── base
│   └── example-config.yaml
└── overlays
    ├── .flux.yaml
    ├── blue
    │   ├── kustomization.yaml
    │   └── ns.yaml
    └── quickstart
        ├── kustomization.yaml
        └── ns.yaml
```

```
# .flux.yaml
version: 1
commandUpdated:
  generators:
    - command: ls -A1 -d */ | tr -d / | xargs -I {} kustomize build ./{}/
```
ouput from `ls -A1 -d */ | tr -d /`
```
blue
quickstart
```
output from generator
```
apiVersion: v1
kind: Namespace
metadata:
  name: blue
---
apiVersion: v1
data:
  example.json: |
    {
    "FOO": "bar",
    }
kind: ConfigMap
metadata:
  name: example-config
  namespace: blue
apiVersion: v1
kind: Namespace
metadata:
  name: quickstart
---
apiVersion: v1
data:
  example.json: |
    {
    "FOO": "bar",
    }
kind: ConfigMap
metadata:
  name: example-config
  namespace: quickstart
```

The problem:
The xargs command runs kustomize for each overlay, and the stdout gets appended together between runs without being "kustomize-aware". Therefore there was no `---` document separator between the `blue` `example-config` ConfigMap resource and the `quickstart` Namespace resource. This made the second (`quickstart`) Namespace resource invalid and prevented it from creating successfully, causing the originally posted error message.

`err="running kubectl: Error from server (NotFound): error when creating \"STDIN\": namespaces \"quickstart\" not found" output=`

```
# an example fix update to .flux.yaml
version: 1
commandUpdated:
  generators:
    - command: ls -A1 -d */ | tr -d / | xargs -I % sh -c 'echo ---; kustomize build ./%/;'
```

fixed output from generator
```
apiVersion: v1
kind: Namespace
metadata:
  name: blue
---
apiVersion: v1
data:
  example.json: |
    {
    "FOO": "bar",
    }
kind: ConfigMap
metadata:
  name: example-config
  namespace: blue
---
apiVersion: v1
kind: Namespace
metadata:
  name: quickstart
---
apiVersion: v1
data:
  example.json: |
    {
    "FOO": "bar",
    }
kind: ConfigMap
metadata:
  name: example-config
  namespace: quickstart
```

**Comment by stefanprodan** [comment]
Here is another way to accomplish this:

1. Place `.flux.yaml` in the root of the repo
2. Set the command to `kustomize build .` 
3. Create a `kustomization.yaml` file next to` .flux.yaml` in the repo root and use all the other customisations as base:

```yaml
bases:
  - ./overlays/blue/
  - ./overlays/quickstart/
```
