### ISSUE TITLE
URL not found

### ISSUE THREAD

**Issue by ctit-cl** [fluxcd/flux#2241]
The url for add the repo of flux is 404 code

helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Unable to get an update from the "weaveworks" chart repository (https://weaveworks.github.io/flux):
	Failed to fetch https://weaveworks.github.io/flux/index.yaml : 404 Not Found
...Successfully got an update from the "stable" chart repository
Update Complete.

**Comment by fnmeissner** [comment]
I am experiencing this issue, too.

When I try to install flux using helm following the documentation at https://github.com/fluxcd/flux/blob/master/site/helm-get-started.md, I get the following error:
```
Error: failed to download "fluxcd/flux" (hint: running `helm repo update` may help)
```

The documentation (https://github.com/fluxcd/flux/blob/master/site/helm-get-started.md) lists the former address: https://weaveworks.github.io/flux which is not available anymore.

When I check https://fluxcd.github.io/flux/index.yaml, I find a repository, but the urls still reference the old url:

```
http https://fluxcd.github.io/flux/index.yaml | grep tgz
    - https://weaveworks.github.io/flux/flux-0.10.2.tgz
    - https://weaveworks.github.io/flux/flux-0.10.1.tgz
    - https://weaveworks.github.io/flux/flux-0.10.0.tgz
...
```

I guess the repository has to be updated as well as the documentation.

Greetings, Felix

**Comment by hiddeco** [comment]
This should now be fixed, and includes a new chart release.
