### ISSUE TITLE
Flux not being able to move sync-tag if --force prevented from git repo

### ISSUE THREAD

**Issue by cazzoo** [fluxcd/flux#2247]
**Describe the bug**
When flux synch with git repo, it adds a sync-tag to identify last state.
If we add a pre-push hook to prevent --force commits on git repo, it prevents flux to get its tag moved from previous commit to the latest.

**To Reproduce**
Steps to reproduce the behaviour:
0. Setup a git pre-push hook to prevent --force push
1. Setup flux to track your git cd repo
2. Let flux to sync once
3. Update your cd adding a new commit
4. See flux error telling he's not able to move tag

**Expected behavior**
Flux should be able to move tag sync. Currently he's push forcing the tag to the new commit id.
Perhaps flux could push the tag deletion then push the tag creation.

**Comment by kingdonb** [comment]
Please let me know if you still need help with this. I apologize for the staleness of this reply, we are in the process of cleaning up stale issues from the Flux v1 repo now, this should be over soon.

Flux v2 no longer utilizes a flux-sync git tag in the repo for accounting.

I will close the issue for now as it is stale. Flux v1 remains in maintenance mode.

We can provide support to Flux v1 users especially with respect to migrating to the new Flux version, which has some breaking changes but is also a total rewrite and also brings many improvements. I'm closing the issue but you are most welcome to write back on this issue, or open another issue. Thanks for using Flux.
