### ISSUE TITLE
ForceUpgrade is not honoured by Helm Operator

### ISSUE THREAD

**Issue by adusumillipraveen** [fluxcd/flux#2265]
**Describe the bug**
Helm operator doesn't honour forceupgrade . We had a  [Helm Release](https://github.com/hmcts/cnp-flux-config/blob/426ae4e21fe959fb5bc4d9dccb3b0f782e75d8a8/k8s/demo/common/money-claims/cmc-demo.yaml#L13) with forceUpgrade set to true . Initial helm release failed and helm operator doesn't force upgrade even after changing the chart version . 

**To Reproduce**
Steps to reproduce the behaviour:
0. Install flux with helm operator 0.10.0
1. Have a broken HelmRelease in flux config with forceUpgarde true
2. Fix the flux config to make it work 
3. Helm Operator doesn't upgrade,  instead errors

**Expected behavior**
Expect helm operator to force upgrade the helm release .

**Logs**
```resource=money-claims:helmrelease/cmc-demo
ts=2019-07-17T09:53:36.52873112Z caller=chartsync.go:328 component=chartsync warning="unable to proceed with release" resource=money-claims:helmrelease/cmc-demo release=cmc-demo err="release requires a rollback before it can be upgraded (FAILED)
```

**Additional context**
Add any other context about the problem here, e.g 
- Flux version:  flux:1.13.2
- Helm Operator version: helm-operator:0.10.0
- Kubernetes version: v1.13.5
- Git provider: GitHub
- Container registry provider: ACR

**Comment by hiddeco** [comment]
_Rewrite of info already [shared on Slack](https://weave-community.slack.com/archives/C4U5ATZ9S/p1563356744356300) to keep everything in one place._

This is not a bug but I can see where your expectation is coming from.

Flux will only move healthy releases forward, one of the reasons for this is to ensure we do not end up in a loop of failure, the `--force` flag is thus not intended to be used to force the upgrade of an unhealthy resource (you should use the [rollback feature](https://github.com/fluxcd/flux/blob/8292179855e15370fb3d3b03135a61b54f00ae42/site/helm-integration.md#rollbacks) for this) but was developed to make it possible to upgrade charts with e.g. backwards incompatible changes (changes on immutable fields for example, which require a resource to be removed first, see #1760).

**Conclusion:** the `forceUpgrade` is honoured, but can not be used to force the upgrade of a release in an `UNHEALTHY` state.

**Comment by adusumillipraveen** [comment]
Thanks for the explanation,
