### ISSUE TITLE
flux: git url example

### ISSUE THREAD

**Issue by aliartiza75** [fluxcd/flux#2275]
**Describe the bug**
In the `values.yaml`, an example has been provided in which it shows how to add the URL of the repository. An example is given below:

```bash
ssh://git@github.com/weaveworks/flux-get-started
```

The problem with this example is that it works well with `Github` but not works properly with bitbucket, for bitbucket we have to provide URL in this format

```
git@github.com/weaveworks/flux-get-started
```

I think an example for each version control service like Gitlab and bitbucket must be provided because it took a lot of time to figure out how it will work with bitbucket. 

**To Reproduce**

0. Run flux for bitbucket repository.

**Expected behaviour**
Examples must be provided for different version control services. 

**Logs**
I haven't stored the logs but in logs it shows that it wasn't able to resolve the url.

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.13.2
- Helm Operator version: NIL
- Kubernetes version: NIL
- Git provider: Bitbucket
- Container registry provider: NIL

**Comment by aliartiza75** [comment]
@dholbach @hiddeco kindly review this issue. thank you!

**Comment by squaremo** [comment]
The syntax `git@github.com:weaveworks/flux-get-started` is equivalent to `ssh://git@github.com/weaveworks/flux-get-started` -- it's just a shortcut, built into git. If you're having trouble with one working and not the other, it may be because there's a non-obvious difference: when using the scp-style syntax, you must use a colon rather than a slash between the host and the path (i.e., your second example is wrong).

**Comment by squaremo** [comment]
By way of proof:

```
~/scratch $ git clone git@bitbucket.org:mbridgen/dummy.git dummy-1
Cloning into 'dummy-1'...
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (6/6), done.

~/scratch $ git clone ssh://git@bitbucket.org/mbridgen/dummy.git dummy-2
Cloning into 'dummy-2'...
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (6/6), 706 bytes | 706.00 KiB/s, done.
```

**Comment by aliartiza75** [comment]
this is the real value I was using :
```
ssh://git@bitbucket.org:username/repo-name.git
```

**Comment by hiddeco** [comment]
@aliartiza75 if you change that to `ssh://git@bitbucket.org/username/repo-name.git`, it should work.

**Comment by aliartiza75** [comment]
@hiddeco this is fine but I think this should be mentioned somewhere in the documentation so that someone else doesn't have to face this issue. By the way, the link that I coped was from the bitbucket repo dashboard.

**Comment by hiddeco** [comment]
> By the way, the link that I coped was from the bitbucket repo dashboard.

I just logged in to Bitbucket and the format they give to copy is the following:

```
git clone git@bitbucket.org:hiddeco/<some repository>.git
```

If you remove `git clone` from that and give it to Flux, it will happily clone your repository.

**Comment by squaremo** [comment]
> but I think this should be mentioned somewhere in the documentation so that someone else doesn't have to face this issue

Which documentation were you following, and where do you reckon is the best place to mention this gotcha?

**Comment by aliartiza75** [comment]
@hiddeco kindly get the clone url in `ssh` format.

**Comment by aliartiza75** [comment]
@squaremo i think should be added in `values.yaml` file. 

https://github.com/fluxcd/flux/blob/77d2afbd180138597326848dba92c3142c7cff4f/chart/flux/values.yaml#L142-L162

after line `143`? what do you think?

**Comment by aliartiza75** [comment]
@squaremo waiting for your response?

**Comment by aliartiza75** [comment]
@squaremo waiting for your response?

**Comment by stealthybox** [comment]
It's mentioned with the ssh format on line 143
What do you propose we add there?

**Comment by aliartiza75** [comment]
@stealthybox ack, closing this issue.

**Comment by stealthybox** [comment]
Thank you for opening this issue :heart_decoration: 
It documents the problem and makes this much more searchable for all flux users
