### ISSUE TITLE
How can i connect to a remote cluster with helm 

### ISSUE THREAD

**Issue by binjheBenjamin** [fluxcd/flux#2277]
is the following command correct?  It  does not work for me

helm install --name flux --set helmOperator.create=true --set helmOperator.createCRD=false --set git.url="git@wwwin-github.cisco.com:binjhe/flux-get-started" --set k8s-in-cluster=false --set-file ssh.known_hosts=/tmp/flux_known_hosts --namespace test fluxcd/flux

the log still shows that:

ts=2019-07-21T07:52:33.460475024Z caller=main.go:317 msg="using in cluster config to connect to the cluster"

any suggestions for me?
thx.

**Comment by hiddeco** [comment]
I do not think that flag is integrated in our Helm chart, nor is it meant to be used for anything else than development purposes.

If you still want to use it after heaving read the above, you can provide the flag as an `additionalArgs`, see: https://github.com/fluxcd/flux/blob/master/chart/flux/values.yaml#L260-L261

**Comment by binjheBenjamin** [comment]
> I do not think that flag is integrated in our Helm chart, nor is it meant to be used for anything else than development purposes.
> 
> If you still want to use it after heaving read the above, you can provide the flag as an `additionalArgs`, see: https://github.com/fluxcd/flux/blob/master/chart/flux/values.yaml#L260-L261

okay, thx a lot.
