### ISSUE TITLE
Helm operater getting into upgrade, rollback loop when values change

### ISSUE THREAD

**Issue by adrian** [fluxcd/flux#2285]
**Describe the bug**
If rollback is enabled and values are provided on a HelmRelease that causes an upgrade to fail (e.g. bad image tag), the operator will (correctly) roll the release back.

Shortly afterwards (I believe after `helmOperator.chartsSyncInterval`) the operator will do a dry-run upgrade to compare the values on the deployed release to those on the HelmRelease. These will be different since the deployed release will have the values that were rolled back to, while the HelmRelease will still have the new values. Consequently an upgrade will be kicked off which will fail and the loop continues again.

**To Reproduce**

0. Create a HelmRelease setting `rollback: true`
1. After the operator installs the release edit the HelmRelease and add values that will cause the release to fail, e.g. set a bad image tag (assuming the helm chart supports this parameter).

**Expected behavior**
The helm upgrade should fail. There should be no further activity on the release until the HelmRelease or helm chart are updated.

**Logs**
n/a

**Additional context**
Add any other context about the problem here, e.g 
- Helm Operator version: 0.10.0
- Kubernetes version: v1.15.0

**Comment by stefanprodan** [comment]
Hi @adrian 

This is the intended behaviour, the operator tries to reconcile the state in git with the cluster. A failure can happen from various reasons, for example you could make a cluster change (add a storage type, have more capacity, etc) that will make the release succeed, if helm-op would not retry the install then the release will get stuck forever.
