### ISSUE TITLE
Allow annotations on helm operator deployment (not pod template)

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/flux#2297]
**Describe the feature**
I would like to use the reloader to restart flux if the flux helm repositories secrets change.
To do this, I need to add an annotation to the flux helm deployment (not the pod annotations). I cannot do that with the current helm chart.

Please add a key to the helm chart to allow insertions of annotations on the deployment manifest for the helm operator.

**Comment by squaremo** [comment]
Seems reasonable to me, for that use case and no doubt others.

**Comment by kingdonb** [comment]
Please let me know if you still need help with this. I apologize for the staleness of this reply, we are in the process of cleaning up stale issues from the Flux v1 repo now, this should be over soon.

I will close the issue for now as it is stale. Flux v1 remains in maintenance mode. Although I can still review and accept some pull requests, there is little labor effort available to develop the Flux v1 codebase and are no new features being added to Flux v1 daemon and this is generally critical fixes only situation at this point.

We can provide support to Flux v1 users especially with respect to migrating to the new Flux version, which has some breaking changes but is also a total rewrite and also brings many improvements. I'm closing the issue but you are most welcome to write back on this issue, or open another issue. Thanks for using Flux.
