### ISSUE TITLE
read-the-docs follow-up

### ISSUE THREAD

**Issue by dholbach** [fluxcd/flux#2303]
Following https://github.com/fluxcd/flux/pull/2152 we should take a look at:

### Content
- [x] factor in [Hidde's feedback](https://github.com/weaveworks/flux/pull/2152#issuecomment-502773997)
  - [x] 'Installing Flux' index should contain a section about installing Flux and the Helm operator at the same time, this could be on a new page or we can divide the 'get started' in two sections, one without the operator and one with.
  - [x] I think we should rethink some of the page titles, e.g. we have a top item 'Using Flux' with a 'child page' 'Using Weave Flux'.
  - [x] I think we should rethink some parts of the (naming of the) new structure, e.g, we have a 'introducing Weave Flux' index, but also a 'how Weave Flux Works' index. As a new user, I would expect the introduction to contain the latter, so we may need to rethink the naming, or merge parts.
  - [x] 'Internals' is something that would scare me away as a user, listing the more important features under this index (garbage collection and manifest factorization) will probably reduce the amount of people finding this information by themselves.
- [x] Helm Operator docs should be in a separate dir
- [ ] fix references from Weaveworks website

### Build
- [ ] generally document how to use this

### Publish
- [ ] pull in older releases
- [x] link to docs from main README.md
- [x] docs.fluxcd.io

**Comment by demisx** [comment]
Would be also helpful if all links in the Readme were working. Currently, a few of them return 404 Not Found error from GitHub.

**Comment by dholbach** [comment]
Thanks @demisx for letting us know. Proposed a fix for this in #2307.

**Comment by stefanprodan** [comment]
@dholbach I think we can close this and open specific issues for dead links if there are any left.

**Comment by dholbach** [comment]
Big +1. I think we're good for now! :-D
