### ISSUE TITLE
fluxctl list-controllers unable to parse files as manifests

### ISSUE THREAD

**Issue by tomcheah** [fluxcd/flux#2321]
Hi. I try to run fluxctl list-controllers, but then I get this error. 

fluxctl seems to try to access non-existent files and I'm not sure why. What can I do about this? 

I've tried uninstalling and reinstalling fluxctl. 

== Error ==

Unable to parse files as manifests

Flux was unable to parse the files in the git repo as manifests,
giving this error:

    walking "/tmp/flux-working970618299/namespaces" for yamels: lstat /tmp/flux-working970618299/namespaces: no such file or directory

Check that any files mentioned are well-formed, and resources are not
defined more than once. It's also worth reviewing

    https://github.com/weaveworks/flux/blob/master/site/requirements.md

to make sure you're not running into any corner cases.

If you think your files are all OK and you are still getting this
message, please log an issue at

    https://github.com/weaveworks/flux/issues

and include the problematic file, if possible.

**Comment by squaremo** [comment]
If you've been following the "Get Started" tutorial, you'll have set the flag `--git-path=workloads,namespaces`; this makes fluxd look for those two subdirectories in your git repo.

You can make it look at the top directory by removing that flag entirely, or just at `workloads` by `--git-path=workloads`, say.

**Comment by tomcheah** [comment]
That solved it! Thanks.
