### ISSUE TITLE
Automation blocks on non-existent image tag

### ISSUE THREAD

**Issue by rhockenbury** [fluxcd/flux#2325]
**Describe the bug**
Flux uses the timestamp associated with the image, and the timestamp does not exist for an image tag that does not exist, and Flux skips the deployment. 

This situation can come about in different ways:
1. The repo that Flux is monitoring has a manifest with an image tag that does not exist in the registry.  This could be because the manifests were copied from a snapshot of another environment that uses different tagging. 
2.  An image that did exist and was deployed with Flux, may no longer exist because it was deleted from the registry.  For example, running a Docker registry out of artifactory allows for setting the number of tags for each image to keep in the registry. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Set up a Helm Release that is auto deployed when new tags are available
2. Delete the image tag (that Flux was expecting to deploy) from the registry 
3. Push a new version of the image with a new tag to the registry
4. Flux cannot deploy the new version of the image

**Expected behavior**
Flux should continue to deploy the newer image tag if the previous image tag does not exist in the registry.  It deploys the newest image that exists in the registry.

**Logs**
```
ts=2019-08-05T15:29:14.81149497Z caller=images.go:107 component=sync-loop workload=master:helmrelease/calc-master container=iisApp repo=artifactory:8080/internal-windows/calc pattern=glob:* current=artifactory:8080/internal-windows/calc:2 warning="image with zero created timestamp" current="artifactory:8080/internal-windows/calc:2 (0001-01-01 00:00:00 +0000 UTC)" latest="artifactory:8080/internal-windows/calc:22 (2019-08-02 19:23:12.45949 +0000 UTC)" action="skip container"
```

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.12.3
- Helm Operator version: 0.9.1
- Kubernetes version: 1.15.0
- Git provider: BitbucketServer
- Container registry provider: Artifactory

**Comment by hiddeco** [comment]
This is expected behaviour, see answers in #2216, #2098, and additional background information in #1817.

**Comment by rhockenbury** [comment]
Fair enough.  Thanks.
