### ISSUE TITLE
What is the purpose of memcached? 

### ISSUE THREAD

**Issue by tomcheah** [fluxcd/flux#2330]
What is the purpose of the memcached pod? What does it do/ accomplish? 

Within the whole schema of GitOps, why does there need to be some type of storage to update the state of a container? Is it not enough to use the Flux pod to sync with Git and check for changes? 

I was reading up the documentation of Flux and couldn't find a clear or satisfactory answer and am trying to get a deeper understanding of this design.

**Comment by stefanprodan** [comment]
Memcached is used to store the container image tags. Flux scans your cluster for container images and fetches the tags from the registries. This allows Flux to automate the image tag update.

**Comment by squaremo** [comment]
Yup, as Stefan says, it's there to support automated image updates. This was the original motivating use for flux. Architecturally, the image update is distinct from syncing. It could in theory run as an optional, separate component, perhaps given some minimal co-ordination with syncing.

memcached is something of an arbitrary choice (less so at the time the choice was made -- it really was caching things)

**Comment by squaremo** [comment]
@tomcheah Is your question answered?

**Comment by stefanprodan** [comment]
I’m closing this, @tomcheah feel free to comment here if you need more details.

**Comment by serain** [comment]
Is memcached necessary if we disable auto-image updates and just use flux for deployments?
