### ISSUE TITLE
expose the `git-secret` support in the chart

### ISSUE THREAD

**Issue by davidkarlsen** [fluxcd/flux#2342]
The feature added in 
https://github.com/fluxcd/flux/pull/2159
should also be possible to activate through the chart.

Probably the activation flag is all that is required:
* either explicit flag to set to true in values.yaml OR
* activate automagically as long as gpg keys are configured.

**Comment by kingdonb** [comment]
No further enhancements can be landed in Flux v1,

* #3320 

Closing.
