### ISSUE TITLE
Publish fluxctl to scoop for windows

### ISSUE THREAD

**Issue by gldraphael** [fluxcd/flux#2357]
**Describe the feature**
Publish fluxctl to a public scoop bucket. Preferably [main](https://github.com/ScoopInstaller/Main/tree/master/bucket) or [extras](https://github.com/lukesampson/scoop-extras).

**What would the new user story look like on windows using scoop?**

```
scoop install fluxctl
```

**Expected behavior**
Scoop is installed for the current user.

----

Related: #1363 on adding fluxctl to chocolatey. (If chocolatey is APT, scoop is homebrew. Kind of.)

For the timebeing, fluxctl can be manually installed using scoop by:

1. Creating a `fluxctl.json` app manifest similar to:
    ```json
    { 
        "version": "1.14.2", 
        "url": "https://github.com/fluxcd/flux/releases/download/1.14.2/fluxctl_windows_amd64#/fluxctl.exe", 
        "bin": "fluxctl.exe" 
    }
    ```
1. And running:
    ```pwsh
    scoop install .\fluxctl.json
    ```

**Comment by squaremo** [comment]
From the look of it, this would help Windows users out a lot :+1:
We may not get to this in the near term, though.

**Comment by gldraphael** [comment]
Meanwhile I'll be maintaining fluxctl as a scoop package here: https://github.com/gldraphael/scoop-bucket

**Comment by gldraphael** [comment]
This ended up in the official scoop bucket.
So closing this.

https://github.com/ScoopInstaller/Main/blob/master/bucket/fluxctl.json
