### ISSUE TITLE
Search in the readthedocs - docs.fluxcd.io site returning broken links

### ISSUE THREAD

**Issue by palemtnrider** [fluxcd/flux#2362]
**Describe the bug**
I performed a search on docs.fluxcd.io site for the term 'ignore'  It returned several links.  All the links with `CHANGELOG.html` or `site` in the URL returned a 404.

**To Reproduce**
Steps to reproduce the behaviour:
0. MacOS, firefox Quantum 68.0.1
1. Go to https://docs.fluxcd.io/en/latest/index.html 
2. Type the word ignore in the search field and hit enter
3. Look at the URLs for the links and if they include either CHANGELOG.html or site, click on them
4. See error 404

**Expected behavior**
Either the links to work or the search to exclude them from the results.

**Comment by hiddeco** [comment]
Thanks for reporting this @palemtnrider. We are aware the search is broken at the moment, and will investigate once the removal of the Helm operator from the Flux codebase has been completed. Thanks for reporting :1st_place_medal:

**Comment by dholbach** [comment]
Is this about https://docs.readthedocs.io/en/stable/subprojects.html#search?

**Comment by hiddeco** [comment]
@dholbach it is about the search in general, some results result in 404 returns. I am not sure when this started, or if it always has been this way and I was just lucky when I used the search before.

**Comment by dholbach** [comment]
It's odd. E.g. `CHANGELOG.md` (which comes up in the search results) does not even turn up in http://docs.fluxcd.io/en/latest/searchindex.js

**Comment by hiddeco** [comment]
It looks like Read the Docs is not updating their index on filename changes or deletions.

https://github.com/readthedocs/readthedocs.org/issues/6069

**Comment by hiddeco** [comment]
RTD has fixed the issue and deployed it recently.

I have just wiped all builds for the published documentation versions, and triggered a rebuild, this has resolved the issue.
