### ISSUE TITLE
Follow symlinks when git.path is used

### ISSUE THREAD

**Issue by zcourts** [fluxcd/flux#2376]
**Describe the feature**
We have two primary clusters, one we've called "staging" and another "production".

We're using one repo to store everything flux needs. Within a single cluster we have "virtual environments" (a K8s namespace). So flux helm operator has `git.path=envs/staging` for the "staging" cluster and `git.path=envs/production` for the production cluster. 

Across the multiple clusters we have several things in common so at the root of the repo is a `shared-manifests` folder. In each cluster's folder e.g. envs/production, we tried to symlink shared-manifests so the operator would see and apply those. Unfortunately it doesn't follow symlinks so we've copied the shared-manifest folder to each cluster's directory.

We've only just started migrating to flux so there are only a few in shared-manifests for now but by the time the migration is finished I expect over a dozen.

**What would the new user story look like?**

As a user I'd like to be able to symlink from a `git.path` to a parent directory and have flux apply the manifests in that symlinked directory.

How would the new interaction with Flux look like? E.g.
Interaction with flux needn't change. It already assumes nothing about directory structure so I imagine following symlink was simply not considered.

**Expected behavior**
If a symlink file or directory exists that leads to a valid file in the same repository then they should be followed and treated the same as any other file or directory.

**Before and after**
Before we had this directory structure
<img width="289" alt="Screenshot 2019-08-20 at 21 13 51" src="https://user-images.githubusercontent.com/692396/63381875-7e691180-c391-11e9-8e0c-237855f8f70e.png">
It had to be changed to
<img width="290" alt="Screenshot 2019-08-20 at 21 14 49" src="https://user-images.githubusercontent.com/692396/63381891-8628b600-c391-11e9-93fc-50933454b9fb.png">

The reason for wanting this is simply not to duplicate where it ins't necessary. We deploy several tools that play a supporting role in our service and are deployed/managed/upgraded at the same time.

**Comment by stefanprodan** [comment]
The git path supports a list of paths, so you can do:
```
--set git.path="shared-manifests\,envs/staging"
```

**Comment by zcourts** [comment]
Yeah that works. Thanks

**Comment by phyrog** [comment]
I have a similar problem where I need to selectively add different manifests to different types of clusters (imagine a customer picking and choosing base services that should be deployed to their cluster). Some manifests should be deployed to multiple (but not all clusters), so what I would like to do is to have a single directory containing the manifests and separate directories for each cluster type containing only symlinks to the manifests.

That being said, @zcourts would you mind re-opening this issue, as I believe there is a valid use-case that can't be easily solved by using multiple `git.path`s.
