### ISSUE TITLE
Restrict flux to a specific namespace

### ISSUE THREAD

**Issue by MehrCurry** [fluxcd/flux#2397]
**Describe the feature**
While trying to use the new `fluxctl install` feature i am missing the old `--k8s-allow-namespace=build` flag to restrict flux to a specific namespace.

**Comment by stefanprodan** [comment]
You can use the Helm chart for advanced use cases, we don't plan to expose all the chart options in `fluxctl install`.

If you don't use Tiller then you can generate the YAMLs with Helm CLI and apply them with kubectl:

```
# add repo
helm repo add fluxcd https://charts.fluxcd.io

# download chart
helm fetch --untar --untardir . fluxcd/flux

# generate YAMLs
helm template flux \
--name flux \
--namespace=build \
--set clusterRole.create=false \ #<-- this sets --k8s-allow-namespace= build 
> $HOME/flux.yaml

# apply
kubectl apply -f $HOME/flux.yaml
```

**Comment by stefanprodan** [comment]
Another option is with Kustomize:

https://docs.fluxcd.io/en/latest/tutorials/get-started-kustomize.html

**Comment by MehrCurry** [comment]
Thanks for making things clear.

I use `fluxctl install` for manifest generation and the add the options later by hand. Works for me.
