### ISSUE TITLE
PR Validation Recommendations

### ISSUE THREAD

**Issue by chainlink** [fluxcd/flux#2398]
What are your recommended tools for validating configuration in a gitops pull request? (ie. something that can be run in a CI pipeline) Frequently we merge to master, only to find out there's a yaml error, or something is misconfigured. I'm looking into kubeval, but are there other tools I should look at as well?

Thanks!

**Comment by stefanprodan** [comment]
Use [kubeval](https://github.com/instrumenta/kubeval) for sanity check, [helm-kubeval](https://github.com/instrumenta/helm-kubeval) for charts and OPA [conftest](https://github.com/instrumenta/conftest) for custom validation e.g. unique ingress hostnames, limits, etc

**Comment by chainlink** [comment]
Thanks!

**Comment by squaremo** [comment]
@chainlink If you got to try any of Stefan's suggestions out, it would be wonderful to hear how it went for you :-) Can we close this in the meantime?
