### ISSUE TITLE
fluxd - add ability to pass flags to klog

### ISSUE THREAD

**Issue by cristian-radu** [fluxcd/flux#2407]
Since fluxd uses client-go, which in turn uses klog for logging, it would be beneficial for fluxd to support setting klog flags from the command line, similar to all other kubernetes components. 

The log level is particularly useful for troubleshooting since the klog package initializes this to 0.
https://github.com/kubernetes/klog/blob/master/klog.go#L404
 
fluxd also uses client-go rate-limiting of requests to the kubernetes API server:https://github.com/fluxcd/flux/blob/master/cmd/fluxd/main.go#L375-L376

Doing some research on this, I believe there is currently no means of identifying when requests are in fact being throttled since those messages are logged at verbosity level 4: https://github.com/kubernetes/client-go/blob/master/rest/request.go#L538 

I suggest the easiest way to add this functionality is to swap out "github.com/spf13/pflag" with the "flag" package from the standard library. After that, simply calling klog.InitFlags() should add all of its flags to the fluxd flagset.

**Comment by stefanprodan** [comment]
Switching to flag is not an option since we depend on specific pflag features. But this is not needed to log the rate limit messages. Klog can be initialised inline and we can pass in a fluxd flag to it that sets the verbosity.

**Comment by cristian-radu** [comment]
Hmmm, are you referring to https://github.com/fluxcd/flux/blob/master/cmd/fluxd/main.go#L283 as the pflag features flux depends on? @stefanprodan I just noticed those.

I don't have any strong preference for how klog initialization is handled. I didn't have much success with trying to pass it a *flag.FlagSet populated through pflag flags, but maybe there is something I missed.

**Comment by stefanprodan** [comment]
Can you please test my PR and see if it works? The fluxd flag is `--k8s-verbosity=4`
