### ISSUE TITLE
Question: can multiple clusters deploy from a single repo

### ISSUE THREAD

**Issue by smartpcr** [fluxcd/flux#2408]
I noticed that when I have more than one clusters, and flux within different clusters use same deployment key but are targeting different branch/path, only one tag is applied to a single commit in the repo, even though clusters are at different stages.

I'd like to know if this is even possible? 

thanks,

**Comment by dranner-bgt** [comment]
Have you tried setting the tag via the `--git-label=<your-label>` fluxd command line option? In case you're deploying flux via helm chart it's in `.Values.git.label`.

**Comment by stefanprodan** [comment]
The git label must be unique per cluster. Flux uses the git label value as the tag name.
