### ISSUE TITLE
Flux /api/flux/v11/services keep returning fixed SyncError 

### ISSUE THREAD

**Issue by jacobsin** [fluxcd/flux#2418]
**Describe the bug**
Flux /api/flux/v11/services keep returning fixed SyncError 

**To Reproduce**
Steps to reproduce the behaviour:
0. What's your setup?
Fork off 1.13.2 tag
1. Create valid SyncError e.g. mutate immutable fields on Deployment.spec.selector.matchLabels
2. Hit /api/flux/v11/services to see SyncError
3. Fix SyncError and ensure flux log is clean
4. Hit /api/flux/v11/services again to see SyncError again
5. Restart fluxd
6. Hit /api/flux/v11/services to see SyncError now gone

**Expected behavior**
Step 4 above should see SyncError gone

**Comment by 2opremio** [comment]
@jacobsin is this still a problem with Flux 1.17.0? What are you trying to do? Can you reproduce this problem through `fluxctl`?

**Comment by jacobsin** [comment]
It is still a problem with v.1.16.0 which I had to downgraded from 1.18.0 for a gc not deleting regression. Can try ungrading again to see if this bug goes away already.

Is fluxctl showing sync error nowadays?
