### ISSUE TITLE
chartFileRef's values is not updated when image updated 

### ISSUE THREAD

**Issue by sureshamk** [fluxcd/flux#2422]
**Describe the bug**
I has value files based on `chartFileRef` as separate file . When I am updating new image, this file is not getting updated with the new image. 

**Expected behavior**
If new image updated, flux cd will update the HelmRelease values image's version same chartFileRef will be updated 

Reference Repo: 
https://github.com/sureshamk/hello-flux-helm

**Comment by hiddeco** [comment]
Flux will only update values in the `spec.values` of the `HelmRelease` resource itself, and not in the underlying referred value files.

**Comment by sureshamk** [comment]
It would be nice , if its happen such a way , any plan for this feature ?

**Comment by hiddeco** [comment]
Given the added complexity it would introduce, I think it is not likely this is every going to happen anytime soon.

**Comment by squaremo** [comment]
It's not just that it's technically tricky: it would go against the design of the helm operator, in which charts are considered read-only (including files that come with them), and values are varied _per release_ by supplying them in the `HelmRelease` resource.

Until there's a strong argument that the design should be changed, there will be no plan to implement this. A strong argument would run along the lines of "a common use case that cannot be accomplished in any other way, is to ...".

**Comment by squaremo** [comment]
> [...] a common use case that cannot be accomplished in any other way

@sureshamk If you describe what you are trying to do, we can help you figure out if there's another way to do it.
