### ISSUE TITLE
fluxctl should give friendlier error when releasing image out of `flux.weave.works/tag`

### ISSUE THREAD

**Issue by emas80** [fluxcd/flux#2441]
**Describe the bug**
I'm trying to use fluxctl release to update a workload.
I've followed the doc on https://docs.fluxcd.io/en/stable/references/fluxctl.html, in particular the paragraph "Rolling back a Workload" as I want to stop the automation and then release a specific version.

**To Reproduce**
I have one workload automated by flux, and I issue

`
fluxctl deautomate --workload=${NAMESPACE}:deployment/${APP_NAME} -n ${NAMESPACE} --k8s-fwd-ns ${NAMESPACE}
`
`
fluxctl release --workload=${NAMESPACE}:deployment/${APP_NAME} -n ${NAMESPACE} --k8s-fwd-ns ${NAMESPACE} --update-image=${DOCKER_IMAGE_NAME}:${VERSION}
`

The first command returns success, the second command returns

`
Submitting release ...
Error: no changes made in repo
Run 'fluxctl release --help' for usage.
`

**Expected behavior**
I am expecting to see my version ${VERSION} being deployed

**Logs**
In the logs immediately after I issue the release command I can see only

`
ts=2019-09-10T13:39:48.751310989Z caller=releaser.go:59 component=sync-loop jobID=ea8aa963-d49f-3a6c-02be-02b18933b47b type=release updates=0
ts=2019-09-10T13:39:48.751598891Z caller=releaser.go:61 component=sync-loop jobID=ea8aa963-d49f-3a6c-02be-02b18933b47b type=release exit="no images to update for services given"
ts=2019-09-10T13:39:51.486452056Z caller=loop.go:144 component=sync-loop jobID=ea8aa963-d49f-3a6c-02be-02b18933b47b state=done success=false err="no changes made in repo"
`

The workloads appears when I list the workloads (this is before I disable the automation:

`ops-1:deployment/core-api                 core-api                 gcr.io/XXX/core-api:ops-1                 ready    automated
`

The image I want to release is present when I do list-images.

I've tried releasing a not existent image or a not existent tag, and in the logs I can see that the image does not exist or the tag does not exist.

I've tried changing the workload during the release command to something that does not exist, and the error message in the logs is the same - no images to update for services given.

I would like to understand what could be wrong with my setup, I think I'm literally doing what written in the doc..

As for the background, Flux is running correctly and the automation is fully working in the cluster- the automated workloads are released whenever a new image is updated and the kubernetes yaml files are kept on sync.

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.14.2
- Kubernetes version: 1.13.2
- Git provider: github
- Container registry provider: gcr

**Comment by 2opremio** [comment]
I need to check the code, but yes, I think that's the expected behavior. That said, `fluxctl` should had given you a friendlier message.

**Comment by 2opremio** [comment]
I can confirm that's the expected behavior:

https://github.com/fluxcd/flux/blob/992f6b3caf8a86e26c1ae37d27ffa54ba29bc749/pkg/update/release_image.go#L233-L239

I will review the docs to try to make them less confusing
