### ISSUE TITLE
Allow specification of git-label

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/flux#2444]
**Describe the feature**
The new experimental gitops support allows on a few options. That is generally fine, however there is a problem.

If two different flux instances refer to the same repo, then the same default `git-label` may be used. This is not a problem if we can pass the git label before flux runs.  However, with the gitops support in eksctl, one cannot do that. 

**Expected behavior**
One can pass the `--git-label label` option to `eksctl install flux`.

**Comment by squaremo** [comment]
Should this be in the eksctl repo?

**Comment by hiddeco** [comment]
Debatable. Making it work in `eksctl` would require work on both sides (`install` package and templates in there need to support the flag on the Flux side).

**Comment by 2opremio** [comment]
Both `eksctl install flux` and Flux's install package both already expose `--git-label`

See https://github.com/weaveworks/eksctl/blob/a244466f9cfec0029ae4b964e5b89e2c173b4f2c/pkg/ctl/install/flux.go#L80

@derrickburns did you try supplying the flag? If it doesn't work please create an issue in the `eksctl` repository including the error message.
