### ISSUE TITLE
Errors while running get-started.md tutorial

### ISSUE THREAD

**Issue by kaushikchaubal** [fluxcd/flux#2447]
**Describe the bug**
Errors while running get-started script for 3 commands:
1. fluxctl install
2. fluxctl identity
3. fluxctl sync

**To Reproduce**
I installed fluxctl on macOS using brew. Note: The version of fluxctl is 1.14.0 and started following the steps as described here: https://github.com/fluxcd/flux/blob/master/docs/tutorials/get-started.md

Bug 1: On running:
```
fluxctl install \
--git-user=${GHUSER} \
--git-email=${GHUSER}@users.noreply.github.com \
--git-url=git@github.com:${GHUSER}/flux-get-started \
--git-path=namespaces,workloads \
--namespace=flux | kubectl apply -f -
```
I got the following error message:
```
Error: unknown flag: --git-path
Run 'fluxctl install --help' for usage.
error: no objects passed to apply
```

Solution 1: On googling, I found this issue: https://github.com/fluxcd/flux/pull/2423. When I swapped `--git-path` with `--git-paths`, it worked successfully and I got the following output:
```
secret "flux-git-deploy" created
deployment.apps "memcached" created
service "memcached" created
serviceaccount "flux" created
clusterrole.rbac.authorization.k8s.io "flux" created
clusterrolebinding.rbac.authorization.k8s.io "flux" created
deployment.apps "flux" created
```

Bug 2: On running:
```
fluxctl identity --k8s-fwd-ns flux
```
I got the following error message:
```
Error: Could not create a dialer: Could not get pod name: Could not find running pod for selector: labels "app=flux"
```

Solution 2: On googling, I found the workaround in this issue: https://github.com/fluxcd/flux/issues/2386, so I swapped it to `fluxctl --k8s-fwd-ns=flux --k8s-fwd-labels=name=flux identity`, it worked successfully and I got the public key as expected

Bug 3: On running:
```
fluxctl sync --k8s-fwd-ns flux
```
I got the following error message:
```
Error: Could not create a dialer: Could not get pod name: Could not find running pod for selector: labels "app=flux"
```

Solution 3: I applied the same workaround as solution 2, so I swapped it to `fluxctl sync --k8s-fwd-ns=flux --k8s-fwd-labels=name=flux`, it worked successfully and I got the following output:
```
Synchronizing with git@github.com:kaushikchaubal/flux-get-started
Revision of master to apply is b15b3c7
Waiting for b15b3c7 to be applied ...
Done.
```

Once I solved these 3 bugs, I was able to get the get-started working successfully!

I will create a PR updating the instructions for the get-started.md based on my experience.

**Comment by hiddeco** [comment]
The problem is that the instructions you were viewing are for the latest stable release of Flux (`1.14.2`), while the version you mention is `1.14.0`.

Following the instructions with the latest version of Flux should work, due to the work done in #2392, #2394, and #2395.

**Comment by kaushikchaubal** [comment]
Sounds good. I will update my fluxctl to the latest version. Thanks for the background 💯 !
