### ISSUE TITLE
Documentation: "Getting Started" references missing ENV variable

### ISSUE THREAD

**Issue by tdensmore** [fluxcd/flux#2456]
I am trying to follow the **Getting Started** instructions [here](https://docs.fluxcd.io/en/latest/tutorials/get-started.html).

The instructions reference this file: `~/workloads/podinfo-dep.yaml` and instruct me to 
"change the `PODINFO_UI_MESSAGE` env var to `Welcome to Flux` and commit the file."

However in my fork on the master branch there is no PODINFO_UI_MESSAGE env var. 

Im not sure if the documentation is wrong, or if I am missing some info...

**Comment by stefanprodan** [comment]
The env var is here https://github.com/fluxcd/flux-get-started/blob/master/workloads/podinfo-dep.yaml#L49 You should sync your fork with the latest master.

**Comment by tdensmore** [comment]
Thanks. I'm not sure what happened. I deleted my fork and cloned again.

**Comment by tdensmore** [comment]
For others running into this... even though I forked the repo today, those changes were not in my copy. I had to do this to see the latest:
`git remote add upstream git://github.com/fluxcd/flux-get-started.git` 
`git fetch upstream`

**Comment by MohanSai1997** [comment]
If you were still unable to find the **PODINFO_UI_MESSAGE** than add the env variable with that name.

This is worked for me😊
