### ISSUE TITLE
Provide a way to create "pre-deployment" and "post-deployment" event actions

### ISSUE THREAD

**Issue by eleaese** [fluxcd/flux#2465]
Is there a way to create "pre" or "post" deployment event/actions in Flux ?. We're looking to submit a HTTP POST to a webhook with customizable headers and payload with release/version deployed and timestamp.

Example in curl:
`curl --location --request POST "https://webhook.domain.com/api/releases"  --header "Authorization: apiToken ******************" --header "Content-Type: application/json"  --data "{\"name\": \"Test Release 1\",\"start\": 1565610536335}"
`

name field could be composed by github repo/version deployed.

**Comment by stefanprodan** [comment]
Flux doesn't deal with deployments but with cluster state in a holistic way. Every 5m or when triggered by `fluxctl sync`, Flux reconciles the cluster with git by applying all manifests from git on the cluster. You could use [Flagger](https://github.com/weaveworks/flagger) to drive the app deployments using canary, ab-testing or blue/green strategies. Flagger working with Flux and has pre/during/post deployment [hooks](https://docs.flagger.app/how-it-works#webhooks) and builtin Slack/MS Teams [notifications](https://docs.flagger.app/usage/alerting).

**Comment by eleaese** [comment]
Thank you Stefan. Flagger hooks are specific to Slack/MS Teams. I'll take a look at https://github.com/justinbarrick/fluxcloud

**Comment by richardcase** [comment]
I think this would be a good feature.
