### ISSUE TITLE
Docs pipeline breaks links to markdown files

### ISSUE THREAD

**Issue by 2opremio** [fluxcd/flux#2468]
**Describe the bug**

https://docs.fluxcd.io/en/latest/references/fluxyaml-config-files.html should be linking to https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md but links to https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch instead (which doesn't exist)

**To Reproduce**

0. Open your browser
1. Go to https://docs.fluxcd.io/en/latest/references/fluxyaml-config-files.html 
2. Click on `YAML merge patch file`
3. See error

**Expected behavior**
The correct link opens and there is no error

**Comment by kingdonb** [comment]
I don't find the error anymore, at https://fluxcd.io/legacy/flux/references/fluxyaml-config-files/

Closing.
