### ISSUE TITLE
Document 'fluxctl install' in fluxctl reference

### ISSUE THREAD

**Issue by dholbach** [fluxcd/flux#2476]
https://docs.fluxcd.io/en/latest/references/fluxctl.html does not explain `fluxctl install` yet. This was apparently not part of the https://github.com/fluxcd/flux/pull/2298 PR.

**Comment by stefanprodan** [comment]
I would not duplicate the install command command in the docs, a link to https://docs.fluxcd.io/en/latest/tutorials/get-started.html#set-up-flux should do.

**Comment by dholbach** [comment]
In the command listings of `fluxctl` it's not even listed. I would expect a mention and brief discussion in a reference type document. No duplication though, sure.

**Comment by domgoodwin** [comment]
I've opened a PR to address this issue
