### ISSUE TITLE
Flux chart upgrade failed with `--reuse-values`

### ISSUE THREAD

**Issue by mar1n3r0** [fluxcd/flux#2480]
**Describe the bug**
Flux upgrade failed

**To Reproduce**
0. flux             1        Wed Jul 31 11:46:18 2019 DEPLOYED flux-0.11.0          1.13.2      flux        
1. helm upgrade --reuse-values flux \
--set image.tag=1.14.2 \
weaveworks/flux
2. Upgrade failed

**Expected behavior**
Upgrade to complete.
**Logs**
Error: render error in "flux/templates/deployment.yaml": template: flux/templates/deployment.yaml:172:35: executing "flux/templates/deployment.yaml" at <.Values.sync.state>: nil pointer evaluating interface {}.state
Error: UPGRADE FAILED: render error in "flux/templates/deployment.yaml": template: flux/templates/deployment.yaml:172:35: executing "flux/templates/deployment.yaml" at <.Values.sync.state>: nil pointer evaluating interface {}.state

**Additional context**
- Flux version: 1.13.2
- Helm Operator version: 2.14.3
- Kubernetes version: 1.13.7
- Git provider: bitbucket
- Container registry provider: dockerhub

**Comment by hiddeco** [comment]
`--reuse-values` does not merge with any new values introduced in the newer version of the chart. It will simply take the old values, and add any additional `--set` arguments to it.

You can read more about this here: https://medium.com/@kcatstack/understand-helm-upgrade-flags-reset-values-reuse-values-6e58ac8f127e

**Comment by mar1n3r0** [comment]
Thanks @hiddeco that was helpful and I can see the release in helm list although it fails with the below:

helm upgrade --reuse-values flux --set image.tag=1.14.2 --set sync.state=git weaveworks/flux
UPGRADE FAILED
Error: failed to create patch: merging an object in json but data type is not struct, instead is: map
Error: UPGRADE FAILED: failed to create patch: merging an object in json but data type is not struct, instead is: map

**Comment by hiddeco** [comment]
@mar1n3r0 isn't this because there are other values that changed from type, and you are still passing along the old type for that value?

**Comment by mar1n3r0** [comment]
The thing is if there is a value missing it just gives me the error with the value missing or wrong. But what's more interesting is that after the rollback it keeps the new pod in the crash loop instead of deleting it. Right now I am back to 1.13.2 but the 1.14.2 pod keeps restarting itself.

**Comment by mar1n3r0** [comment]
Yep that sounds like the sanest option. I am only unsure which is the latest get started since I have 3 different versions open.

**Comment by hiddeco** [comment]
We have published docs these days with a `stable` version, based on the latest semver version of Flux. The Helm get started guide for this version can be found here: https://docs.fluxcd.io/en/stable/tutorials/get-started-helm.html

**Comment by mar1n3r0** [comment]
Thanks a bunch I will report back once going through it.

**Comment by mar1n3r0** [comment]
Solved, the reinstall went smoothly.
