### ISSUE TITLE
flux could use client-go informers

### ISSUE THREAD

**Issue by cristian-radu** [fluxcd/flux#2486]
As user adoption grows, and people start using Flux to manage an ever-increasing number of workloads, I feel like it's important to start thinking about moving away from using the rate-limited Kubernetes REST client in favour of informers. 

This would add some additional complexity to the codebase as initially pointed out by @squaremo, however, I feel like relieving pressure on the API server would be worth this complexity cost. 

I'm not sure how this would impact other parts of the daemon though. 

I am raising this initially as just something to start thinking about.

**Comment by hiddeco** [comment]
Related #46.

**Comment by cristian-radu** [comment]
Initial thoughts around design:

client-go provides informers for all native API types, so all flux workload objects are covered from what I can tell. Informers are tied to a particular namespace so we would need to work out how to maintain the namespace whitelist functionality provided through https://github.com/fluxcd/flux/blob/master/cmd/fluxd/main.go#L173 

I don't believe informers would increase memory usage. If anything, the cache store used by informers can help ensure flux only holds one copy of all relevant workload objects in memory at any given point in time. With the REST client, it is possible to mistakenly load multiple copies if we are not careful.

In terms of CPU usage considerations, removing the rate-limited REST client would allow flux to process a greater number of operations than it can currently which would mean an increase in CPU load in some larger environments. We could, of course, mitigate this by having CPU limits applied to the pod.

**Comment by cristian-radu** [comment]
https://github.com/coreos/prometheus-operator/tree/master/pkg/listwatch looks interesting. 

```
// MultiNamespaceListerWatcher takes allowed and denied namespaces and a
// cache.ListerWatcher generator func and returns a single cache.ListerWatcher
// capable of operating on multiple namespaces.
```

**Comment by stefanprodan** [comment]
Flux v2, based on the [GitOps Toolkit](https://toolkit.fluxcd.io), is using informers cache for all read operations.
