### ISSUE TITLE
Spurious notifications for resources in multi-resource manifest files

### ISSUE THREAD

**Issue by yarinm** [fluxcd/flux#2494]
**Describe the bug**
I have a setup where I have two identical clusters (with same configurations) and both of them are syncing using flux. I have also set up justinbarrick's fluxcloud for notifications in slack / teams.

I have a periodic upgrade to these clusters where I update a deployment's template with a newer image every time.

In the flux logs i always see that message regarding the commit with:
`deployment.apps/myapp configured`

But flux cloud notification always contain arbitrary resource that wasn't changed for instance:
```
Resources updated:
myapp:service/myapp
```

Note that the notification doesn't contain the updated deployment.

Note that all of the resources are defined in a single yaml in the git repo and are only updated with the image version.

I'm not using helm-operator

**Expected behavior**
To get a proper notification that deployment was updated without unrelated resources that were not updated.

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.14.2
- Fluxcloud: 0.3.8
- Kubernetes version: 1.13.10
- Git provider: VSTS
- Container registry provider: Azure Container Registry

**Comment by groodt** [comment]
I'm seeing a similar error.

**Comment by groodt** [comment]
Looks like the error originates here:
https://github.com/fluxcd/flux/blob/28db2f568f4d4b8ead69226309801bd20770f5f9/pkg/daemon/sync.go#L209

It appears flux does not support YAML streams or more than one resource per file if I understand the code correctly.

**Comment by yarinm** [comment]
Good catch, I wonder why flux doesn't just parse the kubectl output with the changed / unchanged logs and sends them instead.

**Comment by trevrosen** [comment]
I'm seeing this too -- my list of resources updated is basically never remotely correct.

**Comment by trevrosen** [comment]
I too am seeing erroneous resources listed as updated in Flux logs (and therefore in Slack messages from Fluxcloud). I'm wondering whether this has anything to do w/ the fact that I'm using `--manifest-generation=true` with Kustomize.

**Comment by 2opremio** [comment]
> I'm wondering whether this has anything to do w/ the fact that I'm using `--manifest-generation=true` with Kustomize.

Yes, I think that makes it worse, because:

https://github.com/fluxcd/flux/blob/28db2f568f4d4b8ead69226309801bd20770f5f9/pkg/daemon/sync.go#L219-L227

**Comment by trevrosen** [comment]
@2opremio yeah that makes sense. Perhaps the best solution here would be to make it easier to alter the event formatter template so that we can just elide the list of altered resources if we choose to.
