### ISSUE TITLE
1.15.0 is not available - docker

### ISSUE THREAD

**Issue by moh-abk** [fluxcd/flux#2507]
**Describe the bug**
Version 1.15.0 is not .available on docker

**To Reproduce**
Steps to reproduce the behaviour:
attempt do deploy `weaveworks/flux:1.15.0`

**Expected behavior**
new image is pulled and flux is deployed

**Logs**
`Failed to pull image "weaveworks/flux:1.15.0": rpc error: code = Unknown desc = Error response from daemon: manifest for weaveworks/flux:1.15.0 not found`

**Comment by stefanprodan** [comment]
Yes that's expected see #2491
