### ISSUE TITLE
Are there any plans to update the version of HelmOperator that is deployed with the flux helm chart to a stable version?

### ISSUE THREAD

**Issue by atbe** [fluxcd/flux#2510]
**Describe the feature**
Currently the `flux` HelmChart (version 0.15.0) is setup to deploy v0.10.0 of the HelmOperator.

There is a stable version of the HelmOperator release, as shown in the [docker hub tag list](https://hub.docker.com/r/fluxcd/helm-operator/tags).

**What would the new user story look like?**
1. User installs flux HelmChart
2. Default value for HelmOperator should use a stable version of the HelmOperator now that a stable version is available.

Feel free to add a diagram if that helps explaining things.

**Expected behavior**
A clear and concise description of what you expect to happen.

**Comment by atbe** [comment]
Here is the line in the flux Helm chart which references the old version of the HelmOperator

https://github.com/fluxcd/flux/blob/v1.15.0/chart/flux/values.yaml#L25

**Comment by hiddeco** [comment]
The Helm operator now has a [dedicated Helm chart](https://github.com/fluxcd/helm-operator/tree/chart-0.2.0/chart/helm-operator), there is a mention of this in the [`CHANGELOG.md` for the latest `0.15.0` release](https://github.com/fluxcd/flux/blob/chart-0.15.0/chart/flux/CHANGELOG.md#0150-2019-10-07).

**Comment by atbe** [comment]
@hiddeco got it, so basically `HelmOperator` will need to be installed separately from flux in the next release. Did I understand that point in the changelog correctly?

**Comment by hiddeco** [comment]
I am not sure if it will be removed completely or if it becomes an optional dependency, but it won't be embedded in the chart as it is now and  all Helm operator related manifests will be removed.

**Comment by stefanprodan** [comment]
Even if we add it as a dependency it will not be possible to upgrade from the current one since the Helm Operator chart values are structured differently. 

@atbe yes you'll have to install Helm Operator separately from Flux, but you have the option to use the same SSH key as Flux. This change will not cause any downtime since it will not affect the installed charts.

**Comment by atbe** [comment]
@stefanprodan yeah that makes sense, I have already upgraded my helm installation of flux to use the new HelmOperator by passing the following value to helm `helmOperator.tag=1.0.0-rc2`.

I haven't had any issues with this so far, but perhaps should reinstall Flux and set `helmOperator.create=false` and then install the Helm Operator through its helm chart individually. Do you think that's a better approach than just updating the `helmOperator.tag` in my Flux helm installation?

**Comment by stefanprodan** [comment]
Replacing the 0.x version with 1.x will not work since the 1.x doesn't know about HelmRelease v1beta1, please see the instruction in the changelog on how to upgrade.

**Comment by atbe** [comment]
@stefanprodan I already updated all of my HelmRelease resource definitions. I will proceed stick with what we've got now and remove the bundled Helm Operator when the next version of Flux is released.

Thanks for the quick responses.
