### ISSUE TITLE
No ECDSA host key is known for **** and you have requested strict checking.\r\nHost key verification

### ISSUE THREAD

**Issue by 13567436138** [fluxcd/flux#2512]
ts=2019-10-12T02:56:27.202180272Z caller=loop.go:101 component=sync-loop err="git repo not ready: git clone --mirror: fatal: Could not read from remote repository., full output:\n Cloning into bare repository '/tmp/flux-gitclone156224658'...\nNo ECDSA host key is known for **** and you have requested strict checking.\r\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"

**Comment by 13567436138** [comment]
i added pub key to gogs,still cant not access

**Comment by hiddeco** [comment]
Judging by the logged message, you did not add the required `known_hosts` entries for your private git server. Instructions on how to do this [can be found in the documentation](https://docs.fluxcd.io/en/stable/guides/use-private-git-host.html).

**Comment by 13567436138** [comment]
actual Ihave add to gogs，when i add to github ，it works。but add to gogs，it doesn't work

**Comment by hiddeco** [comment]
This is because you haven't added the hosts keys of your Gog server to the `known_hosts` file Flux uses to connect to Git over SSH. If you follow the instructions in the linked doc, it will work.

**Comment by cdenneen** [comment]
@hiddeco please update link to non-404 https://docs.fluxcd.io/en/stable/guides/use-private-git-host.html

**Comment by timurista** [comment]
Link is still broken: https://docs.fluxcd.io/en/1.20.0/guides/use-private-git-host.html.

**Comment by kingdonb** [comment]
The docs have been updated thanks to #3426 reports, both links above now show content and so I think this report is answered and can be closed:

https://docs.fluxcd.io/en/stable/guides/use-private-git-host/
