### ISSUE TITLE
Allow setting of git url after installation

### ISSUE THREAD

**Issue by DazKins** [fluxcd/flux#2528]
**Describe the feature**
In our current project we would like to be able to have flux running in a cluster and then set the url of the git repo later on.

**What would the new user story look like?**
How would the new interaction with Flux look like? E.g.
0. User starts up flux with or without a git configuration
1. The user can set the configuration while flux is running using fluxctl

**Expected behavior**
Once the git configuration is set, flux operates just as it would if it had been installed with the git configuration at that point

**Comment by stefanprodan** [comment]
This could be solved by https://github.com/fluxcd/flux/pull/2479 You would modify the config map and push the change in the cluster, Flux will pick it up and use the git repo specified in the config.

**Comment by DazKins** [comment]
> This could be solved by #2479 You would modify the config map and push the change in the cluster, Flux will pick it up and use the git repo specified in the config.

If I understand that PR correctly though, it only amalgamates configuration into a single file. Pushing a git url change to the cluster would still require a re-deployment of flux by changing the yaml. The feature I'm suggesting is being able to set the git url on the active flux pod without re-deploying.

**Comment by stefanprodan** [comment]
You don't need to redeploy it, just delete the pod or make Flux restart itself
