### ISSUE TITLE
aks/acr auto update won't pickup new image when digestion is the same

### ISSUE THREAD

**Issue by smartpcr** [fluxcd/flux#2536]
**Describe the bug**
I had the following annotation in deployment yaml and it's been able to do auto-update when I publish a new image to acr with different tag and digestion.
``` yaml
"flux.weave.works/automated": "true"
```

However, when only image tag is changed, digestion remains the same, flux won't pick up newer image.

It seems ACR uses digestion to associate images of different tags, as when I delete a image with one tag, it will also delete the other image with the same digestion but different tag.

**To Reproduce**
retag the same image and publish to ACR, flux won't be able to pick it up.

**Expected behavior**
flux should be able to pick up image with newer tag, even when digestion is the same as previous image.

**Logs**
don't see any related logs.

**Comment by 2opremio** [comment]
@smartpcr is this still an issue?
