### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by datacticapertti** [fluxcd/flux#2538]
Page http://docs.fluxcd.io/en/stable/references/fluxyaml-config-files.html links to https://github.com/fluxcd/flux-kustomize-example which gives 404.

Paragraph:

Here is a specific .flux.yaml example, declaring a generator and an updater using Kustomize (see https://github.com/fluxcd/flux-kustomize-example for a complete example).

**Comment by hiddeco** [comment]
@fons this is probably the right time to move the repository to the `fluxcd` GitHub organization.

**Comment by stefanprodan** [comment]
or drop that in favour of https://github.com/fluxcd/multi-tenancy-team1

**Comment by hiddeco** [comment]
@stefanprodan I would argue that they both serve a different purpose. One is focused on giving an example of the basics, while the other one provides a boilerplate for a more complex setup.

If the cost of maintaining the examples isn't too high, I would propose to keep them both to prevent a steep learning curve by providing steps.

**Comment by 2opremio** [comment]
This isn't an issue anymore
