### ISSUE TITLE
Add registry-include-image parameter

### ISSUE THREAD

**Issue by bonhamcm** [fluxcd/flux#2545]
**Describe the feature**

As a developer, I would like for Flux to only scan the registry of my private repository. This way I don't have to update the exclude list anytime a new non-validated registry is used in a deployment.

**What would the new user story look like?**

I could exclude all registries, and the include parameter would just include my private repository, e.g.:

```
--registry-exclude-image="*"
--registry-include-image="private.repo/*"
```

Feel free to add a diagram if that helps explaining things.

**Expected behavior**

Flux would look at the exclude list first and then the include list to only scan the appropriate registries for autodeploying images.

**Comment by demisx** [comment]
I would love to see this happen as well. Our use case is very similar. We only want Flux to scan our private GitLab registry where we publish app images and ignore everything else.

**Comment by zsylvia** [comment]
Should be closed for https://github.com/fluxcd/flux/pull/2850
