### ISSUE TITLE
New flux deployment in new namespace picks up git.url from existing flux

### ISSUE THREAD

**Issue by marchmallow** [fluxcd/flux#2556]
**Describe the bug**
We had a cluster with flux deployed in a `flux` namespace via helm with tiller in kube-system namespace, with helm not using tls.

Deployed a new flux in new `fluxns` namespace via helm with tiller in same `fluxns` namespace using tls this time, pointing git.url it to a new repo, but it looks like it is still mirroring and deploying the releases from the github repo that the existing flux was trailing instead.

I then purged both older and newer installations of flux, and also all helm releases deployed from both. Then reinstalled the flux with the new settings in the same `fluxns` namespace, but it keeps mirroring the old repo not just the new one.

At first it did not deploy releases from the new repo then I realized I forgot to grant the new repo access for the user that I added the ssh key to after flux deployment, fixed that then it deployed releases from the new repo but old ones still there.. I tried to delete them from helm after revoking access to the github userid but they got recreated, for now I deleted them without purge option so that flux cannot recreate them, but would like to clean it up properly and understand where does it read the old settings from.

New flux git.url repo: git@github.ibm.com:fd4b-agrotech-incubator/deployment-manifests.git
Old flux git.url repo: git@github.ibm.com:fd4b-agrotech-incubator/deployment-manifests-incubator.git

**To Reproduce**
Steps to reproduce the behaviour:

Installation command:
```
ssh-keyscan github.ibm.com > /tmp/flux_known_hosts

HELM_HOME=/Users/max/.helm TILLER_NAMESPACE=fluxns helm repo add fluxcd https://charts.fluxcd.io

HELM_HOME=/Users/max/.helm TILLER_NAMESPACE=fluxns helm install --tls --name fluxns fluxcd/flux --set git.url=git@github.ibm.com:fd4b-agrotech-incubator/deployment-manifests.git --set git.path=releases --set git.branch=master --set-file ssh.known_hosts=/tmp/flux_known_hosts --set registry.dockercfg.enabled=true --set registry.dockercfg.secretName=dpr-secret --set registry.dockercfg.configFileName=/dockercfg/.dockerconfigjson --namespace fluxns --tiller-namespace fluxns --tls --tls-verify --tls-ca-cert .helm/ca.pem --tls-cert .helm/tiller-cert.pem --tls-key .helm/tiller-key.pem --set helmOperator.create=true --set helmOperator.createCRD=false --set helmOperator.tls.enable=true --set helmOperator.tls.verify=false --set helmOperator.tls.secretName=helm-client --set helmOperator.tls.caContent="$(cat .helm/ca.pem)" --set helmOperator.tillerNamespace=fluxns
```

**Expected behavior**
Flux will mirror and apply releases from value provided to `git.url`

**Logs**
Helm operator log (start up phase):
```
W1025 12:17:46.512719       6 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
ts=2019-10-25T12:17:46.603235661Z caller=helm.go:88 component=helm info="connected to Tiller" version="sem_ver:\"v2.13.1\" git_commit:\"618447cbf203d147601b4b9bd7f8c37a5d39fbb4\" git_tree_state:\"clean\" " host=tiller-deploy.fluxns:44134 options="{Host: Port: Namespace:fluxns TLSVerify:false TLSEnable:true TLSKey:/etc/fluxd/helm/tls.key TLSCert:/etc/fluxd/helm/tls.crt TLSCACert: TLSHostname:}"
ts=2019-10-25T12:17:46.603507008Z caller=operator.go:95 component=operator info="setting up event handlers"
ts=2019-10-25T12:17:46.603889999Z caller=operator.go:115 component=operator info="event handlers set up"
ts=2019-10-25T12:17:46.603962846Z caller=main.go:213 component=helm-operator info="waiting for informer caches to sync"
ts=2019-10-25T12:17:46.704178384Z caller=main.go:218 component=helm-operator info="informer caches synced"
ts=2019-10-25T12:17:46.704281321Z caller=operator.go:127 component=operator info="starting operator"
ts=2019-10-25T12:17:46.704328013Z caller=operator.go:129 component=operator info="starting workers"
ts=2019-10-25T12:17:46.704388368Z caller=chartsync.go:152 component=chartsync info="starting git chart sync loop"
ts=2019-10-25T12:17:46.705075938Z caller=server.go:42 component=daemonhttp info="starting HTTP server on :3030"
ts=2019-10-25T12:17:46.761278318Z caller=chartsync.go:278 component=chartsync info="started mirroring repo" repo=git@github.ibm.com:fd4b-agrotech-incubator/deployment-manifests-incubator.git
```

FLux log (start up phase):
```
Flag --registry-poll-interval has been deprecated, changed to --automation-interval, use that instead
ts=2019-10-25T12:17:46.252188718Z caller=main.go:248 version=1.15.0
ts=2019-10-25T12:17:46.252244757Z caller=main.go:383 msg="using in cluster config to connect to the cluster"
ts=2019-10-25T12:17:46.396184605Z caller=main.go:468 component=cluster identity=/var/fluxd/keygen/identity
ts=2019-10-25T12:17:46.396236876Z caller=main.go:469 component=cluster identity.pub=" ssh key ...."
ts=2019-10-25T12:17:46.396265599Z caller=main.go:474 host=https://172.21.0.1:443 version=kubernetes-v1.14.7+IKS
ts=2019-10-25T12:17:46.396330154Z caller=main.go:486 kubectl=/usr/local/bin/kubectl
ts=2019-10-25T12:17:46.400781174Z caller=main.go:498 ping=true
ts=2019-10-25T12:17:51.403814723Z caller=main.go:633 url=ssh://git@github.ibm.com/fd4b-agrotech-incubator/deployment-manifests.git user="Weave Flux" email=support@weave.works signing-key= verify-signatures=false sync-tag=flux-sync state=git readonly=false notes-ref=flux set-author=false git-secret=false
ts=2019-10-25T12:17:51.40389586Z caller=main.go:736 upstream="no upstream URL given"
ts=2019-10-25T12:17:51.404063042Z caller=loop.go:101 component=sync-loop err="git repo not ready: git repo has not been cloned yet"
ts=2019-10-25T12:17:51.404096435Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2019-10-25T12:17:51.404108527Z caller=images.go:27 component=sync-loop msg="no automated workloads"
```

**Additional context**
Add any other context about the problem here, e.g
- Old Flux version: 1.10.1 (chart flux-0.6.3)
- New Flux version: 1.15.0 (chart flux-0.15.0)
- New Helm Operator version: 0.10.1
- Kubernetes version: 1.14.7
- Git provider: IBM enterprise github (github.ibm.com)
- Container registry provider: IBM Cloud Private Docker registry

**Comment by marchmallow** [comment]
I wonder if this `W1025 12:17:46.512719       6 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.` is the root cause of the problem what/where inClusterConfig is. I can provide more logs if needed. Thanks!

**Comment by hiddeco** [comment]
The git repository you configure for Flux has no relation to the git repositories you define in your `HelmRelease` resources. My theory is that you copied/forked the repository from `deployment-manifests-incubator` to `deployment-manifests`, while not changing the Git repositories defined in the `HelmRelease`s.

**Comment by marchmallow** [comment]
well I copied HelmRelease resources from  deployment-manifests-incubator to deployment-manifests but I updated all the releaseName and metadata name, also copied charts to new repo and pointing to that repo, eg:

**Comment by hiddeco** [comment]
Did you also remove the old `HelmRelease` resources from the cluster after you changed the metadata name? Because if you didn't, they are still defined in the cluster, and the Helm operator performs operations purely based on the resources it receives from the cluster.

**Comment by marchmallow** [comment]
Thanks Hidde... well I did not not initially, as I had 2 separate deployment of flux/tiller and wanted to preserve the original ones while deploying the new flux/tiller in new namespace.. and was trying to do that in parallel, that is why I changed the release names in all the manifests.. but after hitting this problem I deleted everything, the existing flux and all the releases created by it and the new flux with all releases created from it as well - I did not redeploy tiller (so have 2 tillers: one in kube-system and new one in fluxns namespace but helm list ran against both will show no releases if you like..). After this I reinstalled the newer flux with new repo settings but it still went to look for the old repo (logs I copied in the issue are from this last deployment of flux). Hence I do not understand where did it read the old settings from really.

**Comment by hiddeco** [comment]
> Hence I do not understand where did it read the old settings from really.

`ts=2019-10-25T12:17:46.761278318Z caller=chartsync.go:278 component=chartsync info="started mirroring repo" repo=git@github.ibm.com:fd4b-agrotech-incubator/deployment-manifests-incubator.git`

Is added as a mirror because some `HelmRelease` resource was given to the operator with a `chart.git` set to this value.

There is _technically (== literally)_ no other way this would otherwise be possible, given there is no 'settings storage', and it purely operates based on the objects it received from the API milliseconds before creating the mirror: `ts=2019-10-25T12:17:46.704178384Z caller=main.go:218 component=helm-operator info="informer caches synced"`

**Comment by marchmallow** [comment]
Ok.. so right the first time I deployed flux with git.url=git@github.ibm.com:fd4b-agrotech-incubator/deployment-manifests.git the charts repo was still set to git@github.ibm.com:fd4b-agrotech-incubator/deployment-manifests-incubator.git but then on the latest redeployment I copied and pointed the charts to a new repo as: git@github.ibm.com:fd4b-agrotech-incubator/helm-charts.git

**Comment by marchmallow** [comment]
So I see that once I fixed the repo access for the userid where I copied the ssh key, it started to mirror that repo:

`ts=2019-10-25T12:47:12.158823307Z caller=chartsync.go:278 component=chartsync info="started mirroring repo" repo=git@github.ibm.com:fd4b-agrotech-incubator/helm-charts.git`

But I was not expecting it to mirror the other repo at that point. I double checked the commit history and I pushed the chart repo change before latest deployment

**Comment by 2opremio** [comment]
@marchmallow Is this still an issue or can I close this?

**Comment by marchmallow** [comment]
I think can be closed. Didn't occur again. Thanks
