### ISSUE TITLE
fluxctl install does not know about --manifest-generation flag

### ISSUE THREAD

**Issue by datacticapertti** [fluxcd/flux#2557]
**Describe the bug**
Documentation at https://docs.fluxcd.io/en/stable/references/fluxyaml-config-files.html mentions that manifest generation needs to be explicitly enabled. However, `fluxctl install`does not recognize it:

    $ fluxctl version
    1.15.0
    $ fluxctl install --git-url=ssh://example.com --git-email=example@example.com --manifest-generation=true
    Error: unknown flag: --manifest-generation

It is not entirely clear to me whether the flag is really needed or not.

**Comment by hiddeco** [comment]
This is not a bug, `fluxctl install` only supports a subset of flags for the time being.

```sh
$ fluxctl install --help
Print and tweak Kubernetes manifests needed to install Flux in a Cluster

Usage:
  fluxctl install [flags]

Examples:
# Install Flux and make it use Git repository git@github.com:<your username>/flux-get-started
fluxctl install --git-url 'git@github.com:<your username>/flux-get-started' | kubectl -f -

Flags:
      --git-branch string   Git branch to be used by Flux (default "master")
      --git-email string    Email to use as git committer
      --git-label string    Git label to keep track of Flux's sync progress; overrides both --git-sync-tag and --git-notes-ref (default "flux")
      --git-path strings    Relative paths within the Git repo for Flux to locate Kubernetes manifests
      --git-url string      URL of the Git repository to be used by Flux, e.g. git@github.com:<your username>/flux-get-started
      --git-user string     Username to use as git committer (default "Flux")
  -h, --help                help for install
      --namespace string    Cluster namespace where to install flux (default "default")
  -o, --output-dir string   a directory in which to write individual manifests, rather than printing to stdout
```

If you need to set any additional arguments on the daemon container, you need to modify the YAML output the command generates before applying it the cluster.

**Comment by datacticapertti** [comment]
Fair enough. It would be good to indicate it somewhere in the documentation, though.

The getting started tutorial https://docs.fluxcd.io/en/stable/tutorials/get-started.html gives the impression that `fluxctl install` is the way to install flux.

The manifest factorization section https://docs.fluxcd.io/en/stable/references/fluxyaml-config-files.html just mentions that you need to give fluxd the `--manifest-generation` flag which to a novice like me looks just like `--git-branch`or `--git-path` flags, which are obviously given to fluxd.

**Comment by hiddeco** [comment]
#2558 will both make it easier to provide additional arguments to `fluxctl install`, and also document it in the getting started tutorial.

**Comment by datacticapertti** [comment]
Great, that seems to do exactly what I'd hope. I'll close this issue.
