### ISSUE TITLE
flux-helm-operator repeats error the server could not find the requested resource (get helmreleases.flux.weave.works)

### ISSUE THREAD

**Issue by dareolu** [fluxcd/flux#2561]
I have installed fluxcd into our cluster using the helmchart but getting the error 

"Failed to list *v1beta1.HelmRelease: the server could not find the requested resource (get helmreleases.flux.weave.works)"

Ina previous similar issue raised [here ](https://github.com/fluxcd/flux/issues/2326) @stefanprodan suggested to run the step to configure the CRD. But I can see this already defined in the helm templates for fluxcd. So i dont need to run kubectl to install it.

Kindly advise, what am i doing worng here?

**Comment by hiddeco** [comment]
You still need to run it as installing the CRD using the chart is discouraged, and disabled by default.

**Comment by dareolu** [comment]
Thanks @hiddeco 

The url now has a 404

https://raw.githubusercontent.com/fluxcd/flux/master/deploy-helm/flux-helm-release-crd.yaml

**Comment by dareolu** [comment]
Thanks. Is there a slack channel i can join to follow this product?

**Comment by hiddeco** [comment]
@dareolu we are on the CNCF Slack in `#flux`, you can request an invite [here](https://slack.cncf.io).
