### ISSUE TITLE
Memcached connection errors even with `--registry-exclude-image=*`

### ISSUE THREAD

**Issue by cmur2** [fluxcd/flux#2584]
**Describe the bug**
I want to use the great fluxd only for syncing changes from git to a Kubernetes cluster but do not want to use the Docker image registry scanning feature of fluxd. Therefore I specified the `--registry-exclude-image=*` parameter which works.
To avoid having to run the now useless Memcached I removed it manually from the deployment descriptor yaml as this is another moving part that needs oversight and consumes resources.

Now I get error messages like although fluxd continues to work as usual:
```
ts=2019-11-06T08:38:37.409269301Z caller=memcached.go:156 component=memcached err="error updating memcache servers: lookup _memcached._tcp.memcached on 10.96.0.10:53: no such host"
```

**To Reproduce**
Steps to reproduce the behaviour:
1. My setup: fluxd on minikube with a Github repository and `--registry-exclude-image=*` parameter
2. Get deployment descriptor yamls from https://github.com/fluxcd/flux/tree/master/deploy excluding files starting with `memcached-*`
3. Modify https://github.com/fluxcd/flux/blob/master/deploy/flux-deployment.yaml to comment out all `memcached-*` options and include `--registry-exclude-image=*` parameter
4. Apply modified deployment descriptor yamls
5. See error in kubectl logs

**Expected behavior**
I would be great if fluxd would recognize the `--registry-exclude-image=*` parameter to stop trying to connect to Memcached without emitting errors.

**Logs**
```
ts=2019-11-06T08:38:37.409269301Z caller=memcached.go:156 component=memcached err="error updating memcache servers: lookup _memcached._tcp.memcached on 10.96.0.10:53: no such host"
```

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.15.0
- Kubernetes version: 1.16 on minikube
- Git provider: Github
- Container registry provider: disabled

**Comment by texasbobs** [comment]
We are experiencing this as well.  If the values.yaml file, we have set the memcache enabled to false
```
memcached:
  enabled: false
```
This correctly prevents the memcache files from being created. However, the output from helm has the parameter `--memcached-hostname=name-flux-memcached` listed for the flux deployment and Flux constantly produces the following message in the logs.

```
caller=memcached.go:156 component=memcached err="error updating memcache servers: lookup _memcached._tcp.name-flux-memcached on 169.254.25.10:53: no such host"
```

Even when removing the `--memcached-hostname=`, there is still a check for memcache servers and of course, they are not found.  

We are one Flux version 1.16.0

Is there a way to prevent Flux from checking to see if a memcache server exists?

**Comment by masterkain** [comment]
```
│ ts=2019-12-08T08:27:50.821290777Z caller=memcached.go:112 component=memcached err="Fetching tag from memcache: read tcp 192.168.139.158:49960->10.100.168.47:11211: i/o timeout"
```

**Comment by 2opremio** [comment]
This will be fixed by #2524

**Comment by texasbobs** [comment]
Thanks, @2opremio. I see it was last updated 23 days ago.  What do you feel is the timeline for that PR?

**Comment by 2opremio** [comment]
Christmas vacation got on its way. I will retake it next week.
