### ISSUE TITLE
Using oc client (openshift) via --kubernetes-kubectl

### ISSUE THREAD

**Issue by kallanseto** [fluxcd/flux#2591]
**Describe the bug**
Investigating running flux on OpenShift 3.11. 

I have updated the container with the oc binary and set the flux container arg --kubernetes-kubectl accordingly.

Seeing the following messages in the pod logs and can confirm that nothing has been applied in the cluster:
ts=2019-11-08T01:42:25.2367226Z caller=sync.go:545 method=Sync cmd="kubectl apply -f -" took=951.2µs err="running kubectl: " output=
ts=2019-11-08T01:42:25.2376872Z caller=sync.go:545 method=Sync cmd="kubectl apply -f -" took=902.3µs err="running kubectl: " output=
ts=2019-11-08T01:42:25.2383194Z caller=sync.go:545 method=Sync cmd="kubectl apply -f -" took=574.8µs err="running kubectl: " output=
ts=2019-11-08T01:42:25.2390777Z caller=sync.go:545 method=Sync cmd="kubectl apply -f -" took=706.8µs err="running kubectl: " output=
ts=2019-11-08T01:42:25.2397768Z caller=sync.go:545 method=Sync cmd="kubectl apply -f -" took=635.6µs err="running kubectl: " output=

However, from inside the container I can manually apply the kustomized manifests (successfully clone the repo and run "kustomize build . | oc apply -f -") and verified they have actually been applied.

Expect that if its working manually inside the container then it should be working.

**To Reproduce**
I have built a container adding in the oc binary and a simple wrapper script (oc-alpine):
Dockerfile:
FROM fluxcd/flux:1.15.0
COPY oc* /usr/local/bin/

The oc-alpine wrapper script just has the line:
/lib/ld-musl-x86_64.so.1 /usr/local/bin/oc $@

(See https://unix.stackexchange.com/questions/497455/how-to-replace-binary-file-in-bin-inside-a-linux-container for a good explanation on this).

Using Kustomize, patch the flux deployment:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          image: <new image>
          args:
            // _other args_
            - --kubernetes-kubectl=/usr/local/bin/oc-alpine
...

**Expected behavior**
Flux should now be able to apply the kustomized manifests on the cluster. But instead see the above errors in the logs and no changes to the cluster.

If I shell into the container I can clone my repo, and "kustomize build . | oc-alpine apply -f -" and the changes are successfully applied.

If I use the standard kubectl in the container I get validation errors since kubectl doesn't recognise openshift resources (e.g. routes).

**Comment by delhage** [comment]
We're running flux on Openshift 3.11 with the stock flux container. So far we have not seen any need to use oc instead of kubectl, as long as your manifests contain the correct apiVersion, i.e. `apiVersion: route.openshift.io/v1`.

Could it be a limitation of Kustomize to not include the correct apiVersion for openshift specific resources? I'm not familiar with Kustomize myself.

**Comment by kallanseto** [comment]
Thanks, good to hear that you've got it working with OpenShift 3.11.  I checked through my manifests and it turns out the issue is that oc accepts "null" as values for some keys whereas kubectl validation rejects them.  I changed the "null" to "[]" and am no longer getting any errors using the standard flux image and kubectl so will go with that!

I'm still wondering why the oc replacement wouldn't work, if applying the manifests manually inside the container worked.  Does the flux container do something other than a pipe into the kubectl (or --kubernetes-kubectl) command?

**Comment by 2opremio** [comment]
> I'm still wondering why the oc replacement wouldn't work, if applying the manifests manually inside the container worked. Does the flux container do something other than a pipe into the kubectl (or --kubernetes-kubectl) command?

No, it should be just that.

Could you try this again with Flux 1.17.0 and see if it's still a problem?

**Comment by 2opremio** [comment]
@kallanseto since this doesn't seem to be a problem anymore I am going to close this issue. Please let me know if that isn't the case.
