### ISSUE TITLE
Helm Operator attempts to clone git repo with an invalid URL

### ISSUE THREAD

**Issue by antegulin** [fluxcd/flux#2600]
**Describe the bug**
When installing flux via helm, the value supplied in`git.url` is not the final URL which will be used by the fluxcd to clone the repo.

**To Reproduce**
1. Install fluxcd with Helm
```
helm upgrade -i flux \
--set helmOperator.create=true \
--set helmOperator.createCRD=false \
--set git.url="git@bitbucket.com:foo/config" \
--namespace flux \
fluxcd/flux
```

2. See helm operator logs
```kubectl -n flux logs flux-helm-operator```

3. Find that helm operator attempts to clone a git repo with invalid URL
```
ts=2019-11-11T15:20:15.4293725Z caller=chartsync.go:535 component=chartsync info="chart repo not ready yet" resource=test:helmrelease/api-test status=new err="git clone --mirror: fatal: repository 'git@bitbucket.com/foo/config' does not exist, full output:\n fatal: repository 'git@bitbucket.com/foo/config' does not exist\n"
```

**Expected behavior**
I expected the flux to clone the git repo with following URL ```git@bitbucket.com:foo/config```, but instead it attempted to clone via ```git@bitbucket.com/foo/config``` which is invalid.

**Additional context**
- Flux version: 1.15
- Git provider: Bitbucket

**Comment by stefanprodan** [comment]
The Helm Operator doesn't uses the git URL passed to Flux at install time. Check your HelmRelease files, one of them has the `git@bitbucket.com/foo/config`.
