### ISSUE TITLE
Add a resource sync error counter

### ISSUE THREAD

**Issue by evgenii-petrov-arrival** [fluxcd/flux#2608]
**Describe the feature**
I want to have a way to generate prometheus alerts on failure to sync resources.

Currently flux daemon logs such failures, for example:

```
ts=2019-11-13T11:45:25.725480975Z caller=sync.go:159 component=daemon err="default:persistentvolumeclaim/prometheus-server: running kubectl: The PersistentVolumeClaim \"prometheus-server\" is invalid: spec.resources.requests.storage: Forbidden: field can not be less than previous value"
```

Adding a new prometheus metric would make it easy to alert on failure to sync resources. 

Alternatively Daemon.Sync should return an error if resourceErrors slice is not empty, so that `flux_daemon_sync_duration_seconds_count{success="false"}` is incremented.

**What would the new user story look like?**

1. A user commits an invalid manifest to the git repo from which flux syncs resources to the kubernetes cluster
2. Flux daemon tries to apply the commit
3. kubectl apply fails with an error
4. Resource sync error counter is incremented
5. Prometheus scrapes flux daemon
6. An alert fires for sync error rate being above threshold, the alert is routed to the user
7. User reads flux daemon log to get detailed kubectl apply error
8. User reverts the invalid commit

**Expected behavior**
A prometheus counter metric is incremented on resource sync failure.

**Comment by stefanprodan** [comment]
Fixed by https://github.com/fluxcd/flux/pull/2535 and it will be included in the next Flux release.

**Comment by evgenii-petrov-arrival** [comment]
Thanks @stefanprodan !

My initial search failed to turn up https://github.com/fluxcd/flux/issues/2199 and I didn't keep my local branch up to date with master, so didn't observe https://github.com/fluxcd/flux/commit/5c026fab03165f5b336944dedee5a520acc5c93d , will try to do better next time!
