### ISSUE TITLE
Flux not removing deployment field done through manual edits

### ISSUE THREAD

**Issue by rdubya16** [fluxcd/flux#2610]
**Describe the bug**
I was doing some local testing and disabling flux and editing some deployments manually. I added a **name: web** to my deployment's port where there was none in the repo deployment spec. I expected these changes to be wiped out once I re-enabled flux but that didnt occur and after flux successfully ran I still saw the name field in my deployments yaml. 

```
ports:
  - containerPort: 9090
     name: web
     protocol: TCP
```

Wondering if this is expected behaviour?

**To Reproduce**
1. Setup deployment managed by flux
2. Scale flux to zero replicas and perform manual edit of deployment, add a name to the deployment ports where it has none configured in the repo
3. Renable flux, you will see that the deployment spec still has a defined name after the kubectl apply occurs.

**Expected behavior**
The port name would be removed to match the spec the git repo.

**Additional context**
- Flux version: 1.14.2
- Kubernetes version:
- Git provider: Github

**Comment by stefanprodan** [comment]
Flux does a `kubectl apply`, if kubectl 3-way merge doesn't remove then it's nothing Flux can do.
