### ISSUE TITLE
Co-existence with mutating admissions controllers

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/flux#2612]
@stefanprodan 
I read the [notes on Helm 3](https://helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches) today.  They explained to me why, with Helm 2, I was seeing my pods *not* injected with my `linkerd` sidecars in certain situations.  My understanding is that helm *patches* resources  . This means that resources that were modified with a mutating admissions controller do *not* get seen again by the admissions controller.  

What does FluxCD do if I change a resource in Git (not a HelmResource, but a simple K8s manifest)?  Does it patch the resource and *not* pass it through the mutating admissions controller?  Or, does it delete the old resource and insert a new resource?  If it patches the resource, does it suffer the same problem that Helm 2 does, i.e. that the patch could inadvertently undo the work of the mutating admissions controller?

**Comment by stefanprodan** [comment]
> What does FluxCD do if I change a resource in Git (not a HelmResource, but a simple K8s manifest)?

Flux uses `kubectl apply` so all admission controllers will be triggered. 

>  the patch could inadvertently undo the work of the mutating admissions controller?

Flux will never undo something that's not present in git. I've been using Flux with Linkerd, Istio and App Mesh and that's never the case.
