### ISSUE TITLE
Why HelmOperator installed with flux chart uses flux.weave.works instead of fluxcd.io

### ISSUE THREAD

**Issue by cbenjemaa** [fluxcd/flux#2613]
**Describe the bug**
The flux helm chart uses  [flux.wave.works](https://github.com/fluxcd/flux/blob/release/1.15.x/chart/flux/templates/helm-operator-crd.yaml) CRDs.  

Why not using [fluxcd.io](https://github.com/fluxcd/helm-operator/blob/master/chart/helm-operator/templates/crd.yaml) since the v1 release

This is very confusing because of the documentations. Most of guides and tutorials uses `fluxcd.io` annotations. 
https://docs.fluxcd.io/en/stable/tutorials/driving-flux.html
https://github.com/fluxcd/flux-get-started
Except this that uses `flux.weave.works`
https://github.com/fluxcd/helm-operator-get-started

**To Reproduce**
``` 
helm install --name flux --set git.secretName=flux-git-deploy \
    --set helmOperator.create=true \
    --set git.url=ssh://git@github.com/${GHUSER}/${GHREPO} \
    --set helmOperator.tls.enable=true \
    --set helmOperator.tls.verify=false \
    --set helmOperator.tls.secretName=helm-client-certs \
    --namespace flux fluxcd/flux --tls
```

**Logs**
```
➜  ~ kubectl get helmreleases.helm.fluxcd.io
No resources found in default namespace.
➜  ~ kubectl get helmreleases.flux.weave.works
NAME             AGE
myservice   18h
```

**Additional context**
- Flux version: 1.15.0
- Helm Operator version: 0.10.1
- Kubernetes version: 1.14.8
- Git provider: Github
- Container registry provider: GCP

**Comment by stefanprodan** [comment]
The Helm Operator will be removed from the Flux chart once we release helm-op 1.0.0, right now it's in RC. Please check the chart change log https://github.com/fluxcd/flux/blob/master/chart/flux/CHANGELOG.md#0150-2019-10-07

We want to give people enough time to migrate to the new chart before removing it.
