### ISSUE TITLE
Allow automated image updates to partly fail

### ISSUE THREAD

**Issue by HaveFun83** [fluxcd/flux#2619]
**Describe the bug**
If one automated workload failed due to an error like #2618 all automated workloads will be skipped

**To Reproduce**
Steps to reproduce the behaviour:

fluxcd - helmoperator

1. check-in and automated two independent helmrelease workloads
1.1 one should have an error like #2618 
2. update the image within the docker-registry for one image
3. see the flux pod logs
```
ts=2019-11-15T04:46:43.896903279Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2019-11-15T04:46:44.631945883Z caller=images.go:111 component=sync-loop workload=test:helmrelease/truckdispo container=chart-image repo=private-docker-registry.net/test/app-dispo pattern=semver:~1.0 current=private-docker-registry.net/test/app-dispo:1.0.20191112025302 info="added update to automation run" new=private-docker-registry.net/test/app-dispo:1.0.20191115025305 reason="latest 1.0.20191115025305 (1970-01-01 00:00:00 +0000 UTC) > current 1.0.20191112025302 (1970-01-01 00:00:00 +0000 UTC)"
ts=2019-11-15T04:46:44.632758905Z caller=images.go:111 component=sync-loop workload=test:helmrelease/rabbitmq container=chart-image repo=private-docker-registry.net/public/bitnami/rabbitmq pattern=semver:~3.8 current=private-docker-registry.net/public/bitnami/rabbitmq:3.8.0-debian-9-r0 info="added update to automation run" new=private-docker-registry.net/public/bitnami/rabbitmq:3.8.1 reason="latest 3.8.1 (2019-11-11 09:54:51.753729911 +0000 UTC) > current 3.8.0-debian-9-r0 (2019-10-09 14:52:20.19194642 +0000 UTC)"
ts=2019-11-15T04:46:44.632938851Z caller=loop.go:135 component=sync-loop jobID=cbcffd5d-5f97-de26-2303-f46eed9d7492 state=in-progress
ts=2019-11-15T04:46:45.190432924Z caller=releaser.go:59 component=sync-loop jobID=cbcffd5d-5f97-de26-2303-f46eed9d7492 type=release updates=2
ts=2019-11-15T04:46:49.852120628Z caller=loop.go:145 component=sync-loop jobID=cbcffd5d-5f97-de26-2303-f46eed9d7492 state=done success=false err="verifying changes: failed to verify changes: the image for container \"chart-image\" in resource \"test:helmrelease/rabbitmq\" should be \"private-docker-registry.net/public/bitnami/rabbitmq:3.8.1\", but is \"private-docker-registry.net/bitnami/rabbitmq:3.8.1\""
ts=2019-11-15T04:47:45.09607582Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2019-11-15T04:47:45.593071926Z caller=images.go:111 component=sync-loop workload=test:helmrelease/rabbitmq container=chart-image repo=private-docker-registry.net/public/bitnami/rabbitmq pattern=semver:~3.8 current=private-docker-registry.net/public/bitnami/rabbitmq:3.8.0-debian-9-r0 info="added update to automation run" new=private-docker-registry.net/public/bitnami/rabbitmq:3.8.1 reason="latest 3.8.1 (2019-11-11 09:54:51.753729911 +0000 UTC) > current 3.8.0-debian-9-r0 (2019-10-09 14:52:20.19194642 +0000 UTC)"
ts=2019-11-15T04:47:45.59353292Z caller=images.go:111 component=sync-loop workload=test:helmrelease/truckdispo container=chart-image repo=private-docker-registry.net/test/app-dispo pattern=semver:~1.0 current=private-docker-registry.net/test/app-dispo:1.0.20191112025302 info="added update to automation run" new=private-docker-registry.net/test/app-dispo:1.0.20191115025305 reason="latest 1.0.20191115025305 (1970-01-01 00:00:00 +0000 UTC) > current 1.0.20191112025302 (1970-01-01 00:00:00 +0000 UTC)"
```
The log line
`ts=2019-11-15T04:46:45.190432924Z caller=releaser.go:59 component=sync-loop jobID=cbcffd5d-5f97-de26-2303-f46eed9d7492 type=release updates=2` 
is misleading as none of the two images will be updated thru flux.

Only as the failed chart-image was locked flux was able to automate the other image again.

**Expected behavior**
flux should log and skip failed automated releases properly, so that an error within one release should not affect all automated releases.

**Logs**
If applicable, please provide logs of `fluxd` or the helm-operator. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs -n default deploy/flux`.

see above

**Additional context**
Add any other context about the problem here, e.g 
- Flux version:  1.15.0
- Helm Operator version: 1.0.0-rc3
- Kubernetes version: 1.15.4
- Git provider: private gitlab
- Container registry provider: private harbor

**Comment by hiddeco** [comment]
I think it would be better to make this behaviour possible by adding an additional flag to the `fluxctl release` command, e.g. `--allow-failures` (or the opposite, but this proposal would be backwards compatible).

This would make the behaviour and exit status code predictable based on the configured flags.

**Comment by HaveFun83** [comment]
> I think it would be better to make this behaviour possible by adding an additional flag to the `fluxctl release` command, e.g. `--allow-failures` (or the opposite, but this proposal would be backwards compatible).
> 
> This would make the behaviour and exit status code predictable based on the configured flags.

Cool thanks for your quick response. 
But we don't use fluxctl in this case. Only the normal poll interval for new images and changes within the git repo

**Comment by hiddeco** [comment]
@squaremo given the above, is there a reason we currently have a 'succeed all or fail' policy for automated image updates?

**Comment by squaremo** [comment]
I would grant that it's not always -- or even usually -- necessary to make updates atomic (all-or-nothing).

Given the nature of Kubernetes, no-one should be _relying_ on atomic changes. Even if committed to git, and applied to the API at the same time, they won't take effect at the same time. But inconsistencies due to partial updates would persist indefinitely, and probably need human intervention to resolve. So at the least, the failing parts should be made quite visible.

**Comment by hiddeco** [comment]
We could technically just add them to the commit note as 'attempted but failed', to make it observable outside the `fluxd` logs (and maybe even push them as a notification towards the upstream).

**Comment by squaremo** [comment]
> We could technically just add them to the commit note as 'attempted but failed', to make it observable outside the `fluxd` logs (and maybe even push them as a notification towards the upstream).

Yes, and yes. And perhaps introduce (adapt?) a metric for the number of automated updates succeeding/failing.
