### ISSUE TITLE
Git commit triggered all resources from scratch

### ISSUE THREAD

**Issue by alexandrsemak** [fluxcd/flux#2632]
I have created production and development folder and use overlay for determinate common resources but when i added new config flux trigger all HelmRelease from scratch.
I have base/releases with many HelmRelease and development with common `kustomization.yaml`:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- releases/nginx-ingress-controller
- ../releases/ibmcloud-block-storage-plugin
- ../releases/ibm-worker-recovery
- ../patches/coredns-autoscaler-rp
```
Looks like i did smt wrong can you explain?

**Comment by squaremo** [comment]
It is difficult to tell what's wrong from this description. When you say "added new config" do you mean you added a new HelmRelease YAML file, or something else? What did you see that you did not expect? What _did_ you expect?

**Comment by 2opremio** [comment]
Closing due to lack of attention.
