### ISSUE TITLE
Unable to get started with Flux tutorial

### ISSUE THREAD

**Issue by anwarchk** [fluxcd/flux#2635]
**Describe the bug**
I am using the getting started example from : https://docs.fluxcd.io/en/stable/tutorials/get-started.html. After following the instructions to deploy flux deployment, my deployment of flux agent never completes successfully with the pod events shown as below: 
```
Events:
  Type     Reason     Age                From                                                Message
  ----     ------     ----               ----                                                -------
  Normal   Scheduled  <unknown>          default-scheduler                                   Successfully assigned flux/flux-5c8478bf8-vd74q to ip-10-25-9-200.us-west-2.compute.internal
  Normal   Killing    57s                kubelet, ip-10-25-9-200.us-west-2.compute.internal  Container flux failed liveness probe, will be restarted
  Normal   Pulled     31s (x2 over 86s)  kubelet, ip-10-25-9-200.us-west-2.compute.internal  Container image "docker.io/fluxcd/flux:1.16.0" already present on machine
  Normal   Created    31s (x2 over 86s)  kubelet, ip-10-25-9-200.us-west-2.compute.internal  Created container flux
  Normal   Started    30s (x2 over 86s)  kubelet, ip-10-25-9-200.us-west-2.compute.internal  Started container flux
  Warning  Unhealthy  10s (x7 over 80s)  kubelet, ip-10-25-9-200.us-west-2.compute.internal  Readiness probe failed: Get http://10.44.0.3:3030/api/flux/v6/identity.pub: dial tcp 10.44.0.3:3030: connect: connection refused
  Warning  Unhealthy  7s (x5 over 77s)   kubelet, ip-10-25-9-200.us-west-2.compute.internal  Liveness probe failed: Get http://10.44.0.3:3030/api/flux/v6/identity.pub: dial tcp 10.44.0.3:3030: connect: connection refused
```

**To Reproduce**
Steps to reproduce the behaviour:
0. What's your setup? K8 version 1.16.2 , fluxctl 1.16.0
1. Go to https://docs.fluxcd.io/en/stable/tutorials/get-started.html
2. Go to the step where you are deploying flux agent
3. Wait for the deployment to finish. But the pod never gets into a healthy state

**Expected behavior**
Flux agent pod is up and running

**Logs**
ts=2019-11-27T02:08:24.072592862Z caller=main.go:248 version=1.16.0
ts=2019-11-27T02:08:24.072691689Z caller=main.go:383 msg="using in cluster config to connect to the cluster"
ts=2019-11-27T02:08:24.183310373Z caller=main.go:468 component=cluster identity=/etc/fluxd/ssh/identity
ts=2019-11-27T02:08:24.183367829Z caller=main.go:469 component=cluster identity.pub="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAjkquBAIGMsPeAZpGn5hX/xr/SqF8XlObeb/XkWmgjLlVN+8bGfMq6tcGSYb3dxSCjsaBgNQzlbg2LKm7JVVs7t3EAhO0L0MoQ5s6pwQhIXRVDe7D6nD3/bLJyPOKOcasZWnu/f0EkG5ASMR4cfk534whaDn7E0ADLso82m4ox4Rv/IIuV9QFENcrANQknVIFReR24QUPV4MMqa/FJY4Kl0UOJyxWH8/cHTFwj5aw4EBjwZNP0Wlf6krzk2t76zgufzOC0qdiNGDIG5fY8cav9B7U/30mXZEYqFoVSIA0uvIJlR9HdUqhjnU27ixolNpGwomJpG+2GQHIij2gE/U2xRlUgkzOdCRAyLBbfeT8jiaV3/exVnXylIRCUjrzDbXXp9llMdPJTkWvRo2SjKQOzh5ddFgNlf/8IPxLzrQXcmZ8ZsF9ncDUsG3HSGKnV5kxSBCEK22g4VwvMG6EbQpxfNnMrT1vrsna3sgRjcC03Bfo2z+KCEpliVm8Ie+xkas= root@flux-5c8478bf8-6x7f4"
ts=2019-11-27T02:08:24.183398064Z caller=main.go:474 host=https://10.96.0.1:443 version=kubernetes-v1.16.2
ts=2019-11-27T02:08:24.183469429Z caller=main.go:486 kubectl=/usr/local/bin/kubectl
ts=2019-11-27T02:08:24.195807729Z caller=main.go:498 ping=true
ts=2019-11-27T02:09:14.201816389Z caller=main.go:633 url=ssh://git@github.com/anwarchk/flux-get-started user=anwarchk email=anwarchk@users.noreply.github.com signing-key= verify-signatures=false sync-tag=flux state=git readonly=false notes-ref=flux set-author=false git-secret=false
ts=2019-11-27T02:09:14.201903435Z caller=main.go:736 upstream="no upstream URL given"
ts=2019-11-27T02:09:14.201938625Z caller=main.go:771 exiting=terminated
ts=2019-11-27T02:09:14.243626551Z caller=loop.go:101 component=sync-loop err="git repo not ready: git repo has not been cloned yet"
ts=2019-11-27T02:09:14.243687737Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2019-11-27T02:09:14.243711552Z caller=images.go:27 component=sync-loop msg="no automated workloads"
ts=2019-11-27T02:09:14.24372334Z caller=loop.go:70 component=sync-loop stopping=true
ts=2019-11-27T02:09:14.244499356Z caller=main.go:757 addr=:3030
ts=2019-11-27T02:09:14.244859361Z caller=main.go:765 metrics-addr=:3031
ts=2019-11-27T02:09:14.426756416Z caller=warming.go:112 component=warmer stopping=true

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.16.0
- Helm Operator version: N/A
- Kubernetes version: 1.16.2
- Git provider: Github
- Container registry provider: Docker

**Comment by anwarchk** [comment]
Tried an older version and it works. For my demo, this will do. I will get back with more details for 1.16 version

**Comment by ryan4yin** [comment]
same problem with kubernetes 1.16.3

**Comment by rediphone** [comment]
same with 1.15.7 - if there is a solution for this please advise

**Comment by trumhemcut** [comment]
same problem here, any help?
