### ISSUE TITLE
222

### ISSUE THREAD

**Issue by alyonatischenko** [fluxcd/flux#2649]
**Describe the feature**
A clear and concise description of the feature.

**What would the new user story look like?**
How would the new interaction with Flux look like? E.g.
0. What are the prerequisites for this?
1. User starts up Flux using the --add-frobnication flag
2. New commits in git branch happen
3. Deployments happen, which include frobnication

Feel free to add a diagram if that helps explaining things.

**Expected behavior**
A clear and concise description of what you expect to happen.

**Comment by 2opremio** [comment]
Please fill in the template. Closing the issue for now. Feel free to create a new one.
