### ISSUE TITLE
Improve `fluxctl sync` error when Flux cannot clone the git repository

### ISSUE THREAD

**Issue by 2opremio** [fluxcd/flux#2657]
From a user in Slack:

> Hi, could someone point me how can I troubleshoot `Error: git repository ssh://git@gitlab.mydomain.com/myrepo/flux.git is not ready to sync (status: new)`

The user got that error because Flux couldn't clone the repository (the user later fixed the problem by mounting a `known_hosts` file which was missing).

That error is not very helpful because:
* It leaks internal information of how we manage repos (`new` doesn't mean anything to users)
* It's not actionable

A better error would be:

```
Error: git repository ssh://git@gitlab.mydomain.com/myrepo/flux.git cannot be cloned: actual cloning error
```

**Comment by dinosk** [comment]
Hi @2opremio, I would like to work on this issue.
I can reproduce it with a flux pod that fails to clone a repository with this error:
```
sync-loop err="git repo not ready: git clone --mirror: running git command: git [clone --mirror git@<a-gitlab-instance>:user/repo /tmp/flux-gitclone621862374]: context deadline exceeded"
```

and then using fluxctl to sync:
```
$ fluxctl sync --k8s-fwd-ns flux
Error: git repository ssh://git@<a-gitlab-instance>/user/repo is not ready to sync (status: new)
Run 'fluxctl sync --help' for usage.
```

I see the error is passed in https://github.com/fluxcd/flux/blob/master/pkg/daemon/daemon.go#L627 so my idea would be to extend the v6.GitConfig response in https://github.com/fluxcd/flux/blob/master/pkg/daemon/daemon.go#L632 to include it and print it in the fluxctl error message.
Would something along these lines work?
