### ISSUE TITLE
Flux install over HTTPS - error SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by gitsto** [fluxcd/flux#2669]
Hello,
 
After some research on flux I didn't found any issues or pull request about this subject. 
Maybe it's saying somewhere in the documentation... By the way, it's my first issue on github, I'm new to flux too :)

**Describe the bug**
When trying to install [Flux](https://github.com/fluxcd/flux-get-started) using HELM over HTTPS on a Gitea server using https url
I get this error: 
> SSL certificate problem: unable to get local issuer certificate

and so, flux is not starting to perform sync using the git clone commands to deploy images from the flux_get_started/releases/ folder.

**To Reproduce**
Steps to reproduce the behaviour:

0. What's your setup?
I have a Gitea server configured to use HTTPS with a self signed certificate.
I have downloaded and succeed to push the ['flux-get-started'](https://github.com/fluxcd/flux-get-started) project sources over https using the local git 1.8.3.1 of my machine hosting kubernetes, helm, etc...
I've already created a secret in the menu of my account in Gitea "Applications / Manage Access Tokens"

Typically I have a shell script to run the helm install command for flux, inspired from the documentation section [Install Flux with Helm](https://docs.fluxcd.io/en/stable/tutorials/get-started-helm.html#install-flux)

1. my script generates the secret 'flux-git-auth'
```
kubectl create secret generic flux-git-auth --namespace flux --from-literal=GIT_AUTHUSER=myuser--from-literal=GIT_AUTHKEY=mysecretcharsgeneratedfromgitea
```
2. Then my script execute this helm install command for flux

```
helm upgrade --install flux \
--set git.url="https://myuser:mysecretcharsgeneratedfromgitea@mygiteaserver:3000/mysuer/repo.git" \
--set env.secretName=flux-git-auth \
--set git.path="namespaces\,workloads\,releases" \
--set helmOperator.create=true \
--set helmOperator.createCRD=true \
--set image.tag=1.16.0 \
--namespace flux \
fluxcd/flux
```
3. Finally I execute this command to see the logs

```
kubectl -n flux logs deployment/flux -f
```
4. And I can see this error each sync when flux tries to perform a git clone command

> caller=loop.go:101 component=sync-loop err="git repo not ready: git clone --mirror: fatal: unable to access 'https://mygiteaserver:3000/myuser/repo.git/': SSL certificate problem: unable to get local issuer certificate, full output:\n Cloning into bare repository '/tmp/flux-gitclone332431886'...\nfatal: unable to access 'https://mygiteaserver:3000/myuser/repo.git/': SSL certificate problem: unable to get local issuer certificate\n""

**Expected behavior**

Having the sync feature working for flux so the helm releases can be deployed over HTTPS with Gitea.

Note: I've succeeded to use HTTPS with my GitHub account in the past, but here I'm dealing with a self signed certificate on a Gitea server I'm using.

**Logs**
If applicable, please provide logs of `fluxd` or the helm-operator. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs -n default deploy/flux`.

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.16.0
- Helm Operator version: 0.10.1
- Memcached : 1.5.15
- Kubernetes version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1"
- Git provider: gitea
- Container registry provider: ??

**Additional information about my tests**
I've tried many configuration on the git 1.8.3.1 installed on my kubernetes host, to add the self signed certificates or to simply ingore the validation... 
It work for the initial push of the flux-get-started project on my Gitea repository.
But it did not worked for flux sync, because I figured out now that flux has an embeded git client in its docker image

So I looked and it has git v2.22.0 in it.
```
kubectl -n flux exec -it  flux-566c459c89-wzwtj -- bash
bash-5.0# git version
git version 2.22.0
```
And this is why my configuration on my kubernetes host's git was ignored by flux.

I need to find how can I configure flux so I can add the CA certificate file .crt into its image to make its internal git v2.22.0 use it for https connection with the Gitea server.

I've tried to use the helm upgrade --help and tried to use thoses flags without success

>  flag
>       --ca-file string           verify certificates of HTTPS-enabled servers using this CA bundle
>       --cert-file string         identify HTTPS client using this SSL certificate file
> 

I hope I provided enough to get helped on this issue, if not, please ask me to add additional details, and I will

Thanks!
Best regards

**Comment by hiddeco** [comment]
Please read the [Flux documentation about private Git hosts](https://docs.fluxcd.io/en/stable/faq.html#how-do-i-use-a-private-git-host-or-one-that-s-not-github-com-gitlab-com-bitbucket-org-dev-azure-com-or-vs-ssh-visualstudio-com) and the [chart documentation about private Git hosts](https://github.com/fluxcd/flux/tree/master/chart/flux#flux-with-a-private-git-host).

**Comment by gitsto** [comment]
Thanks a lot @hiddeco 
Ok, I understood the usage og the `git.config.data`, it is behaving like a sort of patch which will overwrite in the flux image the /root/.gitconfig file. And this also work is we activate the option `git.config.enabled=true`

So my shell script containing my helm command looks like this now: 

```
# This will be written in the /root/.gitconfig file
GIT_CONFIG_FILE_CONTENT="[http]
  sslCAInfo = /etc/ssl/certs/my_ca_cert.crt
"

helm upgrade --install flux \
--set git.url="https://myuser:mysecretcharsgeneratedfromgitea@mygiteaserver:3000/mysuer/repo.git" \
--set env.secretName=flux-git-auth \
--set git.path="namespaces\,workloads\,releases" \
--set helmOperator.create=true \
--set helmOperator.createCRD=true \
--set image.tag=1.16.0 \
--set git.config.enabled=true \
--set git.config.data="${GIT_CONFIG_FILE_CONTENT}"
--namespace flux \
-f /root/scripts/values.yaml \
fluxcd/flux
```

Note that my knowledge is limited in the mount part.
So you can see that I added a values.yaml file in the helm command, and it contains this code (which is an example I found and adapted for my needs)

```
# this will get the volume and mount it to that path in the container
extraVolumeMounts:
- name: certs
  # location in the container it will put the directory mentioned below.
  mountPath: /etc/ssl/certs

# this is the source folder (local)
extraVolumes:
- name: certs
  hostPath:
    # Path to local directory with the file my_ca_cert.crt
    path: /etc/pki/ca-trust/source/anchors
```

the error message is correct, the file is missing

> fatal: unable to access ''https://mygiteaserver:3000/myuser/repo.git/': error setting certificate verify locations:\n  CAfile: /etc/ssl/certs/my_ca_cert.crt\n  CApath: none

What I'm doing wrong?

**Comment by gitsto** [comment]
Ok, found what was wrong, since the documentation in the [Flux Chart README](https://github.com/fluxcd/flux/blob/master/chart/flux/README.md) was not clear for me about the different usages of the `extraVolumeMounts `and `extraVolumes` properties. I look up on the internet and changed the way I tried before (in my previous helm install command, I used an external file `-f /root/scripts/values.yaml \`).

So now, my command looks like this: 

```
GIT_CONFIG_FILE_CONTENT='
[http]
        sslCAInfo = /etc/ssl/certs/my_ca_cert.pem  <--- here I found a mistake in my previous file and rebuild a new one with .pem instead of .crt extention
'

helm upgrade --install flux \
--set git.url="https://myuser:mysecretcharsgeneratedfromgitea@mygiteaserver:3000/mysuer/repo.git" \
--set env.secretName=flux-git-auth \
--set git.path="namespaces\,workloads\,releases" \
--set helmOperator.create=true \
--set helmOperator.createCRD=true \
--set image.tag=1.16.0 \
--set git.config.enabled=true \
--set git.config.data="${GIT_CONFIG_FILE_CONTENT}"
--namespace flux \
--set extraVolumeMounts[0].name=certs \
--set extraVolumeMounts[0].mountPath="/etc/ssl/certs" \    <--- target folder in the image
--set extraVolumes[0].name=certs \
--set extraVolumes[0].hostPath.path="/etc/pki/ca-trust/source/anchors" \ <--- local folder where the certificate file is
fluxcd/flux
```

And now flux is installed, it looks correctly to the imported CA certificat file in /etc/ssl/certs/ adn synchronize with the repo through HTTPS to deploy helm releases.
