### ISSUE TITLE
Add --sync-interval to Values.yaml

### ISSUE THREAD

**Issue by texasbobs** [fluxcd/flux#2676]
Currently, the sync-interval is set to the value for --git-poll-interval.  We would like to be able to set the git-poll-interval to 1m and set the sync-interval to 5m.  This would allow us to force a sync and overlay any manual editing that might have been performed.

This would allow the output of the helm template command to be used without any manual editing.

### values.yaml
```
  # Period at which to poll git repo for new commits
  pollInterval: "1m"
  # Period at which it will apply what’s in git to the cluster absent new commits
  syncInterval: "5m"
```
### deployment.yaml
- --sync-interval={{ .Values.git.syncInterval }}

**Comment by kingdonb** [comment]
I believe this has been closed through #2721. Thanks for using Flux!
