### ISSUE TITLE
imagePullSecrets best practice

### ISSUE THREAD

**Issue by TomBrouwer** [fluxcd/flux#2677]
Hello,

I searched a lot for a solution to my imagePullSecrets problem. I have installed Flux, it is also running properly. It looks good.

The only problem I still encounter is that in all the namespaces that flux creates (from my git repo) I have to copy my secret for imagePullSecrets. In addition to having the same secret in multiple namespaces, I also cannot easily create a namespace via git. Given the manual action I still do to copy the secret.

How do you and others deal with this? I think I am missing something, but I cannot get it from the docs or search results.

**Comment by texasbobs** [comment]
We use this. https://github.com/homedepot/k8s-global-objects It will copy secrets and configmaps to all namespaces.

**Comment by stealthybox** [comment]
You could use https://github.com/bitnami-labs/sealed-secrets and store the encrypted versions of the ImagePullSecrets in the repository.

The SealedSecret would then be placed into the accompanying new Namespace and the controller will unseal them.

Others use similar encryption techniques to store unreadable Secrets directly in the git repo.
This reduces the manual steps needed to set up a new cluster.

**Comment by TomBrouwer** [comment]
Thanks for your replies.

@texasbobs I will look at it, I think it will solve my problem, but I am also interesed in the answer of stealthybox.

@stealthybox I am using sealed secrets in mij application project now. I am curious how I can solve my problem with sealed secrets. After your answer, I think that when creating a namespace with Flux from git, I can also create imagePullSecrets in the namespace. I hadn't thought of that. I'm going to look at this this week.

**Comment by TomBrouwer** [comment]
Hi,
I created imagePullSecrets within the namespace file. And it did create the secret. So in my directory namespaces I have a dev.yaml. First it was:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
```

Now I added my sealedsecret to this file:
```---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
etc....
```

I hadn't thought of that before. So now I can create namespaces from GIT with there own imagePullSecrets.

Thanks for your responses!
