### ISSUE TITLE
Flux shouldn't get stuck on deadlocked finalizers during garbage collection

### ISSUE THREAD

**Issue by jessebye** [fluxcd/flux#2691]
**Describe the bug**
If any namespace is stuck "terminating" (due to a bad finalizer, for example), flux will stop applying any new changes.

**To Reproduce**
Steps to reproduce the behaviour:
0. Ensure that flux garbage collection is enabled.
1. Add a namespace that has a finalizer. For example, we use an Ansible operator with custom resources, which adds a finalizer to our namespaces so it can clean up the third-party resources it creates.
2. Wait for flux to create the namespace.
3. Delete the namespace from the gitops repo.
4. The namespace gets stuck in "terminating".
5. Add new manifests to the gitops repo.
6. Observe that Flux does not apply the manifests.

**Expected behavior**
Flux should continue creating new resources even if garbage collection is failing.

**Logs**
Nothing noteworthy is logged when flux is hanging.

**Additional context**
- Flux version: `1.16.0`
- Helm Operator version: n/a
- Kubernetes version: `1.14`
- Git provider: GitHub
- Container registry provider: AWS ECR

**Comment by 2opremio** [comment]
We should probably have a timeout with Kubernetes operations. Question is ... to what value since deletionin Flux  is (rightfully) synchronous and finalizers can take a long time .

**Comment by Crevil** [comment]
But its a problem without a timeout as it stops the application from working if no controller is able to respond to the finalize requests.

As long as it is configurable and an error is logged if the timeout is reached, one can tweak it to ones expectations and also get some indication of the problem.

**Comment by 2opremio** [comment]
I am OK with a timeout if we default to none (since we don't know how long finalizers can take) However, I don't think that's very useful.

Alternatively we could make deletions asynchronous, but that's really ugly and can hide errors.

**Comment by Crevil** [comment]
How would they hide? If they appear clear in the logs, I dont find it a problem.

I actually think that approach is better than timeouts, as to your point. That will ensble flux to carry on with other tasks and thus not get to a halt.

**Comment by 2opremio** [comment]
You wouldn't be waiting when an error happens and nothing will be shown in the logs. For instance, when a finalizer hangs like indicated in this issue.

**Comment by Crevil** [comment]
Your right. My mistake. 👍
Any idea how other controllers manage these kind of things? I can think of something right now.

**Comment by jessebye** [comment]
@2opremio any thoughts on how to move forward here? This is a blocker for us using operators more with Flux, since the operators take a while to clean up and the finalizers taking a long time cause all Flux deployments to hang.

**Comment by 2opremio** [comment]
@jessebye can you tell me more about your usecase? 

For instance:

* Why is this blocker?

* How often do finalizers get stuck and why?

* How often do you delete problematic workloads? Are they different workloads all the time? Do you recreate them?

It feels like the underlying cause should be addressed. But I understand that may not be possible.

I don't think we should do synchronous deletions but a few options are:

1. Provide a flag setting the timeout for the k8s clients operations (defaulting to no timeout). Then you can set the timeout to whatever value you think makes sense in your usecase.
2. We could gather the `gracePeriod` from the workloads to be deleted and use that as the deletion timeout. Unfortunately we cannot do that easily until https://github.com/kubernetes/kubernetes/pull/87299 is released and we upgrade the Kubernetes `go-client` to that version.

**Comment by jessebye** [comment]
@2opremio I'd be glad to.

The first place we ran into this was testing new operators we were developing in a cluster. Any time we'd mess up something in the operator, it would start causing any namespace that got deleted to hang at the finalizer step. This would take down Flux deployments every time.

We've since created a separate cluster for testing operators, so this isn't too much of an issue any more. However, now we are considering another use case where the finalizers may take quite a while to finish. Example: destroying an Elasticache instance, which could take 5-10 minutes sometimes. While the instance is being destroyed, the finalizer cannot complete. So every time we destroy an instance (which could be quite frequent, since we spin these up and down dozens of times a day), deployments will hang for that entire time.

So maybe it makes sense to look at this as an issue with deployments hanging whenever a delete takes a long time, rather than thinking of it as an issue when finalizers hang indefinitely.

**Comment by 2opremio** [comment]
> So every time we destroy an instance (which could be quite frequent, since we spin these up and down dozens of times a day), deployments will hang for that entire time.

I think it makes sense for Flux to wait for that time. Is there any undesirable side-effect apart from the wait itself?

We could also supply a deletion timeout (once kubernetes/kubernetes#87299 reaches Flux)

**Comment by jessebye** [comment]
What the wait translates to is all deployments stop for that period of time. If several destroys stack up, that could mean 30-60 minutes of no new deployments.

Since Flux is the only way we create new deployments, and our engineers expect a new deployment to spin up in <5 minutes normally, having a deployment take an unpredictably longer time is a problem for us.

**Comment by jessebye** [comment]
It'd be much better if Flux could have a separate thread that was responsible for garbage collection, so that could take a long time without interfering with new manifests getting applied.

**Comment by 2opremio** [comment]
That would make deletions asynchronous with respect to applications which could bring quite a few problems.

**Comment by kingdonb** [comment]
This is a very interesting thread, thank you for thinking all this through.

The new Flux v2 has a completely redesigned everything, and I believe still waits for finalizers as demonstrated by fluxcd/flux2#997. However it is built to support multiple reconciliation loops, eg. one Kustomization per app, and this issue is no longer a global problem for Flux. If a reconciler is failing, it can be marked with an error and everything else can go on reconciling.

I think this is resolved by the rewrite. Flux v1 is in maintenance mode now, and is not adding any new features unless they are critical.

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now. Thanks for your contributions!
