### ISSUE TITLE
Flux 1.17.0 unable to poll new images from Quay.io

### ISSUE THREAD

**Issue by swade1987** [fluxcd/flux#2697]
**Describe the bug**
Flux 1.16 was unable to pull new images from quay.io cluster-wide. 

**To Reproduce**
See https://weave-community.slack.com/archives/C4U5ATZ9S/p1576512988014000

**Expected behavior**
Flux should poll images as in previous releases.

**Logs**
**1.15.0**
```
ts=2019-12-16T16:14:05.075068806Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2019-12-16T16:14:06.144694048Z caller=images.go:111 component=sync-loop workload=eevee:helmrelease/accounting-registry container=application repo=quay.io/example/accounting-registry pattern=glob:dev-* current=quay.io/example/accounting-registry:dev-887e19980edbc3a65988a7b4936747298c6ee05a info="added update to automation run" new=quay.io/example/accounting-registry:dev-2b884b05efdcd32e7f5e76cb71fd52369a610c90 reason="latest dev-2b884b05efdcd32e7f5e76cb71fd52369a610c90 (2019-12-16 15:11:58.111934921 +0000 UTC) > current dev-887e19980edbc3a65988a7b4936747298c6ee05a (2019-12-16 14:39:14.563515704 +0000 UTC)"
```

**1.16.0**
```
ts=2019-12-16T16:14:05.075068806Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
1.16 :point_up:
```

**Additional context**
- Flux version: v1.16.0
- Helm Operator version: 1.0.0-rc1
- Kubernetes version: v1.14.6
- Git provider: GitHub
- Container registry provider: Quay.io

**Comment by 2opremio** [comment]
@swade1987 the log excerpt of 1.16 you posted doesn't lead to think anything is wrong.

**Comment by swade1987** [comment]
The args we are using is ...

```
args:
            - --automation-interval=1m
            - --connect=ws://fluxcloud
            - --git-poll-interval=30s
            - --listen-metrics=:3031
            - --manifest-generation=true
            - --memcached-service=
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --sync-garbage-collection=true
            - --sync-interval=30s
            - --sync-timeout=5m
```

The interesting question is the flux instance in question that was erroring doesn't use Kustomize however we are providing the ` - --manifest-generation=true` flag.

Additionally, after I saw flux working with 1.15 again I rolled forward to 1.16 and the same issue happened again until I rolled back.

**Comment by 2opremio** [comment]
@swade1987 thanks for the details but, so far, you haven't included any actual evidence of the symptoms you mention. We obviously believe you, but we need something to work with :). Please share the Flux logs and the Memcache logs (if relevant).

**Comment by 2opremio** [comment]
As a side note, quay is known to have pretty restrictive rate-limiting policies, so, it's normal that you get rate limited until the cache gets filled in.

However, when upgrading you should be able to reuse the cache if you don't delete the memcached deployment.

**Comment by hiddeco** [comment]
Other things that are sometimes valuable while debugging issues like this:

```console
$ fluxctl list-images -w <some workload you expect new images for>
$ fluxctl release -w <some workload you expect new images for> --all-images
``

**Comment by swade1987** [comment]
@hiddeco @2opremio going to close this as upgrading to 1.17 fixed the issue almost immediately.

**Comment by 2opremio** [comment]
That is odd since I don't think anything changed on how we handle container registries

**Comment by swade1987** [comment]
The issue is still persisting in our development cluster with 1.17

**Comment by 2opremio** [comment]
Those are only 2 minutes worth of logs from the start. Can you send us a longer excerpt?

Also, can you send us the `memcached` logs?

> Flux 1.16 was unable to pull new images from quay.io cluster-wide.

To be more precise and understand what is happening. What do you mean by _Flux was unable to pull new images_?  Do you mean that Flux fails to make automated updates? (Flux not pulling images isn't a symptom in itself and the logs don't really show there is a problem. )

If so, can you send us the definition from one of the automated HelmReleases which you were expecting to get updated and tell us what Flux didn't do what you were expecting it to?

**Comment by 2opremio** [comment]
@swade1987 please also provide the information asked by @hiddeco at https://github.com/fluxcd/flux/issues/2697#issuecomment-566283067

**Comment by 2opremio** [comment]
OP's Flux instance was being rate-limited by Quay. It got fixed by restricting the scope of Flux to specific namespaces.
