### ISSUE TITLE
Flux should update version label in deployments.

### ISSUE THREAD

**Issue by jdfalk** [fluxcd/flux#2702]
**Describe the feature**
When flux automatically updates to a new container version, update the `version` and `app.kubernetes.io/version` as well. 

**What would the new user story look like?**
How would the new interaction with Flux look like? E.g.
0. User sets `version` or `app.kubernetes.io/version` labels that match the current image tag
1. User sets `fluxcd.io/automated`: `true`
2. New container version is detected by flux, flux updates `flux-patch.yaml` updating `version`, `app.kubernetes.io/version` and the tag.

**Expected behavior**
Flux updates the `version`, `app.kubernetes.io/version` and tag during a new release.

**Other**
This will allow apps like Istio, Flagger, Kiali, etc to all have accurate information for debugging. For deployments that contain several applications if the version label does not match any of the image tags, flux ignores it and does not update it. Otherwise if it matches what would be `tag.chart-image` it's updated when that is updated. Maybe in addition there is a new annotation to turn this on so that legacy behavior stays the same.

**Comment by 2opremio** [comment]
> Flux updates the `version`, `app.kubernetes.io/version` and tag during a new release.

How would you, in detail, expect `app.kubernetes.io/version` to be updated? To what value and exactly when?

**Comment by stefanprodan** [comment]
As a side note, doing this would not help Flagger at all, as it doesn't rely on labels to detect changes, in fact Flagger removes all labels except for the `app.kubernetes.io/name` when it does a canary promotion.

**Comment by jdfalk** [comment]
>As a side note, doing this would not help Flagger at all, as it doesn't rely on labels to detect changes, in fact Flagger removes all labels from the pod selector except for the app.kubernetes.io/name.

The point is to have the correct versions show in the Kiali versioned app graph. I don't care if Flagger uses it internally, it's useful for DevOps, and management to be able to have this view on a wallboard and can use it to get quick accurate information.

**Comment by jdfalk** [comment]
>How would you, in detail, expect app.kubernetes.io/version to be updated? To what value and exactly when?

When flux defines the update in the flux-patch.yaml (or whatever storage) it updates the version tag of the image, at that same time, I would expect it to also update the version annotation, if they matched before the update. It should be pretty simple, grab annotation version, compare it to the container image tag, if they are the same then when the container image tag is updated than version tag is updated. Otherwise if none of them match, then it stays the same.

**Comment by 2opremio** [comment]
Yes, Flux bumps the value of the version annotation. But, to what value? (The same value as the image tag doesn't make sense for pod specs with multiple containers) Should the version be updated one time per container updated? Only if the annotation already exists? How do you deal with versioning conflicts?

The more I think about it, the more I conclude that, unless there is a widespread pattern around this, we shouldn't include it in Flux.

To be
