### ISSUE TITLE
Flux/ECR - Image Upgrades are not working

### ISSUE THREAD

**Issue by jseiser** [fluxcd/flux#2708]
**Describe the bug**
Flux is not able to update images coming from ECR.

**To Reproduce**
Steps to reproduce the behaviour:
0. EKS Running in Account 1
1. Images, in ECR, in Account 2
2. Grant Access to ECR in Account 2, to Account 1 via 
3. Deploy HelmRelease, where images are in ECR
4. Release Deploys Fine
5. Automated Upgrades fail

**Expected behavior**
I would Expect Flux to be able to track/update images.

**Logs**
```
ts=2019-12-20T18:02:03.849831864Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2019-12-20T18:02:04.047916159Z caller=images.go:159 component=sync-loop err="fetching image metadata for 071xxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/image1: Get https://071xxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/v2/image1/tags/list: no basic auth credentials"
ts=2019-12-20T18:02:04.049531625Z caller=images.go:159 component=sync-loop err="fetching image metadata for 071xxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/image2: Get https://071xxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/v2/image2/tags/list: no basic auth credentials"
```

```
fluxctl --k8s-fwd-ns flux list-images -w sandbox2-com:helmrelease/sandbox2-com

WORKLOAD                                                           CONTAINER      IMAGE           CREATED
sandbox2-com:helmrelease/sandbox2-com                              image2                           image data not available
                                                                                  '-> (untagged)  ?
                                                                   image1                          image data not available
                                                                                  '-> (untagged)  ?
```

**Additional context**

There are no IAM roles on the EKS Node
KIAM Is installed in the cluster, which would prevent API calls from a pod unless it has a role allowing it
FLUX pods have no role
The HelmRelease works, and we get the images, from ECR installed without issue. 

Versions:
flux:1.16.0
helm-operator:1.0.0-rc4

**Comment by jseiser** [comment]
Closing this out, because i figured out the issue.  Im not really sure if this is something that could be added to the documentation, since it gets rather specific.

1) The account your ECR is in, needs to grant access to the account Flux is in, OR, to the role that your flux pod will be granted.
2) Your FLUX/Helm Operator pods need to have a IAM Role on them, that grants read access to ECR in general.

So, the account had access to pull images etc, but I had to explicitly grant a policy the pod assumed which allowed the get operations for ecr:*

**Comment by pbn4** [comment]
@jseiser How can I check what is the account for flux? I'm hitting the same issue.

**Comment by pbn4** [comment]
Unfortunately pod execution role with read ECR permissions did not help me in solving this issue.

**Comment by amit-uc** [comment]
I am having the same issue.

Images are in ECR, in Account 2 Grant Access to ECR in Account 2, via Account 1
Deploy HelmRelease, where images are in ECR and the releases are deployed without any problem.
Automated Upgrades are failing and when I run 
```bash
fluxctl list-images --namespace=myapp --k8s-fwd-ns=fluxcd
```
> Output
```bash
IMAGE						CREATED
image data not available
                                             '-> (untagged)                ?
image data not available
                                             '-> (untagged)                ?
image data not available
                                             '-> (untagged)                ?
image data not available
                                             '-> (untagged)                ?

```

**Comment by amit-uc** [comment]
@pbn4 Any luck?

**Comment by pbn4** [comment]
Yes you need to rotate ECR auth token every 12h using https://github.com/bzon/ecr-k8s-secret-creator. This is a service that will run in your cluster, get auth token on predefined interval and update the secret that flux has mounted as an auth secret for ECR. 
 
I did not find any other solution. 

This secret creator must assume it's role so create a new role e.g. `my_role`. Now make a policy allowing ecr:GetAuthorizationToken and assign it to this new `my_role`. Next make this new role assumable with `AssumeRoleWithWebIdentity`. This is how my terraform assumption policy looks like:

```
data "aws_iam_policy_document" "ecr_oidc_assume_role_policy" {
    statement {
        actions = ["sts:AssumeRoleWithWebIdentity"]
        effect  = "Allow"

        condition {
            test     = "StringEquals"
            variable = "${replace(aws_iam_openid_connect_provider.oidc_eks_provider.url, "https://", "")}:sub"
            values   = ["system:serviceaccount:fkux:ecr-k8s-secret-creator"]
        }

        principals {
            identifiers = [aws_iam_openid_connect_provider.oidc_eks_provider.arn]
            type        = "Federated"
        }
    }
}
```

make sure that the service account you created by following ecr-k8s-secret-creator instructions match what is in `values` in this `ecr_oidc_assume_role_policy`. 

One thing I did not mention is that you need an OIDC provider. Here are the instructions for people using terraform to set this up: 

```
resource "aws_iam_openid_connect_provider" "oidc_eks_provider" {
    client_id_list  = ["sts.amazonaws.com"]
    thumbprint_list = [data.external.oidc_thumbprint.result.thumbprint]
    url             = aws_eks_cluster.eks-cluster.identity.0.oidc.0.issuer
}
```

I also had some problems with the thumbprint, hence:

```
data "external" "oidc_thumbprint" {
    program = ["./utils/get_thumbprint.sh", data.aws_region.current.name]
}
```

and the content of the script:

```
#!/bin/bash

THUMBPRINT=$(echo | openssl s_client -servername oidc.eks.${1}.amazonaws.com -showcerts -connect oidc.eks.${1}.amazonaws.com:443 2>&- | tac | sed -n '/-----END CERTIFICATE-----/,/-----BEGIN CERTIFICATE-----/p; /-----BEGIN CERTIFICATE-----/q' | tac | openssl x509 -fingerprint -noout | sed 's/://g' | awk -F= '{print tolower($2)}')
THUMBPRINT_JSON="{\"thumbprint\": \"${THUMBPRINT}\"}"
echo $THUMBPRINT_JSON
```

**Comment by pbn4** [comment]
Do not forget to set --docker-config on fluxcd to the path where secrets updated by ecr-k8s-secret-creator are mounted (https://docs.fluxcd.io/en/1.19.0/references/daemon/)
