### ISSUE TITLE
`fluxctl sync` exposes password when using https

### ISSUE THREAD

**Issue by mjpitz** [fluxcd/flux#2720]
**Describe the bug**
When performing a `fluxctl sync` on an instance who is configured to use HTTPS credentials, the username and password are exposed in the command line.

**To Reproduce**
Steps to reproduce the behaviour:
0. What's your setup?
1. Configure flux to use HTTPS with credentials.
2. Once flux has been configured use `fluxctl` to synchronize the state.
3. You will see the username and password output to command line in plain text

**Expected behavior**
I would expect the username and password portions of the repository to either be omit or masked when printing to the command line.

**Comment by 2opremio** [comment]
What version of flux are you running?

**Comment by mjpitz** [comment]
Ah. Looks like I was on an older version. `1.17` only outputs the username.

**Comment by 2opremio** [comment]
Great

**Comment by mjpitz** [comment]
Still seems less than ideal that all I need to do to expose a password is checkout and use an older version of the CLI. Any desire to improve that specific use case?

**Comment by 2opremio** [comment]
I thought you upgraded the server, not the CLI, we should filter it out on the server side

**Comment by mjpitz** [comment]
Apologies for the vagueness. I upgraded my client only (1.17). We're on `1.16` for the server.

**Comment by mjpitz** [comment]
I'll try and upgrade our server to see what that outcome is. Rolling back the client shouldn't be too hard to do.
