### ISSUE TITLE
Image scan updates last download time in Nexus OSS

### ISSUE THREAD

**Issue by SmilingNavern** [fluxcd/flux#2734]
**Describe the bug**
Flux updates last download time in docker registry when scanning for image tags.

**To Reproduce**
Steps to reproduce the behaviour:
0. We use flux with nexus oss and docker registry
1. Use flux for some image in docker registry
2. Check that last download time updates after flux scan for tags

**Expected behavior**
I would expect that "list tags" operation doesn't trigger download event. https://docs.docker.com/registry/spec/api/#listing-image-tags this endpoint doesn't count towards downloading and still provides list of tags for specific image.

**Additional context**
I am not completely sure if it's bug/feature. But right now this behaviour is inconvenient in our setup. We use "lost download" time to clear our images from docker registry.

**Comment by hiddeco** [comment]
Flux does not just list tags,but analyzes the metadata of every tagged image to gather information, which is probably the reason Nexus (OSS) counts it as a download.

Given this fact, it is not a bug on our side. The value you are using for your determination is simply not compatible with how Flux works.

**Comment by SmilingNavern** [comment]
@hiddeco hello, thanks for the answer. Maybe you can suggest some workarounds or good way to work with flux and still clean our docker registry

**Comment by hiddeco** [comment]
@SmilingNavern this completely depends on your release and/or tagging strategy, one thing I can think of is to delete tags older than `x` days or months, but to keep at least `z` tags.

**Comment by SmilingNavern** [comment]
@hiddeco yeah, thanks. This looks like a better solution. I think i can close this issue then.
