### ISSUE TITLE
Add possibility to specify sort order for when a kind is applied

### ISSUE THREAD

**Issue by goober** [fluxcd/flux#2758]
**Describe the feature**
Today flux applies the manifest in the order according to:
https://github.com/fluxcd/flux/blob/16b85905da6285736735d1e3b29747726970ae68/pkg/cluster/kubernetes/sync.go#L470-L492

Namespaces have the highest priority and are first applied during a sync. However, OpenShift has a higher level definition of a namespace called a [Project](https://docs.openshift.com/container-platform/3.11/rest_api/apis-project.openshift.io/v1.Project.html). This means that OpenShift users do not have a Namespace manifest defined in their git repos, but instead a Project manifest.

It would be great if Flux could take this into account in some way, preferably without adding openshift specific code into the codebase.

**What would the new user story look like?**
A possible solution could be to add  a command line argument that defines the sort order of a given kind.

Maybe something like this:

1. A user starts up Flux with the `--kind-sort-order=project=0`
2. New commits in git branch happen
3. project.openshift.io/Project manifests are applied as the first kind during the next sync.

**Expected behavior**
I expect that the defined kind from the command line argument are applied to the cluster in the order that I have specified.

**Comment by adusumillipraveen** [comment]
This could be made generic and extended to have flexibility for users to choose :

1.  Order is which namespaces are applied ( Example : Admin, monitoring go before any application namespaces)
2. Order in which resource types are applied ( As explained above)
3. Order in which  each resource of a particular type in a given namespace is applied ( Example : A Backend Helm Release is applied before Applying Front end )

**Comment by stefanprodan** [comment]
@adusumillipraveen applying things is a given order doesn't solve dependencies between apps. The `rankOfKind` orders the objects but the apply is atomic (all objects are applied at the same time). For HelmReleases the `rankOfKind` has no effect since Helm Operator reacts to Kubernetes events and the ordering is not guaranteed by design, not to mention that helm-op runs installs/upgrades in parallel.

**Comment by kingdonb** [comment]
Flux v2 has myriad and many possibilities when it comes to specifying the order in which resources are applied:

https://toolkit.fluxcd.io/components/kustomize/kustomization/#kustomization-dependencies

Flux v1 is in maintenance mode now, and is not adding any new features unless they are critical.

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.

If you have a use case for Flux that isn't covered well in the new Flux v2 (which is a total rewrite), we want to hear about it.

If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/
