### ISSUE TITLE
Configure Flux probes through the chart's values

### ISSUE THREAD

**Issue by sa-spag** [fluxcd/flux#2759]
Hey there 👋 

[As discussed on Slack](https://cloud-native.slack.com/archives/CLAJ40HV3/p1579275380025500), I would like to override the default readiness probe for Flux deployment. To do so, I suggest we make probes configurable through the chart.

**Comment by kingdonb** [comment]
Flux v1 is in maintenance mode now, and is not adding any new features unless they are critical.

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.

If you have a use case for Flux that isn't covered well in the new Flux v2 (which is a total rewrite), we want to hear about it.

If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/
