### ISSUE TITLE
fluxctl default namespace

### ISSUE THREAD

**Issue by runningman84** [fluxcd/flux#2768]
**Describe the bug**

It looks like the new default namespace is fluxcd unfortunately fluxctl still looks for flux

**To Reproduce**

Steps to reproduce the behaviour:

```
$ fluxctl sync
Error: No pod found in namespace "flux" using the following selectors:
  app=flux
  name in (flux,fluxd,weave-flux-agent)

Make sure Flux is running in namespace "flux".
If Flux is running in another different namespace, please supply it to --k8s-fwd-ns.
Run 'fluxctl sync --help' for usage.
$ fluxctl version                 
1.17.1
```

**Expected behavior**

fluxctl should assume ns fluxcd

**Additional context**

- Flux version: 1.17.1
- Kubernetes version: 1.14
- Git provider: github
- Container registry provider: docker hub

**Comment by 2opremio** [comment]
How did you install Flux? AFAICT we don't use `fluxcd`as the namespace.

**Comment by runningman84** [comment]
I think I have mistaken the new helm org with the namespace.

**Comment by runningman84** [comment]
Hmm maybe I used the as a reference
https://github.com/alexellis/civo-fluxcd-expressjs/blob/master/README.md

**Comment by stefanprodan** [comment]
@runningman84 the civo repos uses `fluxctl sync --k8s-fwd-ns fluxcd` and that works just fine.

**Comment by stefanprodan** [comment]
@2opremio we use fluxcd in many places, all workshops that I made use it, same with Helm Operator chart docs and eksctl profiles. When deploying both Flux and Helm operator I think `fluxcd` as a namespace is more suitable as it reflects the org where both projects are.

**Comment by cep21** [comment]
I filed https://github.com/fluxcd/flux/issues/2769 recently where `namespaces "flux" not found`.

It would be great if there was consistency in the docs between using fluxcd and flux as a namespace.  I'm switching between the different repositories trying to learn everything I can and the inconsistent namespace makes it difficult to copy/paste commands.
