### ISSUE TITLE
Update docs for helm v3

### ISSUE THREAD

**Issue by cep21** [fluxcd/flux#2769]
**Describe the bug**

Instructions on https://github.com/fluxcd/flux/tree/master/chart/flux are for helm v2 and not helm v3.

**To Reproduce**

Follow steps on https://github.com/fluxcd/flux/tree/master/chart/flux

```
helm install --name flux
```

Get error message

```
Error: unknown flag: --name
```

**Expected behavior**

Commands should work on latest version of helm, or have separate commands per version of helm.

**Comment by cep21** [comment]
Another error, probably from helm version v3
```
helm install --name flux \
--set git.url=git@github.com:fluxcd/flux-get-started \
--namespace flux \
fluxcd/flux
```
Also says

```
Error: create: failed to create: namespaces "flux" not found
```

**Comment by stefanprodan** [comment]
Helm v3 does not create namespaces, you need to do `kubectl create ns flux` before running hem install. You can find the Helm v3 install commands for both Flux and Helm Operator here https://github.com/fluxcd/helm-operator-get-started#install-flux

**Comment by cep21** [comment]
The documentation uses the namespace `flux` in some places and `fluxcd` in others.  Would it be helpful to use a consistent namespace in the documentation?

**Comment by stefanprodan** [comment]
Can you point me to where is fluxcd used in https://docs.fluxcd.io/en/1.17.1/ ?

**Comment by cep21** [comment]
@stefanprodan https://github.com/fluxcd/helm-operator-get-started uses the namespace
```
kubectl create ns fluxcd
```

**Comment by cep21** [comment]
This relates to the linked issue (above).  It would be great if the documentation for all the github.com/fluxcd repositories (and their CLIs) were consistent about which namespace to use.
