### ISSUE TITLE
[Question] Combine kustomize and helm 

### ISSUE THREAD

**Issue by dmourao** [fluxcd/flux#2787]
Currently, i'm implementing a Gitops flow using Flux on top of an existing git repository that have some deployments that are done using kustomize and other that uses Helm charts.

After reading the doc, it is possible to use Helm (HelmRelease) and kustomize, however i cannot understand if it possible to have **one fluxcd daemon** that handles kustomize (specifying a .flux.yaml) and helm charts.
I can guess that i could have two flux daemons, one that handles kustomize and other daemon that handle helm charts, but i'm ensure if this is the best practice since fluxcd daemon tags the repo (flux-sync), which indicates that it is not supposed to have two daemons work on same git repository.

Flux is working great for my deployments that uses kustomize, but in trouble adding helm charts.

 I'm missing something ?

**Comment by hiddeco** [comment]
> I can guess that i could have two flux daemons, one that handles kustomize and other daemon that handle helm charts, but i'm ensure if this is the best practice since fluxcd daemon tags the repo (flux-sync), which indicates that it is not supposed to have two daemons work on same git repository.

It is perfectly fine to have multiple Flux daemons syncing from the same repository (and even the same branch) as long as they both use a different tag, the tag is configurable using the `--git-label` flag.

**Comment by dmourao** [comment]
Thanks @hiddeco ! 

I totally missed that. With some re-organization in my gitops repository is pretty easy to have that.
