### ISSUE TITLE
Ability to disable automated git syncing

### ISSUE THREAD

**Issue by cloudpea** [fluxcd/flux#2794]
**Describe the bug**

Is it possible to disable automated git syncing all together within Flux so that only manual sync via fluxctl sync command will update cluster configuration?

This would be useful in our production environments as we want to only deploy new configuration via a DevOps pipeline which uses fluxctl.

**Expected behavior**

Automated syncing of the git repository is disabled and only manual sync via fluxctl will roll out new configuration.

**Additional context**

- Flux version: 1.17.1
- Kubernetes version: 1.14.8
- Git provider: Azure Devops
- Container registry provider: Azure Container Registry

**Comment by stefanprodan** [comment]
You can set the sync interval to one year with: `--sync-interval=525600m` and `--git-poll-interval=525600m`

**Comment by squaremo** [comment]
Be ware that any kind of update done through the API (e.g., using fluxctl lock) will trigger a git refresh, which will in general trigger a sync.

**Comment by 2opremio** [comment]
We should probably have an explicit flag for this.

**Comment by marcjimz** [comment]
This is a pretty big blocker in our adoption in using Flux, is there any proposed changes for this?

**Comment by Shazzberry** [comment]
Really need to see this as an option, it makes non production environments impossible to test in because flux will just deploy conflicts directly to, for instance, a k8s cluster.

**Comment by kingdonb** [comment]
A proposal was opened for this recently in Flux 2:

https://github.com/fluxcd/flux2/discussions/870#discussioncomment-420896

Manual gating implies that releases will not proceed in Flux without some person or process that triggers a `Gate`, similar to the capability that is available in Flagger, but with more features and as a replacement for Flagger's current [manual gating mechanism](https://docs.flagger.app/usage/webhooks#manual-gating).

I understand this is a feature request from Flagger users as well and I believe it covers the use case described here too.

Flux v1 is in maintenance mode and as a policy will not see any new features added past this point. Please consider upgrading to Flux v2, and report on any use cases that you believe remain underserved. The prerelease version of Flux v2 has passed the Feature Parity milestone, and should already meet or exceed any capability of Flux v1 now, with many great enhancements and a new architecture that has been totally rewritten from scratch.

Thanks for using Flux! Closing.
