### ISSUE TITLE
Default namespace option (--k8s-default-namespace) has no effect

### ISSUE THREAD

**Issue by michaelbeaumont** [fluxcd/flux#2797]
**Describe the bug**

In spite of setting the `--k8s-default-namespace` option, the default namespace isn't applied to namespaced manifests without a specific `namespace`.

Seems to be [present in the `gitops-engine` branch](https://github.com/fluxcd/flux/issues/2614) as well

**To Reproduce**

Steps to reproduce the behaviour:

1. Setup `flux` including the `--k8s-default-namespace` option. E.g.:
```
$ fluxctl install \
--git-user=test \
--git-email=test@users.noreply.github.com \
--git-url=https://github.com/michaelbeaumont/flux_manifests \
--git-path=/ \
--git-readonly=true \
--namespace=flux > out.yaml
$ patch -p0 << EOF
> --- out.yaml    2020-01-29 14:21:09.447424403 +0100
+++ out_p.yaml   2020-01-29 14:21:45.957538447 +0100
@@ -190,6 +190,8 @@

         # Include this to enable git signature verification
         # - --git-verify-signatures
+
+        - --k8s-default-namespace=test

         # Tell flux it has readonly access to the repo (default `false`)
         - --git-readonly
> EOF
```

2. A simple pod manifest:
https://github.com/michaelbeaumont/flux_manifests/tree/master

**Expected behavior**

The pod should be deployed in the `test` namespace, instead:
```
$ kubectl get pod -n default -o yaml
apiVersion: v1
kind: Pod
metadata:
  name: sleep
spec:
  containers:
  - name: sleep
    image: busybox
    command: ['sh', '-c', 'echo Started && sleep 3600']
```

**Additional context**

- Flux version: 1.17.1
- Kubernetes version: 1.16

**Comment by 2opremio** [comment]
:man_facepalming: after reviewing https://github.com/fluxcd/flux/pull/2625 , I can see that the option is not honoured when invoking `kubectl`.

I will fix that.

**Comment by michaelbeaumont** [comment]
I was actually hoping to fix it myself!

**Comment by 2opremio** [comment]
Even better, please do!

It should be as simple as passing `--namespace` to `kubectl` (assuming that respects the namespace in resources that provide it explicitly)

**Comment by michaelbeaumont** [comment]
`kubectl` seems to throw an error if the namespaces disagree so that won't work. I guess the intended usage is to limit operations to a single NS, so it makes sense to throw an error.

**Comment by 2opremio** [comment]
Then we will need to find another way. Maybe appending a default namespace
as a configuration to `KUBECONFIG`?

**Comment by 2opremio** [comment]
For further reference https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#set-the-kubeconfig-environment-variable

Note that users may be already be setting it's value and that it may already contain a context and a default namespace (which should be overriden)
