### ISSUE TITLE
Flux is stripping annotations, preventing aws loadbalancer service

### ISSUE THREAD

**Issue by sean-abbott** [fluxcd/flux#2802]
**Describe the bug**

When running the example guestbook application (https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/eks-guestbook.md) on EKS with eksctl/flux, I couldn't get the loadbalancer to come up.

Finally, I took at look at the annotations. The annotations from my manifest:
```
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    fluxcd.io/automated: true
```

But when I looked at the annotations that were deployed:

```
$ kubectl -n stg get svc guestbook -o jsonpath='{.metadata.annotations}{"\n"}'
map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"guestbook","fluxcd.io/sync-gc-mark":"sha256.********"},"name":"guestbook","namespace":"stg"},"spec":{"ports":[{"port":3000,"targetPort":"http-server"}],"selector":{"app":"guestbook"},"type":"LoadBalancer"}}
]

Now, I suspect this may be because you don't intend to automate this kind of service with flux.

However, the documentation is VERY fuzzy on that. As in, I can't quite understand how to add a fresh application to flux, since I keep getting messages from the logs that say
"automation of this resource kind is not supported" over and over, but no where is there any 

**To Reproduce**

Steps to reproduce the behaviour:

1. Include "automated" annotation on an internal AWS loadbalancer
2. see that flux strips the annotation

**Expected behavior**

Flux should only mess with it's own annotations

- Flux version:  1.17.1 (via snap, version reports "unversioned"
- Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Git provider: github.com
- Container registry provider: n/a

**Comment by 2opremio** [comment]
Are you editing the resource in the cluster? Flux will make make sure that the cluster reflects what's on git. If you edit the annotations in the cluster resource Flux will overwrite them.

**Comment by 2opremio** [comment]
Regardless, I think this bug report belongs to https://github.com/awsdocs/amazon-eks-user-guide and/or https://github.com/weaveworks/eksctl

**Comment by sean-abbott** [comment]
No, this is coming in via git.  The annotations were in git, and were
actually never applied. When I took the same manifest and applied it with
kubectl, those annotations were there.

**Comment by 2opremio** [comment]
Could you narrow down the problem to a self-contained Git repo I can use to reproduce it without EKS? Are you sure it's Flux stripping the annotations and not EKS in some way?

**Comment by kingdonb** [comment]
Flux v1 is in maintenance mode now, and is not adding any new features unless they are critical.

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.
