### ISSUE TITLE
Allow adding annotations to deployments

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/flux#2810]
Tools like `reloader` can restart pods is the `deployment` is properly annotated. 

Please allow the ability to pass in annotations to the `flux` deployment (not the pods).

**Comment by kingdonb** [comment]
Thank you for your feature request. Flux v1 is in maintenance mode now, and is not adding any new features unless they are critical.

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.
