### ISSUE TITLE
Field "ts" in logs is a string not a timestamp

### ISSUE THREAD

**Issue by 0x46616c6b** [fluxcd/flux#2820]
**Describe the bug**

We run various services in our K8s and we collect all the logs in Elasticsearch. Some services (like Vault and Jaeger) use the field `ts` as well as flux does. But flux logs a string in this field, so the Index Mappings from Elasticsearch conflicts with the `ts` field. Some day it is a long, some other day it is a string. 

**To Reproduce**

- start flux with json or fmt logging
- see the logs

**Expected behavior**

The `ts` field should be a real timestamp or the field should be renamed to e.g. `time`.

**Logs**

```json
{"caller":"images.go:17","component":"sync-loop","msg":"polling for new images for automated workloads","ts":"2020-02-04T12:13:34.688745911Z"}
```

**Additional context**

- Flux version: 1.17.1

**Comment by 2opremio** [comment]
The logs are output in JSON, so we cannot simply remove the quotes.

We use the example straight from go-kit (except for the JSON format) so I bet other projects have the same "problem"

Unfortunately we cannot simply change the format because other people may be already be processing the logs.

I suggest you preprocess the logs during ingestion so that the are uniform with respect to other projects.

**Comment by 0x46616c6b** [comment]
The other projects I mentioned use https://github.com/uber-go/zap for logging and zap also uses the `ts` field but with a Unix Timestamp (`long` in Elasticsearch). So there comes the conflict. But as I think ts stands for timestamp and for me a timestamp is a number, not a formatted time string, I would expect in flux it behave the same.

**Comment by prometherion** [comment]
Flux is using the [`log` package](https://github.com/go-kit/kit/tree/master/log#timestamps-and-callers) provided by `go-kit` that, as default, suggests to use the [`DefaultTimestampUTC` func](https://github.com/go-kit/kit/blob/e138ff16a5c15ba8d556294f15ab5377e771e5b0/log/value.go#L102-L105).

If you're using Fluentd (but appliable also for other solutions) you could write your own log parser.

**Comment by 0x46616c6b** [comment]
I did this already. For `ts` field it is okay, but other fields (`took` and `error`) differs also in different data types (string, float, object), so you can for example force that `took` is a string/text in Elasticsearch but the field `error` is somethimes flat, other times a nested object. Elasticsearch is not able to handle this as a text/keyword field.

**Comment by prometherion** [comment]
I got the point and you're totally right.

Can you point me some real-world examples? So I could give a look and see if we can handle better the logging (actually, is [already on the roadmap](https://github.com/fluxcd/flux/issues/2812))

**Comment by 0x46616c6b** [comment]
I tried to find some logs in different formats but I only found strings for both services (flux and flux-helm-operator). So it seems to be fixed from my side.

**Comment by kingdonb** [comment]
Flux v1 in maintenance mode, will consider any changes to the behavior (including log format) as a breaking change, which can no longer be merged. Flux v2 has made great advances on the front of better logging and observability; although I'm not sure this change has been incorporated, there are many other improvements and users are encouraged to plan their upgrades as soon as possible, as Flux v1 maintenance will only continue for a limited amount of time after a first GA release of Flux v2.

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.
