### ISSUE TITLE
Add --k8s-unsafe-exclude-resource flag to helm chart

### ISSUE THREAD

**Issue by Fabian-K** [fluxcd/flux#2832]
**Describe the feature**
I did not find the flag `--k8s-unsafe-exclude-resource ` exposed via the helm chart. This makes it difficult to use the flag when installing flux via the helm chart.

I can contribute this, I´m just unsure how to name it 🙈
- `k8sUnsafeExcludeResource`
- `k8s.UnsafeExcludeResource`
- `k8s.UnsafeExcludedResources`
- `k8s.ExcludedResources`

Thanks,
Fabian

**Comment by stefanprodan** [comment]
You can use the `additionalArgs` option to set any Flux flag that's not specified in values.yaml https://github.com/fluxcd/flux/blob/master/chart/flux/values.yaml#L225

**Comment by Fabian-K** [comment]
Ups, thx for the hint! Feel free to close this - not sure if you want to expose all flags in the helm chart.

**Comment by hiddeco** [comment]
Given this flag should only be used in extreme edge-cases, I think it would be okay to _not_ include it as a dedicated value in the chart.
