### ISSUE TITLE
AWS IAM for service accounts working?

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/flux#2836]
Has anyone actually tested the support for AWS IAM for service accounts?

I ask that because there are two things needed to support it.  

First, you need to bind with a version of the Go libraries that support it.  I see that you do that in 1.17 and beyond.

Second, you need to provide a `securityContext` that allows one to runs as a group that can read the token, e.g:
```     
securityContext:                                                                                                                                                                           
  fsGroup: 65534
```
I do not see that in the helm chart and I do not see a way of adding a `securityContext`.

If this is needed, could you please add a way of providing a `securityContext` to the pod.

**Comment by stefanprodan** [comment]
Flux runs are root, I think the FS group is needed only for non-root containers. We have confirmation that Flux works with IAM for service accounts see https://github.com/fluxcd/flux/pull/2722#issuecomment-572066310
