### ISSUE TITLE
Best practice clusters in different regions

### ISSUE THREAD

**Issue by tombrouwer** [fluxcd/flux#2840]
Hi All!

We have recently started to realize a GitOps flow with FluxCD. We have a number of applications with helmet chart. As far as this all works nicely on a cluster. The applications are facilitated across multiple regions worldwide. At the moment we have the idea to create a separate git branch per region. The disadvantage that I see here is that if we want to change something, this has to happen in every branch.

I prefer to do this from one branch, but I have different credentials for other resources.

Do others have an idea for a best practice in this case. How do you solve this?

Thanks in advance!

**Comment by stefanprodan** [comment]
You could use a single branch with a dir per cluster and use Kustomize overlays to set credentials per env.

**Comment by kingdonb** [comment]
Flux v2 now has first-class documentation providing best practices advice for multi-cluster, multi-tenant, multi-environment...
https://toolkit.fluxcd.io/get-started/#multi-cluster-setup

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.

If you have a use case for Flux that isn't covered well in the new Flux v2 (which is a total rewrite), we want to hear about it.

If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

Closing. Thanks for using Flux!
