### ISSUE TITLE
old failed release gets stuck in memcached; causes helm-operator to fail

### ISSUE THREAD

**Issue by rally25rs** [fluxcd/flux#2844]
**Describe the bug**

I originally filed this under `helm-operator`, please see https://github.com/fluxcd/helm-operator/issues/288

It seems that an old version of a `HelmRelease` defintion that did not work get stuck in memcached. I had to kill/clear memcached to get my release to work again.

**To Reproduce**

I had a `HelmRelease` that failed to release properly doe to a helm templating error. After that I renamed the release without ever having a successful release under the original name.

**Expected behavior**

Should try to release latest HelmRelease definition when the previous one failed

**Logs**

See other bug report lined above.

**Additional context**

- Flux version: 
- Kubernetes version:
- Git provider:
- Container registry provider:

**Comment by 2opremio** [comment]
Memcached doesn't cache HelmReleases. It only caches image metadata and,
even then, the metadata gets refreshed regularly.

**Comment by rally25rs** [comment]
Weird, I wonder why cycling it cleared up my issue 🤷‍♂  Maybe it was just coincidental timing with a regular refresh.

I did just notice that a `kubectl get helmrelease -n {namespace}` for the no-longer-existing `dev` namespace does list my old/broken HelmRelease.

I guess I assumed Flux would delete that if it no longer existed in the `releases/` directory. Manually deleting that would likely have also fixed my issue.
