### ISSUE TITLE
publish events for 3rd party to hook into

### ISSUE THREAD

**Issue by Morriz** [fluxcd/flux#2853]
I don't know if this is feasible, but I would love to see custom k8s events published like:

- a new candidate image is available for workload bla:di/bla :: 1.1.4

Would it be an option to generate k8s events with a toggle to do so?

I have not worked with custom k8s events, so open to other leads ;)

**Comment by squaremo** [comment]
> Would it be an option to generate k8s events

When I considered this, it was the case that Kubernetes events always pertain to a resource. In the case of e.g., "new images", there's no resource to attach them to.

But: the general idea is a good one, especially when there is the idea floating around of factoring out the image database and update automation.

**Comment by kingdonb** [comment]
The new design of Flux v2 takes this request into account, all reconciliation and sync events live inside of a `Kustomization`, `GitRepository`, `HelmRepository`, etc. CRD that is in the GitOps Toolkit API. There is a [Notification Controller](https://toolkit.fluxcd.io/components/notification/controller/) which can be used to notify 3rd-party services, with both `Receiver` and `Provider` capabilities.

Flux v1 is in maintenance mode now, and is not adding any new features unless they are critical.

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.
