### ISSUE TITLE
Flux tag default shouldn't stomp other flux tags

### ISSUE THREAD

**Issue by kav** [fluxcd/flux#2856]
**Describe the feature**
I'd really love it if the default tag included the Cluster UID or a random value so multiple flux installations didn't stomp each other. It's very confusing to get started if multiple people are working locally as they explore and there is no reason not to do it. Also it'd make installing flux via a HelmRelease object a lot easier since I wouldn't need to dynamically set the tag.

**What would the new user story look like?**
As a developer exploring flux I configure my local docker kubernetes cluster to use my teams flux repo to kick the tires. Everything just works, even though other flux instances use this repo as well.

**Expected behavior**
default flux label includes the cluster id i.e. `kubectl get ns kube-system -o jsonpath='{.metadata.uid}'` or even a random postfix ala generateName.

See https://github.com/kubernetes/kubernetes/issues/77487 for discussion of kube-system UID as cluster UID

**Comment by kav** [comment]
Thinking a bit further it'd be ideal to have it appended to any sync tag I set somewhat similarly to generateName. This would greatly simplify my multiple clusters in multiple folders use cases

**Comment by squaremo** [comment]
We do calculate a name to serve as a label for garbage collection, which is based on the git parameters.
That might be good enough to use in the sync tag. Counter-example: you can run more than one flux with exactly the same git parameters, in different namespaces. I'm not sure there is a perfect answer, though.

**Comment by kav** [comment]
Could you hash the namespace UID for the flux namepace in there? That would make it unique across the cases we've mentioned. Not sure if the hole goes any deeper...

**Comment by kingdonb** [comment]
The end of the Flux 2 getting started guide now covers multi-cluster, multi-tenancy, multi-environment... https://toolkit.fluxcd.io/get-started/#multi-cluster-setup

The default mode of Flux v2 is read-only, so I don't think this should be a problem anymore.

Flux v1 is in maintenance mode now, and is not adding any new features unless they are critical.

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.
