### ISSUE TITLE
Failed Liveness Probes

### ISSUE THREAD

**Issue by texasbobs** [fluxcd/flux#2859]
We are running on Flux v1.16.0 and k8s v1.16.3 and noticed an issue with liveness probe failures.

We are processing about 400 items from the git repo.  Each kubectl apply was taking about 6 to 18 seconds to complete.  For the limits, the CPU was set to 100m and the memory was set to 128mi.  With these settings, we would see a lot of failures. `(x71 over 3h36m)`

Based on another issue relate to "stuck" instances of Flux, I increased the limits for CPU to 500m and memory to 256mi.  This seems to have greatly improved the performance as we are now seeing each apply taking about 600-700ms to complete.  Additionally, and more importantly, there are no probe failures.

Further increasing the memory to 512mi does not seem to impact the performance.  Lowering the memory to 128mi and leaving the CPU at 500m causes the probes to start failing again.

Adding `failureThreshold: 5` a does not seem to matter.

Are there any recommended settings for CPU and memory limits?   

Also, what are the typical execution times for each of the kubectl apply commands to complete?

**Comment by texasbobs** [comment]
I'm guessing that perhaps no one else runs Flux with limits.  Is that accurate?

**Comment by stefanprodan** [comment]
> Are there any recommended settings for CPU and memory limits?
> Also, what are the typical execution times for each of the kubectl apply commands to complete?

No, it all depends on the amount of yamls, the git repo history size, the responsiveness of your Kubernetes API server, the etcd node size, etc.
