### ISSUE TITLE
[DX]: Default install config should minimize image scanning

### ISSUE THREAD

**Issue by ryedin** [fluxcd/flux#2864]
**Describe the problem**
For new users setting flux up, it is a source of confusion that flux scans all images that live in the cluster at the time flux is installed, causing a sometimes massive number of requests to registries that can take hours to complete if you have enough things installed in your cluster. This process results in a very spammy looking log, and delays the actual deployment of the repo that was configured to begin with. Please refer to the following issues (not a comprehensive list of related issues, but a good sampling): #2854, #2780, #2516 (not directly related but might be implicated in the below proposal), #2857 

Specifically see this [comment](https://github.com/fluxcd/flux/issues/2780#issuecomment-589084133), which sums up what I feel a new user's expectations likely are about how a single flux install should behave.

**Proposed new behavior**
1. When a user installs flux, flux should do no image scanning of any sort, and should assume that things already installed in the cluster are of no interest. The flux install is scoped to a specific git repo, and a default flux install should only concern itself with images in that repo. 
2. Once the repo is actually successfully cloned and analyzed, only scan the images that have been marked as `automated`. 
3. The scanning process for automated images should strictly honor any and all filter annotations that have been applied.
4. (optional to this proposal, but a possible mitigation for #2516): when scanning, if tags are found with missing metadata, simply take those tags out of consideration, or maybe at least make this an opt-in behavior

This would be the new default install config, and users would still be able to opt-in to the current "scan the world" approach if they wanted to.

(cc: @squaremo - please critique this proposal based on our discussion in #2780)

**Comment by squaremo** [comment]
Thanks for setting this out so clearly, Ryan.

There is a kind of loose dependency between this and the idea of separating out the image database and automation -- most obviously, having all the image stuff in its own component means you can _just not run it_, achieving point 1.). So there is some figuring out of the larger picture to do, before we'll be able to address everything mentioned here. For now, I can add some implementation notes:

 - At present, the registry scanning bit does not have access to the git repository, only the cluster. This is less a matter of design than of path dependence. A reasonable approximation to "should only concern itself with images in that repo" might be to look at only the workloads in the cluster that are marked as automated as well as synced from the git repo in question.

 - The current implementation of scanning is to get the image metadata for every tag, and filter when requested. This is in part to keep the scanning mechanically simple, and in part because in general we don't know ahead of time which images will be of interest. It's possible to switch that around, and scan the image metadata based on the tags of interest, at the cost of being less responsive when that set changes (e.g., someone changes a filter).

**Comment by ryedin** [comment]
Cool, that all makes sense.

> most obviously, having all the image stuff in its own component means you can just not run it, achieving point 1.)

And when separated, "just run it once" can be achieved via modeling it as a k8s `Job` that the fluxd controller can kick off when it's needed?

> At present, the registry scanning bit does not have access to the git repository, only the cluster. This is less a matter of design than of path dependence. A reasonable approximation to "should only concern itself with images in that repo" might be to look at only the workloads in the cluster that are marked as automated as well as synced from the git repo in question.

I think that makes sense. Then if you're tracking multiple repos (with multiple instances of fluxd), each one can just scan its own things. So it would be ideal if they could easily both share a single memcached instance. Apologies, I haven't yet tried installing > 1 flux in my cluster yet, so am not sure if that's the default or if they each right now get their own memcached pod, which would be a little troublesome right now with the default "scan the world" behavior.

> The current implementation of scanning is to get the image metadata for every tag, and filter when requested. This is in part to keep the scanning mechanically simple, and in part because in general we don't know ahead of time which images will be of interest. It's possible to switch that around, and scan the image metadata based on the tags of interest, at the cost of being less responsive when that set changes (e.g., someone changes a filter).

I almost wonder if this is an optimization item where you want to first test whether or not a change is really needed. I would be willing to go out on a limb and guess that getting all tags for the images most people have marked as automated is not going to be that big of a deal. I think the problems come in when flux is fetching all tags for things like istio and nginx and stuff like that by default. It's highly unlikely that anyone wants to automate their infra based on changes to those foundational images, and the volume of tags is pretty massive for some of these things.

That said, if you get feedback to the contrary, where people are saying they definitely would rather flip the scanning to optimize this a bit, and the scanner/warmer process is a `Job` that flux can kick off, you could maybe trigger that based on a mutation of the filters. I'm not sure how dumb/intelligent the diffing logic is right now though and whether understanding when a given filter has changed is easy/hard.

**Comment by kingdonb** [comment]
Flux v2 no longer suffers from the limitations associated with registry scanning and has a new approach that was rewritten from scratch, to provide a thoughtful alternative to the old approach used in Flux v1.

Relevant docs:
https://toolkit.fluxcd.io/guides/image-update/
https://toolkit.fluxcd.io/guides/sortable-image-tags/
https://toolkit.fluxcd.io/guides/flux-v1-automation-migration/

Flux v1 is in maintenance mode now, and is not adding any new features unless they are critical.

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.
