### ISSUE TITLE
New flux service label fluxcd.io/sync-gc-mark must be properly described since it produces significant impact on prometheus metrics

### ISSUE THREAD

**Issue by mpashka** [fluxcd/flux#2874]
**Documentation change proposal**
Some time ago flux introduced new service label: `fluxcd.io/sync-gc-mark` and new annotation: `fluxcd.io/sync-checksum`. Flux puts this on almost all kubernetes objects it manages. This  has impact on prometheus metrics. Currently all service metrics are applied to target during prometheus scraping. This means new label becomes visible which must be properly described. Also information about how to remove new metric from prometheus metric labels must be provided.

**What must be added?**
How would the new interaction with Flux look like? E.g.
1. Add information what labels and metrics are added by flux for kubernetes objects
2. Add information that new labels are visible as labels if prometheus scrapes metrics from kubernetes objects
3. Add information how to remove that flux labels from prometheus metrics.

**Comment by kingdonb** [comment]
Thank you for the suggestion. As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.
