### ISSUE TITLE
Ensure all .yaml files follow a consistent style guide

### ISSUE THREAD

**Issue by rjhenry** [fluxcd/flux#2875]
Many of the yaml files in this repository don't follow the rules used by many YAML parsers. This is easily adjusted by calling a linter as a CI step, which I propose is done.

There would be very little change to how a new user would interact with this project - in fact, ideally none - but would hopefully make things a little easier to read.

The linter I would suggest is Adrien Verge's yamllint:
https://github.com/adrienverge/yamllint

**Comment by 2opremio** [comment]
Can you point to specific problems and indicate what are their negative impact?

If we are not standard-compliant, we should definitely fix it. Otherwise, it depends on the actual impact (if we are standard-compliant, then parsers should accept the input).

**Comment by 2opremio** [comment]
> Many of the yaml files in this repository don't follow the rules used by many YAML parsers.

i.e. please elaborate on this

**Comment by rjhenry** [comment]
Sure thing! Using the linked lint tool, yamllint, I get the following:
```
(master)$ yamllint . | grep '^\.'
./.readthedocs.yml
./snap/snapcraft.yaml
./chart/flux/Chart.yaml
./chart/flux/values.yaml
./chart/flux/templates/rbac-role.yaml
./chart/flux/templates/memcached.yaml
./chart/flux/templates/service.yaml
./chart/flux/templates/serviceaccount.yaml
./chart/flux/templates/psp.yaml
./chart/flux/templates/ssh.yaml
./chart/flux/templates/kube.yaml
./chart/flux/templates/rbac.yaml
./chart/flux/templates/deployment.yaml
./chart/flux/templates/secret.yaml
./chart/flux/templates/servicemonitor.yaml
./chart/flux/templates/gitconfig.yaml
./test/e2e/fixtures/kustom/14_release_image/release_image_patch.yaml
./test/e2e/fixtures/kustom/14_release_image/kustomization.yaml
./test/e2e/fixtures/kustom/22_manifest_generation/gitsrv/manifest_generation_patch.yaml
./test/e2e/fixtures/kustom/22_manifest_generation/gitsrv/kustomization.yaml
./test/e2e/fixtures/kustom/22_manifest_generation/flux/manifest_generation_patch.yaml
./test/e2e/fixtures/kustom/22_manifest_generation/flux/kustomization.yaml
./test/e2e/fixtures/kustom/base/gitsrv/gitsrv.yaml
./test/e2e/fixtures/kustom/base/gitsrv/kustomization.yaml
./test/e2e/fixtures/kustom/base/flux/e2e_patch.yaml
./test/e2e/fixtures/kustom/base/flux/kustomization.yaml
./test/e2e/fixtures/kustom/base/registry/registry.yaml
./test/e2e/fixtures/kustom/base/registry/kustomization.yaml
./test/e2e/fixtures/kustom/15_fluxctl_sync/kustomization.yaml
./test/e2e/fixtures/kustom/15_fluxctl_sync/fluxctl_sync.yaml
./test/e2e/fixtures/kustom/20_gpg/gitsrv/kustomization.yaml
./test/e2e/fixtures/kustom/20_gpg/gitsrv/gpg_patch.yaml
./test/e2e/fixtures/kustom/20_gpg/flux/kustomization.yaml
./test/e2e/fixtures/kustom/20_gpg/flux/gpg_patch.yaml
./test/e2e/fixtures/kustom/13_sync_gc/kustomization.yaml
./test/e2e/fixtures/kustom/13_sync_gc/gc_patch.yaml
./.circleci/config.yml
./deploy/memcache-dep.yaml
./deploy/kustomization.yaml
./deploy/flux-deployment.yaml
```
Here, the `grep` just serves to limit the output to only filenames.

The full output for one such file is here:
```
(master)$ yamllint ./chart/flux/templates/servicemonitor.yaml
./chart/flux/templates/servicemonitor.yaml
  1:1       warning  missing document start "---"  (document-start)
  1:3       error    too many spaces inside braces  (braces)
  1:47      error    too many spaces inside braces  (braces)
  2:1       error    syntax error: expected '<document start>', but found '<block mapping start>'
  5:11      error    too many spaces inside braces  (braces)
  5:38      error    too many spaces inside braces  (braces)
  7:12      error    too many spaces inside braces  (braces)
  7:35      error    too many spaces inside braces  (braces)
  8:14      error    too many spaces inside braces  (braces)
  8:38      error    too many spaces inside braces  (braces)
  9:16      error    too many spaces inside braces  (braces)
  9:30      error    too many spaces inside braces  (braces)
  10:17     error    too many spaces inside braces  (braces)
  11:81     error    line too long (83 > 80 characters)  (line-length)

```
These are minor adjustments, but the standard set of rules used by yamllint works to improve the readability of said files.

In addition, where .yaml files are used from this repository and deposited in another - for example, a `gitops` repository which deploys the CRD - this can cause their pipelines to fail.

**Comment by 2opremio** [comment]
Thanks. That output doesn't seem to show any compliance problems, so I gauge this as low priority.

**Comment by rjhenry** [comment]
I'd agree - it's certainly more of a nice-to-have than a need-to-have.

**Comment by hiddeco** [comment]
I am wondering if the example you listed (`chart/flux/templates/servicemonitor.yaml`, but probably almost any file in `chart/flux/templates/*`) does not contain many false positives due to the fact that those are [_Go templated_ YAML files](https://golang.org/pkg/text/template/), and not _plain_ YAML files.

**Comment by kingdonb** [comment]
I will happily take any pull request that improves the style of any source code within linter boundaries, or adds new linting.

This is not a pertinent issue for Flux v1 in maintenance mode now, though, so I am closing it out. Thanks for using Flux!
