### ISSUE TITLE
SchemaError When Installing Flux on Minikube

### ISSUE THREAD

**Issue by joesan** [fluxcd/flux#2880]
**Describe the bug**

I have been trying to follow the documentation on installing and setting up flux to try it out on my local machine where I'm running Minikube. But when I ran the command to install flux in my Minikube cluster using this command below:

```
fluxctl install \
--git-user=${GHUSER} \
--git-email=${GHUSER}@users.noreply.github.com \
--git-url=git@github.com:${GHUSER}/flux-get-started \
--git-path=namespaces,workloads \
--namespace=flux | kubectl apply -f -
```

I got the following error:

error: SchemaError(io.k8s.api.core.v1.NodeStatus): invalid object doesn't have additional properties

Steps to reproduce the behaviour:

Follow this documentation and try it on Minikube on a Mac to reproduce this error:

**Additional context**

Here is how I ran Minikube:

```
minikube start --vm-driver=virtualbox
😄  minikube v1.2.0 on darwin (amd64)
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
🔄  Relaunching Kubernetes v1.15.0 using kubeadm ...
⌛  Verifying: apiserver proxy etcd scheduler controller dns
🏄  Done! kubectl is now configured to use "minikube"
```

Here is the kubectl version:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

Here is my kubectl namespaces:

```
kubectl get ns --all-namespaces
NAME              STATUS    AGE
default           Active    3m
flux              Active    2m
kube-node-lease   Active    3m
kube-public       Active    3m
kube-system       Active    3m
```

**Comment by joesan** [comment]
I fixed this by installing kubectl client version 1.17.0. May be the documentation can mention this specifically so that anyone else who is trying to set flux following the documentation is aware of this issue!

**Comment by hiddeco** [comment]
I do not think it is worth adding a note about this as `kubectl` v1.10.x was released in March 2018, which makes it ancient given the pretty aggressive release cycle of Kubernetes.

In addition, quoting from https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew:

> Different components are expected to be compatible across different amounts of skew, all relative to the master version. Nodes may lag masters components by up to two minor versions but should be at a version no newer than the master; a client should be skewed no more than one minor version from the master, but may lead the master by up to one minor version. For example, a v1.3 master should work with v1.1, v1.2, and v1.3 nodes, and should work with v1.2, v1.3, and v1.4 clients.

Your client and server version were thus already incompatible according to the design of Kubernetes, which is not a Flux specific issue.
