### ISSUE TITLE
SOPS with GKE Workload Identity Failing to Decrypt

### ISSUE THREAD

**Issue by jeff-minard-ck** [fluxcd/flux#2889]
**Describe the bug**

The flux container in the repository is failing to decrypt SOPS encrypted files with the error:

```
ts=2020-03-02T18:11:56.330733802Z caller=loop.go:107 component=sync-loop err="loading resources from repo: unable to read file at \"/tmp/flux-working406730485/path/to/encrypted.yaml\": failed to decrypt file: Error getting data key: 0 successful groups required, got 0"
```

The encrypted file is protected by a GCP KMS key. We're using Workload Identity to link the Flux containers service account to the Google Service Account which has access to the key. I can confirm this is working by performing a `kubectl exec` into the Flux container and running `sop --decrypt file` manually which decrypts the file as expected.

This error _does_ originate from SOPS upstream, but I'm not sure why it works with the `sops` executable in the container, but not through flux so I figured it would be best to start the bug report here.

**To Reproduce**

Apologies, I don't have the ability to provide a repo with examples at this time.

**Expected behavior**

Expect flux to decrypt the file and apply it

**Additional context**

- Flux version: 1.18.0
- Kubernetes version: 1.13

```
ts=2020-03-02T18:06:41.735353236Z caller=main.go:371 warning="--sops is enabled but there is no GPG key(s) provided using --git-gpg-key-import, we assume that the means of decryption has been provided in another way"
```

Also shows up in the logs, but that's expected IMO, since we're not using a GPG key for these ops. Just adding it for the sake of completeness.

**Comment by jeff-minard-ck** [comment]
I should note, as an update, that at some point Flux gets over this error and is able to decrypt the Yaml file and apply its contents to the cluster. So...that's fun.

**Comment by deltasquare4** [comment]
@jeff-minard-ck Did you experience it again? How do you authenticate `sops` against GCP KMS?

**Comment by jeff-minard-ck** [comment]
> We're using Workload Identity to link the Flux containers service account to the Google Service Account which has access to the key.

And, yes, it has continued to be an issue. I have read some other places (can't find the link now, of course) that this may just be a timing issue with the Workload Identity system being a bit slower to get authed and make that connection function correctly.

However, my (our) usage of sops inside flux has been superseded by other methods, so I won't be able to do any more digging. Feel free to close for my part.

**Comment by gautamr** [comment]
We are testing in our development env and working fine with Workload Identity

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
