### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by nikhilbalekundargi** [fluxcd/flux#2894]
https://docs.fluxcd.io/en/1.18.0/tutorials/get-started-helm.html

In the above url yaml file for Helm Release CRD is wrong. 
Currently it is kubectl apply -f https://raw.githubusercontent.com/fluxcd/helm-operator/master/deploy/flux-helm-release-crd.yaml - is not available

It should be kubectl apply -f https://raw.githubusercontent.com/fluxcd/helm-operator/master/deploy/crds.yaml

![image](https://user-images.githubusercontent.com/32267777/75975990-8c324e80-5eff-11ea-84eb-ef2ceb3ade74.png)

**Comment by hiddeco** [comment]
See https://github.com/fluxcd/helm-operator/issues/323#issuecomment-593894367 and #2887
