### ISSUE TITLE
If the tag is not found on the registry, no updates are done to the workload

### ISSUE THREAD

**Issue by emas80** [fluxcd/flux#2897]
I have a workload that has a docker tag that does not exist on the docker registry, something like:

`MY-DOCKER-REGISTRY/MY-CONTAINER:NOT-EXISTENT`

This causes Flux to have 

`-> (untagged)                                       ?`

under the `list-images` command for such workload.

Now, let's say that the deployment containing that workload is fully automated `    fluxcd.io/automated: "true"`, and that Flux is configured to automatically release the latest images starting with `EXISTENT-`, so `fluxcd.io/tag.MY-CONTAINER: regexp:^EXISTENT-` for the deployment including the MY-CONTAINER.
We are plenty of such images, as they're generated for every build, and they all work, and they're all listed under the `list-images` command for that workload. Flux definitely knows about those docker images.

Flux will NEVER release anything for such a workload, it will never touch it, and the pod will stay in crash loop back off forever because Kubernetes will try over and over again to pull the NOT-EXISTENT tag from MY-DOCKER-REGISTRY.

Now, as soon as I write inside of the deployment, instead of 
`image:MY-DOCKER-REGISTRY/MY-CONTAINER:NOT-EXISTENT`
`image:MY-DOCKER-REGISTRY/MY-CONTAINER:EXISTENT-BUT-PROBABLY-NOT-WORKING`

the pod can start, running the EXISTENT-BUT-PROBABLY-NOT-WORKING docker image, and if I wait just a few more minutes, Flux will happily deploy my latest version
``MY-DOCKER-REGISTRY/MY-CONTAINER:EXISTENT-SHINY-LATEST-JUST-RELEASED`

**Expected behavior**

I would expect Flux to ignore the NOT-EXISTENT docker tag (expecially because the image does not exist!) and do like instructed to: release the latest available version of EXISTENT-.

We have a quite complex setup where Flux will apply some yaml to create new deployments, and then the automatic release will kick in and the new versions will be released.
We do that all the time: new yaml, then Flux apply the new release.

Now, we can create the new deployment with an existing docker tag, but the application would not work until the new version is released, and when we create the yaml we still don't know which will be the final tag.

**Logs**
I cannot see literally anything regarding this in the logs. Any suggestion in how to find more info would be very appreciated.

**Additional context**

- Flux version: 1.18.1

**Comment by hiddeco** [comment]
Duplicate of https://github.com/fluxcd/flux/issues/2325#issuecomment-518296291, which contains more duplicates.

**Comment by emas80** [comment]
Right @hiddeco , I understand the problems. 
I will close this issue.
