### ISSUE TITLE
Feature: GitHub deployments status reporting

### ISSUE THREAD

**Issue by hazcod** [fluxcd/flux#2899]
**Describe the feature**
Since GitOps starts from the git repository & flux pulls in data and deploys it in its own right, we need a way to report the deployment failure or success when deploying from GitHub.
The GitHub deployments API provides a tool for this job, allowing us to register a deployment and set a status on it.

**What would the new user story look like?**
1. Commit a new version to master
2. Flux pulls in this commit and creates a new deployment
3. Flux deploys this commit
4. Flux updates the GitHub deployment with success and/or failure

**References**
https://developer.github.com/v3/repos/deployments/
https://github.com/google/go-github

**Comment by phillebaba** [comment]
I have been thinking about implementing something similar but for [Gitlab Commit Status](https://docs.gitlab.com/ee/api/commits.html#post-the-build-status-to-a-commit). I have been questioning whether or not it would be better to include this functionality as a separate application like [fluxcloud](https://github.com/justinbarrick/fluxcloud). As everyone's needs are different and want to integrate to different git providers.

If the maintainers consider this functionality something that could be part of Flux I would be able to put in the time and implement this for both Github and Gitlab.

**Comment by hazcod** [comment]
@phillebaba I like the idea of the pull-based approach in the GitOps model, but it completely contradicts the idea of having your deployment status integrated to your Git commits.
I think a GitHub integration would be very much welcome via fluxcloud!

**Comment by tomhuang12** [comment]
I would like this functionality as well. It could simply be providing a way to create a webhook event after a deployment. We can customize the webhook to whichever git providers or other tools that are used to monitor deployments.

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
