### ISSUE TITLE
Scaling workloads

### ISSUE THREAD

**Issue by Willem1987** [fluxcd/flux#2905]
**Describe the feature**
We want to keep both the image used and the number of replica's in sync for a workload. When we scale to 0 we don't want flux to undo this.

**Expected behavior**
fluxctl release --workload=namespace:deployment/dep_name --user=flux --message="Scale to 0" --update-scale=0

Either through update-scale or update-replicas i would like to be able to update the replicas. 

A workaround could be excluding the replicas tag in the patch during the sync?

**Comment by Willem1987** [comment]
Related to https://github.com/fluxcd/flux/pull/2908

**Comment by kingdonb** [comment]
Responded on the PR #2908 that you submitted. Closing, as Flux v1 is in maintenance mode.

Thanks for using Flux!
