### ISSUE TITLE
Lots of error logs - "memcache: no servers configured or available" when using readonly

### ISSUE THREAD

**Issue by kyle--lee** [fluxcd/flux#2907]
**Describe the bug**
Flux: Version 1.18.0
Installation: `git.readonly="true"`
We're seeing a large amount of log spew related to memcache. It seems that for this release, `git.readonly` would disable memcached.

Logs might look like:
```
caller=warming.go:162 component=warmer canonical_name=<name> auth={map[]} err="fetching previous result from cache: memcache: no servers configured or available"

caller=memcached.go:112 component=memcached err="Fetching tag from memcache: memcache: no servers configured or available"
```

We're seeing about 80,000 such logs per day.

**To Reproduce**

Steps to reproduce the behaviour:

1. Install Flux 1.18.0 with git.readonly=true

**Expected behavior**

Setting readonly seems to be a valid configuration for Flux, and we would not expect to see lots of error logs as a result.

Is there some kind of remediation? I see that in latest master, a new `disableScanning` parameter has been added https://github.com/fluxcd/flux/blame/f3be85d1130958a3b6f517f2c62b6162d5c26ef1/chart/flux/templates/memcached.yaml#L1 - is the current 1.18.0 logging behavior expected to go away once 1.19.0 is released?

Thanks!

**Comment by kyle--lee** [comment]
Our deployment of Flux is able to poll and pull from Github without any problems, and it's applying our manifests without any issues - would this be possible if TCP22 to GH is blocked? Seems like we might be having a different issue

**Comment by sccoe** [comment]
Hi Kyle, the issue in the end was the traffic was having to pass by 2 firewalls, not one and an AWS NACL. :) In the end we got it working.

**Comment by stefanprodan** [comment]
Set `disableScanning` to configure Flux without memcache.
