### ISSUE TITLE
fluxctl sync errors out

### ISSUE THREAD

**Issue by gnasit** [fluxcd/flux#2918]
I have 3 git private repositories, and i need to install workloads in order repo1, repo2, repo3...

i have installed 3 flux instances with helm install giving a different release name each time.

when i issue the below command `fluxctl --k8s-fwd-ns flux sync`, i get the below error:

`Error: Could not create a dialer: Could not get pod name: Ambiguous pod: found more than one pod for selector: labels "app=flux"`

the syncing works fine periodically behind the scene, but i am not able to force sync... is there a way to specify the release name while doing the fluxctl sync command?

**Comment by LWJ** [comment]
Does adding `--k8s-fwd-labels=release=<release name>` work for you?

**Comment by gnasit** [comment]
No that does not help:

```
fluxctl --k8s-fwd-ns flux --k8s-fwd-labels=release=flux-az-aks-gitops-get sync
Error: Could not create a dialer: Could not get pod name: Ambiguous pod: found more than one pod for selector: labels "release=flux-az-aks-gitops-get"
Run 'fluxctl sync --help' for usage.
```

below are my different helm releases:

```
helm ls -n flux
NAME                           	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART     	APP VERSION
flux-az-aks-gitops-get         	flux     	1       	2020-03-16 19:24:29.212856 -0500 CDT	deployed	flux-1.2.0	1.18.0
flux-az-aks-gitops-gridgain-get	flux     	1       	2020-03-16 18:10:13.653258 -0500 CDT	deployed	flux-1.2.0	1.18.0
flux-az-aks-gitops-nginx-get   	flux     	1       	2020-03-09 15:46:41.963625 -0500 CDT	deployed	flux-1.2.0	1.18.0
```

**Comment by kingdonb** [comment]
The multi-cluster and multi-tenant use case is much better served in the new release of Flux, v2, which is a total rewrite.

Closing this issue. Please upgrade! https://toolkit.fluxcd.io/get-started/#multi-cluster-setup
