### ISSUE TITLE
Flux Errors Out When Reading From Sub Folders

### ISSUE THREAD

**Issue by joesan** [fluxcd/flux#2920]
**Describe the bug**

I have a project structure where I have sub folders and in those sub folders I have my Kubernetes resource files that I would like to deploy using flux, but when I checked the logs it was clear that the resource was not deployed and here is the error message:

`ts=2020-03-16T21:27:05.536145129Z caller=loop.go:107 component=sync-loop err="loading resources from repo: error executing generator command \"kustomize build .\" from file \"../.flux.yaml\": exit status 1\nerror output:\n2020/03/16 21:27:05 got file 'prometheus-deployment.yaml', but '/tmp/flux-working657489386/base/monitoring/prometheus/prometheus-deployment.yaml' must be a directory to be a root\nError: accumulating resources: recursed accumulation of path '/tmp/flux-working657489386/base': accumulating resources: accumulating resources from 'monitoring/prometheus/prometheus-deployment.yaml': YAML file [monitoring/prometheus/prometheus-deployment.yaml] encounters a format error.\nerror converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context\n\n\ngenerated output:\n2020/03/16 21:27:05 got file 'prometheus-deployment.yaml', but '/tmp/flux-working657489386/base/monitoring/prometheus/prometheus-deployment.yaml' must be a directory to be a root\nError: accumulating resources: recursed accumulation of path '/tmp/flux-working657489386/base': accumulating resources: accumulating resources from 'monitoring/prometheus/prometheus-deployment.yaml': YAML file [monitoring/prometheus/prometheus-deployment.yaml] encounters a format error.\nerror converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context\n\n"`

**To Reproduce**

Steps to reproduce the behaviour:

Here is the link to the project that contains the resources:

> https://github.com/joesan/plant-simulator-deployment

**Comment by joesan** [comment]
Was an error on my part!

**Comment by snwfdhmp** [comment]
@joesan what error please ? I face the same issue now.
