### ISSUE TITLE
DNS Resolution fails

### ISSUE THREAD

**Issue by cwrau** [fluxcd/flux#2921]
**Describe the bug**

I have a problem with flux' dns resolution.
My cert manager crd has a conversion endpoint, `cert-manager-webhook.ingress.svc.cluster.local`.
When flux wants to update, it tries to connect with that but fails with `lookup cert-manager-webhook.ingress.svc.cluster.local on 10.90.44.1:53: no such host`
(10.90.44.1 is the nodes dns server)
But in the pods /etc/resolv.conf ,
```
bash-5.0# cat /etc/resolv.conf
nameserver 192.168.128.10
search flux.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```
Everything looks ok, and nslookup works (edited) 

**To Reproduce**

Steps to reproduce the behaviour:

1. Install flux and cert-manager
2. Add a cert-manager resource to flux's git repo

**Expected behavior**

flux uses the containers/pods dns server, not the host's and successfully syncs the resources

**Logs**

```
[pod/flux-main-68cc4c65bd-b6js8/flux] ts=2020-03-17T10:31:32.88553875Z caller=loop.go:133 component=sync-loop event=refreshed url=http://@cluster-base-cluster-git-main branch=master HEAD=af53ef12a151432eb3fa08e6c2
e482dbcf5a08b4                                                                                                                                                                                           
[pod/flux-main-68cc4c65bd-b6js8/flux] ts=2020-03-17T10:32:06.858242318Z caller=loop.go:107 component=sync-loop err="collating resources in cluster for sync: conversion webhook for acme.cert-manager.io/v1alpha3, Ki
nd=OrderList failed: Post https://cert-manager-webhook.ingress.svc.cluster.local:443/convert?timeout=30s: dial tcp: lookup cert-manager-webhook.ingress.svc.cluster.local on 10.90.44.1:53: no such host"
```
**Additional context**

- Flux version: 1.18.0
- Kubernetes version: v1.16.2
- Git provider: ?
- Container registry provider: ?

**Comment by Mistic92** [comment]
It's happening to me too.

**Comment by cwrau** [comment]
Any new on this? Maybe a workaround?

**Comment by hiddeco** [comment]
Have you both tried tweaking the `ndots` configuration? See: https://github.com/fluxcd/flux/blob/f114d6d7b284538ed818d62f73e1d48349f06d7b/deploy/flux-deployment.yaml#L179

**Comment by malmuzaini** [comment]
we are having the same issue on OCI OKE. dsnPolicy didn't work

**Comment by malmuzaini** [comment]
Hey
we solved our issue there was a pending challenge that blocked  the cert-manager-webhook from operating well deleting that challenge after removing the finalizers solved the problem 
 `kubectl patch challenge challenge-name -p '{"metadata":{"finalizers":null}}'`

**Comment by kingdonb** [comment]
There could also be a NetworkPolicy enforcement mechanism in place. It will be necessary to know more about your cluster in order to help resolve this.

Since a fair length of time that has elapsed since your inquiry, if this is still affecting you, I will be happy to reopen and/or troubleshoot with you in the #flux slack channel on CNCF, but in the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode down to something manageable, (and respecting you may have moved on already,) I will go ahead and close out this issue for now.
