### ISSUE TITLE
Retagging an image doesn't cause a write in github

### ISSUE THREAD

**Issue by infa-bsurber** [fluxcd/flux#2923]
**Describe the bug**

Flux version: 1.17.1

I have a HelmRelease with annotations:
```
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: "regexp:(iicsqa)|(prod)-.*"
```
I have docker images stored in Artifactory. My image promotion flow is to take an image tagged as iicsqa-<timestamp>, then tag and push it as prod-<same-timestamp>.

Problem, when I push a new iicsqa-<timestamp> github gets auto-updated correctly, but when I retag it to prod-<timestamp>, github doesn't update. This is a problem as we want to clean up the iicsqa tags after they're promoted, but the HelmRelease hasn't updated to point to the prod tag.

**To Reproduce**

1) create release with annotations from report Description
2) tag image with "docker tag" as "iicsqa-new" & push it with "docker push"
3) check to ensure that release yaml has been updated with new tag
4) re-tag (using "docker tag" again) "iicsqa-new" as "prod-new" & push it with "docker push"
5) check release yaml, and see that it hasn't been updated with the new tag

**Expected behavior**

A new tag was created, even though it refers to the same image artifacts, so the release yaml should be auto updated to include the new tag

**Logs**

The only relevant logs in the flux deployment that I can see:
`ts=2020-03-17T22:42:58.106052514Z caller=images.go:106 component=sync-loop workload=<helmrelease> container=chart-image repo=<repo> pattern=regexp:(iicsqa)|(prod)-.* current=<remote-image>:iicsqa-158439706 warning="image with zero created timestamp" current="<remote-image>:iicsqa-1584397063 (0001-01-01 00:00:00 +0000 UTC)" latest="<remote-image>:iicsqa-1584400547 (2020-03-16 23:16:10.4332904 +0000 UTC)" action="skip container"`

Note, this log may be a red herring as it's referring to a tag I deleted.
When I curl (I've tested this curl with other tags and it works fine) for the manifest of the image tag iicsqa-1584397063, I get 
```
{
  "errors": [
    {
      "code": "MANIFEST_UNKNOWN",
      "message": "The named manifest is not known to the registry.",
      "detail": {
        "manifest": "<image>/iicsqa-1584397063/manifest.json"
      }
    }
  ]
}
```

**Additional context**

- Flux version: 1.17.1
- Kubernetes version: v1.14.9-eks-502bfb
- Git provider: github
- Container registry provider: jfrog artifactory

**Comment by infa-bsurber** [comment]
Did a bit of investigation, turns out this is probably because the image-creation time is used to determine the most recent value, not the tag-creation time. https://github.com/fluxcd/flux/blob/e709da5e514ab6d01c5c00a2e93224ad81c6a667/pkg/image/image.go#L403-L411

**Comment by stefanprodan** [comment]
> turns out this is probably because the image-creation time is used to determine the most recent value, which is not affected by the creation of new tags

That's right and we don't plan to change this behaviour any time soon.
