### ISSUE TITLE
[Question] execute bash script before applying helm chart

### ISSUE THREAD

**Issue by ltagliamonte-dd** [fluxcd/flux#2925]
Is there a way to execute a bash script prior to apply a helm chart?
This is my use case:
grab chart secrets from aws secret manager / vault and pass the secrets to the helm chart.

**Comment by stefanprodan** [comment]
The Helm Operator support [values from secrets](https://docs.fluxcd.io/projects/helm-operator/en/latest/helmrelease-guide/values/#secrets) so you can use a secret manager like https://github.com/mumoshu/aws-secret-operator.

**Comment by ltagliamonte-dd** [comment]
thank you replying @stefanprodan but this is not enough flexible, I have some secrets in aws and some other in vault.
I bet some other folk will have other setup as well, for this reason would be useful to be able to run an `manifestInit` script that will allow all of us to be more flexible on this matter.
