### ISSUE TITLE
Recreate resource instead of editing

### ISSUE THREAD

**Issue by phillebaba** [fluxcd/flux#2928]
**Describe the feature**
There are some fields in a resource that cant be edited after the resource has been created, like a Deployment label selector and Service type. Additionally Kubernetes 1.18 (currently only in Alpha) will introduce immutable Secrets and ConfigMaps https://github.com/kubernetes/enhancements/issues/1412 that will disable any editing after the resource has been created.

Dealing with changes to fields that cant be edited can be a pain point when maintaining multiple clusters.

A solution to dealing with these problems could be to introduce an additional annotation that tells Flux to delete the resource before applying it again. The annotation could look something like this `fluxcd.io/recreate: "true"`.

**What would the new user story look like?**
1. User starts up Flux that targets a git repository
2. User commits a manifest to the git repository
3. Flux syncs with the git repository and applies the changes
4. User makes a change to the manifest and adds the recreate annotation to the resource
5. Flux syncs with the git respository, 
6. Before applying it checks if any resource has the recreate annotation and deletes them
7. Flux applies all the resources it has synced with the git repository again

This might be a too complicated solution to something that turns out to be a non issue. There are some problems with this solution, like what happens when the with the next change that does not require a recreate. Maybe the annotation should only be respected when the apply fails due to non editable fields or resources.

With that said this seems like a problem more people than me have. The [upgrade instructions for cert-manager](https://cert-manager.io/docs/installation/upgrading/upgrading-0.13-0.14/) requires you to delete the deployments before installing as the label selectors has changed.

**Comment by hiddeco** [comment]
Related to #1816, specifically https://github.com/fluxcd/flux/issues/1816#issuecomment-497376316.
