### ISSUE TITLE
Drop support for HelmRelease v1beta1 and v1alpha2

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux#2945]
I think it's time to remove the [integrations](https://github.com/fluxcd/flux/tree/master/integrations) packages and drop support for `flux.weave.works/v1beta1` and `helm.integrations.flux.weave.works/v1alpha2`.

It's been 9 months since we released `flux.weave.works/v1`, those that haven't upgraded will probably never do.

Having these clientsets in Flux makes it hard to upgrade the Kubernetes client-go since we can't re-generate them as the codegen was removed from Flux repo when we moved Helm Operator to its own repository. Currently this is blocking the update to Kubenetes client-go 1.18.0.

**Comment by hiddeco** [comment]
As already discussed in private, +1 for this.
