### ISSUE TITLE
Question- How to apply CRD's using flux

### ISSUE THREAD

**Issue by hussainsaify** [fluxcd/flux#2959]
Hi Team,

Is it possible for flux to apply CRD's  used for chart before installing the chart. Technically we should be able to do it by copying the CRD file in our git repo and flux will apply it, but is there a better way of doing it such that we don't have to copy the CRD to our repo and can simply refer the external git file?

As an example, I need to install CRD before installing cert-manager helm chart

https://hub.helm.sh/charts/jetstack/cert-manager

Thanks,
Hussain

**Comment by gaveezy** [comment]
external git file = external source of truth
I think you shouldn't do that.

**Comment by stefanprodan** [comment]
You can place the CRDs in the Git repo that Flux syncs and set `skipCRDs: true` in the HelmRelease files.
