### ISSUE TITLE
Flux appears unable to proceed when connected for event emission and that fails

### ISSUE THREAD

**Issue by rocktavious** [fluxcd/flux#2963]
**Describe the bug**

We have our flux daemon connected to a local fluxcloud instance which is setup to post to both slack and a webhook.  When fluxcloud is unable to complete one of those things it gives the flux daemon a 500 error and this causes flux to stop proceeding the constantly retry the same commit over and over and over.  In out specific case the slack payload was working but the webhook was throwing a 500.  This caused flux from moving forward in our git history and retrying (succeessfully) to apply the same commit over and over and over.

**To Reproduce**

Deploy flux with fluxcloud and setup a webhook in flux cloud to something that will return a 500.  This will prevent flux from moving forward.

**Expected behavior**

It seems like the event emission aspect of flux should be "fire and forget" and if the downstream event handler doesn't do something properly it shouldn't block flux from moving forward.

**Logs**

```
ts=2020-04-02T15:41:28.486961895Z caller=sync.go:393 component=daemon err="executing HTTP request: 500 Internal Server Error Could not post to Webhook, status: 500\n"
fluxcloud Could not post to Webhook, status: 500 Internal Server Error
```

**Additional context**

- Flux version: 1.18
- Kubernetes version: 1.11
- Git provider: Github

**Comment by hiddeco** [comment]
I created a webhook endpoint that would only return HTTP 500 responses and Flux continued to move forward. Can you double check your logs or provide a bit more context (with logs)?

```
ts=2020-04-07T20:32:43.007483106Z caller=loop.go:107 component=sync-loop err="executing HTTP request: 500 Internal Server Error Could not post to Webhook, status: 500\n"
ts=2020-04-07T20:32:43.011702791Z caller=loop.go:133 component=sync-loop event=refreshed url=ssh://git@github.com/hiddeco/test-repo branch=master HEAD=124683b8a141d0d3080306685da2e45f229b53c2
ts=2020-04-07T20:32:43.06256431Z caller=sync.go:73 component=daemon info="trying to sync git changes to the cluster" old=c03c3ef5f5880a146df60ffb81d676d866135077 new=124683b8a141d0d3080306685da2e45f229b53c2
ts=2020-04-07T20:32:43.365045784Z caller=sync.go:539 method=Sync cmd=apply args= count=1
```

**Comment by rocktavious** [comment]
So flux was moving forward but it wasn't updating git tag.  Also it was constantly posting to slack the same update because (i assume) the git tag was not moving forward.

**Comment by rocktavious** [comment]
I don't think it was that flux wasn't actually moving forward - i think it was the fact that the git tag wasn't moving forward causing flux to constantly report the same message to slack (via flux cloud) over and over and over.

Also I would expect that once the cluster is updated the git tag would move forward and that event emission wouldn't hold that up as the git tag represents where the cluster is at in my understanding.

**Comment by hiddeco** [comment]
This answers part of your question https://github.com/fluxcd/flux/pull/2985#issuecomment-610382840

**Comment by sa-spag** [comment]
I have stumbled upon the same issue. Additionally to the Git tag not being updated, the `flux_daemon_sync_duration_seconds_count{success="false"}` counter was increased, which is misleading in my opinion. I read @squaremo's comment and I wonder if it also applies to this metric.

**Comment by kingdonb** [comment]
I'm not sure if there is anything actionable here, but I'm going to close it out.

Flux v2 has a new read-only by default design with separated notifications out into a separate controller that will absolutely not have the issue of blocking reconciliation on notification failure (though I'm not sure it's established that this happened here, let's say it has been established that the outcome in Flux v1 can be less than optimal when something fails.)

I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

If this is still affecting you, I will be happy to reopen and/or troubleshoot with you in the #flux slack channel on CNCF, but in the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.
