### ISSUE TITLE
Error of fetching image metadata from AWS ECR(China region)

### ISSUE THREAD

**Issue by terrificdm** [fluxcd/flux#2964]
**Describe the bug**

My EKS is running on AWS China region(cn-north-1) with version 1.15, and I have successfully set up Flux using Helm installation. The Flux works well and it could access Git with deploy key and create/update applications thru configurations stored in Git repo. The issue was that Flux cannot fetch app's image metadata from AWS ECR, it turned out that when the newer image was created in ECR repo, the Flux couldn't update configurations accordingly in Git repo then update the applications.
I have checked my EKS node's IAM role, ECR ReadOnly policy was attached properly. And I have even attached ECR FullyAccess policy, but it didn't work. I have also tried IRSA, bonded an IAM role for Flux service account with ECR FullyAccess policy, but still failed.
The weird thing is that I installed EKS+Flux in AWS region us-east-1 with the same configurations in China region(without modify anything like node IAM role or IRSA), the Flux works very well with EKS&ECR, no issue came out...
And I also just checked the source code of "aws.go" https://github.com/fluxcd/flux/blob/master/pkg/registry/aws.go in Flux repo, I noticed that one of const ecrHostSuffix is set to ".amazonaws.com", but for AWS China region the ECR registry URLs should looks like "account-id.dkr.ecr.region.amazonaws.com.cn" according to AWS documents https://docs.amazonaws.cn/en_us/aws/latest/userguide/endpoints-Beijing.html, https://docs.amazonaws.cn/en_us/aws/latest/userguide/ecr.html and https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/aws/aws_credentials.go. So I guess maybe this the main cause for this issue. But I am not 100% sure whether I am right.

**To Reproduce**
Strictly follow the guide [https://docs.fluxcd.io/en/latest/tutorials/get-started-helm/](url) to install Flux thru Helm v3, and EKS is running on AWS China Region: cn-north-1

**Expected behavior**

Expected someone to help point me how to fix this issue.

**Logs**

ts=2020-03-31T18:23:19.267382623Z caller=images.go:159 component=sync-loop err="fetching image metadata for 634072196806.dkr.ecr.cn-north-1.amazonaws.com.cn/gitops-app: item not in cache, last error: Get https://634072196806.dkr.ecr.cn-north-1.amazonaws.com.cn/v2/gitops-app/tags/list: no basic auth credentials"
ts=2020-03-31T18:23:23.195082293Z caller=warming.go:180 component=warmer canonical_name=634072196806.dkr.ecr.cn-north-1.amazonaws.com.cn/gitops-app auth={map[]} err="requesting tags: Get https://634072196806.dkr.ecr.cn-north-1.amazonaws.com.cn/v2/gitops-app/tags/list: no basic auth credentials"

**Additional context**

- Flux version: 1.18.0
- Kubernetes version: AWS EKS 1.15
- Git provider: Github
- Container registry provider: AWS ECR

**Comment by terrificdm** [comment]
Fixed the issue with workaround [https://github.com/terrificdm/ecr-k8s-secret-creator](url), even though it isn't the best way to solve the problem. Better to fix this bug in upstream.

**Comment by hiddeco** [comment]
Flux should be able to pull image metadata with the following image:

`hiddeco/flux:aws-partition-domains-cc2c9a7d`

**Comment by terrificdm** [comment]
> Flux should be able to pull image metadata with the following image:
> 
> `hiddeco/flux:aws-partition-domains-cc2c9a7d`

Thanks @hiddeco , I replaced the image of Flux deployment with yours
<img width="876" alt="Screen Shot 2020-04-07 at 9 47 24 AM" src="https://user-images.githubusercontent.com/62762145/78623479-4b40a780-78ba-11ea-8d3f-ca85d977ff54.png">

But still got error information as blow logs:
`ts=2020-04-07T02:25:34.860707198Z caller=aws.go:233 component=aws warning="AWS registry domain not in expected format <account-id>.dkr.ecr.<region>.amazonaws.com" domain=634072196806.dkr.ecr.cn-north-1.amazonaws.com.cn`
`ts=2020-04-07T02:25:34.863116463Z caller=warming.go:180 component=warmer canonical_name=634072196806.dkr.ecr.cn-north-1.amazonaws.com.cn/gitops-app auth={map[]} err="requesting tags: Get https://634072196806.dkr.ecr.cn-north-1.amazonaws.com.cn/v2/gitops-app/tags/list: no basic auth credentials"`

And I also checked your codes from pull request, maybe "len(bits) != 6" is the reason.
<img width="879" alt="Screen Shot 2020-04-07 at 10 14 45 AM" src="https://user-images.githubusercontent.com/62762145/78623857-ffdac900-78ba-11ea-9f0c-9f279b165da3.png">

**Comment by hiddeco** [comment]
@terrificdm you are absolutely right. `hiddeco/flux:aws-partition-domains-138a98fa` should do a better job.

**Comment by terrificdm** [comment]
@hiddeco Nice job! The new image works very well, truly appreciate your constant help :) 
PS: the Flux's default configuration of registry will scan EKS system's image repo(China Region specific), which is "918309763551.dkr.ecr.cn-north-1.amazonaws.com.cn/*", so better to use flag "--registry-exclude-image" for that repo. Just in case someone might need this info.

**Comment by hiddeco** [comment]
I have added `918309763551` to the default list of excluded ECR IDs in the above PR.
