### ISSUE TITLE
fluxignore ignore files with same spec as gitignore, dockerignore, helmignore

### ISSUE THREAD

**Issue by kav** [fluxcd/flux#2966]
**Describe the feature**
I'd love a `.fluxignore` file I can use to have flux ignore certain yaml files. I know I can use directories and ignore via annotation. And I do, but just for various UX reasons I'd like to keep some files that aren't kubernetes files but are yaml I want the flux instance to ignore in directories it's looking in. My use case is specifically RKE Cluster.yaml files but I imagine there are others.

There is a gitignore spec implementation here that looks like it might be promising
https://github.com/monochromegane/go-gitignore

**Comment by kav** [comment]
`.sops.yaml` files at the root of a cluster folder are another immediate use case

**Comment by darksinge** [comment]
I would love to have this feature too. In my particular case, I have a cluster in AWS I created with [eksctl](https://eksctl.io/). Initially, I created the cluster using flags (e.g., `eksctl create cluster --name foo ...`), but I'd much rather have a `cluster.yaml` config file, [as described here](https://eksctl.io/usage/creating-and-managing-clusters/#using-config-files). 

Currently, I can't put my "infrastructure as code" to describe my cluster's infrastructure inside my GitOps repo, and it feels awkward to put it anywhere else.

**Comment by darksinge** [comment]
As a workaround for my problem, I set `git.path` and `git.label` when installing Flux with Helm.

```bash
$ export STAGE=dev
$ helm upgrade -i flux fluxcd/flux \
>   --set git.url="git@$GIT_HOST:$GIT_USER/$GIT_REPO" \
>   --set git.path="k8s/common\,k8s/$STAGE" \
>   --set git.label="flux-sync-$STAGE"
```

And my repo has a folder structure somewhat like the following:

```
.
├── README.md
├── .gitignore
├── cluster.yaml
└── k8s
    ├── common
    │   ├── kubernetes-dashboard/
    │   └──other-common-stuff/
    ├── dev
    │   └── podinfo.yaml
    └── stable
        └── podinfo.yaml
```

`--set git.path` tells flux where to look for manifest files (in this case, under `k8s/common` and `k8s/dev`), and `--set git.label` tells flux which Git tag to use to keep track of sync progress. See [here](https://hub.helm.sh/charts/fluxcd/flux).

Now `cluster.yaml` won't be touched by flux, and I can keep it under version control. I'm actually quite happy with this setup.

**Comment by kav** [comment]
I have a very similar layout myself. It's not as pretty as inlining but it does work.

**Comment by kingdonb** [comment]
Flux v2 has fine-grained control over directories and git sources, as well as strong multi-tenancy and [multi-cluster setup](https://toolkit.fluxcd.io/get-started/#multi-cluster-setup).

I like the idea of the ignore file, but it is a new feature so cannot be prioritized for development in Flux v1 at this point.

If someone was contributing a pull request, I would be inclined to review it and try to get it merged. But knowing the limitations of how much time is available, and where there are priorities in the [1.22.0 milestone](https://github.com/fluxcd/flux/milestone/31) currently ahead of any other enhancements, my intuition is this feature is not likely to make it into the Flux v1 maintenance release without a benefactor.

The [workaround](https://github.com/fluxcd/flux/issues/2966#issuecomment-619285482) that `@darksinge` suggested is good, 👍 

Closing for now.

**Comment by mosanden** [comment]
Flux v2 offers a `.sourceignore` file. See the [documentation](https://toolkit.fluxcd.io/components/source/gitrepositories/#excluding-files).
