### ISSUE TITLE
All of the sudden nothing is automated and nothing can be pulled (github outage earlier today)

### ISSUE THREAD

**Issue by cyberpwnn** [fluxcd/flux#2968]
There was an outage today across all of github for a good while. After the outage, listing workloads I noticed nothing was automated anymore, so I re-ran the automate command and got this

```
Error: git repo not ready: git clone --mirror: fatal: Could not read from remote repository., full output:
 Cloning into bare repository '/tmp/flux-gitcloneXXXXXXXX'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Run 'fluxctl automate --help' for usage.
```

It's complaining about the public key. So I re-followed the guide, and ran `fluxctl identity` copied the RSA key and tried to add a second deploy key to my repo. Github complained that deploy key is already added... Meaning for some reason my previous deploy key works just fine, but flux cant use it.

Is there any way I can fix this? And possibly prevent this from happening again?

**Comment by hiddeco** [comment]
Can you please confirm this is still an issue today? Given the fact that GitHub complains the key is already known, I think there is a small chance this issue is somehow still related to the outage earlier, and not due to anything Flux does.

**Comment by cyberpwnn** [comment]
Still happening. I don't think it's flux, but i'm also not familiar with the inner workings of deploy keys. I'm pretty sure it has a lot to do with the outage since that's pretty much when it happened. I've been manually deploying at the moment. Have not had the time to try and fix it.

I imagine deleting the deploy key on gh and re-creating it might work.

**Comment by hiddeco** [comment]
I would try to contact GitHub support about the malfunctioning public key before swapping it as you have been the only reporting this thus far since the GitHub outage.

**Comment by jameel23** [comment]
I'm getting the same error as well.

**Comment by cyberpwnn** [comment]
This is still happening by the way. I've just gotten used to manually deploying my stuff lol.
