### ISSUE TITLE
Flux incorrectly shows what resources have been updated when using Kustomize

### ISSUE THREAD

**Issue by wieslaw-decent** [fluxcd/flux#2981]
**Describe the bug**

When using Kustomize (or any other manifest generator it seems) Flux incorrectly shows which resources have been updated both in the logs and in the associated sync event metadata. This means that weave cloud/fluxcloud also posts incorrect information regarding the event.

**Expected behavior**

I have a repository for two environments, `development` and `staging`. Each resides in its own namespace. Each file contains one resource associated with the given application/service, usually a `Deployment` manifest. The repository structure looks like follows:

```
├── common
│   ├── .flux.yaml
│   ├── ambassador.yaml      
│   ├── cert-manager.yaml     
│   ├── fluxcloud.yaml     
│   ├── flux.yaml     
│   ├── helm-exporter.yaml     
│   ├── helm-operator.yaml     
│   └── prometheus-operator.yaml
├── development
│   ├── .flux.yaml
│   ├── app1.yaml      
│   ├── app2.yaml        
│   ├── app3.yaml      
│   ├── proxy.yaml        
│   ├── keycloak-post.yaml  
│   ├── keycloak-pre.yaml      
│   ├── keycloak.yaml         
│   └── sftp.yaml         
├── development-secrets
│   ├── .flux.yaml
│   ├── .sops.yaml
│   └── secrets.enc.yaml    
├── staging                  
│   ├── .flux.yaml
│   ├── app1.yaml   
│   ├── app2.yaml        
│   ├── app3.yaml      
│   ├── proxy.yaml        
│   ├── keycloak-post.yaml  
│   ├── keycloak-pre.yaml      
│   ├── keycloak.yaml         
│   └── sftp.yaml         
└── staging-secrets   
    ├── .flux.yaml
    ├── .sops.yaml
    └── secrets.enc.yaml
```

Manifest generation and SOPS support is enabled in Flux, and everything works great. When `app1` in `development` is updated, Flux generates events properly. This can be seen in the logs, ie. after changing `app1` in `development`:

```
ts=2020-04-06T16:26:29.222506302Z caller=daemon.go:704 component=daemon event="Sync: 17f533a, development:helmrelease/development-app1" logupstream=true
```

**Broken behaviour**

Problems started to appear after I decided to use Kustomize to reduce code duplication. Following https://github.com/fluxcd/flux-kustomize-example I changed `.flux.yaml` in `staging` and `development` directories to:

```
version: 1
patchUpdated:
  generators:
    - command: kustomize build .
  patchFile: flux-patch.yaml
```

I also added a new overlay directory, each environment got its `kustomization.yaml` file, and the newly generated manifests using Kustomize have the same content as the old static files.

The problem I've started encountering is the fact that flux shows completely random resources in its Sync events. For example, doing a simple change in the `app1` manifest in `development` now shows:

```
ts=2020-04-01T20:40:01.10921144Z caller=daemon.go:704 component=daemon event="Sync: b208daf, development:helmrelease/development-app1, staging:helmrelease/staging-app2" logupstream=true
```

The set of shown changed releases looks pretty random - sometimes it shows different resources from another environment, sometimes 2-3 resources from the same one, I haven't found a rule to that. Sometimes even the resource which triggered the update isn't shown in the list (`development/app1` in this case). It never showed resources from the `common` or `secrets` directory, which weren't handled by Kustomize.

To make sure that the problem isn't in my manifests, I browsed the source code a bit and found the following gem:

https://github.com/fluxcd/flux/blob/3e01223d90a5aa9b71cc9d7342ba18e1e2090f01/pkg/daemon/sync.go#L216-L225

Does this mean that all files that hold more than one resource are affected? Not only ones generated by Kustomize? Any workarounds that can be applied for the time being?

**Additional context**

- Flux version: 1.18 and 1.19
- Kubernetes version: 1.13.6, 1.15.9
- Git provider: Github
- Container registry provider: GCR

**Comment by dan-slinky-ckpd** [comment]
I'm also experiencing this behaviour with flux+kustomize. Flux sync events are being emitted at random for different resources, on each interval but randomly hours after an actual change has been applied.

For me, it's then manifest itself through spurious notifications through to fluxcloud/Slack.

**Comment by dan-slinky-ckpd** [comment]
This appears to be related to #2494
