### ISSUE TITLE
Flux should continue despite failure to connect to fluxcloud

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/flux#2984]
If Flux cannot connect to fluxcloud, it will not make progress.  The problem is that one cannot fix this problem using GitOps.

Instead, Flux should continue performing updates.

**Comment by hiddeco** [comment]
Related to #2963.

**Comment by hiddeco** [comment]
Can you describe in what way Flux was unable to connect to fluxcloud? I scaled down fluxcloud and although Flux was chatty about being unable to connect it did still synchronize a new made commit.

```
ts=2020-04-07T20:17:34.193599919Z caller=upstream.go:118 component=upstream err="executing websocket ws://fluxcloud/v11/daemon: dial tcp 10.96.225.106:80: connect: connection refused"
ts=2020-04-07T20:17:37.367327299Z caller=loop.go:133 component=sync-loop event=refreshed url=ssh://git@github.com/hiddeco/test-repo branch=master HEAD=b701a53c921d5db7190138410e8c1b81723f6233
ts=2020-04-07T20:17:37.403196892Z caller=sync.go:73 component=daemon info="trying to sync git changes to the cluster" old=c03c3ef5f5880a146df60ffb81d676d866135077 new=b701a53c921d5db7190138410e8c1b81723f6233
ts=2020-04-07T20:17:37.601686244Z caller=sync.go:539 method=Sync cmd=apply args= count=2
ts=2020-04-07T20:17:37.703718153Z caller=sync.go:605 method=Sync cmd="kubectl apply -f -" took=101.96328ms err=null output="namespace/bar created\ncronjob.batch/delete-me configured"
ts=2020-04-07T20:17:37.707404026Z caller=daemon.go:704 component=daemon event="Sync: b701a53, <cluster>:namespace/bar" logupstream=true
ts=2020-04-07T20:17:38.737594231Z caller=sync.go:395 component=daemon err="executing HTTP request: executing HTTP request: Post http://fluxcloud/v6/events: dial tcp 10.96.225.106:80: connect: connection refused"
```

**Comment by awh** [comment]
@derrickburns could you provide us with some logs demonstrating this behaviour?

**Comment by derrickburns** [comment]
I didn't capture any logs when the problem occurred. 

If it recurs, I will.

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
