### ISSUE TITLE
Unable to use kustomize with flux and helm-operator

### ISSUE THREAD

**Issue by SerialVelocity** [fluxcd/flux#2988]
**Describe the bug**
When flux and helm-operator have been checked into the repo being used by flux, everything fails as namespaces are being created by both `deploy` folders:
```
$ kustomize build .
Error: ./helm-operator: id '"~G_v1_Namespace|~X|~P|flux|~S"' already used
```

**To Reproduce**

Steps to reproduce the behaviour:

1. Create a repo with a `kustomization.yml` containing:
```
bases:
- github.com/fluxcd/flux/deploy
- github.com/fluxcd/helm-operator/deploy
```

**Expected behaviour**

No error to be thrown. This is caused by the namespace creation being checked into the `deploy` folder. This causes two issues:
1- You are forced to use the "flux" namespace as setting `namespace: other` in the `kustomization.yml` doesn't rename namespace resources.
2- You cannot use `kustomize` for more than one repo that defines the namespace.

Is it possible to delete the namespace yaml file? It was initially added in https://github.com/fluxcd/flux/pull/2475.

**Additional context**

- Flux version: 1.19.0
- Kubernetes version: 1.17.4

**Comment by hiddeco** [comment]
As described in the linked PR, the namespace was added to properly configure the RBAC rules. I was however not aware of the issue this would cause while combining both repositories as you describe, as it is [possible to change the namespace using a patch file for issue 1](https://docs.fluxcd.io/projects/helm-operator/en/stable/get-started/using-kustomize/#configure-a-namespace). This may be worth trying until we resolve this issue.

**Comment by SerialVelocity** [comment]
Unfortunately I've tried doing that and `kubectl apply -k` still creates the namespace. If you check the output of `kubectl kustomize .` (or `kustomize build .`) you will see that the namespace still exists. This is because kustomize doesn't  (and most likely never will) allow deleting a resource. See https://github.com/kubernetes-sigs/kustomize/issues/106 and https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#removal-directives.

Using `patchesJson6902` you can at least make it `{}` but then the apply fails because it isn't a valid kubernetes manifest.

**Comment by ChipWolf** [comment]
Experiencing the same

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
