### ISSUE TITLE
Flux is trying to contact weave and give possibly private information without consent or notice

### ISSUE THREAD

**Issue by markxnelson** [fluxcd/flux#2990]
**Describe the bug**

Flux is trying to contact weave and give possibly private information without consent or notice

**To Reproduce**

Run flux, look in the log.

**Expected behavior**

I expected to be told about this telemetry and asked for consent.

**Logs**

```
https://checkpoint-api.weave.works/v1/check/weave-flux?arch=amd64&flag_cluster-version=kubernetes-v1.17.0&flag_git-configured=true&flag_kernel-version=5.3.0-7642-generic&os=linux&signature=o5U7xxxxxxxxxxxxxxxx%2BinfzV%2BfbzM4dho%3D&version=1.19.0:
```

**Comment by stefanprodan** [comment]
There is no private information being collected. Flux sends its own version and the Kubernetes API version so we know what Kubernetes version to support. https://github.com/fluxcd/flux/blob/master/cmd/fluxd/main.go#L638

You can disable the checkpoint https://github.com/weaveworks/go-checkpoint

**Comment by markxnelson** [comment]
thank you for the information
