### ISSUE TITLE
Memcached lookup fails when overwriting the default namespace with Kustomize as described in Getting Started guide

### ISSUE THREAD

**Issue by dschulten** [fluxcd/flux#2998]
**Describe the bug**

The description [How to bootstrap Flux using Kustomize, overwriting the default namespace](https://docs.fluxcd.io/en/1.19.0/tutorials/get-started-kustomize/#overwriting-the-default-namespace) sets up a failing memcached connection.

When I follow the description, I get many errors in the logs which tell me that memcached is unreachable (see logs below).

The reason seems to be that the custom namespace  makes this argument value wrong: 

    --memcached-hostname=memcached.flux

**Workaround**

Change the `--memcached-hostname` argument [to memcached](https://github.com/dschulten/flux-bootstrap-kustomize/commit/324ae243811e49eaf8dbcbe2875ad20a3d854d6a#diff-92df6eedeb5e9dd885df771c0afc4996).

**To Reproduce**

Following the description I have set up these [kustomize files](https://github.com/dschulten/flux-bootstrap-kustomize/commit/90b71e26b76e2a62b583a0c3ae6c33a4a480eecc#diff-92df6eedeb5e9dd885df771c0afc4996) to overwrite the default namespace.

I applied them with 

    kubectl apply -k fluxcd

**Expected behavior**

When following the getting started guide and overwriting the default namespace as described, there should be no memcached errors.

**Logs**

```
ts=2020-04-13T07:41:46.687070011Z caller=memcached.go:156 component=memcached err="error updating memcache servers: lookup memcached.flux on 10.96.0.10:53: no such host"
```

**Additional context**

- Flux version: 1.19.0
- Kubernetes version: 1.15.5 (Docker Desktop for Windows)
- Git provider: Github
- Container registry provider: Docker hub

**Comment by awh** [comment]
Thankyou for the report @dschulten - we should update the `Overwriting the default namespace` section of the documentation to mention that the `--memcached-hostname` argument in `patch.yaml` needs updating too.

**Comment by kingdonb** [comment]
I added a note to the docs in fluxcd/website#467 which will close this issue. 👍
