### ISSUE TITLE
Fluxctl installation issue

### ISSUE THREAD

**Issue by prathapar** [fluxcd/flux#3005]
**Describe the bug**
I am trying to setup Gitops, currently am stuck . please help.  Thank you

Flux is not installing on "Red Hat Enterprise Linux Server release 7.7 (Maipo) "

Installed Snap successfully. then trying to install flux as per the wiki 
https://snapcraft.io/docs/installing-snap-on-red-hat
https://docs.fluxcd.io/en/1.18.0/references/fluxctl.html

Console Output:
**[root@hcmx-sonarqube snapd]# cat /etc/redhat-release**
Red Hat Enterprise Linux Server release 7.7 (Maipo)
**[root@hcmx-sonarqube snapd]# snap**
The snap command lets you install, configure, refresh and remove snaps.
Snaps are packages that work across many different Linux distributions,
enabling secure delivery and operation of the latest apps and utilities.

Usage: snap <command> [<options>...]

Commands can be classified as follows:

         Basics: find, info, install, list, remove
        ...more: refresh, revert, switch, disable, enable
        History: changes, tasks, abort, watch
        Daemons: services, start, stop, restart, logs
       Commands: alias, aliases, unalias, prefer
  Configuration: get, set, unset, wait
        Account: login, logout, whoami
    Permissions: connections, interface, connect, disconnect
      Snapshots: saved, save, check-snapshot, restore, forget
          Other: version, warnings, okay, ack, known, model, create-cohort
    Development: run, pack, try, download, prepare-image

For more information about a command, run 'snap help <command>'.
For a short summary of all commands, run 'snap help --all'.
**[root@hcmx-sonarqube snapd]# snap install fluxctl --classic**
error: cannot install "fluxctl": Post https://api.snapcraft.io/v2/snaps/refresh: EOF

**To Reproduce**

Steps to reproduce the behaviour:

1. Provide Flux install instructions
2. Provide a GitHub repository with Kubernetes manifests

**Expected behavior**

**Logs**

If applicable, please provide logs of `fluxd`. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs deploy/flux  -n flux`.

**Additional context**

- Flux version: 
- Kubernetes version:
- Git provider:
- Container registry provider:

**Comment by awh** [comment]
Hi @prathapar, thanks for the report. It looks like you could have a networking issue talking to the snap store. Do other snap installs work? Does the host you're running the snap install command on have direct internet access, or is it behind some kind of firewall or proxy? What do you get if you run `curl -X OPTIONS --verbose https://api.snapcraft.io/v2/snaps/refresh` from the same machine? For comparison, I see

```
$ curl -X OPTIONS --verbose https://api.snapcraft.io/v2/snaps/refresh
*   Trying 91.189.92.41...
* TCP_NODELAY set
* Connected to api.snapcraft.io (91.189.92.41) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=api.snapcraft.io
*  start date: Feb 29 13:04:42 2020 GMT
*  expire date: May 29 13:04:42 2020 GMT
*  subjectAltName: host "api.snapcraft.io" matched cert's "api.snapcraft.io"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> OPTIONS /v2/snaps/refresh HTTP/1.1
> Host: api.snapcraft.io
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: gunicorn/19.7.1
< Date: Wed, 15 Apr 2020 10:19:46 GMT
< Content-Type: text/html; charset=utf-8
< Allow: POST, OPTIONS
< Snap-Store-Version: 22
< X-View-Name: snapdevicegw.webapi_refresh.snap_refresh
< Content-Length: 0
< X-VCS-Revision: 0bf41e1
< X-Request-Id: D9A91105ECD80A325CA101BB5E96DFC2208DEAD5
< 
* Connection #0 to host api.snapcraft.io left intact
```

**Comment by prathapar** [comment]
Thank you very much for the prompt response. 

**curl -X OPTIONS --verbose https://api.snapcraft.io/v2/snaps/refresh**

console output: 
root@hcmx-sonarqube kubernetes]# curl -X OPTIONS --verbose https://api.snapcraft.io/v2/snaps/refresh
* About to connect() to proxy web-proxy.in.softwaregrp.net port 8080 (#0)
*   Trying 15.122.63.30...
* Connected to web-proxy.in.softwaregrp.net (15.122.63.30) port 8080 (#0)
* Establish HTTP proxy tunnel to api.snapcraft.io:443
> CONNECT api.snapcraft.io:443 HTTP/1.1
> Host: api.snapcraft.io:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=api.snapcraft.io
*       start date: Feb 29 13:04:42 2020 GMT
*       expire date: May 29 13:04:42 2020 GMT
*       common name: api.snapcraft.io
*       issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
> OPTIONS /v2/snaps/refresh HTTP/1.1
> User-Agent: curl/7.29.0
> Host: api.snapcraft.io
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: gunicorn/19.7.1
< Date: Wed, 15 Apr 2020 10:35:57 GMT
< Content-Type: text/html; charset=utf-8
< Allow: POST, OPTIONS
< Snap-Store-Version: 22
< X-View-Name: snapdevicegw.webapi_refresh.snap_refresh
< Content-Length: 0
< X-VCS-Revision: 0bf41e1
< X-Request-Id: 0F7C9615EC9F0A325C8101BB5E96E38C213CAF1A
<
* Connection #0 to host web-proxy.in.softwaregrp.net left intact

**Comment by prathapar** [comment]
please help me. if everything goes fine with demo. we are ready to adopt it. would really appreciate.

**Comment by awh** [comment]
@prathapar I don't think this is a flux issue, I think this is a problem with your company's web proxy which I can see is mediating your connections to the snap store. Have you tried installing any other software with snap? I strongly suspect it will fail in the same way.

Whilst we're figuring that out, you can install `fluxctl` by downloading a binary release from here: https://github.com/fluxcd/flux/releases

**Comment by prathapar** [comment]
Yes we have a proxy. 
1. Can you please suggest how do i pass proxy as an argument during execution of the **snap** command. so that it can traverse and execute it properly.  

2. I have already set the system proxy.  

3. Is there any file where i can set the proxy information, snap can use the same and install flux properly.

**Comment by dholbach** [comment]
You might want to ask over here: https://forum.snapcraft.io/search?q=proxy

**Comment by prathapar** [comment]
Thanks a lot. 
Really appreciate  very much Dholbach and Adam Harrison.
Please close the ticket. Thank you once agian.
