### ISSUE TITLE
fluxd not logging and not syncing but process still alive

### ISSUE THREAD

**Issue by bcbrockway** [fluxcd/flux#3014]
**Describe the bug**

We have 5 instances of fluxd on 5 different GKE clusters syncing from the same repo in Gitlab. Two of them stopped syncing (`flux_daemon_sync_duration_seconds_count` prometheus metric no longer incrementing) and stopped logging at roughly the same time. The `/healthz` endpoint is still sending 200 responses so k8s is not automatically restarting the pod.

***Metrics still increasing:***

* flux_cache_request_duration_seconds_count
* flux_client_fetch_duration_seconds_count
* flux_fluxd_connection_duration_seconds

***Metrics stopped:***

* flux_daemon_sync_duration_seconds_count
* flux_registry_fetch_duration_seconds_count

**To Reproduce**

Unable to reproduce. Probably caused by something at the GitLab end given that 2 instances stopped at the same time.

**Expected behavior**

1. The process should not stop syncing
2. The `/healthz` endpoint should be returning 500 errors

**Logs**

In both instances the last message logged was a checkpoint message but it looks like the sync freeze started at around 07:30 UTC:

***Instance 1:***
```
ts=2020-04-20T07:27:23.861400561Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-04-20T07:27:26.440287703Z caller=images.go:27 component=sync-loop msg="no automated workloads"
ts=2020-04-20T07:27:57.42265251Z caller=loop.go:133 component=sync-loop event=refreshed url=ssh://git@gitlab.com/path/to/repo.git branch=production HEAD=c34fa4b547a470273a6363a1993664f3ccfc6d9a
ts=2020-04-20T07:28:58.986421306Z caller=loop.go:133 component=sync-loop event=refreshed url=ssh://git@gitlab.com/path/to/repo.git branch=production HEAD=c34fa4b547a470273a6363a1993664f3ccfc6d9a
ts=2020-04-20T07:30:00.552782777Z caller=loop.go:133 component=sync-loop event=refreshed url=ssh://git@gitlab.com/path/to/repo.git branch=production HEAD=c34fa4b547a470273a6363a1993664f3ccfc6d9a
ts=2020-04-20T07:35:02.723776775Z caller=checkpoint.go:24 component=checkpoint msg="up to date" latest=1.19.0
```

***Instance 2:***
```
ts=2020-04-20T07:28:05.190137879Z caller=loop.go:133 component=sync-loop event=refreshed url=ssh://git@gitlab.com/path/to/repo.git branch=qa HEAD=aef718d6acb17d45bc9acb9fe9d0c9897cdc7a43
ts=2020-04-20T07:28:05.190313465Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-04-20T07:29:05.005378461Z caller=loop.go:133 component=sync-loop event=refreshed url=ssh://git@gitlab.com/path/to/repo.git branch=qa HEAD=aef718d6acb17d45bc9acb9fe9d0c9897cdc7a43
ts=2020-04-20T07:30:12.150126169Z caller=loop.go:133 component=sync-loop event=refreshed url=ssh://git@gitlab.com/path/to/repo.git branch=qa HEAD=aef718d6acb17d45bc9acb9fe9d0c9897cdc7a43
ts=2020-04-20T10:16:58.148058741Z caller=checkpoint.go:24 component=checkpoint msg="up to date" latest=1.19.0
```

**Additional context**

- Flux version: 1.19.0
- Kubernetes version: 1.14.10-gke.27
- Git provider: Gitlab
- Container registry provider: Gitlab

**Comment by bcbrockway** [comment]
Incidentally, when I deleted the pod to restart it logged the following so some parts of the process were clearly still working:

```
ts=2020-04-20T10:50:10.217853678Z caller=upstream.go:174 component=upstream disconnected=true
ts=2020-04-20T10:50:10.218022108Z caller=upstream.go:145 component=upstream connectionclosing=true err="websocket: close sent"
ts=2020-04-20T10:50:10.218573926Z caller=main.go:809 exiting=terminated
ts=2020-04-20T10:50:10.218892694Z caller=warming.go:127 component=warmer stopping=true
ts=2020-04-20T10:50:15.218313742Z caller=upstream.go:133 component=upstream connecting=true
```

**Comment by kingdonb** [comment]
This issue has gone stale, and might have been fixed in the latest Flux v1 release according to #3044.

In any case, please be aware that Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
