### ISSUE TITLE
Fluxcd sends success status even when helmrelease is in failed state

### ISSUE THREAD

**Issue by c4m4** [fluxcd/flux#3021]
**Describe the bug**

Fluxcd sends success status even when helmrelease is in failed state

**To Reproduce**
deploy an image with an error, that make the container unable to start

Steps to reproduce the behaviour:

kubectl get hr
NAME    RELEASE   STATUS   MESSAGE                                                 AGE
myapp   myapp     failed   Release failed for Helm release 'myapp' in 'default'.   43m

**Logs**
```
{
  "id": 0,
  "serviceIDs": [
    "default:helmrelease/myapp"
  ],
  "type": "autorelease",
  "startedAt": "2020-04-23T22:31:56.254249608Z",
  "endedAt": "2020-04-23T22:31:57.761242888Z",
  "logLevel": "info",
  "metadata": {
    "Revision": "63813123499682dad8e7536f0938b4a1ab348b5c",
    "result": {
      "default:helmrelease/myapp": {
        "Status": "success",
        "PerContainer": [
          {
            "Container": "chart-image",
            "Current": "docker.pkg.github.com/bigcompany/store-docker-repo/hello:sha-6506ba6",
            "Target": "docker.pkg.github.com/bigcompany/store-docker-repo/hello:sha-4f09fb4"
          }
        ]
      }
    },
    "spec": {
      "Changes": [
        {
          "WorkloadID": "default:helmrelease/myapp",
          "Container": {
            "Name": "chart-image",
            "Image": "docker.pkg.github.com/bigcompany/store-docker-repo/hello:sha-6506ba6"
          },
          "ImageID": "docker.pkg.github.com/bigcompany/store-docker-repo/hello:sha-4f09fb4"
        }
      ]
    }
  }
}
```

If applicable, please provide logs of `fluxd`. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs deploy/flux  -n flux`.

**Additional context**

- Flux version: 
  flux:1.18.0
- Kubernetes version:
Server Version: v1.15.6
- Git provider:
github
- Container registry provider:
github

**Comment by hiddeco** [comment]
A success for Flux is a successful apply on the cluster and not the resulting state of the release the Helm operator performs. [This should be monitored separately.](https://docs.fluxcd.io/projects/helm-operator/en/stable/references/monitoring/)

**Comment by c4m4** [comment]
> A success for Flux is a successful apply on the cluster and not the resulting state of the release the Helm operator performs. [This should be monitored separately.](https://docs.fluxcd.io/projects/helm-operator/en/stable/references/monitoring/)

but I am using the wait: true parameter in my helmrelease file, kubectl describe crd helmrelease says

 ```
Wait:
                  Description:  Wait will mark this Helm release to wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are in a ready state before marking the release as successful.
```

It could be nice, if flux wait and pods are in failed state, send an error to fluxcloud and not a success

**Comment by hiddeco** [comment]
This would be a Helm Operator feature and is tracked in https://github.com/fluxcd/helm-operator/issues/13

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
