### ISSUE TITLE
fluxctl install command should support inclusion of pre-existing SSH key

### ISSUE THREAD

**Issue by errordeveloper** [fluxcd/flux#3028]
I prefer to control SSH key generation. In order to use my pre-existing key I had to modify manifest that I generated with `flux install` and remove the secret object, it'd be nice if I could exclude the secret from the manifest or pass `--git-private-ssh-key` to the `flux install` command.

**Comment by kingdonb** [comment]
This is possible in Flux v2, with the `flux` CLI which has numerous options for how to manage secrets through bootstrap or otherwise. 👍
