### ISSUE TITLE
fluxctl install command requires --git-email and --git-user even when --git-readonly is set

### ISSUE THREAD

**Issue by errordeveloper** [fluxcd/flux#3029]
With `--git-readonly` the `--git-user` and `--git-email` flags are meaningless, these shouldn't be required.

**Comment by kingdonb** [comment]
This looks like a change that I can do.

I am still learning the codebase, and still learning to be proficient in the language, but the purpose of this change is clear and as it sounds perfectly straightforward to implement, it should also be easy to test, so `good-first-issue` 👍

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

I think this won't be implemented here.
