### ISSUE TITLE
fluxd trips over YAML files it cannot parse

### ISSUE THREAD

**Issue by errordeveloper** [fluxcd/flux#3030]
I have `foo.yaml` in my top level directory, it is an array of objects. This file is not meant to be read by flux, however I'm seeing this error:

```
ts=2020-04-24T17:58:00.51440607Z caller=loop.go:107 component=sync-loop err="loading resources from repo: parsing YAML doc from \"foo.yaml\": yaml: unmarshal errors:\n  line 1: cannot unmarshal !!seq into resource.baseObject"
```
It appears that the sync loop bearks after this. ~I tried setting `--git-paths` to point flux at subdirs that I need, which is not ideal, but it still kept tripping over `foo.yaml`.~

I am assuming the sync doesn't succeed as I'm not seeing the log line that I normally see:
```
 method=Sync cmd="kubectl apply -f -" took=3.164698 ...
```

**Comment by errordeveloper** [comment]
It'd be nice to be able to specify a list of files for flux to ignore, but even then it shouldn't expect to be able to read just any YAML file.

**Comment by kingdonb** [comment]
Flux v2 has both `.sourceignore`, and `gitrepository.spec.ignore` now for handling this.

In addition, if you use a hand-crafted `kustomization.yaml` which is other than the default automatic, recursive kustomization generated by Flux, you can explicitly include each YAML file that is to be included as part of the kustomization. This way if you have many YAML files to ignore and only a few to apply, you no longer need to call out each file that is meant to be ignored.
