### ISSUE TITLE
Recursively search for .flux.yaml files in git-path(s)

### ISSUE THREAD

**Issue by marshallford** [fluxcd/flux#3036]
**Describe the feature**

Search for `.flux.yaml` files recursively in git-path(s).

**What would the new user story look like?**

In the case where a git repo is by and large raw yaml files and only certain deeply nested folders have manifest generation enabled it's a pain to maintain and sync up a long list of overlapping/deep git paths. For example: `--git-path=foo/bar/baz1,foo/bar/baz3,a/b/c,a/b/c/d/e`. 

As a workaround I have considered created two top level folders under each cluster name (in the example below) called "raw" and "kustomize". This isn't ideal either. If I have two files that are related (both cluster roles) and one is raw and the other is generated I would like to keep them close in the folder structure (sibling folders perhaps), not in an entirely different part of the repo.

Example directory structure:
```
/tmp/some-git-repo
❯ tree -a
.
├── .gitignore
└── config
    ├── cluster
    │   └── cluster-foo
    │       └── prod
    │           ├── applications
    │           │   ├── istio
    │           │   │   └── foobar.yaml
    │           │   └── some-app
    │           │       └── baz.yaml
    │           └── policy
    │               └── constraint-templates
    │                   └── pod-security-policy
    │                       ├── .flux.yaml
    │                       └── kustomization.yaml
    └── common
        └── prod
            └── rbac
                └── admin.yaml
```

```
helm upgrade -i --atomic flux fluxcd/flux --namespace fluxcd --version "1.3.0" -f flux-overrides.yaml --set git.path="config/common/$CLUSTER_ENV\,config/clusters/$CLUSTER_NAME/$CLUSTER_ENV"
```

**How would the new interaction with Flux look like?**

No changes in interaction. Perhaps a new flag for recursive search would be needed if there are edge cases that break backwards compatibility?

**Expected behavior**

Find deeply nested `.flux.yaml` files **like** the path was explicitly defined in `--git-path`.

**Comment by aaron-trout** [comment]
Ahhh, this explains a lot! Just been banging my head against the desk trying to get manifest generation working! The docs do not make it very clear that the `.flux.yaml` *must* live at the root of your repo (or whatever you specified in `--git-path`).

I would very much like this feature too! We have a fairly substantial gitops repo already containing plain manifests (including `HelmRelease` objects), but I want to use kustomize for one specific application (kubeflow, since they only provide kustomize manifests not helm charts). It would be quite annoying to have to maintain a `.flux.yaml` right at the top of the tree for this purpose.

**Comment by marshallford** [comment]
Sounds like we have similar use cases. For others that stumble onto this issue, this part of the docs is the crucial bit:

> With manifest generation enabled, fluxd will look for processing instructions in a file .flux.yaml, which can be located at the target path, or in a directory above it in the git repository.

**Comment by kingdonb** [comment]
Please let me know if you still need help with this. I apologize for the staleness of this reply, we are in the process of cleaning up stale issues from the Flux v1 repo now, this should be over soon.

I will close the issue for now as it is stale. Flux v1 remains in maintenance mode.

We can provide support to Flux v1 users especially with respect to migrating to the new Flux version, which has some breaking changes but is also a total rewrite and also brings many improvements. I'm closing the issue but you are most welcome to write back on this issue, or open another issue. Thanks for using Flux.
