### ISSUE TITLE
Unable to install Fluxctl on WSL

### ISSUE THREAD

**Issue by Zauxst** [fluxcd/flux#3037]
**Describe the bug**
Because snapd is not supported on WSL, I cannot install fluxctl to further install it on a K8s Cluster.

**To Reproduce**
Open WSL, install snap and snapd, try to install/search for fluxctl

It would be helpful if we have some binaries to install Flux locally, bypassing snap alltogether.

**Comment by hiddeco** [comment]
https://docs.fluxcd.io/en/stable/references/fluxctl/#binary-releases

**Comment by Zauxst** [comment]
Silly me... Thanks.
