### ISSUE TITLE
Flux cannot auth when OIDC provider enabled in EKS

### ISSUE THREAD

**Issue by mariusmitrofan** [fluxcd/flux#3040]
**Describe the bug**

AWS has released a few months ago the OIDC provider for EKS and has since updated its SDK to include the authorization chain automatically for it.

Unfortunately, either Flux goes around the AWS auth by doing some "weird" auth mechanism, or the SDK for AWS has yet to be properly updated.

PS: The "new" (and correct way) to fetch a session in GO AWS SDK is to now use session.NewSession instead of session.New as per the documentation ->

DEPRECATED -> https://docs.aws.amazon.com/sdk-for-go/api/aws/session/#New 
CORRECT -> https://docs.aws.amazon.com/sdk-for-go/api/aws/session/#NewSession

```
Deprecated: Use NewSession functions to create sessions instead. NewSession has the same functionality as New except an error can be returned when the func is called instead of waiting to receive an error until a request is made.
```

Steps to reproduce the behaviour:
Normal Flux install using helm connected to an AWS ECR repository.

**Expected behavior**

AWS is able to log in

**Logs**

{"caller":"aws.go:104","component":"aws","exclude-ids":"[123]","include-ids":"[OBFUSCATED_ACCOUNT_ID]","info":"restricting ECR registry scans","regions":"[eu-west-1]","ts":"2020-05-01T10:44:25.322069354Z"}
{"caller":"main.go:534","err":"EC2MetadataRequestError: failed to get EC2 instance identity document\ncaused by: RequestError: send request failed\ncaused by: Get http://169.254.169.254/latest/dynamic/instance-identity/document: dial tcp 169.254.169.254:80: connect: connection refused","error":"AWS API required (due to --registry-require=ecr), but not available","ts":"2020-05-01T10:44:25.322124214Z"}

**Additional context**

- Flux version: 1.19.0
- Kubernetes version: 1.15.0
- Git provider: gitlab
- Container registry provider: ECR

**Comment by mariusmitrofan** [comment]
Clarifications:

* How OIDC out-of-the-box-provider basically replaced Kube2IAM -> https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html

* How to create an OIDC provider for EKS -> https://eksworkshop.com/beginner/110_irsa/oidc-provider/

* How to assume role with web identity -> https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role-with-web-identity.html

**Comment by juanpmarin** [comment]
@mariusmitrofan have you figured out a way to fix the issue?

**Comment by kingdonb** [comment]
I would be happy to review a PR, if there is anyone who has encountered this issue and can work around it.

I have not encountered this issue myself

**Comment by mariusmitrofan** [comment]
I forgot to update, BUT the problem appears only when the cluster is switched from no-oidc (aka kube-2-iam or simple ecr credentials on the node) to oidc.

This is not happening on new cluster.

So I don't think it's a flux error after all...
