### ISSUE TITLE
Filters (glob, regexp etc.) seemingly cannot contain a space after the colon

### ISSUE THREAD

**Issue by anlutro** [fluxcd/flux#3041]
This is either a bug in code or in documentation.

Judging by [this documentation](https://docs.fluxcd.io/en/1.19.0/references/helm-operator-integration/#annotations), `glob: foo-*` should be a valid filter.

However, I just spent an hour debugging Flux when the solution turned out to be changing `glob: foo-*` to `glob:foo-*`.

I quickly glanced over the code and didn't see any trimming of whitespace going on in `pattern.go` so I suppose this is just something that snuck into documentation.

It would be nice to support using spaces like this, though.

**Comment by circa10a** [comment]
@anlutro docs were updated
