### ISSUE TITLE
Should I not expect garbage collection when removing a dir from --git-path ?

### ISSUE THREAD

**Issue by MikaelElkiaer** [fluxcd/flux#3043]
**Describe the bug**

Updating --git-path to an additional directory correctly adds the resources in the newly added dir.
However, removing the additional directory does not result in garbage collection (cleanup/pruning) of the now-missing resources.

**To Reproduce**

Steps to reproduce the behaviour:

1. Start up flux with the --git-path parameter set, e.g.: `main_dir/existing_subdir`
2. Update flux, adding an additional dir to --git-path, e.g.: `main_dir/existing_subdir\\,main_dir/additional_dir`
3. Update flux again, removing the additional dir (reverting to step 1).

**Expected behavior**

Flux removes all resources that were contained in the `main_dir/additional_dir` path - similar to what happens when you remove a dir containing resources from an included path.

**Logs**

No logs, as nothing is happening. :)

**Additional context**

- Flux version: 1.19.0
- Kubernetes version: 1.17.2+k3s1
- Git provider: GitLab CE 12.x
- Container registry provider: Docker Hub

**Comment by stefanprodan** [comment]
Have you enabled garbage collection?

**Comment by MikaelElkiaer** [comment]
> Have you enabled garbage collection?

Important detail I suppose - but yes I have.

**Comment by jtnz** [comment]
I can confirm we have the same problem. Garbage collection works as expected otherwise, but if you remove a monitored directory it won't tidy up the resources from the removed directory.

**Comment by hiddeco** [comment]
This is expected behaviour, as described in the table on the documentation page: https://docs.fluxcd.io/en/1.19.0/references/garbagecollection/

**Comment by jtnz** [comment]
Ah, I feel like I've even read that at some point. Thanks for pointing it out :+1:

**Comment by MikaelElkiaer** [comment]
> This is expected behaviour, as described in the table on the documentation page: https://docs.fluxcd.io/en/1.19.0/references/garbagecollection/

Thanks for clarifying.

In order to manually clear removed dirs, I'll probably do something along the lines of:
```
fd yaml $REMOVED_DIR | xargs cat | yq -r '(.kind)+"/"+(.metadata.name)' | xargs kubectl delete
```
