### ISSUE TITLE
fluxd api documentation

### ISSUE THREAD

**Issue by vvbogdanov87** [fluxcd/flux#3045]
I'm working on the integration of flux with Jenkins(I'm using Active Choices plugin to select a workload and an image). I can't find API documentation(like swagger or something similar). I have to go through the code in order to understand fluxd interface(https://github.com/fluxcd/flux/blob/master/pkg/http/transport.go and client packages). But it is time-consuming. Where can I find API docs?

**Comment by mtmn** [comment]
This would be highly appreciated - I have similar use-case as the reporter.

**Comment by dholbach** [comment]
This was requested in #1069 already.
