### ISSUE TITLE
failed to determine sync action for release: status 'failed' of release does not allow a safe upgrade

### ISSUE THREAD

**Issue by marclamberti** [fluxcd/flux#3050]
**Describe the bug**

Even after updating my release from Helm, I still got the message:
failed to determine sync action for release: status 'failed' of release does not allow a safe upgrade
It's like flux is stuck in this state

**To Reproduce**

Just pushed an error in my manifest:
`ime\\\":\\\"2020-05-10T14:30:41Z\\\",\\\"reason\\\":\\\"ProgressDeadlineExceeded\\\",\\\"message\\\":\\\"ReplicaSet \\\\\\\"pro-web-565777bcb7\\\\\\\" has timed out progressing.\\\"}]}}\": v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects \" or n, but found t, error found in #10 byte of ...|,\"value\":true}],\"env|..., bigger context ...|me\":\"MY_EMV_VAR\",\"value\":true}],\"envFrom\":[{\"configMapRef\":{\"name\":\"prog-|..." action=upgrade`
and then I got flux stuck in this state

**Expected behavior**

Well, I expect to have Flux getting sync with my latest update on the repo

**Logs**

If applicable, please provide logs of `fluxd`. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs deploy/flux  -n flux`.

**Additional context**

- Flux version: 1.19.0
- Kubernetes version: 1.16
- Git provider: Github
- Container registry provider: ECR

**Comment by marclamberti** [comment]
Related to Helm sorry

**Comment by hiddeco** [comment]
https://docs.fluxcd.io/projects/helm-operator/en/stable/faq/#a-helmrelease-is-stuck-in-a-failed-release-state-how-do-i-force-it-through
