### ISSUE TITLE
Flux  unable to pull from the GitHub repository

### ISSUE THREAD

**Issue by chakilams** [fluxcd/flux#3056]
flux unable to clone the GitHub repository, says public key permission denied.

kubectl logs -f flux-7fb55644d7-dwp7q -n flux
Flag --git-verify-signatures has been deprecated, changed to --git-verify-signatures-mode, use that instead
ts=2020-05-12T18:16:23.24711247Z caller=main.go:259 version=1.19.0
ts=2020-05-12T18:16:23.247152282Z caller=main.go:412 msg="using kube config: \"/root/.kube/config\" to connect to the cluster"
ts=2020-05-12T18:16:23.305785897Z caller=main.go:492 component=cluster identity=/etc/fluxd/ssh/identity
ts=2020-05-12T18:16:23.306050806Z caller=main.go:493 component=cluster 
ts=2020-05-12T18:16:23.306170235Z caller=main.go:498 host=https://10.98.0.1:443 version=kubernetes-v1.14.10-gke.27
ts=2020-05-12T18:16:23.306330752Z caller=main.go:510 kubectl=/usr/local/bin/kubectl
ts=2020-05-12T18:16:23.313682217Z caller=main.go:527 ping=true
ts=2020-05-12T18:16:23.316402838Z caller=main.go:666 url=ssh://git@github.com/chakilams/flux-get-started user="Weave Flux" email=support@weave.works signing-key= verify-signatures-mo
de=none sync-tag=flux-sync state=git readonly=false registry-disable-scanning=false notes-ref=flux set-author=false git-secret=false sops=false
ts=2020-05-12T18:16:23.316610961Z caller=main.go:772 upstream="no upstream URL given"
ts=2020-05-12T18:16:23.317231842Z caller=main.go:795 addr=:3030
ts=2020-05-12T18:16:23.343130621Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-05-12T18:16:23.343370479Z caller=images.go:27 component=sync-loop msg="no automated workloads"
ts=2020-05-12T18:16:23.34352121Z caller=loop.go:107 component=sync-loop err="git repo not ready: git repo has not been cloned yet"
ts=2020-05-12T18:16:23.620600229Z caller=checkpoint.go:24 component=checkpoint msg="up to date" latest=1.19.0

**To Reproduce**

Steps to reproduce the behaviour:

1. Installed flux on GKE using helm as per the instructions laid out in the official flux documentation for helm
2. https://github.com/chakilams/flux-get-started/

**Expected behavior**

flux should be able to connect to GitHub and replicate the cluster status

**Logs**
gcppractice_devops@cloudshell:~ (practice2020)$ kubectl -n flux logs deployment/flux -f
Flag --git-verify-signatures has been deprecated, changed to --git-verify-signatures-mode, use that instead
ts=2020-05-12T18:16:23.24711247Z caller=main.go:259 version=1.19.0
ts=2020-05-12T18:16:23.247152282Z caller=main.go:412 msg="using kube config: \"/root/.kube/config\" to connect to the cluster"
ts=2020-05-12T18:16:23.305785897Z caller=main.go:492 component=cluster identity=/etc/fluxd/ssh/identity
ts=2020-05-12T18:16:23.306050806Z caller=main.go:493 component=cluster
ts=2020-05-12T18:16:23.306170235Z caller=main.go:498 host=https://10.98.0.1:443 version=kubernetes-v1.14.10-gke.27
ts=2020-05-12T18:16:23.306330752Z caller=main.go:510 kubectl=/usr/local/bin/kubectl
ts=2020-05-12T18:16:23.313682217Z caller=main.go:527 ping=true
ts=2020-05-12T18:16:23.316402838Z caller=main.go:666 url=ssh://git@github.com/chakilams/flux-get-started user="Weave Flux" email=support@weave.works signing-key= verify-signatures-mo
de=none sync-tag=flux-sync state=git readonly=false registry-disable-scanning=false notes-ref=flux set-author=false git-secret=false sops=false
ts=2020-05-12T18:16:23.316610961Z caller=main.go:772 upstream="no upstream URL given"
ts=2020-05-12T18:16:23.317231842Z caller=main.go:795 addr=:3030
ts=2020-05-12T18:16:23.343130621Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-05-12T18:16:23.343370479Z caller=images.go:27 component=sync-loop msg="no automated workloads"
ts=2020-05-12T18:16:23.34352121Z caller=loop.go:107 component=sync-loop err="git repo not ready: git repo has not been cloned yet"
ts=2020-05-12T18:16:23.620600229Z caller=checkpoint.go:24 component=checkpoint msg="up to date" latest=1.19.0
ts=2020-05-12T18:21:23.343634696Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-05-12T18:21:23.343698294Z caller=images.go:27 component=sync-loop msg="no automated workloads"
ts=2020-05-12T18:21:23.343997326Z caller=loop.go:107 component=sync-loop err="git repo not ready: git clone --mirror: fatal: Could not read from remote repository., full output:\n Cl
oning into bare repository '/tmp/flux-gitclone441136455'...\ngit@github.com: Permission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you h
ave the correct access rights\nand the repository exists.\n"

**Additional context**

- Flux version: latest
- Kubernetes version:
Client Version: v1.18.2
Server Version: v1.14.10-gke.27
- Git provider:GitHub
- Container registry provider:NA

**Comment by circa10a** [comment]
@chakilams Please review the [documentation](https://docs.fluxcd.io/en/1.19.0/tutorials/get-started-kustomize/#setup-github-write-access) for adding the flux ssh key to your GitHub repo.

[More on deploy keys](https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys)

**Comment by kingdonb** [comment]
Closing.
