### ISSUE TITLE
Cannot override the value of --registry-cache-expiry

### ISSUE THREAD

**Issue by mshasib** [fluxcd/flux#3059]
I am using the latest version of flux and I set the value of --registry-cache-expiry to 5m. But it seems that registry cache still refreshes after 1 hour.

**Comment by circa10a** [comment]
I think that's the intent according to this:
https://github.com/fluxcd/flux/blob/master/cmd/fluxd/main.go#L203

**Comment by mshasib** [comment]
@circa10a I understand that it was deprecated. However, I still want to disable the cache or set expiration to a defined value. The documentation does not say what the default is and there is no explanation on what "expired adaptively" means.

**Comment by pwithams** [comment]
This gives a bit more information about the adaptive scheme and reasons for deprecating the option: https://github.com/fluxcd/flux/commit/847ef25a0af9262e634fe41dcab3cc2d8f44ef79

**Comment by kingdonb** [comment]
Closing. Thanks for using Flux!
