### ISSUE TITLE
Implement --k8s-disallow-namespace

### ISSUE THREAD

**Issue by max-lobur** [fluxcd/flux#3064]
**Describe the feature**
This is coming from a https://github.com/fluxcd/flux/issues/1677#issuecomment-621315356 

**What would the new user story look like?**
It's very inconvenient to keep whitelist of namespaces up-to-date due to dynamic nature of our clusters, so we'd like to maintain blacklist instead.
Unfortunately, I can't do this on clusterrole level because there is no Deny rules, so hopefully will be able to do on flux level.

**Expected behavior**
--k8s-disallow-namespace accepts a list of namespaces denied to touch

**Comment by benyanke** [comment]
We could also use this.

**Comment by kingdonb** [comment]
Please let me know if you still need help with this. I apologize for the staleness of this reply, we are in the process of cleaning up stale issues from the Flux v1 repo now, this should be over soon.

Although I can still review and accept some pull requests, there is little labor effort available to develop the Flux v1 codebase and are no new features being added to Flux v1 daemon and this is generally critical fixes only situation at this point. Flux v2 has documentation supporting real RBAC and is probably better for this use case. All users are recommended to upgrade!

I will close the issue for now as it is stale, and the likelihood is low that you are still waiting for our response. Please feel free to respond, we hope you are able to upgrade to Flux v2, but Flux v1 remains in maintenance mode.

We can provide support to Flux v1 users especially with respect to migrating to the new Flux version, which has some breaking changes but is also a total rewrite and also brings many improvements. I'm closing the issue but you are most welcome to write back on this issue, or open another issue. Thanks for using Flux.
