### ISSUE TITLE
Support Azure managed identities to check Images+Charts from ACR

### ISSUE THREAD

**Issue by ivanthelad** [fluxcd/flux#3065]
**Describe the feature**
Flux should the support the usage of Azure managed identities. Today flux relies on /etc/kubernetes/azure.json for its ACR credentials. In AKS clusters with managed identities enabled flux will fail as the identity in this file no longer has rights on ACR. 
 a workaround today is fix this a user needs to set the secret value "registry.acr.secretName" 

https://docs.microsoft.com/en-us/azure/aks/use-managed-identity

**What would the new user story look like?**
Managed identity aks clusters generate a managed identity for the kublet. this identity is used to pull images from a target ACR.   
- 
- Create a new managed identity (not sure if using exisiting one would be recommend). 
-Pass new identity to flux chart/deployment 
-user AAD pod identity to retrieve pull token from ACR
pod identity 
https://github.com/Azure/aad-pod-identity
Login with Identity 
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication-managed-identity#use-the-identity-to-access-the-registry

**Expected behavior**
ACR login and check are no longer performed by the cluster SP but instead controlled using a user assigned identity

**Comment by UnwashedMeme** [comment]
Few research points for whoever comes along next.  I spent an hour going down the rabbit hole; I don't think the implementation will be that hard but is more than I have time for at the moment.

* I think this is the area in flux to edit: https://github.com/fluxcd/flux/blob/master/pkg/registry/azure.go#L19 --  First impression is that instead of reading from the json file we would get the same token from the MSI provider and return that instead
* using the API:
   * The [go sdk](https://docs.microsoft.com/en-us/azure/developer/go/azure-sdk-authorization#use-an-authentication-client) has some helpers
   * [How managed identities for Azure resources work](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-managed-identities-work-vm) has some details on what's happening under the hood.

I don't think the aad-pod-identity would change the implementation it just gives better control and security of access to the MSIs. Can anyone confirm this?

**Comment by jgalliers** [comment]
This is high priority for us as we cannot use Flux in our managed AAD clusters, which is breaking our plans to use Flux widely. 

Azure is going to push this feature quite hard as it allows automated rollouts without all the crazy MS Graph integrations we needed previously.

Can we get an idea of timelines please?

**Comment by cloudpea** [comment]
@jgalliers Flux does give the option to read SPN credentials from a kubernetes secret. We are syncing an azure.json file from a keyvault secret using Azure KeyVault CSI Secret Store Provider to a kubernetes secret and then flux is authenticating to the acr via that. This has allowed us to enable the MSI feature on our AKS clusters hope this helps!

**Comment by mickeahlinder** [comment]
@claudeleveille Cloud you please elaborate on how you manage to authenticate as the MSI created for the AKS cluster using a custom azure.json, more specifically how do you manage to get the value for aadClientSecret that I presume by looking at the GO code is required? Or are you using a completely different SPN that is manually created for just this purpose?

**Comment by cloudpea** [comment]
@mickeahlinder 

Ware creating a separate SPN for flux with AcrPull permissions on the ACR. We then add a secret to an Azure keyvault with the same content as the azure.json file containing the new SPN creds.

The keyvault secret is then synced in to the cluster as a kubernetes secret where flux reads the SPN creds from to authenticate.

Although this doesn’t allow flux to authenticate with an MSI it does allow us to move to MSI enabled AKS clusters. Hope that makes sense!

**Comment by mickeahlinder** [comment]
@cloudpea Alright, thank you for your very swift response. Yeah, makes perfect sense then, I was a little bit confused by your last statement mentioning you then were able to enable the MSI feature on the cluster as like you were authenticating using that SPN.
But a separate SPN explains it all, thank you!

**Comment by hieumoscow** [comment]
Hi team, is there a plan for this feature as Managed Identity is now our goto deployment option for AKS in most scenario.

**Comment by bpoudel1210** [comment]
> @mickeahlinder
> 
> Ware creating a separate SPN for flux with AcrPull permissions on the ACR. We then add a secret to an Azure keyvault with the same content as the azure.json file containing the new SPN creds.
> 
> The key vault secret is then synced into the cluster as a Kubernetes secret where flux reads the SPN creds from to authenticate.
> 
> Although this doesn’t allow flux to authenticate with an MSI it does allow us to move to MSI enabled AKS clusters. Hope that makes sense!

@cloudpea 
As you suggested, I created a new SP which has AcrPull  permission on the ACR and created a Kubernetes secret same content as the azure.json. I am still error. `s=2020-11-09T20:21:47.515407149Z caller=warming.go:180 component=warmer canonical_name={acr_name}/{Image_name} auth={map[]} err="requesting tags: Get https://{acr_name}/v2/{Image_name}/tags/list: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information."`
I added below config in `flux.yaml`:

      volumes:
      - name: acr-credentials
        secret:
          secretName: acr-secret


        volumeMounts:
        - name: acr-credentials
          mountPath: /etc/acr
        readOnly: true

```
Do you think if I have missed anything?

**Comment by cloudpea** [comment]
@bpoudel1210 have you updated the registry.acr.hostPath helm value to your new mountpoint (/etc/acr/azure.json)?

**Comment by bpoudel1210** [comment]
> @bpoudel1210 have you updated the registry.acr.hostPath helm value to your new mountpoint (/etc/acr/azure.json)?

Thank you for the quick response. We are not using helm to install flux. We are using deployment YAMLs.

**Comment by bpoudel1210** [comment]
@cloudpea It looks like mountpoint must be `/etc/kubernetes/`. Now its working.
```
volumes:
  - name: acr-credentials
    secret:
      secretName: acr-secret


    volumeMounts:
    - name: acr-credentials
      mountPath: /etc/kubernetes/
    readOnly: true
```

**Comment by kingdonb** [comment]
This use case (AAD + managed identity authentication) is well-documented in Flux v2, https://toolkit.fluxcd.io/guides/image-update/#generating-tokens-for-managed-identities-short-lived

If there is anything missing from the docs there, we will appreciate it if you can contribute or complain about the problems that you find! I am not sure of the state of AAD support in Flux v1 after reading the history of this issue.

I am going to close this, as Flux v2 (the complete rewrite) has reached the long-awaited Feature Parity release and we are now recommending all users who are able to upgrade to read the Flux v2 documentation, and test out their use cases.

If you are not able to upgrade for some reason, we are interested in that and we want to support you. Please find us in the [discussions page](https://github.com/fluxcd/flux2/discussions) for Flux v2, or join us on the CNCF #flux slack channel.

Thanks for using Flux!

**Comment by stealthybox** [comment]
For anyone using Flux v1, the Deployment/CronJob solutions from the above Flux v2 docs produce an ImagePullSecret.
This is not Flux v2 specific.
Flux v1 can read this ImagePullSecret from your workloads and auth to Azure Container Registry.

You can also use `fluxd`'s `--docker-config` flag.

It's possible that these are the only ways to use Flux v1 with Azure Managed Identities, since it sounds coupled to the JSON credential file.
There are no plans to modify the current `azure.go` provider in v1 `fluxd` going forward.

**Comment by wiebeck** [comment]
@kingdonb I'm having trouble following the steps in https://toolkit.fluxcd.io/guides/image-update/#generating-tokens-for-managed-identities-short-lived. I'm getting the following error in my Flux Kustomize Controller:

```json
{
    "level": "error",
    "ts": "2021-03-03T08:15:42.686Z",
    "logger": "controller.kustomization",
    "msg": "Reconciliation failed after 651.33262ms, next try in 10m0s",
    "reconciler group": "kustomize.toolkit.fluxcd.io",
    "reconciler kind": "Kustomization",
    "name": "flux-system",
    "namespace": "flux-system",
    "revision": "main/efad4586fba93322940dfd838257f77748b09204",
    "error": "kustomize build failed: accumulating resources: 2 errors occurred:\n\t* accumulateFile error: \"accumulating resources from './acr-access': read /tmp/flux-system920041142/clusters/staging/acr-access: is a directory\"\n\t* accumulateDirector error: \"recursed accumulation of path '/tmp/flux-system920041142/clusters/staging/acr-access': accumulating resources: 2 errors occurred:\\n\\t* accumulateFile error: \\\"accumulating resources from 'git@github.com/fluxcd/flux2//manifests/integrations/registry-credentials-sync/azure': open /tmp/flux-system920041142/clusters/staging/acr-access/git@github.com/fluxcd/flux2/manifests/integrations/registry-credentials-sync/azure: no such file or directory\\\"\\n\\t* loader.New error: \\\"git cmd = '/usr/bin/git fetch --depth=1 origin HEAD': exit status 128\\\"\\n\\n\"\n\n"
}
```
I try to improve readability for the `error`:
```
kustomize build failed: accumulating resources: 2 errors occurred:
	* accumulateFile error: "accumulating resources from './acr-access': read /tmp/flux-system920041142/clusters/staging/acr-access: is a directory"
	* accumulateDirector error: "recursed accumulation of path '/tmp/flux-system920041142/clusters/staging/acr-access': accumulating resources: 2 errors occurred:"
	 	* accumulateFile error: "accumulating resources from 'git@github.com/fluxcd/flux2//manifests/integrations/registry-credentials-sync/azure': open /tmp/flux-system920041142/clusters/staging/acr-access/git@github.com/fluxcd/flux2/manifests/integrations/registry-credentials-sync/azure: no such file or directory"
	 	* loader.New error: "git cmd = '/usr/bin/git fetch --depth=1 origin HEAD': exit status 128"
```

My directory structure is:
```
├── clusters
│   └── staging
│       ├── acr-access
│       │   ├── config-patches.yaml
│       │   └── kustomization.yaml
│       └── [...]
```
File `acr-access/kustomization.yaml` is the same as from the link:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- git@github.com/fluxcd/flux2//manifests/integrations/registry-credentials-sync/azure
patchesStrategicMerge:
- config-patches.yaml
```
...and `config-patches.yaml` contains my Azure resource IDs for the managed identity (btw I'm using the Kubelet identity since it already has the `AcrPull` role assignment on my ACR.

Any help is highly appreciated.

**Comment by wiebeck** [comment]
Well, I finally got it working according to the instructions from https://toolkit.fluxcd.io/guides/image-update/#generating-tokens-for-managed-identities-short-lived but I needed to perform some changes:

- I could not get the `git@github.com/fluxcd/...` Kustomization resource to work, so I copied everything under `github.com/fluxcd/flux2/manifests` into my own control repository
- the deployments create resources named `acr-credentials-sync` with an `acr-` name prefix but at some point the sync deployment complained that it cannot find a service account named `credentials-sync` (without prefix). So I commented out the `namePrefix` in `manifests/integrations/registry-credentials-sync/azure/kustomization.yaml`
- the `AzureIdentity` was missing a corresponding `AzureIdentityBinding`. The `mic` pods complained.
- the `credentials-sync` service account wasn't allowed to create secrets so I added a `Role` and `RoleBinding` resource
- the secret mixed up the ACR container name and its token (call to bash method `apply-secret`)

And after all of this: total success!
```
Last Transition Time:     2021-03-03T13:09:03Z          
Message:                  successful scan, found 32 tags
Reason:                   ReconciliationSucceeded
Status:                   True
Type:                     Ready
```

Now on to the actual image updating...

**Comment by chaholl** [comment]
What am I missing? The only approach here that works is to use a separate service principal and create an azure.json via some other mechanism. That kinda defeats the purpose of managed service identity :)

Sure, the credential sync foo above will work for pulling images but it doesn't work when checking for an updated version. I don't see a working solution for v2 either for the same reason.

**Comment by chaholl** [comment]
Yes, I am missing something the `--docker-config` arg

Assuming the above hoops have been jumped through, the next step is to configure fluxd to use the generated creds:

```
... snipped for brevity

volumes:
    - name: acr-credentials
      secret:
        secretName: acr-my-registry
        items:
        - key: .dockerconfigjson
          path: config.json

... snipped for brevity

volumeMounts:                    
  - name: acr-credentials
    mountPath: /etc/fluxd/.docker/
    readOnly: true

... snipped for brevity

args:
   - --docker-config=/etc/fluxd/.docker/config.json
 ```

Would be nice if it just worked without all of this hassle, as it does on AWS and GCP, but such is life

**Comment by kingdonb** [comment]
Thanks for commenting, please open up a discussion on [fluxcd/flux2](/fluxcd/flux2/discussions) if there is something which you think should be improved in Flux 2. This repo is for Flux v1 maintenance and Flux 2 questions cannot be answered here.

**Comment by alxy** [comment]
@wiebeck Have you been able to use flux2 and fetch Helm charts from a `HelmRepository` source linked with an ACR?
Following your tips I was able to make this run and flux creates the kubernetes secrets with the token and username (`00000000-0000-0000-0000-000000000000`) correctly, however, I was not able to use these credentials to authenticate to ACR.

**Comment by wiebeck** [comment]
@alxy No, I'm just pulling regular container images from the ACR. No Helm charts.
