### ISSUE TITLE
Support Sparse Checkouts

### ISSUE THREAD

**Issue by rawkode** [fluxcd/flux#3069]
**Describe the feature**

I'm experimenting with using FluxCD inside of a mono repo to deploy in a GitOps fashion.

This repo has an `apps` directory with the source code for each app in a subsequent directory.

This repo also has a `deploy` directory for the FluxCD and Kustomize files.

When FluxCD clones this in cluster, I only want it working with the deploy directory

The following workflow shows how sparse checkouts work, while still allowing for modifications.

```
git clone git@github.com:rawkode/dotfiles --no-checkout
cd dotfiles
git sparse-checkout set states/terminal/zsh
# Make changes
git commit
git push
```

When using `fluxd`, I'd like to be able to execute something like so:

`fluxd --git-repo git@github.com:app/apps --sparse --path path1 --path path2 --path path3`

**Comment by kingdonb** [comment]
This sounds like a very useful feature, I haven't worked with sparse checkouts before. I am aware of shallow clones, but I actually didn't think a sparse checkout was something git could even do.

Does it actually provide real performance benefits?

I know that Flux v2 has some support for shallow clones, but I do not think I've seen any other proposals for sparse checkout. It makes sense that especially if you are working with a monorepo, this would be an important feature.

At this point with Flux v1 in maintenance mode, I cannot see a path for this feature being added here.

If you have moved on to Flux v2 or not, you may find https://github.com/fluxcd/flux2/discussions is a good place to reopen this question. There is certainly more activity over there than here in the Flux v1 repo at this point.

**Comment by kingdonb** [comment]
Closing, as new features cannot be supported at this time in Flux v1.
