### ISSUE TITLE
Flux not being able to authenticate to a new ACR

### ISSUE THREAD

**Issue by kwontae** [fluxcd/flux#3073]
**Describe the bug**

Changed to a different ACR for image repository and the flux is having an issue retrieving tags from the new acr.

**To Reproduce**

1. Deploy a cronjob via flux
2. change the image endpoint to a new acr and update the imagePullSecrets
3. fluxctl sync
4. fluxctl release update all images for that workload

**Expected behavior**

Flux to pick up the change and start retrieving tags from the new ACR and auto release for new image tags.

**Logs**
```
ts=2020-05-23T00:02:04.536828271Z caller=warming.go:180 component=warmer canonical_name=scepter.azurecr.io/spe/factcollection/scheduler auth="{map[spepperegistry.azurecr.io:<registry creds for 7a9f38ae-29ab-4aef-9901-2787012ba6e5@spepperegistry.azurecr.io, from factcollection:secret/speppeacr>]}" err="requesting tags: Get https://scepter.azurecr.io/v2/spe/factcollection/scheduler/tags/list: unauthorized: authentication required"
```
**Additional context**

I've deployed all ACR secrets (Docker logins) to the namespace of the flux tenant that does deployment of the application.

- Flux version: 1.17.0
- Kubernetes version: 1.16
- Git provider: Github
- Container registry provider: Azure Container Registry

**Comment by asubmani** [comment]
- Are you using the AAD integrated AKS+ACR thingy?
- What is the Authentication mechanism you are using? (SPN, AKS integrated <this one may not work without some tweaks HINT:#aadpodidentity> , or using admin user (similar to regular) or tokens?
- Most likely the issue could be due to your secret (i.e. creds) not having acrpush,acrpull rights on ACR.

NOTE: Flux does not use the logged in users kube config context.

**Comment by kwontae** [comment]
> * Most likely the issue could be due to your secret (i.e. creds) not having acrpush,acrpull rights on ACR.

I already have another deployment that was using this secret to pull and works like expected. So this is definitely not the rbac issue of the secret on ACR

> * Also note that Flux will periodically try to refresh images from all repos that are in the "gitops" dir it needs to sync.

Yes I am aware of this and the error comes from this periodic check because it is still trying to use the old acr secret even though it's from a different acr endpoint.

> 
> **This check does not use the "ImagePullsecret" from the deployment YAML.**
> 
> Your app deployment might be working, just that the "Validate all repos and see if something new exists; piece in Flux's code" might be running into issues.

my app deployment works completely fine. It's when flux tries to pull the tags for automation.

> 
> Another issue I realized was that Flux seems to batch stuff.. so any unrelated error can cause other things to backlog at times.

hmmm Can you elaborate on this?

**Comment by kwontae** [comment]
I've restarted the flux tenant and the memcache and it works now.
