### ISSUE TITLE
Add *persistent* private git host to weaveworks deployment 

### ISSUE THREAD

**Issue by jesusvazquez** [fluxcd/flux#3074]
**Describe the bug**

I'm using Weaveworks fluxcd solution with license. I've configured weave to target a private git server following https://github.com/fluxcd/flux/blob/master/docs/guides/use-private-git-host.md. 
- This required me to edit the weave flux agent deployment myself so that I could overwrite `/root/.ssh/known_hosts`.
- I placed this new deployment version in the flux repository so that flux applies it to himself aswell.
- After applying the deployment it works.

After some time, something reapplies a different deployment version without the ssh known hosts volumes attached and I get `git repo not ready; git clone .... error` errors until I reapply my custom  deployment again.

**Expected behavior**

I don't expect the deployment version of the flux agent to be overwritten by anything, the version I wrote on git should prevail with my changes.

**Logs**

```
ts=2020-05-23T11:18:31.735691259Z caller=loop.go:85 component=sync-loop err="git repo not ready: git clone --mirror: fatal: Could not read from remote repository., full output:\n Cloning into bare repository '/tmp/flux-gitclone925536715'...\nNo ECDSA host key is known for <private-server> and you have requested strict checking.\r\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
```

**Additional context**

- Flux version: 1.13.3
- Kubernetes version: v1.12.7
- Git provider: Self maintained Gitlab

**Comment by jesusvazquez** [comment]
I figured out where "the other" Deployment version comes from. Weave agents runs in a loop where it polls for the configuration from the weave site:
```
time="2020-05-25T07:27:24Z" level=info msg="Updating self from https://get.weave.works/k8s/agent.yaml?instanceID=<instance-id>"
time="2020-05-25T07:27:24Z" level=info msg="Revision before self-update: 4"
time="2020-05-25T07:27:25Z" level=info msg="Revision after self-update: 4"
time="2020-05-25T07:27:26Z" level=info msg="Updating WC from https://cloud.weave.works/k8s.yaml?....
```

The latest curl `https://cloud.weave.works/k8s.yaml?..` returns all the manifests and the agent reapplies them so I lose my deployment configuration.

**I guess the issue then is how can I configure a private git host from weave?**

**Comment by dholbach** [comment]
It looks like this is already tracked in https://github.com/weaveworks/launcher/issues/215
