### ISSUE TITLE
Documentation code formatting issues for Helm "get started" tutorial

### ISSUE THREAD

**Issue by igrybkov** [fluxcd/flux#3082]
**Describe the bug**

There are formatting issues related to code blocks on the Helm tutorial. The code is rendered as markdown instead of being a code. See screenshot for details:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/228986/82859970-eb3fa800-9edd-11ea-98ce-3112e0f370ab.png">

**To Reproduce**

Look at the page: https://docs.fluxcd.io/en/latest/tutorials/get-started-helm/#install-flux

**Expected behavior**

The code should look like a code on this page.

**Logs**

N/A

**Additional context**

N/A

**Comment by dholbach** [comment]
Thanks for letting us know, @igrybkov !
