### ISSUE TITLE
Executing a "release" command returns an exit code of 1

### ISSUE THREAD

**Issue by mshasib** [fluxcd/flux#3089]
**Describe the bug**

When executing a release command, after successful execution, the command exits with a code of 1 indicating an error

**To Reproduce**

Steps to reproduce the behaviour:

1. Run any successfully executing "release" command

**Expected behavior**

On successful execution of a "release" command, the exit code should return a "0" (zero)

**Additional context**

- Flux version: 1.19
- Kubernetes version:
- Git provider:
- Container registry provider:

**Comment by kingdonb** [comment]
Closing. Not enough information to reproduce the error.
