### ISSUE TITLE
KubeConfig file in home dir takes precedence over KUBECONFIG

### ISSUE THREAD

**Issue by jMarkP** [fluxcd/flux#3099]
**Describe the bug**

#2741 added support for the `KUBECONFIG` environment var and deprecates the `--kube-config` command line. When building the rest client, the command line switch still takes precendence it looks like (see [main.go#L411](https://github.com/fluxcd/flux/blob/master/cmd/fluxd/main.go#L411)).

However, the `kube-config` variable takes a default value pointing at the user's home dir and so this will always take precedence over the env var, even if the file in the home dir doesn't exist and the one pointed to by `KUBECONFIG` does.

**To Reproduce**

Steps to reproduce the behaviour:

1. Edit `docker\Dockerfile.flux` to place the default kubeconfig file in a different location :
```
(l50) COPY ./kubeconfig /etc/fluxd/kube/config
```
2. Uncomment the `KUBECONFIG` env in `deploy\flux-deployment.yaml`:
```
        env:
        - name: KUBECONFIG
          value: /etc/fluxd/kube/config
```
3. Run a `make`
4. Deploy with `kubectl apply -f ./deploy`
5. Check the logs

**Expected behavior**

Flux should use the Kube config file specified in the Env var and not error. In fact it still looks for `$HOME/.kube/config`.

I haven't tested it but I presume this will cause suprising behaviour if custom kube config is supplied to the helm chart but flux continues to use the default one baked into the Docker image.

**Logs**

```
/Users/mark/dev/flux % kubectl -n flux logs flux-6db789f5f7-wfqqn
ts=2020-06-02T08:22:55.867387354Z caller=main.go:259 version=kubeconfig-3b40b58d-wip
ts=2020-06-02T08:22:55.867457288Z caller=main.go:412 msg="using kube config: \"/root/.kube/config\" to connect to the cluster"
ts=2020-06-02T08:22:55.867507094Z caller=main.go:421 err="stat /root/.kube/config: no such file or directory"

/Users/mark/dev/flux % kubectl -n flux describe pod flux-6db789f5f7-wfqqn
Name:         flux-6db789f5f7-wfqqn
Namespace:    flux
Priority:     0
Node:         minikube/192.168.64.11
...
    Args:
      --memcached-service=
      --ssh-keygen-dir=/var/fluxd/keygen
      --git-url=git@github.com:fluxcd/flux-get-started
      --git-branch=master
      --git-label=flux-sync
      --git-user=Flux automation
      --git-email=flux@example.com
      --listen-metrics=:3031
...
    Environment:
      KUBECONFIG:  /etc/fluxd/kube/config
    Mounts:
      /etc/fluxd/ssh from git-key (ro)
      /var/fluxd/keygen from git-keygen (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from flux-token-qxzbq (ro)...
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  113s                 default-scheduler  Successfully assigned flux/flux-6db789f5f7-wfqqn to minikube
  Normal   Pulled     23s (x5 over 112s)   kubelet, minikube  Container image "docker.io/fluxcd/flux" already present on machine
  Normal   Created    23s (x5 over 112s)   kubelet, minikube  Created container flux
  Normal   Started    23s (x5 over 112s)   kubelet, minikube  Started container flux
  Warning  BackOff    22s (x10 over 111s)  kubelet, minikube  Back-off restarting failed container
```

**Workaround**
Workaround is to also specify the kube config path on the command line:

```
args:
...
- --kube-config=/etc/fluxd/kube/config
```

This logs a warning but continues successfully

**Additional context**

- Flux version: HEAD of master
- Kubernetes version:
```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Git provider: 
```
% git version
git version 2.21.1 (Apple Git-122.3)
```
- Container registry provider: minikube

**Comment by jMarkP** [comment]
If this is confirmed as a bug I'm happy to work on a fix - think I can see what needs doing.

**Comment by salaxander** [comment]
I've been running into this today too - happy to provide any addition data if I can

**Comment by nfickas** [comment]
Also seeing this issue, any updates?

**Comment by kingdonb** [comment]
If there was a PR for this issue, I missed it in my review. I'm happy to merge a fix for this if one is available.

I'm still doing deep dives into the source code and would really appreciate a pointer to the code that has an issue.

**Comment by kingdonb** [comment]
I see what you're talking about now. Here is the code:

https://github.com/fluxcd/flux/blob/2dc2680d2f6637b57c0c5c532209c53cd3ffdb35/cmd/fluxd/main.go#L209-L218
... runs ahead of the code below... tl;dr: It seems to be true, if either `HOME` is set (or `USERPROFILE`, for Windows), then `fluxd` will look for kube.config in `$HOME/.kube/config` first, regardless of any `KUBECONFIG` variable setting.

https://github.com/fluxcd/flux/blob/2dc2680d2f6637b57c0c5c532209c53cd3ffdb35/cmd/fluxd/main.go#L406-L419
It is too late to change this default behavior now, with Flux v1 in maintenance mode, unless the change is gated behind a feature flag. It looks like if you can at least ensure that `HOME` and `USERPROFILE` are not set, the value for `KUBECONFIG` is then honored. I agree this seems like an unreasonable behavior and I would propose to resolve it by adding a `--kube-config` flag, but:

https://github.com/fluxcd/flux/blob/2dc2680d2f6637b57c0c5c532209c53cd3ffdb35/cmd/fluxd/main.go#L218

...apparently that would be going backwards!

Please try unsetting `HOME` in case this is still affecting anyone. If there is a proposal for how to fix this from anyone with time to implement it, I would consider reviewing it, but I will consider it closed with this workaround for now. Closing.
