### ISSUE TITLE
Flux fails to use existing secret - failed to chmod identity file

### ISSUE THREAD

**Issue by haines** [fluxcd/flux#3110]
**Describe the bug**

After installing Flux with the Helm chart, the pod starts successfully the first time but subsequent pods fail to launch, with the error

```
failed to chmod identity file: chmod /etc/fluxd/ssh/identity: read-only file system
```

It appears that the permission on the file is 0440 rather than 0400:

```console
# ls -la /etc/fluxd/ssh
total 0
drwxrwsrwt    3 root     1337           100 Jun  4 09:30 .
drwxr-xr-x    3 root     root            17 Jun  4 09:31 ..
drwxr-sr-x    2 root     1337            60 Jun  4 09:30 ..2020_06_04_09_30_30.765212260
lrwxrwxrwx    1 root     root            31 Jun  4 09:30 ..data -> ..2020_06_04_09_30_30.765212260
lrwxrwxrwx    1 root     root            15 Jun  4 09:30 identity -> ..data/identity

# ls -la /etc/fluxd/ssh/..data/
total 4
drwxr-sr-x    2 root     1337            60 Jun  4 09:30 .
drwxrwsrwt    3 root     1337           100 Jun  4 09:30 ..
-r--r-----    1 root     1337          2610 Jun  4 09:30 identity
```

**To Reproduce**

Steps to reproduce the behaviour:

We installed from the Helm chart (version 1.3.0). I don't think the values we overrode are relevant but the resulting manifests are here: https://gist.github.com/haines/74979de137ca974d78eb0bed79bd6c8f

After Flux is running, we cannot create new pods:

```console
$ kubectl -n flux rollout restart deployment/flux 
$ kubectl -n flux get pods
NAME                              READY   STATUS             RESTARTS   AGE
flux-57bcb79fdb-qmmwt             1/2     CrashLoopBackOff   3          85s
flux-655df46df-bsg6m              2/2     Running            2          4m19s
flux-memcached-64f7865494-vvgjd   2/2     Running            0          4m19s
```

Note that we have Istio sidecars injected into the pods, hence 2 containers each.

**Expected behavior**

A new Flux pod is created and starts successfully.

**Logs**

```
Flag --git-verify-signatures has been deprecated, changed to --git-verify-signatures-mode, use that instead
ts=2020-06-04T09:06:45.614614427Z caller=main.go:259 version=1.19.0
ts=2020-06-04T09:06:45.614660913Z caller=main.go:284 warning="--git-readonly prevents use of --sync-state=git. Forcing to --sync-state=secret"
ts=2020-06-04T09:06:45.614703115Z caller=main.go:303 warning="configuring any of {git-user, git-email, git-set-author, git-ci-skip} has no effect when --git-readonly is set"
ts=2020-06-04T09:06:45.614757102Z caller=main.go:412 msg="using kube config: \"/root/.kube/config\" to connect to the cluster"
ts=2020-06-04T09:06:45.635959133Z caller=main.go:485 err="failed to chmod identity file: chmod /etc/fluxd/ssh/identity: read-only file system"
```

**Additional context**

- Flux version: 1.19.6
- Kubernetes version: 1.16.8-eks-e16311
- Git provider: GitHub
- Container registry provider: ECR

**Comment by haines** [comment]
Ah - 1337 seems to be a group used by Istio, so that's most likely the culprit - sorry!

**Comment by Sreddy-gs** [comment]
@haines can you let us know how did you fix the issue?. even we installed istio and got the same issue. Thank you !!

**Comment by haines** [comment]
@Sreddy-gs I didn't end up looking in too much depth how to get it working properly with Istio enabled - I just disabled sidecar injection on the `flux` namespace by adding the `istio-injection: disabled` label.
