### ISSUE TITLE
Fluxcd keeps reinstalling helm release

### ISSUE THREAD

**Issue by AlexandreRoba** [fluxcd/flux#3113]
**Describe the bug**
I delete an helm release from the git repository.
Deleted the container image
Deleted the helm release manualy from the cluster
synchronized with fluxctl sync

This Ghost Helm release keeps reinstalling..... out of nowhere.

**To Reproduce**

Steps to reproduce the behaviour:

- Delete the HelmRelease yaml from the git repository.
- Deleted the helm manually.
- Sync flux with Fluxctl sync

**Expected behavior**

I expect the release to be deleted.

**Logs**

If applicable, please provide logs of `fluxd`. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs deploy/flux  -n flux`.

**Additional context**

- FluxCD 1.19.0 
- Kubernetes 1.18.3
- Git provider: Github
- Container registry provider: Scaleway

**Comment by hiddeco** [comment]
You are likely looking for the garbage collection feature which is not enabled by default. Please read https://docs.fluxcd.io/en/1.19.0/references/garbagecollection/ to understand the limitations and how to enable this feature.

For now, to get rid of the image while it already has been removed for Git you will need to remove the `HelmRelease` that is still present on the cluster (and keeps re-installing the Helm chart).

```console
$ kubectl get helmreleases -A
$ kubectl delete helmrelease <name> -n <namespace>
```

**Comment by AlexandreRoba** [comment]
I though that uninstalling the helm chart would be enough. 
Deleting the helmrelease object did stop uninstalling it. 
Thanks a lot for the help. 
Alex.
