### ISSUE TITLE
Invalid revision range after force-pushing to branch

### ISSUE THREAD

**Issue by varac** [fluxcd/flux#3120]
**Describe the bug**

After rebasing and forcepushing to the git branch that flux is configured for, flux complains about an 
`Invalid revision range`, stops working and doesn't recover from this failed state.

**To Reproduce**

Steps to reproduce the behaviour:

1. Install flux via helm:

  `helm upgrade --install --repo "https://charts.fluxcd.io" --namespace oas --version 1.3.0 --set git.url="https://open.greenhost.net/varac/openappstack " --set git.branch="varac" --set git.path="flux" --set git.readonly=true --set registry.excludeImage='*' --set sync.state="secret" --set syncGarbageCollection.enabled=true --set manifestGeneration=true --set git.pollInterval=1h flux flux  `

2. Provide a GitHub repository with Kubernetes manifests: See https://open.greenhost.net/varac/openappstack

3. Rebase the configured git branch and force push

**Expected behavior**

The rebased, force-pushed branch should get checked out without any problem and the flux resources should get applied.

**Logs**

If applicable, please provide logs of `fluxd`. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs deploy/flux  -n flux`.

```
Flag --git-verify-signatures has been deprecated, changed to --git-verify-signatures-mode, use that instead                                                                                                        
ts=2020-06-09T12:51:42.103797283Z caller=main.go:259 version=1.19.0
ts=2020-06-09T12:51:42.103946496Z caller=main.go:303 warning="configuring any of {git-user, git-email, git-set-author, git-ci-skip} has no effect when --git-readonly is set"                                      
ts=2020-06-09T12:51:42.10410687Z caller=main.go:412 msg="using kube config: \"/root/.kube/config\" to connect to the cluster"                                                                                      
ts=2020-06-09T12:51:42.160811998Z caller=main.go:498 host=https://10.43.0.1:443 version=kubernetes-v1.18.3+k3s1                                                                                                    
ts=2020-06-09T12:51:42.161113171Z caller=main.go:510 kubectl=/usr/local/bin/kubectl
ts=2020-06-09T12:51:42.163756801Z caller=main.go:527 ping=true
ts=2020-06-09T12:51:42.170570349Z caller=main.go:666 url=https://@open.greenhost.net/varac/openappstack user="Weave Flux" email=support@weave.works signing-key= verify-signatures-mode=none sync-tag=flux-sync state=secret readonly=true registry-disable-scanning=false notes-ref=flux set-author=false git-secret=false sops=false                                                                                                 
ts=2020-06-09T12:51:42.177066044Z caller=main.go:772 upstream="no upstream URL given"
ts=2020-06-09T12:51:42.179815008Z caller=main.go:795 addr=:3030
ts=2020-06-09T12:51:42.180623224Z caller=loop.go:61 component=sync-loop info="Repo is read-only; no image updates will be attempted"                                                                               
ts=2020-06-09T12:51:42.180929767Z caller=loop.go:107 component=sync-loop err="git repo not ready: git repo has not been cloned yet"                                                                                
ts=2020-06-09T12:51:42.922683297Z caller=checkpoint.go:24 component=checkpoint msg="up to date" latest=1.19.0                                                                                                      
ts=2020-06-09T12:51:50.349362748Z caller=loop.go:133 component=sync-loop event=refreshed url=https://@open.greenhost.net/varac/openappstack branch=varac HEAD=dff92ab3eb73a84ab0f1dd9049eef24da5d08239             
ts=2020-06-09T12:51:50.548001206Z caller=loop.go:107 component=sync-loop err="fatal: Invalid revision range 02f68e40212176ecf0da8955de178f75c5213f98..dff92ab3eb73a84ab0f1dd9049eef24da5d08239, full output:\n fatal: Invalid revision range 02f68e40212176ecf0da8955de178f75c5213f98..dff92ab3eb73a84ab0f1dd9049eef24da5d08239\n"                            
```

`dff92ab3eb73a84ab0f1dd9049eef24da5d08239` is the current HEAD of the branch, whereas `02f68e40212176ecf0da8955de178f75c5213f98` is probably the old HEAD before rebasing.

What makes me wonder is where is the old ref stored, I deleted both flux and flux-memcached pods, I don't understand where a possible state would be stored ?

**Additional context**

- Flux version: 1.19.0
- Kubernetes version: v1.18.3+k3s1
- Git provider: self-hosted gitlab
- Container registry provider: several (doesn't apply here)

**Comment by varac** [comment]
There's also #696 and #859 which are related.

**Comment by varac** [comment]
So sth is really weird here, I changed back the branch to master and the git repo url to the upstream one (https://open.greenhost.net/openappstack/openappstack/), deleted all flux related pods (`kubectl -n oas delete pods -l 'app in (helm-operator, flux, flux-memcached)'`), but flux still complains:

```
root@oas:~# kubectl -n oas logs flux-dd5849c44-zfxpv 
Flag --git-verify-signatures has been deprecated, changed to --git-verify-signatures-mode, use that instead
ts=2020-06-09T14:55:18.366656036Z caller=main.go:259 version=1.19.0
ts=2020-06-09T14:55:18.366810638Z caller=main.go:303 warning="configuring any of {git-user, git-email, git-set-author, git-ci-skip} has no effect when --git-readonly is set"
ts=2020-06-09T14:55:18.366998283Z caller=main.go:412 msg="using kube config: \"/root/.kube/config\" to connect to the cluster"
ts=2020-06-09T14:55:18.417295073Z caller=main.go:498 host=https://10.43.0.1:443 version=kubernetes-v1.18.3+k3s1
ts=2020-06-09T14:55:18.41751348Z caller=main.go:510 kubectl=/usr/local/bin/kubectl
ts=2020-06-09T14:55:18.419152028Z caller=main.go:527 ping=true
ts=2020-06-09T14:55:18.422770359Z caller=main.go:666 url=https://@open.greenhost.net/openappstack/openappstack user="Weave Flux" email=support@weave.works signing-key= verify-signatures-mode=none sync-tag=flux-sync state=secret readonly=true registry-disable-scanning=false notes-ref=flux set-author=false git-secret=false sops=false
ts=2020-06-09T14:55:18.437519917Z caller=main.go:772 upstream="no upstream URL given"
ts=2020-06-09T14:55:18.437849626Z caller=loop.go:61 component=sync-loop info="Repo is read-only; no image updates will be attempted"
ts=2020-06-09T14:55:18.438012705Z caller=loop.go:107 component=sync-loop err="git repo not ready: git repo has not been cloned yet"
ts=2020-06-09T14:55:18.439842592Z caller=main.go:795 addr=:3030
ts=2020-06-09T14:55:19.669361686Z caller=checkpoint.go:24 component=checkpoint msg="up to date" latest=1.19.0
ts=2020-06-09T14:55:26.967553335Z caller=loop.go:133 component=sync-loop event=refreshed url=https://@open.greenhost.net/openappstack/openappstack branch=master HEAD=6810ea7782d810bd45c0c3f32bd63ed7d240eb32
ts=2020-06-09T14:55:27.171488323Z caller=loop.go:107 component=sync-loop err="fatal: Invalid revision range 02f68e40212176ecf0da8955de178f75c5213f98..6810ea7782d810bd45c0c3f32bd63ed7d240eb32, full output:\n fatal: Invalid revision range 02f68e40212176ecf0da8955de178f75c5213f98..6810ea7782d810bd45c0c3f32bd63ed7d240eb32\n"
```

We have the same repo using the master branch configure for flux in exact the same way and there it works fine. What's going on ?

**Comment by ariep** [comment]
Your setup uses `sync.state: secret`, which means that the "high water mark", which tracks up to which git revision flux followed your repo, is stored as an annotation on a Kubernetes secret on your cluster. So even if you removed all flux pods, that piece of information still remains, and it refers to a git commit that flux can probably no longer access.

I'm not sure what the easiest recovery would be. If you can get back the git repo in a state that includes the commit flux knows about, that would be my first bet. Otherwise you could manually change the annotation, though you'd have to think about the commit you replace it with: flux will try to apply the diffs between that commit and the latest one on your branch. If you're OK with a more radical solution, you could also remove everything flux-related, including the secret, and reinstall it.

**Comment by varac** [comment]
Awesome, thanks !
Editing the secret and restarting hte flux* pods afterwards fixed it !

    kubectl -n oas edit secret flux-git-deploy
    kubectl -n oas delete pods -l 'app in (helm-operator, flux, flux-memcached)'

**Comment by varac** [comment]
I still would like that flux would recover from force pushes without manual intervention.

**Comment by kingdonb** [comment]
Flux v1 has issues with force push, especially when using the secret sync-store. That is something I'm coming to understand is a common report in Flux v1. Maybe it can be added to the FAQ. Thanks for the report.

Closing, as it sounds like this was resolved for the submitter. Flux v1 is in maintenance mode and we are recommending all users start upgrading to the completely rewritten and redesigned Flux v2, check out https://toolkit.fluxcd.io for more info!

Thanks for using Flux. 🎶
