### ISSUE TITLE
1.20.0 release?

### ISSUE THREAD

**Issue by groodt** [fluxcd/flux#3162]
**Describe the bug**

It has been a while since there was a release. 3 April.

There have been a number of bug fixes since then and the 1.20.0 milestone appears to be complete. Is it worth cutting a 1.20.0 release, or even a 1.19.1 release?

Is there a reason there hasn't been a new release?

**Comment by arrase** [comment]
And is there a reason to release the version but not upgrade the chart? Chart still at 1.19.0 after the version release
