### ISSUE TITLE
Document links broken

### ISSUE THREAD

**Issue by nikhilbalekundargi** [fluxcd/flux#3165]
**Describe the bug**

Below link for the documents are broken. 

https://docs.fluxcd.io/en/latest/references/fluxyaml-config-files.html

This is the case with all the links which are pointing to latest version of the docs.
 
Attached screenshot for reference.

![image](https://user-images.githubusercontent.com/32267777/85954754-4fe79a00-b997-11ea-9a18-6a56e45e6996.png)

**Comment by dholbach** [comment]
The link you're looking for is https://docs.fluxcd.io/en/latest/references/fluxyaml-config-files/ (without `.html`).

It looks like this is just like #3004 -only that this time it affects URLs with trailing `/`?

**Comment by dholbach** [comment]
OK: https://docs.fluxcd.io/en/latest/missing.html
OK: https://docs.fluxcd.io/en/latest/missing/
BROKEN: https://docs.fluxcd.io/en/latest/missing/
BROKEN: https://docs.fluxcd.io/en/latest/references/fluxyaml-config-files.html

**Comment by nikhilbalekundargi** [comment]
> OK: https://docs.fluxcd.io/en/latest/missing.html
> OK: https://docs.fluxcd.io/en/latest/missing/
> BROKEN: https://docs.fluxcd.io/en/latest/missing/
> BROKEN: https://docs.fluxcd.io/en/latest/references/fluxyaml-config-files.html

https://docs.fluxcd.io/en/latest/missing/ - also broken.

**Comment by kingdonb** [comment]
All of the broken links mentioned in this report appear to have been fixed by a config change related to #3426 – the only one I can see does not work is https://docs.fluxcd.io/en/latest/missing/

I cannot tell if there was ever a doc there, but otherwise these links should all work now, with or without the `.html` extension.
