### ISSUE TITLE
Kustomize  issue - component=sync-loop err="loading resources from repo: duplicate definition

### ISSUE THREAD

**Issue by nikhilbalekundargi** [fluxcd/flux#3166]
**Describe the bug**

Tried to implement kustomize from https://github.com/fluxcd/flux-kustomize-example. 

Forked the repo to my github account.

**To Reproduce**

Steps to reproduce the behaviour:

1. Provide Flux install instructions
helm upgrade -i flux fluxcd/flux --set git.url=git@github.com:nikhilbalekundargi/flux-kustomize-example.git --set manifest-generation=true --set git-path=staging --set syncGarbageCollection.enabled=true --namespace flux --set helm.versions=v3 --wait

2. Provide a GitHub repository with Kubernetes manifests
https://github.com/nikhilbalekundargi/flux-kustomize-example 

forked from https://github.com/fluxcd/flux-kustomize-example. 

**Expected behavior**
pod info should be deployed

**Logs**

```
ts=2020-06-29T11:39:09.815173017Z caller=images.go:27 component=sync-loop msg="no automated workloads"
ts=2020-06-29T11:39:45.025457267Z caller=loop.go:133 component=sync-loop event=refreshed url=ssh://git@github.com/nikhilbalekundargi/flux-kustomize-example.git branch=master HEAD=6afd0470c3e3638e6be049e4cc092f5181cd4f40
ts=2020-06-29T11:39:45.078872121Z caller=sync.go:73 component=daemon info="trying to sync git changes to the cluster" old= new=6afd0470c3e3638e6be049e4cc092f5181cd4f40
ts=2020-06-29T11:39:45.085088452Z caller=loop.go:107 component=sync-loop err="loading resources from repo: duplicate definition of 'demo:deployment/podinfo' (in base/podinfo-dep.yaml and production/flux-patch.yaml)"
ts=2020-06-29T11:44:09.815463121Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-06-29T11:44:09.835403727Z caller=images.go:23 component=sync-loop error="getting unlocked automated resources: duplicate definition of 'demo:deployment/podinfo' (in base/podinfo-dep.yaml and production/flux-patch.yaml)"
ts=2020-06-29T11:44:45.615135015Z caller=sync.go:73 component=daemon info="trying to sync git changes to the cluster" old= new=6afd0470c3e3638e6be049e4cc092f5181cd4f40
ts=2020-06-29T11:44:45.621421577Z caller=loop.go:107 component=sync-loop err="loading resources from repo: duplicate definition of 'demo:deployment/podinfo' (in base/podinfo-dep.yaml and production/flux-patch.yaml)"
ts=2020-06-29T11:44:45.623190679Z caller=loop.go:133 component=sync-loop event=refreshed url=ssh://git@github.com/nikhilbalekundargi/flux-kustomize-example.git branch=master HEAD=6afd0470c3e3638e6be049e4cc092f5181cd4f40
```

**Additional context**

- Flux version: 1.19.0
- Kubernetes version: 
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

- Git provider: Github

**Comment by mikesir87** [comment]
We just ran into this ourselves and found that it was a combination of two things...

1. Make sure you have the manifest generation enabled (`manifestGeneration: true` if using the helm chart)
1. Make sure the `.flux.yaml` file exists and has the right file extension. It doesn't pick up `.flux.yml` 😄

**Comment by Wolfium** [comment]
> 1. manifestGeneration

Great catch @mikesir87, didn't realize and worked like a charm!
Just weird bacuase the .flux.yaml is already including the command updated using kustomize before kubectl apply.
I don't get the relation to this setting which clearly is part of the deployment procedure, where I thought it was only using the command updated output alone.

Thanks in advance for any clarification on that.
Regards

**Comment by kingdonb** [comment]
Manifest generation (`--manifest-generation` or `manifestGeneration`) enables the `.flux.yaml` feature itself. I don't quite understand your question, @Wolfium but I hope that answers it. If the error message was confusing, it is regrettable but this tutorial has been retired now, and development efforts are focused on Flux v2 now.

The Kustomize tutorial made an assumption that if you were reading the Kustomize tutorial, that means you probably weren't using Helm to deploy your Flux. So it provided some instructions about how to enable the feature in Flux, the alternative installation advice is provided in for example the Helm chart's `values.yaml` file, where this option can be enabled for Helm-based flux installations. This could have been explained better, but the good news for support questions and answers is there are now fewer different ways to install Flux v2.

There are at least two other ways to deploy Flux, by `helm template` and by `fluxctl install`, the latter I think being preferred as it is closer to the direction used by Flux v2, with the `flux bootstrap` and `flux install` commands which are similar in form and structure. Happy to answer additional questions if there are any in the #flux channel on CNCF slack, or in the Flux 2 discussions where you can help us testing solutions for the missing "manifest generation" feature of Flux v2.

I'm closing this, but I want to advertise to any Flux v1 users my services to help migrate to the next release. #3433 is open regarding a migration path for users of Flux v1's `.flux.yaml` or `manifestGeneration` feature. Users needed, apply within.

**Comment by Wolfium** [comment]
> Manifest generation (`--manifest-generation` or `manifestGeneration`) enables the `.flux.yaml` feature itself. I don't quite understand your question, @Wolfium but I hope that answers it. If the error message was confusing, it is regrettable but this tutorial has been retired now, and development efforts are focused on Flux v2 now.
> 
> The Kustomize tutorial made an assumption that if you were reading the Kustomize tutorial, that means you probably weren't using Helm to deploy your Flux. So it provided some instructions about how to enable the feature in Flux, the alternative installation advice is provided in for example the Helm chart's `values.yaml` file, where this option can be enabled for Helm-based flux installations. This could have been explained better, but the good news for support questions and answers is there are now fewer different ways to install Flux v2.
> 
> There are at least two other ways to deploy Flux, by `helm template` and by `fluxctl install`, the latter I think being preferred as it is closer to the direction used by Flux v2, with the `flux bootstrap` and `flux install` commands which are similar in form and structure. Happy to answer additional questions if there are any in the #flux channel on CNCF slack, or in the Flux 2 discussions where you can help us testing solutions for the missing "manifest generation" feature of Flux v2.
> 
> I'm closing this, but I want to advertise to any Flux v1 users my services to help migrate to the next release. #3433 is open regarding a migration path for users of Flux v1's `.flux.yaml` or `manifestGeneration` feature. Users needed, apply within.

Hi @kingdonb,

May be I was some vague on giving context on my case.
I had an existing enabled flux repo using manifest generation with kustomize deploying on an existing cluster
Later on, I installed flux in another cluster using same repo and it was not working showing stated error.
Once I read comment on manifest generation I just realized that the new flux instance installed was missing manifest generation config activated.
Once fixed I understood that no matter flux.yaml config already in the repo, if manifest config is not active, it will not pick up kustomize build generation config and so, it will do a simple kubectl apply of manifests configured with each kustomization.yaml.
Not sure but seems to have 2 configs applied to being able to integration kustomize build generation working, first the manifest generation config and also the generator command with kustomize build within the flux,yaml, 
which both combined got me in my wrong config case
why not having the generator command added to flux.yaml would be sufficient to activate manifest generation?
Not sure if manifest generation config does anything else than getting the command update config applied
otherwise if generator command is configured and manifest generation is not active might be would warn you regarding generator command configured but not active because manifest generation is not active.

Last, thanks for the prompt feedback and a great tool.

**Comment by yebyen** [comment]
It sounds like the mode switching behavior from non-manifest generating to manifest-generating was the problem. Probably your cluster had leftover copies of the objects that were installed without Kustomize, then when manifest generation enabled they weren't updated or overwritten, because from Flux's perspective at that point the change cannot be captured as a diff.
