### ISSUE TITLE
Update kustomize to at least version 3.5.5

### ISSUE THREAD

**Issue by asheynkmansafeguard** [fluxcd/flux#3167]
**Describe the bug**

There is a bug in kustomize version 3.5.4 that deletes new lines as part of configMap and Secret generators. See 

https://github.com/kubernetes-sigs/kustomize/issues/2125

Version 3.5.5 of kustomize resolves the issue. Please update flux with new kustomize binary.

**Comment by swade1987** [comment]
We might as well upgrade to v3.6.1 if we are going to upgrade in the next release, surely?

**Comment by asheynkmansafeguard** [comment]
That would work too.

**Comment by stefanprodan** [comment]
Fixed in https://github.com/fluxcd/flux/pull/3088
