### ISSUE TITLE
git repo not ready: git repo has not been cloned yet

### ISSUE THREAD

**Issue by astraldragon** [fluxcd/flux#3171]
**Describe the bug**

- i know there have been previous bugs for this type of error but the solution was to use latest master tag which also didn't seem to work for me
- using 1.19.0 and latest master tag it fails to clone my repo over ssh
- k8s cluster set up using k3s
- i can clone public repo over https fine while shell'd into the pod, can't clone via ssh while in the pod
- i have added the ssh key to the deploy keys with read/write

**To Reproduce**

Steps to reproduce the behaviour:

1. follow install guide using 1.19.0 or latest master tag
2. run install command
3. monitor the pod
4. see that it can't clone the repo
5. https://github.com/astraldragon/flux-get-started

**Expected behavior**

1. be able to clone the repo

**Logs**

```
ts=2020-07-05T00:29:37.895767093Z caller=main.go:259 version=1.19.0
ts=2020-07-05T00:29:37.895839275Z caller=main.go:412 msg="using kube config: \"/root/.kube/config\" to connect to the cluster"
ts=2020-07-05T00:29:37.934128744Z caller=main.go:492 component=cluster identity=/etc/fluxd/ssh/identity
ts=2020-07-05T00:29:37.934184602Z caller=main.go:493 component=cluster identity.pub="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQClyFPsl2BSz5Fmc5h1k5Vi2h5TJBahHw3iSjHO5+ZSWD8GLM9o80Y6zC0kraOl0p/1Sq58L4uqkH3a2i1O3ZcyepHPZdCZHSuR6eBsmkrf2xiGGxNIy6MpHdC9azyjfY
3FU9G8PT80hmxMNuEjnwHJgU1OWCO5Anp/Z4jVIJDWCoUedfWOb3KVSel5L/y0Ijutypi8Oo23EUK7YOkXElpEw3Sq/BF/niNaddQwz4dQ0pHySm225WYbcYmQkXiyk6K1NInxgQlYeJXwI88AG9k2LzIlh39MxG/siH4mLF8GxZseSMpsHqxcJ87eVf5BzFgZjxGG+8OoWqFSxuLQipsr+j6IilAQAEkUwQF+5kPmWcVbM0jluWDah+pOP
llOv7jmNFSCWT3kAfBsN7h3IHhoM+NcPR/QCkhjCIj5PMmYAiiZAowa5yRtVQGjgTKyJ498IrOG4Eh/KVMF6IVuEbeP6txJ+LZKF4UqmgCJ624RWdEIzvOaLXoFyMBCc6ZvRzU= root@flux-655bfb7cd9-tffvh"
ts=2020-07-05T00:29:37.934221918Z caller=main.go:498 host=https://10.43.0.1:443 version=kubernetes-v1.17.3+k3s1
ts=2020-07-05T00:29:37.934270397Z caller=main.go:510 kubectl=/usr/local/bin/kubectl
ts=2020-07-05T00:29:37.934835149Z caller=main.go:527 ping=true
ts=2020-07-05T00:29:37.935989682Z caller=main.go:666 url=ssh://git@github.com/astraldragon/flux-get-started user=astraldragon email=astraldragon@users.noreply.github.com signing-key= verify-signatures-mode=none sync-tag=flux state=git readonly=false r
egistry-disable-scanning=false notes-ref=flux set-author=false git-secret=false sops=false
ts=2020-07-05T00:29:37.936048892Z caller=main.go:772 upstream="no upstream URL given"
ts=2020-07-05T00:29:37.937005561Z caller=main.go:803 metrics-addr=:3031
ts=2020-07-05T00:29:37.937298947Z caller=loop.go:107 component=sync-loop err="git repo not ready: git repo has not been cloned yet"
ts=2020-07-05T00:29:37.937393073Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-07-05T00:29:37.937470854Z caller=images.go:27 component=sync-loop msg="no automated workloads"
ts=2020-07-05T00:29:37.937910336Z caller=main.go:795 addr=:3030
ts=2020-07-05T00:29:38.613084481Z caller=checkpoint.go:24 component=checkpoint msg="up to date" latest=1.19.0
```

If applicable, please provide logs of `fluxd`. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs deploy/flux  -n flux`.

**Additional context**

- Flux version: 1.19.0, also tried latest master tag
- Kubernetes version: v1.17.3+k3s1
- Git provider: github.com
- Container registry provider:

**Comment by irraz** [comment]
I have a same issue, when force manual sync I can see:

```
fluxctl sync --k8s-fwd-ns flux
Error: git repository ssh://git@bitbucket.org/carritustechnology/tol-devops-configuration.git is not ready to sync

Full error message: git fetch --tags origin []: running git command: git [fetch --tags origin]: context deadline exceeded
Run 'fluxctl sync --help' for usage.`

```

To mitigate I deploy versión: fluxcd/flux-prerelease:master-1f0f862b  and --sync-timeout=10m
I read this in another issue...

**Comment by Marx2** [comment]
I'm next with similar problem
I have private GIT repository accessible only via https. I see it clones something, because I've checked /tmp in pod, but it doesn't seem to have "namespaces" subfolder in cloned repo:
```
ts=2020-08-03T08:17:33.564389078Z caller=loop.go:134 component=sync-loop event=refreshed url=https://x.x%40xy.com@github.x.y/team/gitops-test.git branch=master HEAD=2d9814c046a3305b7bb78178d503f6c634d9c59d
ts=2020-08-03T08:22:33.725337649Z caller=sync.go:60 component=daemon info="trying to sync git changes to the cluster" old= new=2d9814c046a3305b7bb78178d503f6c634d9c59d
ts=2020-08-03T08:22:33.744390333Z caller=loop.go:108 component=sync-loop err="loading resources from repo: unable to read root path \"/tmp/flux-working004839179/namespaces\": stat /tmp/flux-working004839179/namespaces: no such file or directory"
ts=2020-08-03T08:22:33.744523902Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-08-03T08:22:33.763599569Z caller=images.go:23 component=sync-loop error="getting unlocked automated resources: unable to read root path \"/tmp/flux-working632717038/namespaces\": stat /tmp/flux-working632717038/namespaces: no such file or directory"
ts=2020-08-03T08:22:33.766156287Z caller=loop.go:134 component=sync-loop event=refreshed url=https://x.x%40xy.com@github.x.y/team/gitops-test.git branch=master HEAD=2d9814c046a3305b7bb78178d503f6c634d9c59d
```

**Comment by kvaps** [comment]
Hi I had the similar error, after a while I found that my coredns pods were crashed, and flux wasn't able to resolve github.com

**Comment by astlock** [comment]
the same here
```
ts=2020-12-22T16:11:28.245150792Z caller=main.go:259 version=1.20.1
ts=2020-12-22T16:11:28.245232952Z caller=main.go:412 msg="using kube config: \"/root/.kube/config\" to connect to the cluster"
ts=2020-12-22T16:11:28.315992473Z caller=main.go:492 component=cluster identity=/etc/fluxd/ssh/identity
ts=2020-12-22T16:11:28.3160425Z caller=main.go:493 component=cluster identity.pub="ssh..."
ts=2020-12-22T16:11:28.316987702Z caller=main.go:498 host=https://10.147.182.155:443 version=kubernetes-v1.16.9-aliyun.1
ts=2020-12-22T16:11:28.317079434Z caller=main.go:510 kubectl=/usr/local/bin/kubectl
ts=2020-12-22T16:11:28.318727134Z caller=main.go:527 ping=true
ts=2020-12-22T16:11:28.319185013Z caller=main.go:666 url=ssh://git@github.com/ORG/ops-repo-io.git user="Weave Flux" email=support@weave.works signing-key= verify-signatures-mode=none sync-tag=ch-v1 state=git readonly=false registry-disable-scanning=true notes-ref=ch-v1 set-author=false git-secret=false sops=false
ts=2020-12-22T16:11:28.319261083Z caller=main.go:772 upstream="no upstream URL given"
ts=2020-12-22T16:11:28.31939696Z caller=main.go:803 metrics-addr=:3031
ts=2020-12-22T16:11:28.389712534Z caller=loop.go:67 component=sync-loop info="Registry scanning is disabled; no image updates will be attempted"
ts=2020-12-22T16:11:28.389821647Z caller=sync.go:51 component=daemon warning="failed to load last-synced resources. sync event may be inaccurate" err="git repo not ready: git repo has not been cloned yet"
ts=2020-12-22T16:11:28.389869286Z caller=loop.go:108 component=sync-loop err="git repo not ready: git repo has not been cloned yet"
ts=2020-12-22T16:11:28.390743821Z caller=main.go:795 addr=:3030
ts=2020-12-22T16:11:29.406947351Z caller=checkpoint.go:24 component=checkpoint msg="up to date" latest=1.20.1
ts=2020-12-22T16:19:40.172422916Z caller=sync.go:51 component=daemon warning="failed to load last-synced resources. sync event may be inaccurate" err="git repo not ready: git clone --mirror: running git command: git [clone --mirror git@github.com:ORG/ops-repo-io.git /tmp/flux-gitclone114229348]: context deadline exceeded"
ts=2020-12-22T16:19:40.172550724Z caller=loop.go:108 component=sync-loop err="git repo not ready: git clone --mirror: running git command: git [clone --mirror git@github.com:ORG/ops-repo-io.git /tmp/flux-gitclone114229348]: context deadline exceeded"
ts=2020-12-22T16:24:40.172664312Z caller=sync.go:51 component=daemon warning="failed to load last-synced resources. sync event may be inaccurate" err="git repo not ready: git fetch --tags origin []: running git command: git [fetch --tags origin]: context deadline exceeded"
ts=2020-12-22T16:24:40.172735363Z caller=loop.go:108 component=sync-loop err="git repo not ready: git fetch --tags origin []: running git command: git [fetch --tags origin]: context deadline exceeded"
ts=2020-12-22T16:29:40.172903509Z caller=sync.go:51 component=daemon warning="failed to load last-synced resources. sync event may be inaccurate" err="git repo not ready: git fetch --tags origin []: running git command: git [fetch --tags origin]: context deadline exceeded"
ts=2020-12-22T16:29:40.172984004Z caller=loop.go:108 component=sync-loop err="git repo not ready: git fetch --tags origin []: running git command: git [fetch --tags origin]: context deadline exceeded"
```
```
 --git-timeout=60s
--sync-timeout=10m
```
After
`--git-timeout=300s`
works like a charm.

**Comment by nitingadekar** [comment]
Facing same issue setting up the fluxcd with gitlab repo. I have installed the k8s cluster using Rancher RKE provisioning. 
Followed the helm method to install the fluxcd deployment. After getting the public key from the logs and adding it to the concerned repo "deploy keys" section, I get below error 
```
Flag --git-verify-signatures has been deprecated, Changed to --git-verify-signatures-mode, use that instead
ts=2021-05-11T05:16:59.946266559Z caller=main.go:259 version=1.22.2
ts=2021-05-11T05:16:59.946313744Z caller=main.go:412 msg="Using kube config: \"/root/.kube/config\" to connect to the cluster"
ts=2021-05-11T05:16:59.969190143Z caller=main.go:492 component=cluster identity=/etc/fluxd/ssh/identity
ts=2021-05-11T05:16:59.969233274Z caller=main.go:493 component=cluster identity.pub="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDizmPGwhYSSuSlbIc3NamgRTMAF26NNL/ip4JaCww0FpgPIukMmg4dEsPl59QNk7raR/Ihi3kAcDZfpoi7aELN3vGGZzbzM15hPntd3zxuvNpCi6Ju1TDvO7BtE1pYDbwrwvQHEsegslL8lRSEPoEWvVfGhWt7jXvaFdZlf5EfUmB6qv2bpJ3Df1Zlash98fha4fjab74f9a48hI9UHAOSDHfEYPPd1LN4HxNwUR7bJgN4yRtxd41/KybxX6qVUb/T3Nkda9HUh4EbDQ1d0yYtfNn+7t6nEzahD8t23X3sr4MStRboa9PcbW2eWTCNzXOE2E0pvH7c1fX8uVpTDzkTsrJpWaSoj+5o8atGpH9CMzoswg891rgMksLnLL2w251e332PjBRnp6S8upfxqqPuawDNfJsLU8lE4w9rUrkiAIL25oYIC00W5JaaSXx25wSQXS9Q232SORVkV70wbyeBAMfv3ruHzbMmvzooegt66qZ+S40y1Ds= root@flux-848c54b8bf-8v2kc"
ts=2021-05-11T05:16:59.969254109Z caller=main.go:498 host=https://10.43.0.1:443 version=kubernetes-v1.17.5
ts=2021-05-11T05:16:59.969297298Z caller=main.go:510 kubectl=/usr/local/bin/kubectl
ts=2021-05-11T05:16:59.97019861Z caller=main.go:527 ping=true
ts=2021-05-11T05:16:59.971464242Z caller=main.go:666 url=ssh://git@gitlab.com/finoptsys/finoptsys-engg/deploy-chart.git user="Weave Flux" email=support@weave.works signing-key= verify-signatures-mode=none sync-tag=flux-sync state=git readonly=false registry-disable-scanning=false notes-ref=flux set-author=false git-secret=false sops=false
ts=2021-05-11T05:16:59.9715117Z caller=main.go:772 upstream="no upstream URL given"
ts=2021-05-11T05:16:59.971586368Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2021-05-11T05:16:59.97203145Z caller=images.go:27 component=sync-loop msg="no automated workloads"
ts=2021-05-11T05:16:59.97207657Z caller=sync.go:54 component=daemon warning="failed to load last-synced resources. sync event may be inaccurate" err="git repo not ready: git repo has not been cloned yet"
```

Suspecting the `upstream="no upstream URL given" ` log, but not able to understand the reason for same. 
Tried increasing the `--git-timeout ` but no help. DNS resolution is working fine as well. 

here is my configuration: 
```
      - args:
        - --log-format=fmt
        - --ssh-keygen-dir=/var/fluxd/keygen
        - --ssh-keygen-format=RFC4716
        - --k8s-secret-name=flux-git-deploy
        - --memcached-hostname=flux-memcached
        - --sync-state=git
        - --memcached-service=
        - --git-url=git@gitlab.com:myorg/myproject/deploy-chart.git
        - --git-readonly=false
        - --git-user=Weave Flux
        - --git-email=support@weave.works
        - --git-verify-signatures=false
        - --git-set-author=false
        - --git-poll-interval=5m
        - --git-timeout=2000s
        - --sync-interval=5m
        - --git-ci-skip=false
        - --automation-interval=5m
        - --registry-rps=200
        - --registry-burst=125
        - --registry-trace=true
        - --registry-include-image=registry.gitlab.com/*
        - --docker-config=/dockercfg/.dockerconfigjson
```

Any help/lead will be appreciated, Thanks in advance.

**Comment by kingdonb** [comment]
`upstream="no upstream URL given"` is not related to your issue, it comes from this parameter which is unlikely to be related to any reason why your repo is not cloning:

```
                upstreamURL = fs.String("connect", "", "Connect to an upstream service e.g., Weave Cloud, at this base address")
```

@nitingadekar I cannot verify that your issue is the same issue, setting `git-timeout` to 2000s and `sync-interval` to 5m seems counter-indicated, but I am not sure that would be a problem, I think the sync interval is the amount of time to wait between successful syncs; I only see like 3s of log messages in your output paste, (can I assume there was nothing else helpful in the output as you arrived at the timeout value of 2000s?)

You would need to make sure you added the deploy key as read-write also, with the parameters you're passing.

Can you perhaps try exec'ing into the flux daemon pod for debugging purposes, and see if there is any issue reaching the git repo from in there?

If it is a network issue, (or practically anything else really,) the error messages may not always be super helpful, things like "context deadline exceeded" are examples of error outputs that don't tell anything other than "it didn't succeed within the timeout"

**Comment by kingdonb** [comment]
I'm going to close this issue because it is stale and has been necro-bumped.

If there is an active issue to report, please feel free to open a new one. I am less likely to see your response on the issue timely if it has been closed, but issues can also be reopened if needed.

**Comment by nitingadekar** [comment]
@kingdonb , Thanks for confirming the error message. My installation is working fine despite of the message `caller=sync.go:54 component=daemon warning="failed to load last-synced resources. sync event may be inaccurate" err="git repo not ready: git repo has not been cloned yet"`  
Maybe the error is misleading, as this error was visible even in the working setup as I confirmed the repo was getting synced and the Helm Release was getting created. 

So either you need to get rid of this error message, or give proper reason for this error.

**Comment by kingdonb** [comment]
If you're experiencing an issue that is similar to an existing issue, open or closed, you can refer to it from your own report. Please still include all relevant information as despite your best assertions to have encountered the same issue, we cannot verify that your issue is the same unless you provide all the details that may have differed which are requested in the issue template.

Some of which may or may not have even been present in the original report that you're responding to.

https://fluxcd.io/support/#stable-flux-repositories-in-maintenance-mode

> `git repo not ready: git repo has not been cloned yet`

@nitingadekar This can be a transient error. If you see it in your logs, but everything is fine, then perhaps your git repo is large and was not able to be cloned before the tick. If there are no problems, and error does not recur, there is nothing to report.

If the error repeats many times, you may need to reconsider the organization of your repo so that it does not take so long for Flux to clone.

I'm sorry, you will have to open a new issue and provide steps to reproduce. I'm not otherwise going to be able to help without a fresh report and all the reproduction information that is required to reproduce your condition. You are welcome to open a new issue, please observe the support policy information regarding best-effort. https://fluxcd.io/support/#i-am-stuck

Re-raising your concerns on an issue that is already closed, makes noise for all other subscribers on an issue even if their report was already resolved. This is why I recommend strongly against necro-bumping an issue report, or responding on an issue that is already closed.
