### ISSUE TITLE
RFI: Flux tag synced to last commit even if helm release was not deployed

### ISSUE THREAD

**Issue by TPX01** [fluxcd/flux#3172]
I have an open question on how the flux sync tag actually works. I've been using Flux in combination with the Helm operator for some months now but it's unclear to me why, when the HelmRelease failed to install the flux tag is still pointing to the last commit.

![image](https://user-images.githubusercontent.com/12391965/86542552-e0cdf080-bf16-11ea-8258-f238fdfb1103.png)

From what I read and see it makes sense as Flux will apply all resource definitions from the repo and will pass an 'event' when a HelmRelease is found.

It is very frustrating though, as when a helm release failed to install..
..the developer is tricked into believing that the changes made were ok
..and rollbacked the repository is not reflecting the real state of the cluster

**Question**
Is it expected behaviour that Flux ignores the helm releases deploy status after the kubernetes resources were applied?

**Comment by stefanprodan** [comment]
Flux has no insight into what it applies on the cluster, they only thing it cares about is if `kubectl apply` succeeded. Flux v2 will support health checks and it will be able to determine if a Deployment/Statefulset/Daemonset/HelmRelease failed, see the GitOps toolkit project for more details https://toolkit.fluxcd.io/components/kustomize/kustomization/#health-assessment

**Comment by TPX01** [comment]
Thanks for the clarification but also for taking you time to answer this @stefanprodan !
