### ISSUE TITLE
Flux image update functionality without GitOps

### ISSUE THREAD

**Issue by michaelgeorgeattard** [fluxcd/flux#3173]
Is it possible to leverage Flux's image tag update functionality without applying resource itself (such as `HelmRelease`) to cluster?

Reasoning is using Flux for it's image tag update functionality + Argo CD for GitOps

**Comment by stefanprodan** [comment]
The image update will be refactored into a dedicated controller part of the GitOps toolkit, see the Flux v2 roadmap for more details https://toolkit.fluxcd.io/roadmap/#flux-image-update-feature-parity

**Comment by michaelgeorgeattard** [comment]
Thanks for the clarification @stefanprodan

**Comment by kingdonb** [comment]
This use case should be possible now.

> Image automation is available as a prerelease.

From the roadmap. Please let us know about your interesting use case and we will be glad to help support this! Not a Flux v1 issue at this point, so, closing.
