### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by axozoid** [fluxcd/flux#3192]
Hi guys, 
While I was going through the docs I found the following issues:

#### Finding 1 
In the [reference](https://docs.fluxcd.io/en/1.20.0/references/), it seems that CSS didn't load.

![image](https://user-images.githubusercontent.com/26317349/87370689-fd2cf580-c5c6-11ea-8099-2f3d3f13632c.png)

Not sure if you're aware of this, just decided to report in any case

#### Finding 2
In the daemon's [`setup and configuration`](https://docs.fluxcd.io/en/latest/references/daemon/) section I think there is a typo in `offers customization though a multitude of flags.`, I believe it should be `through` instead of `though`.

#### Finding 3
In [`Recording user and message with the triggered action`](https://docs.fluxcd.io/en/latest/references/fluxctl/#recording-user-and-message-with-the-triggered-action) section, the sentence 

> If set, the commit author will be customized in the following way:

seems to be referring to nothing, since there is a new section begins straight away:

![image](https://user-images.githubusercontent.com/26317349/87372623-6151b880-c5cb-11ea-9610-5b6d6d3ed0e2.png)

#### Finding 4
Bullet list didn't work in `helm repositories` [section](https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/chart-sources/#helm-repositories):
![image](https://user-images.githubusercontent.com/26317349/87390350-0a101000-c5ec-11ea-9b9a-285bf5fb1dde.png)

P.S. Thanks for the Flux!

**Comment by kingdonb** [comment]
Hi, `references` is not a page, it is just a group heading with other TOC pages on it. Did you find that link from somewhere? As for the rest of these reports I think I can see the issues you've pointed out, I will submit a PR and fix them up. Thanks!

**Comment by kingdonb** [comment]
At this time, we hope you have already begun migration away from Flux v1 / legacy over to the [current version of Flux](https://github.com/fluxcd/flux2).

I've finally gone ahead and fixed these issues in fluxcd/website#467 and meanwhile, we hope you've been able to upgrade to Flux v2, and note that Flux v1 remains in maintenance mode. Bugs with Flux v1 can be addressed as long as it remains in maintenance, according to the plan laid out in the [Flux Migration Timetable](https://fluxcd.io/docs/migration/timetable/). 👍 

Thanks for using Flux.
