### ISSUE TITLE
Is FluxCD "RollBack Automatically" or Manual ?

### ISSUE THREAD

**Issue by prathapar** [fluxcd/flux#3201]
**Describe the bug**
  May i know if FLUXCD , RollBack is automatically when new deployment failed .
  fluxctl is able to sync every 5 min and working properly whenever a new/updated deployment is available.
  However when new/updated deployment failed, it is not rolling back automatically. 
  i have to git  revert manually whenever something faills. please ket me know what is the expected behaviour is manual or automatic,
  
**To Reproduce**
  
Steps to reproduce the behaviour:

1. Provide Flux install instructions
2. Provide a GitHub repository with Kubernetes manifests

**Expected behavior**

**Logs**

If applicable, please provide logs of `fluxd`. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs deploy/flux  -n flux`.
**May i know how to do i check fluxctl logs.** 
**Additional context**

- Flux version: 
  When i check "**fluxctl version**" it says **unversioned**. 
  I have installed Flux 1.20.0
  May i know how do i check the version. ?
- Kubernetes version:
- Git provider:
- Container registry provider:

**Comment by prathapar** [comment]
Can someone please help

**Comment by NekoTashi** [comment]
Im not sure, but i think if you have automatic deployment Flux try to ensure the same state in kubernetes cluster, git repo and your registry. Then, if you try to rollback an application Flux reverts the changes because it ensures that the image tag in git repo is the same as cluster and registry. I see two options: remove auto deployment and change tag in repo or remove image tag container from registry.

**Comment by prathapar** [comment]
thank you Neko for response. 
what am asking is 
1. When flux deploy updated image on top existing deployment.
2, Due to some issue, updated image failed to deploy. 
3. Is Flux rollback automatically to previous state.
 or 
We have to git revert manually?

**Comment by stefanprodan** [comment]
Flux does not rollback not do we consider adding such a feature as the git state can diverge between sync and apply.
