### ISSUE TITLE
Intermittent errors from Flux during synchronisation

### ISSUE THREAD

**Issue by nwv-danvulpe** [fluxcd/flux#3217]
**Describe the bug**

We are seeing intermittent errors from Flux when it synchronises manifests. It happens for <5% of the manifests (see the below graph from Prometheus.

We don't have a consistent way to reproduce it, when it happens the following messages are logged:
```
ts=2020-07-27T10:00:00.771306649Z caller=sync.go:606 method=Sync cmd="kubectl apply -f -" took=268.630315ms err="running kubectl: " output=
```
Here is also a graph from Prometheus showing the flakiness.
<img width="1764" alt="flux-sync-errors" src="https://user-images.githubusercontent.com/64857066/88534248-96183380-cfff-11ea-8a34-3520c5c476fb.png">

**Additional context**

- Flux version: 1.20.0
- Kubernetes version: 1.17

We believe the underlying Go error is hidden by the error wrapping here https://github.com/fluxcd/flux/blob/master/pkg/cluster/kubernetes/sync.go#L601-L604 and adding more information to the error would help us understand why Flux intermittently is failing for some manifests.

**Comment by nwv-danvulpe** [comment]
We've upgrade late last week to `1.20.2` and we've not seen any intermittency since.
This could be related to https://github.com/fluxcd/flux/pull/3246 (we apply CRDs with flux).

I believe we can close this issue. If any intermittency happens again we will have access to the kubectl exit code from the logs and we could investigate more.

**Comment by nwv-danvulpe** [comment]
Spoke too soon, apparently. The flakiness is back and now we have more info from the logs. 
It took about five days since the upgrade of Flux for the intermittent errors to start showing up.

```
method=Sync cmd="kubectl apply -f -" took=223.731064ms err="running kubectl: signal: killed, stderr: "
```

We have flux deployed with a memory limit of 1G and a cpu limit of 1. Occasionally it can get OOMKilled, but normally it consumes less than 100MB of memory. 
The time where the above failure was reported it was rather quiet from a release point of view.

Are there any suggestions about what may have caused the intermittency and how can we further investigate it?

**Comment by nwv-danvulpe** [comment]
Flux was quite stable over the past two weeks and seems that for our usage of it the 2GB max memory limit has made the difference.

Closing as it's not really a bug, more a resource limit problem.

**Comment by laszlocph** [comment]
Had the same issue. 1.20.2 had better error messages as it logged out the signal not just the empty stderr.

Adding more resources fixed the problem.
