### ISSUE TITLE
certificate-authority-data and certificate-authority are clashing when running with external kubeconfig

### ISSUE THREAD

**Issue by MaxRink** [fluxcd/flux#3222]
**Describe the bug**

We are running Cluster-API and are tying to use Flux to do provisioning of Clusters with components like CNIs.
We have two clusters, mgmt and workload, and flux is running in mgmt but with a kubeconfig for workload.
This kubeconfig is cluster-admin.
Each workload cluster has its own CA, thus the kubeconfig contains certificate-authority-data so that the cluster is trusted by kubectl.
Unfortunately Flux also adds certificate-authority via flag to the internal calls of kubectl, which leads to this error and applies failing
```
ts=2020-07-29T15:35:19.265648429Z caller=sync.go:605 method=Sync cmd="kubectl apply -f -" took=44.927395ms err="running kubectl: error: certificate-authority-data and certificate-authority are both specified for demo-ref-2. certificate-authority-data will override." output=
```
**To Reproduce**

Steps to reproduce the behaviour:

1. Install Flux with the helm chart, mount the external kubeconfig and point flux towards it with KUBECONFIG PATH

**Expected behavior**

The applies work and the resources from the git are mirrored.
**Logs**

If applicable, please provide logs of `fluxd`. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs deploy/flux  -n flux`.

**Additional context**

- Flux version: 1.19.0
- Kubernetes version: 1.18.2
- Git provider: GitLab
- Container registry provider: Harbor

**Comment by kingdonb** [comment]
Flux v2 does now address Kubeconfig of a remote cluster and I think this multi-cluster scenario is handled better in the latest version of Flux. If there is still an issue there, please open it against the fluxcd/flux2 repo.

At this time, we hope you have already begun migration away from Flux v1 / legacy over to the [current version of Flux](https://github.com/fluxcd/flux2).

I'm going to close this without action, but we hope you've been able to upgrade to Flux v2 and note that Flux v1 remains in maintenance mode. Bugs with Flux v1 can be addressed as long as we keep it in maintenance mode, according to the plan laid out in the [Flux Migration Timetable](https://fluxcd.io/docs/migration/timetable/). 👍 

Thanks for using Flux.
