### ISSUE TITLE
ECR image polling for multiple regions

### ISSUE THREAD

**Issue by amithapa** [fluxcd/flux#3240]
**ECR image polling for multiple regions**

I have ECR images present in different regions and providing the paramater `registry.ecr.region="us-east-1 us-west-1"` stops scaning all my ECR repository. Providing individual region work's fine.

**To Reproduce**

Steps to reproduce the behaviour:

1. Provide Flux install instructions
```bash
helm upgrade -i flux fluxcd/flux --version 1.4.0 --namespace fluxcd --set git.url=git@git.example.com:amithapa/k8-deployments.git --set git.branch=master --set git.path=dev --set git.email=amithapa@example.com --set git.pollInterval=1m --set registry.automationInterval=1m --set git.user="My Flux" --set dnsConfig.options[0].name=ndots --set dnsConfig.options[0].value="'1'" --set syncGarbageCollection.enabled=true --set registry.includeImage="*dev*" --set registry.ecr.region="us-east-1 us-west-1"
```
**Expected behavior**

Expected behavior is to start polling all the ECR images across the list of regions i have provided as a parameter `registry.ecr.region="us-east-1 us-west-1"`

**Logs**

Following was the only relevent log on ECR and there were no warning or error logs generated.

```bash
ts=2020-08-10T11:41:04.707619181Z caller=aws.go:117 component=aws info="restricting ECR registry scans" regions="[us-east-1 us-west-1]" include-ids=[] exclude-ids="[602401143452 918309763551]"
```

**Additional context**

- Flux version: 1.4.0
- Container registry provider: ECR

**Comment by kingdonb** [comment]
Thank you for the report! As far as I can tell, `registry.ecr.region` is not a list field, and only expects to have one region listed.

Is your cluster multi-region? I would expect to see different clusters hosted in different regions, with the same images mirrored to registries in both regions. Then each Flux v1 instance would only need to list one ECR region, for the region that a cluster is hosted in. If there's something I didn't get, sorry for the confusion.

This is simply misunderstanding about the feature, I think. Closing, Flux doesn't currently support using region field that way.
