### ISSUE TITLE
how to manage shared cluster environment using flux (gitops)

### ISSUE THREAD

**Issue by myvelcn** [fluxcd/flux#3241]
**Describe the feature**
I have k8s cluster which is shared among different team, we need to maintain seperate repo for each application. How to manage this kind of shared cluster environmen using gitops (flux with helm). Each application team should manage their application manifest in the repo and deployed using flux and other team should not have access. how to restrict it.

**Comment by nabadger** [comment]
See https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/introduction/

**Comment by myvelcn** [comment]
> See https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/introduction/

Is this related to my query?  i want to implement flux with helm deployment in shared environment.  5 different team have different project  and manifest. Each should deployment their app using gitops flow and it should be restricted they should not modify others application manifest.

**Comment by kingdonb** [comment]
The current iteration of this guide is at https://github.com/fluxcd/flux2-kustomize-helm-example - showing multiple-environment deployments with Flux and Helm, on the latest version of Flux.

At this time, we hope you have already begun migration away from Flux v1 / legacy over to the [current version of Flux](https://github.com/fluxcd/flux2).

Bugs with Flux v1 can be addressed as long as we keep it in maintenance mode, according to the plan laid out in the [Flux Migration Timetable](https://fluxcd.io/docs/migration/timetable/). 👍 

Thanks for using Flux.
