### ISSUE TITLE
Flux Unable To Resolve Github.com

### ISSUE THREAD

**Issue by dcplaya** [fluxcd/flux#3243]
**Describe the bug**

Flux is unable to resolve `github.com`. When exec inside the flux pod, I am able to do a `nslookup github.com` with no issues but I am unable to ping `github.com`

**To Reproduce**

Steps to reproduce the behaviour:

Install flux using Ansible, below is the shell command Ansible runs to install Flux

```
    fluxctl install --git-user=dcplaya \
    --git-email=dcplaya@users.noreply.github.com \
    --git-url=git@github.com:dcplaya/k8s-gitops \
    --git-branch=master \
    --git-path=cluster \
    --namespace flux | kubectl apply -f -
```

**Expected behavior**

Flux is able to connect to github.com

**Logs**

Running `fluxctl sync` manually 
```
Synchronizing with ssh://git@github.com/dcplaya/k8s-gitops
Revision of master to apply is 19619a4
Waiting for 19619a4 to be applied ...
== Error ==

Error: git repo not ready: git clone --mirror: fatal: Could not read from remote repository., full output:
 Cloning into bare repository '/tmp/flux-gitclone409691078'...
ssh: Could not resolve hostname github.com: Name does not resolve
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


We don't have a specific help message for the error above.

It would help us remedy this if you log an issue at

    https://github.com/fluxcd/flux/issues

saying what you were doing when you saw this, and quoting the message
at the top.
```

Logs from the pod

```
│ ts=2020-08-12T12:15:50.240742543Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"                                                                                    ││ ts=2020-08-12T12:15:50.2407592Z caller=images.go:27 component=sync-loop msg="no automated workloads"                                                                                                              ││ ts=2020-08-12T12:16:37.712460483Z caller=sync.go:51 component=daemon warning="failed to load last-synced resources. sync event may be inaccurate" err="git repo not ready: attempt to push tag: fatal: Could not  ││ read from remote repository., full output:\n ssh: Could not resolve hostname github.com: Name does not resolve\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access r ││ ights\nand the repository exists.\n"                                                                                                                                                                              ││ ts=2020-08-12T12:16:37.712511741Z caller=loop.go:108 component=sync-loop err="git repo not ready: attempt to push tag: fatal: Could not read from remote repository., full output:\n ssh: Could not resolve hostn ││ ame github.com: Name does not resolve\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n" 
```

From the shell inside the pod
```
bash-5.0# nslookup github.com
Server:         10.43.0.10
Address:        10.43.0.10:53

Non-authoritative answer:
Name:   github.com
Address: 192.30.255.112

Non-authoritative answer:
bash-5.0# ping github.com
ping: bad address 'github.com'
bash-5.0#
```
**Additional context**

- Flux version: 1.20.1
- Kubernetes version: 1.18.6
- Git provider: github.com

**Comment by swade1987** [comment]
We have experienced this as well and the only way to fix it seems to be restarting the flux pod.

**Comment by matthaywardwebdesign** [comment]
I've also experienced this, and same as @swade1987 here. @dcplaya You aren't running a cluster with spot instances / pre-emptible nodes by any chance are you?

From what I am seeing it is happening after the `kube-dns` pods are rebooting / new ones are being created.

**Comment by matthaywardwebdesign** [comment]
Also seems similar to #3083

**Comment by dcplaya** [comment]
Except, even after restarting the flux pod, I get the same result (no resolution).  Some times, randomly, it will work but then go right back to no resolving. 

Also, if I shell into flux and remove the `ndots:5` from `resolv.conf`, syncing works great (until the next pod restart)

```
search flux.svc.cluster.local svc.cluster.local cluster.local cluster.home.com
nameserver 10.43.0.10
options ndots:5
```

@matthaywardwebdesign 
No pre-emptible nodes, im running the cluster on my own baremetal. CoreDNS pod is rarely restarted unless I manually force it to restart.

**Comment by dcplaya** [comment]
After pulling out all but about 3 hairs on my head, I have finally figured out what the actual issue was. Luckily for the flux devs, it wasnt a flux issue! But I am detailing what it was in case others have the same problem.

Do NOT, DOOOO NOOOOTTT, enable DNSSEC if you are using Cloudflare as your DNS provider. Apparently, they do some trickery when that is enable and someone does a lookup for a domain you do not explicitly define. If it is enabled, Cloudflare will report a `NOERROR` for ANY subdomain of yours, even if it doesn't exist. I could get a `NOERROR` on a domain such as `weijhlejlhefjlhafgkljharkjh.MyFQDN.com`

If you have DNSSEC enabled, disable it and I also had to run a curl command to manually delete the zone data. Info on how to delete the zone manually is located https://api.cloudflare.com/#dnssec-delete-dnssec-records

The post that lead me to this fix is located https://community.cloudflare.com/t/noerror-response-for-not-exist-domain-breaks-nslookup/173897/2

I am closing this issue since it was not a flux issue. Hopefully it helps someone else!

**Comment by mitsumaui** [comment]
Ran into this one too - however after digging deeper, it was my mistake with how I defined search suffices on the physical interface - thus documenting here for others!

in netplan yaml file:
```
  ethernets:
    ens33:
      dhcp4: no
      addresses:
        - 192.168.1.10/24
      gateway4: 192.168.1.1
      nameservers:
        addresses:
          - 192.168.1.1
        search:
          - .lan
```
I had set the "search" originally to just "lan" without the preceding . - once I updated that to ".lan" and restarted coredns / flux pods it was able to resolve properly!
