### ISSUE TITLE
Deploy helm releases in order

### ISSUE THREAD

**Issue by adasari** [fluxcd/flux#3244]
Hello,

Flux helm operator is used to deploy/sync a helm chart with HelmRelease. 

Consider a scenario where Chart A -> Chart B and Chart C -> Chart B. Is it possible with flux to deploy the charts B, A, C in order ? if this is not possible, this is nice feature to add by adding new CRD with DAG implementation internally.

If i undersand the flux correctly,  it only cares about single chart. Let me know otherwise.

Thanks.

**Comment by adasari** [comment]
Seems HelmReleaseSpec.DependsOn is used to deploying helm releases in order. will try. thanks.

**Comment by stefanprodan** [comment]
@adasari HelmReleases install/upgrade ordering can be configure in Flux v2, see https://toolkit.fluxcd.io/components/helm/helmreleases/#helmrelease-dependencies

@VarroReve for plain manifests this can be done with https://toolkit.fluxcd.io/components/kustomize/kustomization/#kustomization-dependencies

**Comment by joshuaspence** [comment]
@stefanprodan Is Flux v2 in a usable state? The documentation looks very comprehensive but based on the latest release version of the toolkit (v0.0.18) I am guessing that there is still a lot of work todo?
