### ISSUE TITLE
flux-sync label gets incorrectly applied when there is a yaml parse error

### ISSUE THREAD

**Issue by justinkillen** [fluxcd/flux#3245]
**Describe the bug**

When there is a JSON patch that updates a deployment replica count incorrectly as a string instead of an integer, the flux run failes (as expected).  The problem, however, is that the flux-sync label is still applied (not expected).

**To Reproduce**

Steps to reproduce the behaviour:

Introduce a json patch to a Deployment that updates the replica count to a string, e.g.:
[
  {
    "op": "add",
    "path": "/spec/replicas",
    "value": "2"
  }
]

**Expected behavior**

It is expected that when a flux run fails, the flux-sync label is NOT applied to the repo

**Logs**

ts=2020-08-12T00:06:02.799928537Z caller=loop.go:107 component=sync-loop err="loading resources from repo: parsing YAML doc from \"k8s/istio-system/../.flux.yaml\": yaml: unmarshal errors:\n  line 11: cannot unmarshal !!str `2` into int"

**Additional context**

- Flux version: 1.18.0 - fluxcd/flux:1.18.0
- Kubernetes version: 1.15.11 - Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
- Git provider: gitlab
- Container registry provider: AWS ECR

**Comment by kingdonb** [comment]
At this time, we hope you have already begun migration away from Flux v1 / legacy over to the [current version of Flux](https://github.com/fluxcd/flux2). (To be honest, I have seen issues like this crop up in Kustomize with Flux v2 as well, but I am pretty sure that most of the more grievous issues were reduced in some way at least by Kustomize v4 becoming more strict.)

We hope you've been able to upgrade to Flux v2, and note that Flux v1 remains in maintenance mode. Bugs with Flux v1 can be addressed as long as it remains in maintenance, according to the plan laid out in the [Flux Migration Timetable](https://fluxcd.io/docs/migration/timetable/). 👍 

Thanks for using Flux.
