### ISSUE TITLE
flux and/or helm-operator no longer perform automatic image upgrades in flux v1.20 (or helm-operator v1.2.0)

### ISSUE THREAD

**Issue by billimek** [fluxcd/flux#3251]
**Describe the bug**

After upgrading to flux v1.20 & helm-operator 1.2.0, the HelmRelease image update automation doesn't seem to work anymore where it did previously.  Here is an [example HelmRelease annotation](https://github.com/billimek/k8s-gitops/blob/master/default/home-assistant/home-assistant.yaml#L9-L10) which previously worked and doesn't seem to update anymore.

... I already bounced the flux and helm-release pods with no effect.  Is there something I can further explore to understand this change in behavior?

**To Reproduce**

1. Provide Flux install instructions

* `flux` installed with [this helm chart](https://github.com/billimek/k8s-gitops/blob/master/flux/flux/flux.yaml) using [these values](https://github.com/billimek/k8s-gitops/blob/master/flux/flux/flux-values.yaml)
* `helm-operator` installed with [this helm chart](https://github.com/billimek/k8s-gitops/blob/master/flux/helm-operator/helm-operator.yaml) using [these values](https://github.com/billimek/k8s-gitops/blob/master/flux/helm-operator/flux-helm-operator-values.yaml)

2. Provide a GitHub repository with Kubernetes manifests

* https://github.com/billimek/k8s-gitops

**Expected behavior**

When running `flux` version `1.20.0` this behavior works as documented/expected.  See [this flux automation commit with automation working properly](https://github.com/billimek/k8s-gitops//commit/a684ebe42ce6592582a96b5d932a2509d2e62724).  From that same commit sha we see an example HelmRelease with the [annotations informing an automated upgrade](https://github.com/billimek/k8s-gitops/blob/a684ebe42ce6592582a96b5d932a2509d2e62724/default/node-red/node-red.yaml#L9-L10) which obviously worked.

The expected behavior is that this automation continue to work in `flux` version `1.20.1` (also `helm-operator` version `1.2.0`)

`fluxctl list-images` suggests that there is a new image ready to be upgraded, but it doesn't actually do it:

```
➜ fluxctl list-images -n default -c helmrelease/node-red
Flag --controller has been deprecated, changed to --workload, use that instead
WORKLOAD                      CONTAINER    IMAGE                         CREATED
default:helmrelease/node-red  chart-image  nodered/node-red
                                           |   1.1.3-12-minimal-arm64v8  05 Aug 20 16:11 UTC
                                           |   1.1.3-12-minimal-s390x    05 Aug 20 16:11 UTC
                                           |   1.1.3-12-minimal-arm32v7  05 Aug 20 16:09 UTC
                                           |   1.1.3-12-minimal-arm32v6  05 Aug 20 16:09 UTC
                                           |   1.1.3-12-minimal-i386     05 Aug 20 16:08 UTC
                                           |   1.1.3-12-minimal          05 Aug 20 16:06 UTC
                                           |   1.1.3-12-minimal-amd64    05 Aug 20 16:06 UTC
                                           |   latest-12-minimal         05 Aug 20 16:06 UTC
                                           |   1.1.3-12-arm64v8          05 Aug 20 16:06 UTC
                                           |   1.1.3-12-s390x            05 Aug 20 16:05 UTC
                                           : (31 image(s) omitted)
                                           '-> 1.1.2-12-minimal          12 Jul 20 13:59 UTC
```

**Logs**

From `flux` within the context of the `node-red` image:

```
2020-08-16T12:44:06.530182162Z stderr F ts=2020-08-16T12:44:06.530014158Z caller=images.go:111 component=sync-loop workload=default:helmrelease/node-red container=chart-image repo=nodered/node-red pattern=regexp:^(1\.[0-9]+\.[0-9]+-12-minimal)$ current=nodered/node-red:1.1.2-12-minimal info="added update to automation run" new=nodered/node-red:1.1.3-12-minimal reason="latest 1.1.3-12-minimal (2020-08-05 16:06:35.448873919 +0000 UTC) > current 1.1.2-12-minimal (2020-07-12 13:59:55.813614396 +0000 UTC)"
```

From `helm-operator` within the context of the `node-red` HelmRelease:

![image](https://user-images.githubusercontent.com/6393612/90334616-f108cf00-df9c-11ea-8e35-dc78878fd38f.png)

**Additional context**

- Flux version: 1.20.1
- Kubernetes version: v1.18.6+k3s1
- Git provider: github
- Container registry provider: docker

May be related to #3206 ?

**Comment by billimek** [comment]
After searching through the flux logs, I cam across an obscure log entry about an unrelated `HelmRelease`:

```
"applying changes: updating resource kube-system:helmrelease/kured in kube-system/kured/kured.yaml: [721223] Failed to execute script kubeyaml\nTraceback (most recent call last):\n File \"kubeyaml.py\", line 311, in <module>\n File \"kubeyaml.py\", line 304, in main\n File \"kubeyaml.py\", line 77, in apply_to_yaml\n File \"site-packages/ruamel/yaml/main.py\", line 454, in dump_all\n File \"kubeyaml.py\", line 82, in update_image\n File \"site-packages/ruamel/yaml/main.py\", line 365, in load_all\n File \"site-packages/ruamel/yaml/constructor.py\", line 104, in get_data\n File \"site-packages/ruamel/yaml/composer.py\", line 68, in get_node\n File \"site-packages/ruamel/yaml/composer.py\", line 101, in compose_document\n File \"site-packages/ruamel/yaml/composer.py\", line 138, in compose_node\n File \"site-packages/ruamel/yaml/composer.py\", line 218, in compose_mapping_node\n File \"site-packages/ruamel/yaml/composer.py\", line 138, in compose_node\n File \"site-packages/ruamel/yaml/composer.py\", line 218, in compose_mapping_node\n File \"site-packages/ruamel/yaml/composer.py\", line 138, in compose_node\n File \"site-packages/ruamel/yaml/composer.py\", line 218, in compose_mapping_node\n File \"site-packages/ruamel/yaml/composer.py\", line 111, in compose_node\n File \"site-packages/ruamel/yaml/parser.py\", line 141, in check_event\n File \"site-packages/ruamel/yaml/parser.py\", line 604, in parse_block_mapping_value\n File \"site-packages/ruamel/yaml/scanner.py\", line 1762, in check_token\n File \"site-packages/ruamel/yaml/scanner.py\", line 1804, in _gather_comments\n File \"site-packages/ruamel/yaml/scanner.py\", line 321, in fetch_more_tokens\nruamel.yaml.scanner.ScannerError: while scanning for the next token\nfound character '\\t' that cannot start any token\n in \"<stdin>\", line 10, column 32"
```

.. Which seems to indicate that it found a tab character in a HelmRelease yaml file.  I removed that tab and then the image automatic updates began working as expected.  It should be noted that other flux operations were still working properly and `fluxctl sync` never reported an error.

Is it expected behavior that a parsing issue with one HelmRelease to cause image update automations to fail for all other HelmReleases?

**Comment by br0ziliy** [comment]
I seem to experience the same issue - Flux 1.20.1 does not automatically update the running container (no HelmOperator is in play in my case):

```
WORKLOAD                                   CONTAINER      IMAGE                                       CREATED
bulkprocessor-qa:deployment/bulkprocessor  bulkprocessor  docker-registry.myorg.local/bulkprocessor  
                                                          |   dev-deadbeeb                            19 Aug 20 13:12 UTC
                                                          |   dev-deadbeef                            19 Aug 20 13:12 UTC
                                                          |   dev                                     19 Aug 20 11:21 UTC
                                                          '-> dev-a73af38                             19 Aug 20 11:21 UTC
                                                              dev-dd95cee                             19 Aug 20 11:21 UTC
                                                              latest                                  19 Aug 20 11:21 UTC
```

I'd expect the workload to be running from `dev-deadbeeb`, which is newer?
 
The deployment I use is pretty simple:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulkprocessor
  namespace: bulkprocessor-qa
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.bulkprocessor: glob:dev-*
  labels:
    app: bulkprocessor
    env: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulkprocessor
      env: qa
  template:
    metadata:
      labels:
        app: bulkprocessor
        env: qa
    spec:
      nodeSelector:
        kubernetes.io/hostname: node1.myorg.local
      containers:
        - name: bulkprocessor
          image: 'docker-registry.myorg.local/bulkprocessor:dev-a73af38'
```

In the Flux logs I see messages from `component=warmer` that say that a new tags were seen, and updated in memcached - but Flux then takes no action to actually update the running pod... How I can troubleshoot it further (except trying to downgrade to 1.20.0)?

**Comment by br0ziliy** [comment]
Hm, tried to bump the Flux pod, and saw this log message at the top: 

```
ts=2020-08-19T15:04:30.740841079Z caller=loop.go:62 component=sync-loop info="Repo is read-only; no image updates will be attempted"
```

Does this mean that automatic image updates only possible with RW Git repo?..

**Comment by stefanprodan** [comment]
Flux automated updates work by writing to Git the change, not by changing things in-cluster as that's not GitOps.

**Comment by br0ziliy** [comment]
@stefanprodan Thanks. Might be good idea to mention this in the documentation "Automated deployment of new container images" section - took me some time to find out what am I doing wrong.

**Comment by kingdonb** [comment]
It sounds like the issue was resolved. Closing.
