### ISSUE TITLE
Upgrade memcached:1.5.20 image into memcached:1.6.6 or latest 

### ISSUE THREAD

**Issue by PKalhara** [fluxcd/flux#3275]
**Describe the feature**

Currently flux repository using a little bit older  **_memcached_** image  which is version **_1.5.20_** in following places
[memcache-dep.yaml](https://github.com/fluxcd/flux/blob/8609b01765984664cad3615801efa550417442ff/deploy/memcache-dep.yaml#L23) and [values.yaml](https://github.com/fluxcd/flux/blob/8609b01765984664cad3615801efa550417442ff/chart/flux/values.yaml#L206). We need to upgrade this memcached image in to the latest available tag in the docker hub.  

**What would the new user story look like?**

This memcached image upgrade will fix the vulnerabilities in the existing image and essentially this will help us to pass the twistlock vulnerability scan as we are blocked in this place due to the high number of security vulnerabilities in the exsting docker image tag **_memcached_:_1.5.20_**

**Expected behavior**

Please update [memcache-dep.yaml](https://github.com/fluxcd/flux/blob/8609b01765984664cad3615801efa550417442ff/deploy/memcache-dep.yaml#L23) and [values.yaml](https://github.com/fluxcd/flux/blob/8609b01765984664cad3615801efa550417442ff/chart/flux/values.yaml#L206) with the latest available docker image tag in [memcached:1.6.6](https://hub.docker.com/layers/memcached/library/memcached/1.6.6/images/sha256-8f521bdbfb7f948840c4aaeebd1d0b51bce37f9aae033bbf0417c2ccb40df5ad?context=explore)

**Comment by kingdonb** [comment]
@PKalhara Have you been able to test this configuration and seems to work fine?

This can be a priority for the next Flux v1 milestone, if you want to submit it as a pull request that will help expedite it and you will get all the credit for having resolved this issue in the glorious release notes.

Apologies about the length of time that has elapsed since your inquiry.

**Comment by kingdonb** [comment]
I will try to make sure this gets addressed in 1.22.2, sorry for the delay.

**Comment by kingdonb** [comment]
Actually we can still address it with #3456 today, taking a look at this now 👍
