### ISSUE TITLE
missing prometheus metrics

### ISSUE THREAD

**Issue by mrafieee** [fluxcd/flux#3285]
**Describe the bug**

I'm using flux 1.20.0 some prometheus metrics are missing in /metrics endpoint.

flux_cache_request_duration_seconds
flux_client_fetch_duration_seconds
flux_registry_fetch_duration_seconds
flux_fluxd_connection_duration_seconds

**Additional context**

- Flux version:  1.20.0
- Git provider: azuredevops
- Container registry provider: azurecr

**Comment by blhagadorn** [comment]
Is there any update on this?

**Comment by kingdonb** [comment]
Is this an azure specific issue? How did you install flux, and have you been able to upgrade to the latest version?

I'm not sure why these metrics in particular would be missing, if they still show up on a Flux instance that is not installed with Azure DevOps, etc. if this is Flux, or is Azure DevOps maintaining separately as a fork of Flux, I'm not sure. I will learn some about Azure DevOps and try to figure out if there is something I can do. But without some link to a guide to repro the issue, (I cannot follow this up without an active reporter, I'm not sure if you're still on this problem.)

Please welcome to post more information and I will be happy to reopen and work through this issue with you.

Flux v2 has provided some in-depth guides supporting Azure-specific services and I'm sure we will be able to support your use case there. All Flux v1 users are recommended to upgrade to Flux v2, the feature parity has been reached with 0.8 and production readiness has been announced for all of the default controllers at least. The next milestone is production ready image updates, many users already are using image updates in production and the feature is now much better than Flux v1.
