### ISSUE TITLE
The version of Kustomize in Flux does not handle $patch: delete correctly and needs to be upgraded

### ISSUE THREAD

**Issue by Crayeth** [fluxcd/flux#3286]
Using

    image:
      repository: docker.io/fluxcd/flux
      tag: 1.20.1

I've found that the Kustomize therein included (**3.7.0**) does not render patches with $patch: delete correctly. 
If I have something like:

    external_services:
      grafana:
        $patch: delete

I expect grafana and everything belonging to it to be deleted but it is not.
Using Kustomize **3.8.2** locally does render correctly.

**Comment by stefanprodan** [comment]
Fixed in https://github.com/fluxcd/flux/pull/3309
