### ISSUE TITLE
Git authorization fails when specifying non-default git.secretDataKey when installing via helm

### ISSUE THREAD

**Issue by ztj** [fluxcd/flux#3287]
**Describe the bug**

I am deploying flux using the helm chart, version 1.5.0. I am specifying values for `git.secretName` and `git.secretDataKey` amongst others. When doing this, during startup fluxd acknowledges these parameters and outputs the expected public key. However, it fails to authorize against the git repository despite successfully manually testing git operations with the same key.

**To Reproduce**

Steps to reproduce the behaviour:

1. Follow the instructions for using the helm chart including the optional step of creating a deploy key ahead of time and be sure to create a secret where the key name is not the default. In my case I used `id_rsa`.
2. Install the chart and remember to specify the `git.secretName` and `git.secretDataKey` values as appropriate.
3. Look at the logs. There will be some form of permission denied error when flux tries to clone the repository.

**Problem diagnosis and workaround**

I've already identified the core issue. Once deployed the way I described, there is only one place where ssh is configured to look for its identity files and that is in `/etc/ssh/ssh_config`.  This file explicitly tells ssh to look for files named `identity` in the usual default paths. So that means it will work if the key in the secret that was mounted is `identity` but not for any other key. Changing this file such that it includes a reference to the path for the custom secret key name fixes the issue. As a workaround I've started adding the following values entry:

```yaml
ssh:
  config: |-
    Host *
    IdentityFile /etc/fluxd/ssh/id_rsa
```

Given that my secret's key name is `id_rsa` this solves the issue for now.

**Expected behavior**

I expect that setting a parameter for `git.secretDataKey` in the chart will result in ssh configured correctly in the resulting running container so that it will actually use the specified key for the identity file, rather than the default of `/etc/fluxd/ssh/identity`

**Comment by kingdonb** [comment]
Has anyone who solved this found the issue in the code, and can provide a PR?

**Comment by kingdonb** [comment]
I am not sure how to fix this.

At this time, we hope you have already begun migration away from Flux v1 / legacy over to the [current version of Flux](https://github.com/fluxcd/flux2).

I'm going to close this without action, but we hope you've been able to upgrade to Flux v2 and note that Flux v1 remains in maintenance mode. Bugs with Flux v1 can be addressed as long as we keep it in maintenance mode, according to the plan laid out in the [Flux Migration Timetable](https://fluxcd.io/docs/migration/timetable/). 👍 

Thanks for using Flux.
