### ISSUE TITLE
How does Flux compare image versions to determine the latest version?

### ISSUE THREAD

**Issue by cer** [fluxcd/flux#3289]
Let's imagine that I've enabled automation. How does Flux determine that a new image is actually a later version than what's currently deployed? Is it the image creation time timestamp? Semantic versioning comparison?

**Comment by stefanprodan** [comment]
Hi Chris, 

There are several update policies you can use with Flux, semver is one of them. When using glob or regex, Flux will order the images by `org.opencontainers.image.created`, more details here https://docs.fluxcd.io/en/1.20.2/references/fluxctl/#image-tag-filtering

**Comment by kingdonb** [comment]
Thanks for contributing this to the discussion. Closing!
