### ISSUE TITLE
Will flux destroy any deployment that's not scripted in repo?

### ISSUE THREAD

**Issue by TheMisir** [fluxcd/flux#3291]
I have a namespace in k8 which contains:

- Microservice pods
- Database cluster managed by [postgres-operator](https://github.com/CrunchyData/postgres-operator)

---

My question is simple. Will Flux remove database pods (which is managed / created / removed automatically by postgres-operator) if I deploy flux to my cluster cause my repo doesn't contains manifest files for database deployments?

If yes, is there a way to let flux to manage only specified resources (eg: specified by special label).

---

PS: I want to use flux to automatically restart pods with new image when new image is published to my private docker repository.

Btw thanks for an amazing project 👍

**Comment by stefanprodan** [comment]
> My question is simple. Will Flux remove database pods (which is managed / created / removed automatically by postgres-operator) if I deploy flux to my cluster cause my repo doesn't contains manifest files for database deployments?

No, Flux doesn't remove things that it didn't apply.

**Comment by TheMisir** [comment]
Thanks @stefanprodan .
