### ISSUE TITLE
fluxctl should have a --kubeconfig option

### ISSUE THREAD

**Issue by sylr** [fluxcd/flux#3295]
**Describe the feature**

As kubectl does, fluxctl should allow to use a custom kube config file.

**Comment by stealthybox** [comment]
As a workaround, I'm fairly sure you can just set the `KUBECONFIG` environment variable, since the code-paths for client loading are the same as those in kubectl, cli-runtime, and client-go.

You can add this env var in your fluxd Deployment

Let us know if this works for you.

**Comment by kingdonb** [comment]
If you are interested in providing this as a PR, I will be glad to review it and can try to help get it merged. Flux v1 is in maintenance mode though, and feature requests are generally not being added anymore unless they are critical or for security, or bug fixes. A workaround is viable with the `KUBECONFIG` variable as was suggested, I think that's perfectly good answer and no feature update is needed.

Please also consider upgrading to Flux v2 👍 Closing.
