### ISSUE TITLE
Unnecessary caching logs

### ISSUE THREAD

**Issue by karlmuscat** [fluxcd/flux#3298]
**Describe the bug**

The cache manager logs a warning when a manifest is missing for an image on docker hub. There are certain opensource repos, such as, `grafana/loki` and `grafana/promtail` that do not add manifests to all their images. This is resulting in hundreds/thousands of log lines every few minutes that are littering the flux logs. Unfortunately, we can neither fix the manifest images nor the logs, and is making the logs difficult to use. 

Incidentally, these 2 repos, have thousands of images and a few hundred of them have missing manifests. 

**To Reproduce**

**Expected behavior**

It would be nice if either the logs are ignored, or else have a way how to silence/disable them.

**Logs**

```
ts=2020-09-18T15:35:06.856098487Z caller=warming.go:198 component=warmer info="refreshing image" image=grafana/loki tag_count=2154 to_update=2154 of_which_refresh=0 of_which_missing=2154
ts=2020-09-18T15:35:27.983269012Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/grafana/loki auth={map[]} warn="manifest for tag master-00ee652-arm missing in repository grafana/loki" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"
ts=2020-09-18T15:35:28.224384818Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/grafana/loki auth={map[]} warn="manifest for tag master-00f494e-amd64 missing in repository grafana/loki" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"
ts=2020-09-18T15:35:28.915888164Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/grafana/loki auth={map[]} warn="manifest for tag master-0202884 missing in repository grafana/loki" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"
ts=2020-09-18T15:35:30.449898104Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/grafana/loki auth={map[]} warn="manifest for tag master-0520a0a-arm missing in repository grafana/loki" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"
ts=2020-09-18T15:35:30.507305497Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/grafana/loki auth={map[]} warn="manifest for tag master-0520a0a-arm64 missing in repository grafana/loki" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"
...
...
```

**Additional context**

- Flux version: 1.15.0
- Kubernetes version: 1.15
- Git provider: Github
- Container registry provider: ECR

**Comment by lucioveloso** [comment]
I'm getting the same. That's not generating an issue, but make a lot of noise in the logs.

**Comment by kingdonb** [comment]
I am not sure how to fix this, if it is just noise in the logs, those logs will correspond to some events, and now that Flux v1 is in maintenance mode, the particular behavior of the logs is considered behavior of flux by integrations providers. This has to be maintained as consistent, since Flux v2 is the focus of development efforts, there can be no further breaking changes in v1.

If there is a PR suggested I will be happy to review, but there is nothing I can see that is actionable for me here. Closing.
