### ISSUE TITLE
`fluxctl sync` reports success even if flux has failed to apply changes.

### ISSUE THREAD

**Issue by neubieser** [fluxcd/flux#3304]
**Describe the bug**

`fluxctl sync` reports success even if flux has failed to apply changes.

**To Reproduce**

Steps to reproduce the behaviour:

I had removed a label from a deployment's manifest (variant=nonprod). This causes `kubectl apply` to fail because the labelSelector does not match.

**Expected behavior**

I would have expected flux to give an indication that applying the changes had failed. Instead I had to find out by looking at the logs.

**Logs**

 85 ts=2020-09-24T16:53:57.819465961Z caller=sync.go:606 method=Sync cmd="kubectl apply -f -" took=179.491566ms err="running kubectl: exit status 1, stderr: The Deployment \"nginx-ingress-controller\" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{\"app\":\"ingress-nginx\", \"app.kubernetes.io/name\":\"ingress-nginx\", \"app.kubernetes.io/part-of\":\"ingress-nginx\", \"variant\":\"nonprod\"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable" output=

**Comment by kingdonb** [comment]
This story is substantially improved in the new Flux v2

Feature parity was announced with v2's latest release 0.8, and I'll explain how this is improved

```
flux reconcile kustomization app --with-source 
```
is the equivalent command to `fluxctl sync`. There's a bit to unpack in here, and the Flux migration documentation does explain it well

https://toolkit.fluxcd.io/guides/flux-v1-migration/#install-flux-v2-cli

The monolith design of Flux Daemon has been split into APIs that cover each of the composite concerns in Flux's main job of applying sources of manifests to the cluster and putting image updates into the cluster.

So the new CLI provides rich feedback about what we're waiting for and what has succeeded or failed. Here's the current output of a successful sync in 0.8:

```
$ flux reconcile kustomization flux-system --with-source
► annotating GitRepository flux-system in flux-system namespace
✔ GitRepository annotated
◎ waiting for GitRepository reconciliation
✔ GitRepository reconciliation completed
✔ fetched revision main/a3270390ff14158603d057a7864b8e52ac16809d
► annotating Kustomization flux-system in flux-system namespace
✔ Kustomization annotated
◎ waiting for Kustomization reconciliation
✔ Kustomization reconciliation completed
✔ reconciled revision main/a3270390ff14158603d057a7864b8e52ac16809d
```

The source can be successfully downloaded and reconciled as current, or else it fails. The manifest can be successfully reconciled into the cluster or else it fails.

In Flux v1, you should get an error if the latest commit has not synced to the cluster. I'm not sure I have enough information to reproduce the failure that you ran into, it will help me close this issue if you can provide some more detail. Did flux apply a `flux-sync` tag to the commit that failed kubectl apply? What is the output of `fluxctl sync`?

It should not say the commit was applied from branch if kubectl apply failed.

**Comment by kingdonb** [comment]
If you have steps to repro, I can follow this up. Even a screen recording would help. I will happily reopen and debug this issue with you if you are still affected by it. Closing for now, as the issue has gone stale and there is not enough information for a test case as I can see.
