### ISSUE TITLE
Mention that Flux v1 is in maintenance mode

### ISSUE THREAD

**Issue by dholbach** [fluxcd/flux#3312]
I think we should 

- [x] create an issue which explains the status of v1 and pin it
- [ ] edit the issue template for /f/flux and point out that we're in maintenance mode 
- [x] add a slack pinned message

Also point to a good place for how to get involved, learn about what's happening, how to get started, etc.

**Comment by dholbach** [comment]
Point to https://docs.fluxcd.io/en/stable/troubleshooting/ and https://docs.fluxcd.io/en/stable/faq/ for v1 users too.

**Comment by stealthybox** [comment]
Should our quick note in the issue template point to the pinned issue?
People can then comment there

**Comment by dholbach** [comment]
Sounds good, yes!
