### ISSUE TITLE
fluxctl list-images --k8s-fwd-ns=xxx --workload=deployment/xxx returns empty

### ISSUE THREAD

**Issue by joerg-walter-de** [fluxcd/flux#3318]
I have mostly successfully set up a multi tenant flux cluster with currently two namespaces managed by flux.
It basically works in the sense that a new tag in the registry triggers an update in the namespace repository and then in the namespace.

The remaining problem is, that

fluxctl list-images --k8s-fwd-ns=xxx --workload=deployment/xxx

returns nothing.

The registry is a private gitlab registry. 
What might be the cause?

**Comment by kingdonb** [comment]
The `fluxctl list-images` command also takes a workload namespace, I suspect this was omitted and is the root of the issue.

In `--k8s-fwd-ns` you should pass the namespace that flux is installed into (usually flux, fluxcd, or it could have been installed into the same namespace as your workloads, which if true could have been the source of the confusion.)

In `--namespace` you should pass the namespace of the workload, or the default / current context namespace is likely used.

Hope this helps! (Closing)
