### ISSUE TITLE
is there any way we can deploy the pods on kubernetes cluster using flux in sequence manner ?

### ISSUE THREAD

**Issue by cloudengineers** [fluxcd/flux#3324]
Hi All, 

I am using flux in my development environment, Can you please help me on the below query?

is there any way we can deploy the pods on kubernetes cluster using flux in sequence manner ? 

for example  I have 2 pods, once the pod 1 is up and running then pod 2 should be created  as i have some dependencies 

Any help much appreciated.

Thank you

**Comment by toddkazakov** [comment]
You can just use stateful sets

**Comment by stefanprodan** [comment]
You define your apps dependency graph with Flux v2, see https://toolkit.fluxcd.io/components/kustomize/kustomization/#kustomization-dependencies

**Comment by cloudengineers** [comment]
thank you @stefanprodan @toddkazakov 

I will go through this documents,  Will this doc help me to deploy my application pods in sequence manner using fluxv2?

**Comment by kingdonb** [comment]
Yes, the dependency feature will allow you to separate workloads into dependency order as suggested. This feature is not available in Flux v1, but it is supported in `kustomize-controller`. If you are using `helm-controller` too, it is supported there as well, but inter-resource dependencies are a bit more complicated. Here is a relevant discussion in the Flux 2 forum:

https://github.com/fluxcd/flux2/discussions/730

Closing, please feel free to ask if you have more questions.
