### ISSUE TITLE
Question: Can multiple fluxd instances share a memcached ?

### ISSUE THREAD

**Issue by smveloso** [fluxcd/flux#3334]
Hi,

  To work around the [ "single git repo" limitation](https://docs.fluxcd.io/en/1.21.0/faq/#does-it-work-only-with-one-git-repository), I've got several instances of fluxd running, each using its own instance of memcached. 

  I would like to make them share a single memcached instance (or a cluster, but a single one).

  Is it possible/advisable ? Would there be any trouble if I simply pointed each instance of fluxd to the same memcached (via `--memcached-...`) ?

  Thanks !
  
PS.  [this comment](https://github.com/fluxcd/flux/issues/1164#issuecomment-478328315) on [issue 1164](https://github.com/fluxcd/flux/issues/1164) suggests that it is in fact possible.

**Comment by stefanprodan** [comment]
Yes, it is advised to used the same memcached for all Flux instances running on a cluster.

**Comment by smveloso** [comment]
Ok, thank you !
