### ISSUE TITLE
Deploying to flux using different fix/feature git branches

### ISSUE THREAD

**Issue by absnamohammed** [fluxcd/flux#3336]
Hi, 
Currently we can deploy to chef using git master by default. I have noticed that we can only deploy from one branch whether it is default master branch or any other one fix/feature branch. 

Is it possible to deploy on flux using any feature branch?

Can someone shed some light on it? Thanks

Regards, 
Abdul

**Comment by mf-svc-github** [comment]
Closing this out as the similar issue is being dealt under [#3308 ](https://github.com/fluxcd/flux/issues/3308)
