### ISSUE TITLE
Flux deployment is quite slow, auto-sync and auto-release gets applied in 30-45 mintues. 

### ISSUE THREAD

**Issue by absnamohammed** [fluxcd/flux#3338]
Flux deployment is quite slow, using default 5 mintues, but the manifest get applied in 30-45 mintues. This is happening on flux running in eks dev cluster. Flux runs perfectly fine on eks prod cluster. 

**Dev cluster flux and helm chart version**
Flux chart version: 1.5.0
image: docker.io/fluxcd/flux:1.20.2
Helm operator chart version: 1.2.0

I have upgarded to the latest stable version after the slow deploy complains. 

**Prod cluster still having previous version,**
Flux chart version: 1.3.0
Helm operator chart version: 1.1.0

I have noticed in flux version 1.5.0 kubedir is mounted to `/root/.kubectl` and the `cache` and `http-cache` exist in .kube folder. But, for helm operator 1.2 kubedir is mounted to `/root.kube` and hence the `cache` and `http-cache` folders are missing from it. 

**Dev fluxcd**

```env:
    - name: KUBECONFIG
      value: /root/.kubectl/config
```

```
~/.kubectl # ls -la
total 0
drwxrwxrwx    3 root     root            73 Oct 20 09:33 .
drwx------    1 root     root            67 Oct 21 04:07 ..
drwxr-xr-x    2 root     root            20 Oct 20 09:33 ..2020_10_20_09_33_58.176722620
lrwxrwxrwx    1 root     root            31 Oct 20 09:33 ..data -> ..2020_10_20_09_33_58.176722620
lrwxrwxrwx    1 root     root            13 Oct 20 09:33 config -> ..data/config
```

```
~/.kube # ls -la
total 8
drwxr-xr-x    1 root     root            37 Oct 20 09:34 .
drwx------    1 root     root            67 Oct 21 04:07 ..
drwxr-x---    3 root     root            23 Oct 20 09:34 cache
-rw-rw-r--    1 root     root           181 Apr  2  2020 config
drwxr-x---    3 root     root          4096 Oct 21 04:06 http-cachecd 
```

**Dev Helm-operator**

```/dev/nvme0n1p1           20.0G      6.4G     13.6G  32% /root/.kube```

```
~/.kube # ls -la
total 0
drwxrwxrwx    3 root     root            73 Oct 20 17:24 .
drwx------    1 root     root            51 Oct 21 04:29 ..
drwxr-xr-x    2 root     root            20 Oct 20 17:24 ..2020_10_20_17_24_11.108998213
lrwxrwxrwx    1 root     root            31 Oct 20 17:24 ..data -> ..2020_10_20_17_24_11.108998213
lrwxrwxrwx    1 root     root            13 Oct 20 17:24 config -> ..data/config
```

Removed from helm-operator(args)
```- --kubeconfig=/root/.kube/config```

Removed the mount point of /root/.kube and matched with prod mount. I now see the `cache` and `http-cache` folders in `/root/.kube` folder, flux is deploying but still taking 30-45 minutes for a deployment or automated release which used to take max 5-10 minutes. Prod cluster with above config works absouletly fine but if I downgrade the flux and helm operator to match prod version, deployment an auto-release is happening but with delays of more than 30 minutes. 

I don't see any specific errors that could be the reason of slowness, I tried upgrading the flux and helm version, scaling the resources on both. 

Please let me know if you need any further information or have a question.

**Comment by nabadger** [comment]
Have you tried latest Flux `1.21.0` ?

I was finding some weird slowness with `1.20.2` which appeared to be hanging on `kubectl` commands which flux issues (the sync). The version of kubetl jumps between these 2 versions, so worth checking.

**Comment by absnamohammed** [comment]
@nabadger thank you for getting back on this. I have tried lastest version of Flux `1.21.0` but that didn't make any difference. 
After further investigation I have figured out the issue, which is due to high number of configmaps revision for each release which accumulated over 3.5k.

Following are the steps taken to fix the issue, 

1. Cleaned up the configmap revisions for each release(specifically secrets and configmaps)
2. Restricted tiller max history to 10 revision

Again, thanks for your input.

**Comment by danepowell** [comment]
We also just experienced the same symptoms (extremely slow syncing, with new CRDs not even appearing in Flux / Helm Operator logs for 45 minutes) and fixed it the same way, by cleaning up old config maps. But this doesn't seem like a long-term fix, eventually the cluster will grow and presumably cause the same issue.

Is there a deeper issue here? How could flux or helm-operator be more performant over larger configmap sets? And how could I go about debugging the slowdown, given that changes don't even show up in the logs for 45 minutes? Is there some way to monitor the sync queue/backlog size?

**Comment by grasmash** [comment]
I'm interested in:
> But, for helm operator 1.2 kubedir is mounted to /root.kube and hence the cache and http-cache folders are missing from it.

Seems like cleaning up the config maps is a workaround to an underlying caching issue.

**Comment by absnamohammed** [comment]
> We also just experienced the same symptoms (extremely slow syncing, with new CRDs not even appearing in Flux / Helm Operator logs for 45 minutes) and fixed it the same way, by cleaning up old config maps. But this doesn't seem like a long-term fix, eventually the cluster will grow and presumably cause the same issue.
> 
> 
> 
> Is there a deeper issue here? How could flux or helm-operator be more performant over larger configmap sets? And how could I go about debugging the slowdown, given that changes don't even show up in the logs for 45 minutes? Is there some way to monitor the sync queue/backlog size?

You can see the release commit instantly in flux, but helm operator taking time to deploy due to the number of revisions for each release.

**Comment by absnamohammed** [comment]
> I'm interested in:
> 
> > But, for helm operator 1.2 kubedir is mounted to /root.kube and hence the cache and http-cache folders are missing from it.
> 
> 
> 
> Seems like cleaning up the config maps is a workaround to an underlying caching issue.

Yeah, I too believe the same as I have tried the other recommendations from flux docs like restricting helm operator to single namespace,but that is leading to number of helm operators, still the main issue of slowness persist. But if you have a separate tiller and helm operator per namespace fix the issue, in long run it will again pile up the release history. So, best is clean up the confit and restrict the tiller max history.
