### ISSUE TITLE
Flux v1 leaks URI encoded Git password to logs

### ISSUE THREAD

**Issue by jvanmalder** [fluxcd/flux#3339]
**Describe the bug**

The logs contain the URI encoded password of the Git credentials when using Git with the HTTPS protocol and when there are special characters (e.g. `^`) in the password.

**To Reproduce**

Steps to reproduce the behaviour:

1. Install Flux 1.21.0
2. Configure it with the --git-url argument set to a Git repository with username and credentials, making sure that there are special characters in the password (e.g. `^`): `--git-url=https://user:password^1234@bitbucket.org/my/repo`

**Expected behavior**

Logs do not contain the URI encoded password of the Git credentials.

**Logs**

Using a password which contains the `^` character (.e.g. `password^1234`) generates the following log line:

`2020-10-22 10:56:03 | ts=2020-10-22T08:56:03.858045882Z caller=loop.go:134 component=sync-loop event=refreshed url=ssh://@https//user:password%5E1234@bitbucket.org/my/repo.git branch=test HEAD=8203285d5073f7a0b0f5a36fc883d3444d7701d0`

Note the encoded string `%5E` instead of the `^` character.

Using a password which contains only alphanumeric characters (.e.g. `password1234`) generates the following log line:

`2020-10-22 10:12:26 | ts=2020-10-22T08:12:26.087500577Z caller=loop.go:134 component=sync-loop event=refreshed url=https://user@bitbucket.org/my/repo.git branch=test HEAD=8203285d5073f7a0b0f5a36fc883d3444d7701d0`

**Additional context**

- Flux version: 1.21.0
- Kubernetes version: 1.17.9
- Git provider: Atlassian Bitbucket
- Container registry provider: JFrog Artifactory

**Comment by kingdonb** [comment]
That's interesting, looks like a naive search and replace has failed due to the special character replacement.

Have you had a chance to look for the relevant section of code that does the masking, and find out if there is any easy fix possible? This is a good find.

**Comment by kingdonb** [comment]
Flux v1 is formally superseded, since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

I will leave this issue open for visibility, since it is a very rough edge, but unless there were a PR or suggestion for how to fix this, I can't see any strong likelihood of this issue being addressed as part of Flux v1 maintenance.

**Comment by kingdonb** [comment]
At this time, we hope you have already begun migration away from Flux v1 / legacy over to the [current version of Flux](https://github.com/fluxcd/flux2).

We hope you've been able to upgrade to Flux v2, and note that Flux v1 remains in maintenance mode. Bugs with Flux v1 can be addressed as long as it remains in maintenance, according to the plan laid out in the [Flux Migration Timetable](https://fluxcd.io/docs/migration/timetable/). 👍 

Thanks for using Flux.

**Comment by pjbgf** [comment]
This project is in Migration and security support only, so unfortunately this issue won't be fixed. We recommend users to migrate to Flux 2 at their earliest convenience.

More information about the Flux 2 transition timetable can be found at: https://fluxcd.io/docs/migration/timetable/.
