### ISSUE TITLE
sops version 3.6.0 adds single quotes around  values it decrypts, that issue was fixed in version 3.6.1, can you please upgradeversion to 3.6.1

### ISSUE THREAD

**Issue by hroyg** [fluxcd/flux#3343]
**Describe the bug**
the issue is not regarding flux, rather sops version that is bundled with flux container.

when sops 3.6.0 decrypts an encrypted secret.env file it surrounds the original encrypted values with single quotes.
so if i had secret.env file  with the content:
`password=XXXXXXXXX ;
token=XXXXXXXX`

then encrypting it on my local machine, uploaded the encrypted secret.env file to github.
then telling .flux.yaml file to run:
 `sops --kms xxxx.xxxxxx.xxxxxx -d secret.env ;
kustomize build .`

the above command will decrypt the file,  then using kustomize to generate a k8s secret from it , the newly created secret will contain the follow content:
`password='XXXXXXXXX' ;
token='XXXXXXXX'`

the new secret is with the same key=value but with surrounded single quotes.
this behavior was fixed in sops 3.6.1 version.

**To Reproduce**

Steps to reproduce the behaviour:

1. install flux using helm V3, e.g:
helm upgrade -i flux fluxcd/flux --wait \
 --namespace fluxcd \
 --set git.pollInterval=3m \
 --set git.url=git@github.com:GITHUBUSERNAME/k8s-resources
 --set manifest-generation=true
 --set sops=true

encrypt a secret:
- create a secret env file with key=value, data you wish to encrypt.
`>> cat secret.env
password=XXXXXXXXX ;
token=XXXXXXXX

>> sops --kms arn:aws:kms:us-east-1:xxxxxxxxxxxxx:key/lsdkjfsl-389l-sdlkfsklklsjhdf-lskdjf  secret.env`

- then decrypt the same file with the same key, and the result will be with added quotes :
`>> sops --kms arn:aws:kms:us-east-1:xxxxxxxxxxxxx:key/lsdkjfsl-389l-sdlkfsklklsjhdf-lskdjf  secret.env ;
password='XXXXXXXXX' ;
token='XXXXXXXX'`

2. Provide a GitHub repository with Kubernetes manifests
.
├── base
│   └── timestamps
│       └── video-timestamps-api
│           ├── deployment.yaml
│           ├── ingress.yaml
│           ├── kustomization.yaml
│           ├── service_account.yaml
│           └── service.yaml
├── namespaces
│   └── ns-timestamps.yaml
├── overlays
│   ├── dev
│   │   ├── kustomization.yaml
│   │   └── timestamps
│   │       └── video-timestamps-api
│   │           ├── config.properties
│   │           ├── kustomization.yaml
│   │           └── secrets
│   │               └── secrets.env
│   └── staging
└── README.md

**Expected behavior**

The decrypted file with key=value should be exactly the same as file that was encrypted without any additional quotes (or any other characters).

**Additional context**

- Flux version: 1.21.0
- Kubernetes version:  1.17
- Git provider:github
- Container registry provider:ECR

**Comment by kingdonb** [comment]
It looks like this would be resolved by #3401, which is set to release with #3421.

Sorry for the delay. I should be able to release this update soon, perhaps over the weekend. The new version that should resolve this issue will be Flux v1.21.2. Thanks for the report.

**Comment by kingdonb** [comment]
@hroyg can you confirm if the last Flux v1 release – v1.21.2 – has resolved your issue?

I'm not sure why #3421 merging did not close this issue. We can hopefully close it when you confirm it has been resolved.
