### ISSUE TITLE
Flux not working with StatefulSet

### ISSUE THREAD

**Issue by hieu29791** [fluxcd/flux#3347]
Because Flux executes this command when deploying: `kubectl apply -f`. If the type is Deployment everything is fine, but if the type is StatefulSet, the pod doesn't do an update in turn. You need to execute the command `kubectl patch` instead of` kubectl apply`. [StatefulSet docs](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#rolling-update)

1. Prepare a full setup environment: Flux agent and Memcached with stable helm version, script deploy on the repo.
2. Commit & push code. Flux does the deployment, this time with success because Application A (of type StatefulSet) will be generated with the command `kubectl apply -f`.
3. Commit & push code again. This time will fail because Application A exists and the result of command `kubectl apply -f` is **configured** but nothing happens. I need to remove the StatefulSet A application, after an interval time, flux trigger the `kubectl apply -f` with the latest manifest and the behavior looks like step 2.

**Expected behavior**

StatefulSet will automatically update.

**Logs**
![fluxcd](https://user-images.githubusercontent.com/10827875/97526543-f8584a00-19db-11eb-8351-86310bfc2d20.png)

The image shows step 3 (when application A is created). And then I push a new commit into the repo, enable throughput and a StatefulSet state that is ** configured **. Then I removed application A and everything worked as I explained above.

**Comment by stefanprodan** [comment]
You need to set the updateStrategy inside the YAML in Git and it will work with apply.

**Comment by hieu29791** [comment]
> You need to set the updateStrategy inside the YAML in Git and it will work with apply.

What kind of updateStrategy did you talk about? By default, it is RollingUpdate and it doesn't work with my case. 
![image](https://user-images.githubusercontent.com/10827875/97542308-1b452700-19f9-11eb-8ed0-ea475c3f645a.png)
