### ISSUE TITLE
[helm-chart] Add serviceaccount to the memcache deployment

### ISSUE THREAD

**Issue by davidkarlsen** [fluxcd/flux#3350]
In constrained clusters with strict security one might want to give roles via service-accounts, hence use the created service-account for the memcached pod as well as the flux-deployment.

**Comment by kingdonb** [comment]
This is a good idea, I think, but as Flux v1 is in maintenance mode and this will represent a breaking change for some users, it cannot be accepted here anymore. Thanks for the suggestion.

Closing.
