### ISSUE TITLE
Flux bootstrap of private git fails with pre-receive hook

### ISSUE THREAD

**Issue by notwedtm** [fluxcd/flux#3351]
**Describe the bug**

When trying to bootstrap a new cluster I get a pre-received hook failure with no further context as to why the failure occured.

**To Reproduce**

Steps to reproduce the behaviour:

```
➜ flux bootstrap gitlab --repository flux2-dev --hostname gitlab.example.com --branch master --owner devops --path my-cluster
► connecting to gitlab.azlo.io
✔ repository cloned
✚ generating manifests
✗ git push error: command error on refs/heads/master: pre-receive hook declined
```

**Expected behavior**'

Cluster to provision successfully

**Additional context**

```
➜ flux check
► checking prerequisites
✔ kubectl 1.18.3 >=1.18.0
✔ Kubernetes 1.18.2 >=1.16.0
► checking controllers
✔ source-controller is healthy
✔ kustomize-controller is healthy
✔ helm-controller is healthy
✔ notification-controller is healthy
✔ all checks passed
```

- Git provider: Gitlab
- Container registry provider: Gitlab

**Comment by hiddeco** [comment]
Is it possible you have something like a global rule in GitLab that prevents people from pushing to `master` branches?

In any case: it is a server-side configuration that prevents `flux` from being able to push the commit, and the `pre-receive hook declined` is as much context as we (can) get from Git.

**Comment by kingdonb** [comment]
This report for Flux 2 is in the Flux 1 repository, I'm going to close it.

Protected `master` branch is an extremely common config, I think that's the right answer. Thanks for using Flux!
