### ISSUE TITLE
AllowedNamespace doesn't work when deploy with Helm

### ISSUE THREAD

**Issue by hieu29791** [fluxcd/flux#3352]
I using helm to deploy flux with custom values file. But **allowedNamespaces** field doesn't work. I describe deployment and don't have args **k8s-allow-namespace** .

**To Reproduce**

Steps to reproduce the behaviour:

1. Edit values file.
2. Run command: `helm upgrade -i flux-test fluxcd/flux 
--namespace flux-test 
-f values-optimized.yaml`  
3. Flux work with all namespaces.

**Expected behavior**

AllowedNamespaces option working.

**Image**

![image](https://user-images.githubusercontent.com/10827875/98191945-bfc0ef00-1f4c-11eb-9a42-56784398a537.png)

**Comment by aogier** [comment]
You probably don't have disabled clusterrole creation, that is enabled by default. A questionable design choice maybe, but that way it works

**Comment by kingdonb** [comment]
Thanks for the report and hope that your issue is resolved with the information that was provided @hieu29791 . If you think there is still a problem, we can reopen, but seeing no further activity on this issue report, I'm going to close it now.

Thanks for using Flux!
