### ISSUE TITLE
Couldn't get resource list for admission.stash.appscode.com/v1beta1: the server is currently unable to handle the request.

### ISSUE THREAD

**Issue by hieu29791** [fluxcd/flux#3353]
A few days ago, I deployed and ran flux successfully. Then I ignored this and didn't do anything. Yesterday suddenly flux wasn't working, here is the logs: `couldn't get resource list for admission.stash.appscode.com/v1beta1: the server is currently unable to handle the request`. I don't know what's wrong and the root cause of it.

**Expected behavior**

Flux works normally and finds the root cause of the problem.

**Logs**

>ts=2020-11-05T03:11:40.765943516Z caller=loop.go:134 component=sync-loop event=refreshed url=https://xxxx@gitlab.com/xxxxxxxx/config.git branch=master HEAD=efc8e21444d15c56f9b82ef7abc848ca2e79633b  
>
>ts=2020-11-05T03:12:14.986596069Z caller=sync.go:61 component=daemon info="trying to sync git changes to the cluster" old=299a4ca4fd7231f07d6757863a0ea19029d6da07 new=efc8e21444d15c56f9b82ef7abc848ca2e79633b  
>
>ts=2020-11-05T03:12:15.119207302Z caller=main.go:276 type="internal kubernetes error" kubernetes_caller=k8s.io/client-go@v0.17.11/discovery/cached/memory/memcache.go:111 err="couldn't get resource list for admission.stash.appscode.com/v1beta1: the server is currently unable to handle the request"  
>
>ts=2020-11-05T03:12:15.123162497Z caller=loop.go:108 component=sync-loop err="collating resources in cluster for sync: the server is currently unable to handle the request"

**Comment by hieu29791** [comment]
I detected the problem. Because I deployed stash before, so Flux some way **connecting** with Stash. Currently, Stash scale to 0, so Flux cannot connect with Stash, and the problem will occur.  
Ps: I don't know why Flux needs to connect to Stash. So if anyone has the answer, please enlighten me. Thank you.

**Comment by hiddeco** [comment]
See: https://docs.fluxcd.io/en/1.21.0/troubleshooting/#flux-fails-with-an-error-log-similar-to-couldnt-get-resource-list-for-examplecomversion-the-server-is-currently-unable-to-handle-the-request
