### ISSUE TITLE
when using with kustomize configuration file must be .flux.yaml not .flux.yml

### ISSUE THREAD

**Issue by duxinxiao** [fluxcd/flux#3374]
**Describe the bug**

it seems flux wont detect .flux.yml file

**Expected behavior**

I think it should support both .flux.yml and .flux.yaml

**Additional context**

- Flux version: 1.21.0

BTW, I think it's better to auto detect kustomization.yml file, for now it seems that I should manually import all kustomization.yml in one, which is really verbose. And it seems that I cant have multiple flux-patch.yml files. I prefer to have flux-patch.yml file per workload, which seem I can only achieve by add more git.path (Its not possible, cuz I have hundred of apps). Dont know if it will approve in flux v2

**Comment by kingdonb** [comment]
Thank you for the suggestion! There are many improvements in Flux v2, but the `.flux.yaml` feature got the chop. It is too unconstrained and the ability to run arbitrary binaries makes it very difficult to cover every use case with documentation.

It is now possible to omit kustomiztion.yaml entirely in the new kustomize-controller, as explained in the new API docs:

https://toolkit.fluxcd.io/components/kustomize/kustomization/#generate-kustomizationyaml - some of this information or other nearby may help you to find a way to implement your use case in Flux v2.

Flux v1 is in maintenance mode, and is generally not receiving new features anymore. In general the newly re-architected Flux behaves much better with large and complex workloads. If you find it doesn't meet your use case well, we are interested to hear more about why. Please review the docs and let us know if there's something else we could add to make it better.

If you want to submit a patch that makes `.flux.yml` read the same as `.flux.yaml`, I think that is a non-breaking change and could be accepted, but I suspect that further development of this feature is not a high priority for the Flux team.

Closing for now, but you are welcome to ask more questions.
