### ISSUE TITLE
Can't understand resetValues & forceUpgrade in HelmRelease

### ISSUE THREAD

**Issue by pratikbalar** [fluxcd/flux#3375]
Need Help, cannot fully understatnd `resetValues` and `forceUpgrade` in HelmRelease

**Comment by kingdonb** [comment]
The `resetValues` flag is the inverse of `--reuse-values` from Helm itself – this `resetValues` defaults to True, which implies that your release is based only on the information provided by passed-in values. 

https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/release-configuration/#reusing-values-during-upgrade

The `forceUpgrade` flag is for use with upgrades that may fail without passing the flag. If you are not upgrading across breaking releases of a Helm chart, it should generally be left in the default `false` value.

https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/release-configuration/#forcing-resource-updates

Thanks for your inquiry, sorry for the delay in response. Flux v1 is in maintenance mode and it is recommended for Flux users to upgrade to Flux v2 soon, as it is already better in many ways for very close to all use cases.

If there is something else which can be clarified, please feel free to ask more questions! Closing
