### ISSUE TITLE
Flux is not able to get the EC2Metadata to detect the AWS region when switching the EKS EC2-instances Metadata-Service-Version from IMDSv1 to IMDSv2.

### ISSUE THREAD

**Issue by raviranjithkumar** [fluxcd/flux#3384]
**Describe the bug**

Flux is not able to get the EC2Metadata to detect the AWS region when switching the EKS EC2-instances Metadata-Service-Version from IMDSv1 to IMDSv2. Due to this the deployments are getting impacted.

Switching from IMDSv1 to IMDSv2 is necessary because of the Security issues that we have with [IMDSv1](https://medium.com/@shurmajee/aws-enhances-metadata-service-security-with-imdsv2-b5d4b238454b)

In our Org, we use flux in production and there is a security concern to update to IMDSv2 but the current Flux is not supporting it so this fix is critical for us. We need the community help to address this issue.

I see the flux code is using ec2metadata: https://github.com/fluxcd/flux/blob/2f8e2075784fdc217c4359a5f25286d46230eda8/pkg/registry/aws.go#L130

*About IMDSv2: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

**To Reproduce**

Steps to reproduce the behaviour:

1. Disable IMDSv1 and start using IMDSv2 in EC2 instances of the EKS cluster

**Expected behavior**

Flux should be able to get the AWS region information and do the deployments as expected

**Logs**

`{"caller":"aws.go:137","component":"aws","err":"EC2MetadataRequestError: failed to get EC2 instance identity document\ncaused by: EC2MetadataError: failed to make EC2Metadata request\n\tstatus code: 401, request id: \ncaused by: ","error":"fetching region for AWS","ts":"2020-12-09T12:37:34.324397636Z"}
`
**Additional context**

- Flux version: 1.20.2
- Kubernetes version: v1.15.11-eks-065dce
- Git provider: Github
- Container registry provider: AWS-ECR

**Comment by relu** [comment]
I suspect this might have something to do with the outdated version of the go aws-sdk [flux depends on (v1.27.1)](https://github.com/fluxcd/flux/blob/v1.20.2/go.mod#L34). I wasn't able to pinpoint in its changelog exactly when or if this particular issue was resolved, but I did find some references to potentially related fixes introduced in more recent versions:
- https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#sdk-bugs-18
- https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#sdk-bugs-4

Some more information:
- [AWS announced support for IMDSv2 in Aug 24, 2020](https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-eks-supports-ec2-instance-metadata-service-v2/) - https://github.com/aws/containers-roadmap/issues/930
- [AWS user guide to configure blocking access to IMDS for pods not running on the host network using HTTP put response hop limit](https://docs.aws.amazon.com/eks/latest/userguide/best-practices-security.html) - might be relevant

**Comment by dtandon** [comment]
This is the critical feature for us. look forward to get some update for the same

**Comment by squaremo** [comment]
So far as I can tell, the AWS SDK currently used Flux does support IMDSv2 -- the relevant PR is https://github.com/aws/aws-sdk-go/pull/2958 (I deduce this from the title of a linked issue https://github.com/aws/aws-sdk-go-v2/issues/437, but frankly, it's not very well signposted :-( ). That was released in aws-sdk-go 1.25.something, and Flux already uses 1.27.something.

I can update the version of aws-sdk-go -- it builds cleanly -- but I'm not sure it will fix the reported problem.

**Comment by squaremo** [comment]
If you want to see if updating the AWS SDK helped, the prerelease build image docker.io/fluxcd/flux-prerelease:master-e065c88d has this change.

So far as I can see, there's no different way to use the SDK that makes it use IMDSv2 rather than v1. So if updating the SDK doesn't solve things, I would propose that the problem doesn't lie in how Flux uses the SDK.

**Comment by raviranjithkumar** [comment]
> If you want to see if updating the AWS SDK helped, the prerelease build image docker.io/fluxcd/flux-prerelease:master-e065c88d has this change.
> 
> So far as I can see, there's no different way to use the SDK that makes it use IMDSv2 rather than v1. So if updating the SDK doesn't solve things, I would propose that the problem doesn't lie in how Flux uses the SDK.

Ok sure @squaremo. I will try with  docker.io/fluxcd/flux-prerelease:master-e065c88d and update.

**Comment by kingdonb** [comment]
@raviranjithkumar Were you able to get this working? The commits referenced above are in master since Jan 19, flux v1.21.2 release is imminent now (#3421) now which will include the change. It would be good to get confirmation if this issue is resolved by them before publishing the next release! 😄

**Comment by raviranjithkumar** [comment]
@kingdonb @squaremo  Sorry for the delay in response. I have tested with docker.io/fluxcd/flux-prerelease:master-e065c88d but no luck. Still i'm getting the same error.

**Comment by kingdonb** [comment]
OK. I think this same conversation is perhaps being had on the Flux 2 side, or if we're lucky has already been resolved there.

It will help us get to resolution faster if we can track down a working example that does use IMDSv2, for comparison.

**Comment by kingdonb** [comment]
May be related #3409

**Comment by swade1987** [comment]
I managed to fix this by adding the following setting to our KIAM agent configuration 

```
# Ref: https://github.com/uswitch/kiam/issues/359
      allowRouteRegexp: "/latest/*"
```

I then had to wait for all KIAM agent pods to restart, then delete all flux pods in the cluster for the issue to be resolved.

**Comment by kingdonb** [comment]
I will make sure to mention this in the release notes, though I am not sure how we can resolve it in Flux. I understand it requires a KIAM update to v4.0 and a config change (as @swade1987 mentions.)

The other alternative is to enable the flag to allow hostnetwork as in #3409, which is a non-starter for serious use.

**Comment by kingdonb** [comment]
If there is a documentation change that can resolve this, I am unfortunately not in a position to be the one to write it, as I am not using AWS or any sort of cloud-provider-based pod (or cluster-wide) identity provisioning with Flux v1.

I am hoping that someone in the eksctl team has been able to provide a fix for AWS users.

If anyone was affected and has a better understanding of the fix, or what documentation updates we could add, I'm all ears.

But given there is no action I can see which is needed from Flux at this time, I'm closing this for now.
