### ISSUE TITLE
Flux time outs on bulk update of workloads

### ISSUE THREAD

**Issue by pavel-spacil** [fluxcd/flux#3385]
**Describe the bug**

We are calling flux's REST API endpoint `/api/flux/v9/update-manifests` directly to update multiple workloads in a bulk, not just to produce single commit with changes but also to speed up the operation. Concrete, we call lock and unlock operations for all workloads (~20) in given namespace. We have also SOPS in place for secrets.
But the update job fails on timeout regularly. Tried 4 mins and based on job log flux got to 2/3 of workloads. After some investigation what's going on under the hood I've found out that for every workload flux calls all generator commands from `.flux.yaml` file, that means decrypting all secrets and calling `kustomize build` all the time in a loop. That takes a lot of time and seems unnecessary to me.
I want to avoid manual update of `flux-patch.yaml` file and triggering the update as it brings another layer of issues to the topic. 

**To Reproduce**

Steps to reproduce the behaviour:

1. Have flux in k8s cluster with bunch of automated workloads
2. Have SOPS and call the `sops --decrypt` together with `kustomize build` as generator commands in `.flux.yaml`
3. Call REST API to lock/unlock all automated deployments
4. Watch created job for progress

**Expected behavior**

Job should finish successfully in timely manner, workloads are locked and git commit was pushed

**Logs**

Logs say nothing special:

```
ts=2020-12-11T08:03:37.973421752Z caller=loop.go:142 component=sync-loop jobID=cd73ce43-be1c-44e2-0bd6-4783ea127472 state=in-progress
ts=2020-12-11T08:07:38.036036093Z caller=loop.go:152 component=sync-loop jobID=cd73ce43-be1c-44e2-0bd6-4783ea127472 state=done success=false err="error executing generator command \"cmd\" from file \".flux.yaml\": context deadline exceeded\nerror output:\n\ngenerated output:\n"
```

**Additional context**

- Flux version: 1.20.0
- Kubernetes version: 1.18.9
- Git provider: github
- Container registry provider: AWS ECR

**Comment by kingdonb** [comment]
I think this is an architectural issue that is addressed in the redesigned Flux v2.

Flux v1 takes one git repository with one or more paths, and as I understand it, each commit either applies successfully or fails as a singular atomic change. This potentially takes longer and longer as a collection of manifests continues to grow in size. Adding additional generator steps in `.flux.yaml` slows this down even further, so Flux applies can start to fail under what I assume isCPU pressure. (To suggest a fix inside of Flux v1, you might try increasing the CPU request or limit to see if this process can complete in a reasonable amount of time...) but to be clear, it is an architectural issue with the design of "one flux per repo," when the repo grows larger and larger, the sync execution time will grow with it.

In Flux v2, cluster admins are encouraged to break up collections of manifests across the logical groupings that make sense for your cluster (eg. one or more `Kustomizations` mapped to one or more `GitRepositories`) such that the controllers can synchronize them one at a time. This way the syncs can be kept small enough to better guarantee they will complete within a reasonable timeout. When a given Kustomization grows too large, the solution is clear, to break it into more smaller Kustomizations. This resolves the issue without any need for vertical scaling, and without additional controllers.

This architectural change provides a number of additional benefits, for example it's now possible to ensure that CRDs are applied before the applications or HelmReleases that may depend on them, using `dependsOn` to order Kustomizations can prevent more predictable errors like this. I hope this helps!

**Comment by kingdonb** [comment]
Thanks again for the detailed report with enough information to repro the issue. I wonder if you were able to resolve this with my advice from the previous reply:

> try increasing the CPU request or limit to see if this process can complete in a reasonable amount of time

... or if you can report that you've been able to upgrade successfully to Flux v2, that will be helpful information as well.

If this issue is blocking you from adopting Flux, I can still provide further assistance. The recommendation in my last post was to try moving to the new version of Flux 2, since the architecture is designed to address scaling problems such as this one. A new release of Flux v2 is pending today, which may address certain issues that you have had in the past if you attempted to migrate but were stopped from migration by missing features. The documentation and support for use cases keeps growing to support the diverse implementations in use by members of the Flux community.

If there is something else that we can do to support your use of Flux, (v1 or v2), please do let me know and we can reopen, or work with you on a new issue report if this situation is no longer a problem for you. Closing as I have heard no response.

**Comment by pavel-spacil** [comment]
Suddenly I did not have a chance to work more on the project where this flux issue was present. We were considering also some workarounds, like direct modification of patch file, but none got applied. 
The CPU was fine in the pod, it just took a time to call `sops` for many secrets multiple times, increasing the limits did not help much. I went thru the code and did not find any kind of pre/post actions which may help here a lot. 
We need to do some research about possibility of upgrade to v2.
Thanks anyway for your time and valuable comments here.

**Comment by yebyen** [comment]
Thanks for your reply. I'd be willing to help characterizing the performance issue if you have time. It might be something we can fix by applying more resources somewhere else, but I suspect the core maintainers have done their homework and the rearchitecture is going to turn out to be the solution that presents the least pain.

Please let us know if there's anything more that we can do to help!
