### ISSUE TITLE
when i excute fluxctl list-workloads -a,get errorlike this

### ISSUE THREAD

**Issue by dachen2020** [fluxcd/flux#3389]
![image](https://user-images.githubusercontent.com/76671032/103198132-8e4c1a80-4922-11eb-9794-877c27f71bd3.png)

anyone the same problem?

**Comment by kingdonb** [comment]
The error message suggests a problem in one of your manifests, or something that was duplicated. Without access to your manifests it will be difficult to narrow the issue. Did you perhaps manage to resolve this on your own, @dachen2020 ?

**Comment by kingdonb** [comment]
I did not hear back from the submitter after requesting some additional information to help troubleshoot the issue.

Closing. Please post again if you believe there is a bug, or in case you still require assistance resolving this.
