### ISSUE TITLE
Flux not applying yaml files to the cluster 

### ISSUE THREAD

**Issue by sooranatesh** [fluxcd/flux#3402]
Hi,

I installed Flux in one of the namespaces of Openshift cluster. When i am giving the command fluxctl sync --k8s-fwd-ns "flux installed namespace"

it says :

Synchronizing with ssh://git@github.ibm.com/$organisation/$repo
Revision of master to apply is bf85aa1
Waiting for bf85aa1 to be applied ...
Done.

but it's not applying the yaml to the cluster, the yaml is a namespace yaml

apiVersion: v1
kind: Namespace
metadata:
labels:
name: testing-flux
name: testing-flux

Kindly help !

**Comment by kingdonb** [comment]
At a glance, I can't tell if your yaml is valid because it is not shown with space-significant formatting, you can use the ``` markdown to ensure the spacing is preserved in your comments.

Here is a valid Namespace yaml generated by `kubectl create`:

```
$ kubectl create namespace --dry-run=client testing-flux -oyaml
```

The yaml output:
```
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: testing-flux
spec: {}
status: {}
```

Can you kindly double check two things:

1. does your yaml include "name" field, properly nested under "metadata" section?
2. does your yaml include the "name" field twice? In your paste, it looked like it might have been duplicated.

In case either of these does not shed light on the problem, can you add the log output of flux to a gist and share the link?

```
$ kubectl logs -n flux deployment/flux
```

**Comment by kingdonb** [comment]
Cannot pursue the issue without further information from the submitter, closing for now.

If you believe there is a bug or need further assistance, please post a follow-up and we can reopen.
