### ISSUE TITLE
WIP: Flux Daemon/Chart 1.21.2 Release Planning

### ISSUE THREAD

**Issue by kingdonb** [fluxcd/flux#3418]
There is a need for new release to include #3401 at least, (which has already been merged since 1.21.1, but not yet in a release.)

I want to include also #3409, ~#3221~, #3325, #3293, #3161

Others that are hope to include, but may need further review first: #3282, #3406 (#3296), ~#3216~ #3407, #3302, #3316, #3229,

This is not a final review nor is this list necessarily exhaustive, it is a work in progress

I will use this issue report to stage and plan before completing reviews, then edit here and build into the changelog for 1.21.2. If your issue or PR is not mentioned but needs attention for the next release, please link it here in a comment.

(Some of these above may not make it, so if your issue is very important to you, please also welcome to post here even if it is already mentioned above.)

**Comment by stefanprodan** [comment]
I think you want #3407 as #3216 is closed.

**Comment by stefanprodan** [comment]
Also #3221 is closed.

**Comment by kingdonb** [comment]
Thanks, that is right, my checklist is somewhat out of date. I have the Triage role now which will make organizing much easier hopefully without need for heavyweight spreadsheet anymore. I meant to include #3138 as well, if it will help smooth transition for people who are using envsubst in flux2, to have the similar feature support made available in Flux v1.

(That is, unless it won't be used... I considered that by including the `envsubst` feature in Flux v2, perhaps now means it won't be necessary to have it added in v1 anymore. @stevehipwell ?)

**Comment by kingdonb** [comment]
Most of the PRs I mentioned haven't made it to release. I opened #3421 which closes this.

PRs which were not able to be included in 1.21.2 can still be considered for 1.21.3 (or 1.22.0). Thanks for everyone who made contributions in code or discussions! I am closing this, now discussion can continue on #3421.
