### ISSUE TITLE
create a giant warning banner on flux v1 docs

### ISSUE THREAD

**Issue by alisondy** [fluxcd/flux#3422]
Suggestion

place a giant warning banner on  the top of old flux docs, similar to what kubernetes does see this image

![Screen Shot 2021-02-10 at 14 01 19](https://user-images.githubusercontent.com/19580905/107519783-909fc680-6ba8-11eb-8805-98aa26858166.png)

New users may accidentally follow tutorials on the wrong docs, getting halfway through a tutorial and then realizing it's for a different version of flux.

---

I was browsing this page

https://docs.fluxcd.io/en/1.21.1/tutorials/get-started/#set-up-flux

After doing a google, for a flux guide, and i thought initially that it was the flux v2 docs,

But it wasn't until I looked at the flux-get-started repo that I was looking at docs for an old version of flux 🤦‍♀️

**Comment by dholbach** [comment]
https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#announcement-bar maybe?

**Comment by dholbach** [comment]
If we enable this globally, we can maybe revert https://github.com/fluxcd/flux/pull/3419?
