### ISSUE TITLE
flux-write-check pipeline randomly fails 

### ISSUE THREAD

**Issue by kmaounis** [fluxcd/flux#3424]
I am recently using flux 1.21 in gitlab with additional gitlab CI pipelines.

Although I see that flux successfully creates a tag `flux-sync` and my pipeline is running successfully I get random failures of the `flux-write-check` pipeline.

Inside my pipeline I see 
```
Preparing environment
Running on runner-<...> via runner-<...>-gitlab-docker-machine-...
Getting source from Git repository
Fetching changes with git depth set to 50...
Reinitialized existing Git repository in /builds/<...repo path here>/.git/
fatal: couldn't find remote ref refs/tags/flux-write-check-efc373bfe2
Uploading artifacts for failed job
ERROR: Job failed: exit code 1
```

First of all , I can not find a commit efc373bfe2 in my git history. Second I thought it was because the git depth is set to 50 but I have doubts that this is the case.

Any ideas on why flux-write-check fails randomly ? is that important or I can ignore it since I see the flux-sync tag?

**Comment by kingdonb** [comment]
Is your flux severely resource constrained, or git repository very large?

Scaling issues are being addressed en banc by the whole development team for the new Flux v2, which is fast approaching feature parity now. I can help you try to diagnose the issue if it is critical or blocking you, Flux v1 remains in maintenance and will continue to be supported for some 6 months or more after feature parity and GA/1.0 are declared.

The `efc373bfe2` that you found does not correspond to any git commit, it is a bit of pseudo-randomness that is added here: https://github.com/fluxcd/flux/blob/a194e2fcd1e5e39dbce74e5370133c7ffc147233/pkg/git/operations.go#L114-L115

If it cannot be reproduced reliably then it will be harder to diagnose and debug. You may be experiencing a less-severe case of the conditions reported in #3075. There is a timeout when flux-write-check tag is created, and if success is not reported before the timeout completes, the tag is left behind without being cleaned up. There may be other surprise error conditions that can lead to this too. It is safe to delete.

**Comment by kmaounis** [comment]
Thank you for your feedback. 

No, it is not critical nor blocking.   
I will check and clean up my repo a bit and monitor the behavior . The connected issue might help. I will close this for now then.
