### ISSUE TITLE
Search engine results direct to some old, broken docs

### ISSUE THREAD

**Issue by derTobsch** [fluxcd/flux#3426]
see https://docs.fluxcd.io/en/1.21.1/references/helm-operator-integration.html 
e.g. but other versions are also affected.

Googled with https://www.google.com/search?channel=fs&client=ubuntu&q=fluxd+helm+operator+example

**Comment by kingdonb** [comment]
I do not completely understand how the docs are deployed, and how the release history is maintained in url slugs with the release tag. Is it a feature of readthedocs?

I've reached this error page before through the same link, and I'm familiar with the fact that it shows up in Google results with the wrong extension, chopping off the '`.html`' at the end of the URL makes it a good link again. I'm not super clear on how Google prioritizes this, or if this means we broke the docs at this version in particular (why it only shows up on this one version?)

I think the solution is to push over this release with a fixed up version of this doc, but I'm not familiar with the inner workings of the CI just yet enough to know where to find these, or which parts are done as SaaS from readthedocs.

**Comment by kingdonb** [comment]
I've been trying to reproduce the search result that includes the page having an `.html` extension and I have not.

I wonder if it's been resolved already. The nearest I can do to reproduce is: https://www.google.com/search?q=fluxd+helm+operator+example+helm+operator+integration

The top link it provides back is: https://docs.fluxcd.io/en/1.18.0/references/helm-operator-integration.html

(In that version, the `.html` extension is apparently OK.)

**Comment by kingdonb** [comment]
When searching with `&q=fluxd+helm+operator+example` what I see now is, Google tries to autocorrect this to `fluxcd` 👍 and the link from top comment on this issue report no longer gives me any reference to that broken `references/helm-operator-integration.html` from Version `1.21.1` – I have not yet processed the next release, will watch for changes in this Google result over the next few days.

The good news is I can't find that broken link anymore in search results. The bad news perhaps, one of the top results is still pointing at that `1.18.0` release from three minor versions ago. @derTobsch if nothing has changed for you, then I may have to concede that we have different Google juice and I might not see what you see with my logged in account.

**Comment by dholbach** [comment]
This is why the URL schema changed somewhat:
- 1.18.x used sphinx: https://github.com/fluxcd/flux/blob/release/1.18.x/docs/requirements.txt
- 1.19.x moved over to mkdocs: https://github.com/fluxcd/flux/blob/release/1.19.x/docs/requirements.txt

**Comment by hiddeco** [comment]
I have hidden al versions prior to the `1.21.2` release from today, resulting in the following `robots.txt`: http://docs.fluxcd.io/robots.txt

**Comment by dholbach** [comment]
https://www.google.com/search?q=site:docs.fluxcd.io+html still gives me 161 results - maybe let's review that in a week and repeat the same with helm-operator? WDYT?

cc @alisondy (you were interested in this as well)

**Comment by hiddeco** [comment]
We could speed things up by signing up for [Google Search Console](https://search.google.com/search-console/), but that would require some work to verify that we have ownership over the website.

It would in general be good practice (for this and future websites), as it will show you insights in search traffic and how Google sees the website.

**Comment by hiddeco** [comment]
Fixed the broken HTML links by enabling `Sphinx HTML -> HTMLDir` redirects, this fixes the links to the latest documentation in the warning showed on pre-mkdocs documentation pages, e.g.: https://docs.fluxcd.io/en/1.17.1/references/monitoring.html

**Comment by kingdonb** [comment]
I can confirm the broken link from the original report is a valid URL now, thanks @hiddeco for providing a resolution! 🥇
