### ISSUE TITLE
Move off of peter-evans/link-checker GH action

### ISSUE THREAD

**Issue by dholbach** [fluxcd/flux#3430]
Move off of peter-evans/link-checker GH action, it's been replaced with https://github.com/lycheeverse/lychee-action

I tried using lychee, but it finds lots of broken links, a few false-positives. So this will need work. Do we maybe just want to remove link checking for now?

**Comment by kingdonb** [comment]
We might not want this issue to close with #3432 - wdyt?

I personally think we should do link checking on the live site, with some CI, and possibly alerting when links become bad (or when sites we reference start to 503 above a certain threshold)

It will be difficult to do proper link checking in CI without actually having the docs deployed somewhere temporarily as part of the CI process.
