### ISSUE TITLE
Describe a framework for manifest generation (migration guide for Flux v2)

### ISSUE THREAD

**Issue by kingdonb** [fluxcd/flux#3433]
Providing a solution for manifest generation, even documenting an external solution that works in tandem with Flux to provide similar capabilities to the `.flux.yaml` manifest generation feature from Flux v1, is absolutely a priority for the Flux team so that all users can follow us from Flux v1 to Flux v2. The newly redesigned Flux v2 is basically at feature parity for what we commit to include as features of Flux v2, but this feature is not included. But we can understand this is still an important use case.

Some features in the newly released Flux v2 0.8 include `envsubst` support and I am working on a new tutorial guide for how to implement manifest generation to a target branch or directory, S3 bucket, or Helm Release, for your Flux v2 cluster apps. This is meant to be implemented as a process on your CI of choice, so user feedback is essential to gather early in the process, as it will depend on your CI solution how such provisions can be implemented. (This issue is a stub for that effort for now.)

Github Actions seems like a natural choice because it can provide directly a git token that never leaves the git provider's purview. It is at less risk of compromise since the access authorization is not shared across different systems, it is all GitHub.

Other CI solutions will need to be granted access to write to a git repository (or one of these others) in order to facilitate the solution. If folks are interested in supporting other CI providers with documentation and experimentally verifying the workflow with your specific use cases, that might be distinct or unique from my own interpretation of how this feature is used, I am interested to hear from you. WIP

**Comment by seh** [comment]
One aspect in which I'm particularly interested is support for generating—and then applying—manifests that are not committed to the VCS. That is, treat the manifests as derived artifacts that some generation procedure projects from sources committed the VCS. In the past I've used tools like Jsonnet, CUE, _kustomize_, and _kpt_ for this purpose, in some cases wrapped in Bazel targets that produce updated manifests when the necessary inputs change.

I recognize that it's _simpler_ for Flux to know only how to consume committed sources. Being able to handle generated sources that we don't have to commit would allow many more integration paths.

**Comment by kingdonb** [comment]
Thank you for the feedback @seh. I will do my best core maintainer impersonation and try to explain the position, as this is not something I can decide, I'm a junior member on the team and still learning my way around. It's not only that it makes things simpler, it is a security consideration and it is also a fundamental idea in the architecture that we want to work with, not against. Applying manifests that do not come from a source provides significant new opportunities to complicate support.

To clarify and redirect, I was hoping to get someone to respond with a specific preference. "I want to use [eg. Jsonnet] for manifest generation, and my CI platform is [eg. Jenkins]. Adding a separate branch where these generated manifests can be published on the way to deployment is not a deal-breaker for us. Please include this specific request in your examples!"

I will be publishing a bevy of examples soon and it will be extremely helpful to know my audience so I can target the specific examples that will actually get used by real live users who have not been able to convert their implementations from Flux v1 to Flux v2 yet, because of this change.

Planning to try to follow a format of "if you did XXX in Flux v1, now you can do YYY in Flux v2 instead," again with specific examples targeted to specific tooling choices, rather than broadly one-size-fits-all "plug in your specific details here." If there are specific problems that arise with a specific tooling choice, then we can address them directly without complicating the general case – like for example, many of these tools export their generated manifests in the form of a single document list. If one tool doesn't do this, this will complicate things slightly since something has to prune any manifests that are missing now. We can start with simple examples that don't have as many things to trip over, and build up to more complicated ones.

I have squelched some of my response to avoid re-litigating the decisions of Flux v2 or rehashing things which we cannot change here, that have already been decided. My goal is to demonstrate the best approaches to do manifest generation while living within the new constraints. I hope that I can show how any of these tools you mentioned can still be used with Flux v2... but it unfortunately complicates my responding with an example, to have mentioned not just one preferred tool, but a list of tools without sharing any preference or favor for one specific tool that you're still counting on using today.

Could you provide another response with more information in this direction? Is there a specific CI and manifest generation tool combination that you need an example for, and would it be OK to create a separate "deploy" branch where generated manifests go (or do you work with multiple envs in your `fleet-infra` repo, such that using just one "deploy" branch won't fit?)

I want to make sure I can provide realistic examples so if there's something you would trip over, I want to make sure my example replicates that complexity sufficiently in order to totally enable your migration. That's the type of collaboration I'm hoping to open up on this issue. Thanks again for being the first to respond @seh 👨‍💻

**Comment by kingdonb** [comment]
Some of the stuff I left out for brevity (I have a tendency to write a wall of text, sorry): Flux (v2) does not run arbitrary binaries provided by an initContainer; Kustomize controller does not do manifest generation with any tools other than Kustomize or `envsubst`. This is a design constraint that helps to provide guarantees about error reporting and security, as well as supportability. We could say "sure, attach any arbitrary binary that you want, but then you are no longer running Kustomize controller and we cannot support it directly." This is not particularly helpful though, I don't think it's what you're asking for, and I don't know what it buys (other than perhaps adding a more direct upgrade path from `.flux.yaml` that also replicates many of the old problems, observability, things extra difficult to diagnose when an error happens in there somewhere, etc.)

Flux can apply manifests from any `Source` implementation in the Source API. It need not be one single VCS that drives your infrastructure. A separate "deploy" repository or branch can be hooked up to Flux by adding another `GitRepository`. If it's the semantics of interacting with a GitRepo from CI that has you troubled, you can use another `Source` implementation, like `Bucket`. If you have misgivings about reaching outside of the cluster, you can host a bucket internally with Minio, generate, and publish your generated manifests to that bucket, where Source Controller can apply them from.

Minio/S3 bucket provided as an example. These are all variations I hope to show, as long as there is someone who will prefer to use them, but I hope I can leave out the examples that nobody will use. I'm trying to find out who will use what by asking, this approach is somewhat limited of course because nobody can reliable tell you what is wrong with your solution or specific implementation before you have presented it... so the approach will have to be iterative and I'll be gathering lots of feedback.

I appreciate your responding and I don't want to scare anyone away by preaching the dogma of GitOps Toolkit and Flux v2.

**Comment by kingdonb** [comment]
There is fluxcd/flux2#1083 now WIP but mostly there.

This example is for GitHub Actions to write back to Git, both in the same repo and to a different repo.

I hope to finish this example soon. I'm pretty happy with the way it's shaping up now! I'd say it's about 80% of the way.

**Comment by kingdonb** [comment]
If you looked at fluxcd/flux2#1083 when I posted it 4 days ago, it has grown a bit since then. There is now back-story and more descriptive text explaining why this example, and who needs each example.

(Some of the examples are only throw-away, like `sed -i` for example, but others could turn out to become a permanent part of your infrastructure, like Docker Build and push workflow from the GitHub Actions Marketplace.)

There is a placeholder for a Jsonnet example, which I plan on figuring out today, then asking for reviews to hopefully merge this into Flux v2 documentation, (and finally closing this issue.) This could all happen by tomorrow, but that's very optimistic, I think it will more likely take about two weeks from today.

**Comment by bob-rohan** [comment]
@kingdonb thanks for documenting your progress. My thoughts on similar stuff  https://github.com/fluxcd/flux2/discussions/745#discussioncomment-534220

Plain old kustomize, no helm for internal artefacts - currently.

**Comment by yebyen** [comment]
@bob-rohan (this is kingdon b)

I am working on a few more examples for this and I am nearly ready to push them up. Handling secrets and/or replication of encrypted secrets across namespaces is an intended use case that I plan to cover, but I have considered that in some cases it should happen outside of the cluster, maybe not even in CI (or in others, be handled by a tool-for-the-job like kubed)

I haven't completely understood your secret generation use case and don't think it will be covered by any of the 3 examples I have planned to add currently. It would be good to get your feedback directly, since I really want these examples to be realistic and to cover actual living users use cases as well as possible.

Can I reach you on slack later, or another way if you prefer, to run some of these ideas by you? (I'll be back in the saddle in about two hours or less, currently at the vet 🐕🩺👩‍⚕️) feel free to DM me, or we can start a thread in #flux where others can participate as well?

**Comment by bob-rohan** [comment]
Surething, weave-community.slack.com I presume. Will ping you there

**Comment by kingdonb** [comment]
Subscribers to this issue, please consider reviewing fluxcd/flux2#1200 as it is basically complete and should be merged soon.

If you are interested in using Jsonnet or GitHub Actions and you have time to check out this tutorial, I will appreciate your review and feedback.

If Jsonnet or GH Actions is not your preferred platform for CI or Manifest Generation toolkit, we would like to produce more of these guides. So far we are considering adding Jenkins and `jkcfg` as possible variants. Feel free to reply with your favorites, if you would like to see them represented in a similar guide. ✍️
