### ISSUE TITLE
is there any way to used flux only for scanning image repo and update to git only and not deploy to cluster?

### ISSUE THREAD

**Issue by packdhe** [fluxcd/flux#3443]
Hi Every one, is there any way to used flux only for scanning image repo and update to git only and not deploy to cluster?
I want to used flux for update the git automatically when new  image release. but for deployment to kubernetes cluster i want to used approval step like used keel.

Thank you

**Comment by kingdonb** [comment]
I think you'll be interested in fluxcd/flux2#870

This is the Flux v1 repo, it does not have this feature but arguably when used together with Flagger and with Manual Gating, it does: https://docs.flagger.app/usage/how-it-works#canary-analysis

As Flux contrib efforts have been focused on Flux v2, we have developed a support policy page with references to how community works in our new architecture for Flux v2, with more different ways to meet and engage with us for help. If you've been following our development efforts then of course we hope you are able to upgrade, if you are still on Flux v1.

Here's more info on how to find support with that: https://fluxcd.io/support/ - tl;dr: the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2) - the Migration Guide begins [here](https://toolkit.fluxcd.io/guides/flux-v1-migration/)!

**Comment by kingdonb** [comment]
The direct answer is, no, Flux requires a Kubernetes cluster to operate and it will crash without one. You cannot run the Flux automation without making any deployments.

If you want to use Flux to update a staging cluster, and let the production cluster be upgraded by a pull request, this is certainly something you can use to get close to what you asked for, but it is currently very much a manual process to do this.

This discussion in Flux v2 is also related: https://github.com/fluxcd/flux2/discussions/952 - so there is some support for the idea in the current stages of development, but it is only in the Proposal stage.
