### ISSUE TITLE
Flux V2  fluxcd.io/ignore: equivalent

### ISSUE THREAD

**Issue by SimplySeth** [fluxcd/flux#3479]
Greetings.

Is there an equivalent to ` fluxcd.io/ignore: true` in flux v2?

Or how would one ignore  a manifest in v2 ?

Thanks.

**Comment by kingdonb** [comment]
Equivalent, no – the equivalent would be if there was another annotation that you can place on the YAML manifest to exclude, it is not going to work this way anymore.

This function has moved into `spec` of GitRepository:

https://fluxcd.io/docs/components/kustomize/kustomization/#generate-kustomizationyaml

> This expects all YAML files present under that path to be valid kubernetes manifests and needs non-kubernetes ones to be excluded using .sourceignore file or spec.ignore on GitRepository object.

The manifests must be excluded in the Source resource, by setting `spec.ignore` on the repository Spec, or by using the `.sourceignore` file inside the repo content.

**Comment by kingdonb** [comment]
Hope this helps, I think this can be closed!
