### ISSUE TITLE
Flux Pulling Many Unused Images Constantly

### ISSUE THREAD

**Issue by mhoppe-cedar** [fluxcd/flux#3516]
In the flux logs we see many images being pulled that we do not use.

Ex.
`ts=2021-07-29T01:47:07.454344466Z caller=repocachemanager.go:226 component=warmer canonical_name=index.docker.io/library/traefik auth={map[]} err="toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" ref=traefik:windowsservercore-1809`

**To Reproduce**

Steps to reproduce the behaviour:

1. Flux-0.6.3
2. We have excluded docker.io.
3. We have upgraded docker account and have the imagepullsecret set with auth creds.

**Expected behavior**

Not all these polls for unused images which are slowing down deployments for up to 45 minutes.

**Comment by kingdonb** [comment]
What version is Flux-0.6.3?

I'm not sure how you've installed Flux, but this makes me skeptical about the details of the report. Can you provide more details about the installation method and options passed?

Was this installed using Helm?

**Comment by yebyen** [comment]
Please have a look at the Flux V1 FAQ:

https://fluxcd.io/legacy/flux/faq/#migrate-to-flux-v2

The guidance under the heading "Flux v1 behavior doesn't scale well" explains in some detail what is going on here.

I don't know if you are aware but Flux v1 is in maintenance mode, and Flux v2 has as one of the main changes that it no longer pulls image metadata as part of the image automation feature.

**Comment by mhoppe-cedar** [comment]
My goodness I did not read the v2 info yet. Thank you so much for pointing this out!

**Comment by mhoppe-cedar** [comment]
@ kingdonb I did not do the initial installation, but I do see some evidence it may have been done using helm. Thank you for raising this.

**Comment by kingdonb** [comment]
Thanks for the report.

I see there was a chart tag version 0.6.3 published in February 2019. This corresponds to Flux Daemon v1.10.1. While that's quite a bit behind the current release, I'm nonetheless quite impressed that it has apparently served you well thus far, for the most part at least!

The latest release of Flux v1 is some 12 or 13 minor versions ahead of this now. It may be more challenging to migrate from Flux v1.10 directly to Flux v2. You may get relief from bugs by upgrading first to Flux 1.23.1, (or 1.23.2 which is due out early next week.) This should be entirely straightforward and is likely to solve some issues for you, if you are seeing strange behavior like image ignores not being honored as expected.

I'm sure you'd find this on your own, but the new docs site for Flux v2 is at: https://fluxcd.io/docs/

There is also a migration guide:
https://fluxcd.io/docs/migration/flux-v1-migration/

Helm Operator is covered too, in a follow-on guide, if you are also using that. The new version of Helm Operator is Helm Controller, which is part of the whole renovated Flux v2 "gitops toolkit" suite.

You're welcome to join us for more support in the CNCF slack, #flux in case you have any difficulties with the upgrade.

**Comment by mhoppe-cedar** [comment]
Thank you so much for the guidance. Flux has been an amazing little dynamo for us here across several clusters.
