### ISSUE TITLE
--registry-include-image= not working with fluxctl 1.23.1

### ISSUE THREAD

**Issue by arunzco** [fluxcd/flux#3526]
--registry-include-image=

Error: unknown flag: --registry-include-images

and help only shows the following flags 

Flags:
      --add-security-context        Ensure security context information is added to the pod specs. Defaults to 'true' (default true)
      --git-branch string           Git branch to be used by Flux (default "master")
      --git-email string            email to use as git committer
      --git-label string            Git label to keep track of Flux's sync progress; overrides both --git-sync-tag and --git-notes-ref (default "flux")
      --git-path strings            relative paths within the Git repo for Flux to locate Kubernetes manifests
      --git-readonly                tell flux it has readonly access to the repo
      --git-url string              URL of the Git repository to be used by Flux, e.g. git@github.com:<your username>/flux-get-started
      --git-user string             username to use as git committer (default "Flux")
  -h, --help                        help for install
      --manifest-generation         whether to enable manifest generation
      --namespace string            cluster namespace where to install flux
  -o, --output-dir string           a directory in which to write individual manifests, rather than printing to stdout
      --registry-disable-scanning   do not scan container image registries to fill in the registry cache

Global Flags:
      --context string                  The kubeconfig context to use, will use your current selected if not specified
      --k8s-fwd-labels stringToString   Labels used to select the fluxd pod a port forward should be created for. You can also set the environment variable FLUX_FORWARD_LABELS (default [app=flux])
      --k8s-fwd-ns string               Namespace in which fluxd is running, for creating a port forward to access the API. No port forward will be created if a URL or token is given. You can also set the environment variable FLUX_FORWARD_NAMESPACE (default "default")
      --timeout duration                Global command timeout; you can also set the environment variable FLUX_TIMEOUT (default 1m0s)
  -t, --token string                    Weave Cloud authentication token; you can also set the environment variable WEAVE_CLOUD_TOKEN or FLUX_SERVICE_TOKEN
  -u, --url string                      Base URL of the Flux API (defaults to "https://cloud.weave.works/api/flux" if a token is provided); you can also set the environment variable FLUX_URL

**Comment by yebyen** [comment]
The scanning is performed in the daemon, not the fluxctl client. This option must be added to the flux daemon deployment (or through the helm chart) at install/deploy time.

**Comment by arunzco** [comment]
> 
> 
> The scanning is performed in the daemon, not the fluxctl client. This option must be added to the flux daemon deployment (or through the helm chart) at install/deploy time.

i was using the flag with fluxctl install

**Comment by kingdonb** [comment]
This option is only available in the Flux daemon. Over time, many options were added to the Helm chart installation method that are not all available in `fluxctl install`. It is acknowledged that the Flux v1 CLI install method, `fluxctl install`, may not cover every option in Flux v1. Please be aware also that [Flux v1 is in maintenance mode](/fluxcd/flux/issues/3320).

This feature is available in the Helm chart for Flux v1, as `registry.includeImage`:
https://github.com/fluxcd/flux/blob/32f9ab7daa523ce9c8f700253f39422b4377bff0/chart/flux/values.yaml#L185-L188

At this point, neither installation method of Flux v1 can be expected to cover every possible configuration, or is intended to provide the full "Swiss-army knife" experience. Helm provides a Post-Render feature, so chart authors can avoid releasing new versions of their chart for every last customization request that comes in, and chart consumers can build them ad-hoc.

The recommended installation method if you need to do something that is not supported in the Helm chart is to use Helm and Helm's post render functionality.

From the other end of this concern, Flux v2, which is a recommended upgrade for all users, has already added support for [PostRenderer](https://github.com/fluxcd/helm-controller/issues/104) via Helm Controller. No new features can be added to Flux v1 while we are in maintenance mode.

**Comment by kingdonb** [comment]
Please feel free to ask questions if you have them.
