### ISSUE TITLE
Flux doesn't update image from ECR after a new image was pushed

### ISSUE THREAD

**Issue by avdeev-a** [fluxcd/flux#3529]
**Describe the bug**

I use Flux v2.  After a new docker images was build and pushed in to AWS ECR, flux did,'t update deployment image. The image tag is the same but hashes are different.

**To Reproduce**

Steps to reproduce the behaviour:

1. Install Flux for gitlab (with token)
`flux bootstrap gitlab \
  --components-extra=image-reflector-controller,image-automation-controller \
  --hostname=gitlab.local \
  --token-auth \
  --owner=platform  \
  --repository=kube-dev \
  --branch=main \
  --path=dev`
2. Run Gitlab pipeline to build docker images and push it into ECR.
3. Wait for image updates. 
4. Maybe i do something wrong?

**Expected behavior**

Update deployment image with a new hash and the same tag.

**Logs**
No errors in logs.

**Additional context**

- Flux version:  0.16.1
- Kubernetes version: 1.20
- Git provider: gitlab
- Container registry provider: aws ecr

**Comment by kingdonb** [comment]
Thanks for the report. This repo is for Flux v1.

Have you found the [image update guide](https://fluxcd.io/docs/guides/image-update/) for Flux v2? There are more steps than what you described here, you need to create `ImageUpdateAutomation` and ImageRepo as well as some other associated resources, then add ImagePolicy tags in comments to the YAML manifests that you wish to be updated.

**Comment by avdeev-a** [comment]
@kingdonb Thank you for updates! 
Closed.
