### ISSUE TITLE
Releasing an automated service, then having it reset is confusing

### ISSUE THREAD

**Issue by paulbellamy** [fluxcd/flux#356]
You should probably not be allowed to do (or warned when doing) a manual release to an automated service, and be told to deautomate it.

**Comment by squaremo** [comment]
See also `--force`

**Comment by philwinder** [comment]
Possibly boot, depending on how the new automation is implemented. E.g. Automation might just be the difference between a git commit of `HEAD` vs a specific commit id. Hence, automated/manual would be mutually exclusive.

**Comment by squaremo** [comment]
I think this'll still happen, so we should come up with the least surprising way of avoiding surprises ..

**Comment by kingdonb** [comment]
This issue has the distinguished honor of being Flux v1's oldest and most un-responded issue.

It continues to be a topic of the discussion pages on Flux v2 repo, yes it is still confusing in Flux v1, but disambiguated in the docs for the GitOps Toolkit by now, as explained through this discussion: https://github.com/fluxcd/flux2/discussions/936

Flux v2 makes this feature a little bit more inaccessible IMHO but if it is still something that we want to improve, we can open a PR on the fluxcd/flux2 repo for it. Closing this discussion for now, in favor of making such improvements in the next version.
