### ISSUE TITLE
Please release Flux helm chart 1.11.4

### ISSUE THREAD

**Issue by daiyinong** [fluxcd/flux#3581]
### Describe the bug

We would like to upgrade to flux 1.24.3 in our products but the latest flux helm chart still points to 1.24.2 at the moment so would really appreciate it if a new helm chart version can be released. Thanks!

### Steps to reproduce

https://github.com/fluxcd/flux/blob/cdd9c9b94201f1099120ea92799822a332859d1d/chart/flux/values.yaml#L12

### Expected behavior

a helm chart referring to flux 1.24.3 is available.

### Kubernetes version / Distro / Cloud provider

Azure kubernetes 2.30.0

### Flux version

1.24.3

### Maintenance Acknowledgement

- [X] I am aware of Flux v1's maintenance status

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kingdonb** [comment]
Thanks for the report! I'm releasing the chart version next as we speak, it must only pass the CI check which will be finished in about 15 minutes. I'm sure you are aware but Flux v1 is in maintenance mode and will not be supported forever.

We are asking all reports to consider upgrading to Flux v2, and offering free migration workshops to help it along.

If there is some particular issue that prevents your upgrade, would you consider filing an issue in the Flux v2 repo, or opening a discussion on our new GitHub discussion page? https://github.com/fluxcd/flux2/discussions

Thanks for using Flux! 🌪️ 🍞

**Comment by daiyinong** [comment]
Thanks! We're planning to migrate to flux v2 in the next few months and much appreciate your help.

**Comment by kingdonb** [comment]
Sorry, lost track of this in the middle of a busy day! :)

The release is inbound now, CI running again so that the release date in the CHANGELOG is accurate.

**Comment by kingdonb** [comment]
It is published. The PR will merge later, once CI completes this third time. 👍

**Comment by daiyinong** [comment]
Perfect, thanks again!
