### ISSUE TITLE
Flux is not confirmed. Flux is running with limited capabilities.

### ISSUE THREAD

**Issue by yousefbaagil** [fluxcd/flux#3601]
Hey everyone, 

I have been trying to set a VPS Nimbus and Cumulus nodes. Both are failing with the same message:

**Flux is not confirmed. Flux is running with limited capabilities.**

Anyone knows how can I fix this? 

I have asked the VPS server service provider ( Contabo) to increase the SSD and they did based on their recent response. however, nothing has changed and still nodes are not functioning well. 

Thanks in advance.

**Comment by kingdonb** [comment]
This repo is not related to $FLUX the cryptocurrency, (you are on FluxCD)
