### ISSUE TITLE
automate --all

### ISSUE THREAD

**Issue by paulbellamy** [fluxcd/flux#399]
To automate all services. Need to figure out how to show this in the UI and cli. and what it means for new services, and deleted services.

**Comment by paulbellamy** [comment]
No need for an `--except` or `--exclude` flag, as if you want to keep a service at a version you could `lock` it.

**Comment by philwinder** [comment]
When moving to gitsync, the commit will specify whether we automate all or not. I.e. `HEAD` vs. specific commit hash.

**Comment by squaremo** [comment]
> When moving to gitsync, the commit will specify whether we automate all or not. I.e. HEAD vs. specific commit hash.

This issue relates to automated image releases, rather than automated synchronisation.

**Comment by squaremo** [comment]
@geoah Am I right to interpret what you're describing as a kind of automation on/off switch?

That's different to the original proposal, which was to have a shortcut to annotating all workloads with "flux.weave.works/automation: true" -- but it's also well-motivated and plausible as a feature.

**Comment by geoah** [comment]
Basically either force automation on/off and ignore the annotation.
Or alternatively set the default automation if the annotation os not set.

**Comment by tomjohnburton** [comment]
Any more movement on this?

**Comment by 2opremio** [comment]
Not a priority right now, but we accept PRs!

**Comment by kingdonb** [comment]
Flux v1 is in maintenance mode now, and is not adding any new features unless they are critical.

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.
