### ISSUE TITLE
Idea: Universal bash script to install flux

### ISSUE THREAD

**Issue by philwinder** [fluxcd/flux#412]
Create a bash script that is able to install the latest release of fluxctl, and optionally install a standalone version or a cloud based version of flux.

This would benefit users by making the install process much simpler.

**Comment by dholbach** [comment]
#1363 #1377 weaveworks/homebrew-tap#2 are looking at the `fluxctl` portion of this.

**Comment by kingdonb** [comment]
I can see that `fluxctl` is installable through brew (linuxbrew/homebrew) and updating the binary in brew is part of the regular release CI process. So also is the new `flux` cli for Flux v2, not sure what else remains for this issue so I am closing it!

🐰 Thanks for using Flux!
