### ISSUE TITLE
Watch kubernetes, instead of requesting info every time.

### ISSUE THREAD

**Issue by paulbellamy** [fluxcd/flux#46]
I suspect this will speed up responses to the cli quite a lot.

**Comment by squaremo** [comment]
@paulbellamy Would using a caching client in the daemon accomplish this?

**Comment by paulbellamy** [comment]
probably

**Comment by paulbellamy** [comment]
but you'll still have the latency on the first request. Using something like a ListWatcher will pre-fetch all the k8s data, so even the initial request will be speedy.

**Comment by paulbellamy** [comment]
We should upgrade to k8s go-client when we do this.

**Comment by squaremo** [comment]
We are much better at assembling results these days (after #139 was resolved), to the point that API requests are not a limiting factor.

**Comment by bboreham** [comment]
I see fluxd polling my kubernetes API server twice every 10 seconds, for every resource type and namespace.  It would place a lot less load on the servers if this was a 'watch'.

**Comment by squaremo** [comment]
@bboreham PRs welcome.

**Comment by stevenpall** [comment]
Hey, I was wondering if any work has been done to improve API server polling of late? I've been seeing a decent increase in `LIST` operation latency since implementing Flux on January 8th.

<img width="1352" alt="screen shot 2019-01-28 at 10 44 49 am" src="https://user-images.githubusercontent.com/2805687/51858782-62fdc280-22ea-11e9-9a0c-bc260817fa71.png">

**Comment by squaremo** [comment]
Making a cache for each workload type is probably do-able, though rather fiddly when limited to particular namespaces (or by RBAC).

The new sync code (in #1442) will end up looking at every API resource during a sync. Caching that would be rather trickier, but we can cut down on the resources checked.

**Comment by stefanprodan** [comment]
Flux v2, based on the [GitOps Toolkit](https://toolkit.fluxcd.io), is using the informer cache for all read operations.
