### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by awh** [fluxcd/flux#548]
Once we have completed the re-architecting of flux, much of the security guarantee relies on the auditability of the fluxd source; if our builds are reproducible, security conscious end-users can consume our binary builds with complete confidence.

https://blog.filippo.io/reproducing-go-binaries-byte-by-byte/

**Comment by kingdonb** [comment]
Greetings! Flux v1 is in maintenance and Flux v2 is rapidly narrowing the gap towards 100% feature parity with the original v1, but if Flux v1 has not yet made the builds 100% reproducible, I'm afraid it likely won't happen after now.

Hopefully this is possible for [Flux v2](/fluxcd/flux2), I have not spent time to evaluate reproducibility of builds there as of yet, but the new design is broken into micro-services and operators which each do an even smaller job than Flux v1, so if there were specific obstacles to reproducible builds, maybe they can be addressed better now?

If you think this issue should be revisited for components of the newly re-architected Flux v2, please let us know.
