### ISSUE TITLE
UI for bulk changes

### ISSUE THREAD

**Issue by awh** [fluxcd/flux#635]
This morning I had to deautomate and rollback cortex in dev, resulting in a string of separate commits; additionally, the operations had to be done manually in sequence waiting for the each one to sync before moving onto the next. Instead, the UI could allow the construction of a change spec consisting of an arbitrary mix of policy changes & image updates, and commit/sync them in a single operation.

**Comment by squaremo** [comment]
I suppose the the requirement _here_ would be for the API to support being sent an arbitrary set of amendments. Then the CLI and web UI can take advantage of that.

**Comment by awh** [comment]
Yes - it makes me wonder if `UpdateImages` and `UpdatePolicies` should in fact be collapsed into a single general purpose function.

**Comment by awh** [comment]
Or some kind of API for starting & commiting 'transactions'...

**Comment by squaremo** [comment]
> Yes - it makes me wonder if UpdateImages and UpdatePolicies should in fact be collapsed into a single general purpose function.

They are, in the daemon protocol, though it could be more general (you can only supply one update at a time).

> Or some kind of API for starting & commiting 'transactions'...

It might take a bit of thought and experimentation to get this right, but git could help us here. For example, one could start a topic branch, make changes onto that, then squash it into a commit or submit it as a PR or whatever.

**Comment by squaremo** [comment]
Just being able to specify multiple images to `fluxctl release --all ...` would be a great start wrt our own use of flux.

**Comment by rade** [comment]
@rndstr does the new  /v9/update-manifest API help with this?

**Comment by rndstr** [comment]
`/v9/update-manifest` can be used to update policies, images, or specific containers. but it is not possible to combine them in a single call.

for the case of reverting multiple deployments at once, the `containers` spec would help but we still need a CLI to pass in the specification. supporting multiple images as mentioned by @squaremo in combination with `--interactive` would allow you to selectively skip containers that weren't part of the initial release. that only works if all the containers with the same image were on the same version/tag, though.

**Comment by kingdonb** [comment]
New developments around this type of functionality are happening in the [image-automation-controller](/fluxcd/image-automation-controller) for Flux v2.

Closing, as Flux v1 is in maintenance mode.
