### ISSUE TITLE
Monitor SSH private key for change

### ISSUE THREAD

**Issue by awh** [fluxcd/flux#649]
If the Kubernetes secret containing the SSH private key is updated externally, the change is eventually (potentially after several minutes) reflected inside the container tmpfs mount. We should monitor for this event with inotify and update fluxd state accordingly.

**Comment by squaremo** [comment]
Do we not use the SSH key by referring to the file?

**Comment by awh** [comment]
The private key yes; the public key & fingerprints are extracted from the private key and kept in memory.

**Comment by squaremo** [comment]
It's possible the rewrites have fixed this; review at some point.

**Comment by dholbach** [comment]
Is there a simple test-case for this?

**Comment by squaremo** [comment]
> Is there a simple test-case for this?

 1. Start fluxd and let it generate an SSH
 2. Ask for the public key with `fluxctl identity`
 3. Generate a fresh key locally, and overwrite the secret that's mounted in fluxd
 4. Wait for ten minutes so Kubernetes has had copious time to update the file in the container
 4. Ask for the public key again -- did it change to reflect the key change?

**Comment by dholbach** [comment]
I used `kubectl exec <..> -- sh` and `ssh-keygen -t -rsa -f <..>` to update the key. The output of `fluxctl identity` after waiting 10 mins was the same as before.

**Comment by squaremo** [comment]
What were the exact arguments to `ssh-keygen`, and did you do anything else?

**Comment by dholbach** [comment]
Only this:

```sh
[daniel@reef flux (⎈ |minikube:default)]$ kubectl exec -it flux-7bf686479d-5xqt4 -- sh
/home/flux # ssh-keygen -t rsa -f /var/fluxd/keygen/..weave-keygen473400537/iden
tity
Generating public/private rsa key pair.
/var/fluxd/keygen/..weave-keygen473400537/identity already exists.
Overwrite (y/n)? y
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /var/fluxd/keygen/..weave-keygen473400537/identity.
Your public key has been saved in /var/fluxd/keygen/..weave-keygen473400537/identity.pub.
```

**Comment by smartpcr** [comment]
I also had same problem, after patched k8s secret `flux-ssh`, then run `fluxctl identity`, it returns old public key

**Comment by stefanprodan** [comment]
Flux v2, based on the GitOps Toolkit does monitor the SSH secret and uses the latest version every time it runs a git action.
