### ISSUE TITLE
Run build step before syncing

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#651]
Some config repos may have a build step to generate configuration. For example, we generate a ConfigMap from Promethus alert/rule specification. It'd be good to be able to run this at some point so that the generated files are taken into account.

At which point? The most obvious is after pulling a new version of the repository.

How to run it? It's going to depend very much on the repo in question! But possibly we can overcome that by somehow using a container they add to the pod. Somehow.

NB if the things generated are yamels we want to alter when doing releases, this is going to cause problems. In our case, we don't generate deployment yamels; but it's easy to imagine someone doing so.

**Comment by jml** [comment]
We actually want to generate more than just the Prometheus ConfigMap this way. It's actually the first, prototypical step in generating _all_ of our configurations.

Other approaches I can think of:
  1. Store the generated files in git
  2. Encourage users who want to do this to run generation in their CI and somehow push the results to Weave Cloud / flux

**Comment by squaremo** [comment]
> Encourage users who want to do this to run generation in their CI and somehow push the results to Weave Cloud / flux

This seems like TRTTD. We want to operate on the output of CI as much as possible (if we can't operate directly on checked-in files), so we're getting artefacts that have been passed through automated testing and built in a standard environment. It takes that latter concern out of Flux's hands, where it arguably does not belong.

The next question is: what is it that CI would output, and how would that make its way to Flux? One simple answer is that everything should be driven by images; so, bundle all the built config into an image and get Flux to treat that specially (sync from that instead of from git). Not using git would be a pretty big change, mind you.

**Comment by jml** [comment]
As the potential author of such a hook, I'd much rather post my YAML directly to flux. Building a Docker image seems like an usually cumbersome way of sharing a tarball.

**Comment by awh** [comment]
> As the potential author of such a hook, I'd much rather post my YAML directly to flux
What value is flux adding, if your $CI is watching the git repo and pushing config with a webhook? It might as well just push it straight to kubernetes...

**Comment by squaremo** [comment]
> As the potential author of such a hook, I'd much rather post my YAML directly to flux

Maybe. The rationale behind building an image is that it's a package for all the things you need to tell your cluster about. Might be more than one yamel, for example. Could be a tarball, it's just we have the machinery for dealing with images (pushing them, storing them in a registry, etc.). Marginal call.

> What value is flux adding, if your $CI is watching the git repo and pushing config with a webhook? It might as well just push it straight to kubernetes...

Well, it *keeps* the cluster in sync with what's in git. If you are just applying yamels when they get to the other end of CI, you're not really doing that.

But there are still a couple of requirements to answer here:

 1. What if your config is the product of a build process?
 2. What if you want your config to pass automated testing before being designated as the desired state of the cluster?

Building something in CI then sending it to Flux (effectively putting another step in the sync loop) can address these both, I think, though we'd have to be very careful about preserving the state that flux currently keeps in the upstream git repo.

**Comment by jml** [comment]
Contra image:
- building a docker image that contains generated files and uploading it is strictly more work than uploading generated files, with a whole other component (Docker) that can fail
- how do I inspect the generated YAML files?
- what is an image that doesn't contain an executable?

> 1. What if your config is the product of a build process?
> 2. What if you want your config to pass automated testing before being designated as the desired state of the cluster?

These are indeed our requirements. Note that for Weave Cloud itself, we already require our config to pass a lint checker before being merged to master.

Thinking about it, I'd be content to store the generated files in Git.

**Comment by jml** [comment]
This is bugging me a lot. If we could reach consensus on an acceptable design, I would like to try to fix this.

**Comment by boxcee** [comment]
See: https://github.com/fluxcd/flux/issues/3264
