### ISSUE TITLE
Cross-over of syncing and image updating 

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#676]
A user de-automated something expecting that to also stop it being synced.

We have the ability to stop resources being synced (by giving them the "ignore" annotation). One problem here is that it's not visible, and hence or otherwise, easily conflated with de-automation -- which you usually want to do at the same time.

I think we still want sync'ing and automated updates to be separate concerns, though they interact to some extent. We could do more to distinguish them (where they need to be distinct), and to support workflow that involves them both, e.g., as in the above.

**Comment by squaremo** [comment]
"Automate" & "Deautomate" are not the best verbs for what those entail, although I think we'd probably need a compound verb to get the right idea across. In any case, now it's not the only thing Flux is doing (not even the main thing, arguably), they need, at the least, better explanation and labeling in UI.

**Comment by kingdonb** [comment]
I think this can be closed as it is well and fully resolved by the redesign in Flux v2.

Image automation is imposed through the use of ImageUpdateAutomation and ImagePolicy markers. Source synchronization can be set to `suspend` in eg. `GitRepository` source, and cluster reconciliation can be set to `suspend` on `Kustomization` or `HelmRelease` resources.

There is no longer any central monolith which users who have understood the redesign can expect to invoke stopping all automations at once, so these concerns are no longer conflated.
