### ISSUE TITLE
Change Freeze Button

### ISSUE THREAD

**Issue by bboreham** [fluxcd/flux#748]
This would be a single button for a whole environment that had the effect of locking all automated deployments, and perhaps adding an "are you sure" phase to manual changes.

Further enhancement would be to schedule future freezes, e.g. the week before Xmas.

**Comment by stefanprodan** [comment]
Flux v2, based on GitOps Toolkit has support for suspending the cluster reconciliation https://toolkit.fluxcd.io/components/kustomize/kustomization/#reconciliation
