### ISSUE TITLE
Deal with multiple tags referring to the same image layer, and moving tags

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#822]
Many library images have tags that track e.g., major versions. That means any given image pushed will have two or three tags that refer to it; e.g., `{alpine:2, alpine:2.3, alpine:2.3.4}`.

We do in general know that these are the same, since the manifests refer to the image layer hash.

By the same token, we could know when e.g., a `":latest"` image is different, since we can check the image layer hash from Kubernetes (or given in the manifest), against the one we see in the image registry.

**Comment by sambooo** [comment]
Deal with them how?

**Comment by squaremo** [comment]
> Deal with them how?

Exactly.

**Comment by kingdonb** [comment]
Current releases of Flux v2 are moving away from knowing more about the image layers.

This feature will not make the cut in Flux v1.
