### ISSUE TITLE
connect to multiple upstreams

### ISSUE THREAD

**Issue by rade** [fluxcd/flux#832]
Flux can be told to connect to an upstream service with the `--connect` and `--token` options.

For testing, it would be useful to be able to connect to multiple upstream services.

**Comment by rade** [comment]
A typical flux `--connect` looks like `--connect wss://cloud.weave.works/api/flux`.

In Weave Scope, upstreams can be specified as `https://<token>@<host>`, so perhaps here we could support multiple `--connect` options like `--connect wss://<token1>@cloud.weave.works/api/flux --connect wss://<token2>@frontend.dev.weave.works/api/flux`.

Tokens in `--connect` would override any specified `--token`.

**Comment by rade** [comment]
A stepping stone, in case that is easier, would be to have 1 "proper" upstream and 0..n read-only upstreams.

**Comment by stefanprodan** [comment]
Flux v2, based on the GitOps Toolkit has support multiple notification providers https://toolkit.fluxcd.io/guides/notifications/
