### ISSUE TITLE
convenient rollback

### ISSUE THREAD

**Issue by rade** [fluxcd/flux#854]
ATM flux offers no convenient way to roll back to a previously deployed version of a resource. The closest one can get is to inspect the history of the manifest for the resource in git, and then update git with a selected older version. That actually isn't so bad, as gitops goes, but a more convenient CLI/UI would be helpful.

**Comment by squaremo** [comment]
> ATM flux offers no convenient way to roll back to a previously deployed version of a resource.

If you want to roll back arbitrarily, I'm not sure how we can do better than showing the list of versions, then letting you release one of them.

`fluxctl` could make this interactive ("type the number of the version you want to release"). I'm not sure this would be worth the trouble, though.

**Comment by rade** [comment]
> I'm not sure how we can do better than showing the list of versions,

I would want to see _which versions were deployed when_.

**Comment by squaremo** [comment]
The API could also give more context on what has happened to a controller or resource, to make the job of picking where to roll back to easier.

In git terms, we can show the history of changes to a resource (probably -- multidoc files make this tricky). In image terms, if images are labelled we may be able to show some build information.

**Comment by alwaysastudent** [comment]
If there is any error on any resources while doing a sync, there should be a way to automatically sync from the previous git sha. The sync and rollback should be atomic and not per resources

**Comment by kingdonb** [comment]
Please let me know if you still need help with this. I apologize for the staleness of this reply, we are in the process of cleaning up stale issues from the Flux v1 repo now, this should be over soon.

In Flux v2, the kustomize controller enables validation and atomic applies. If some resources failed to validate according to the client or server validation that you requested, then the whole commit will not be applied. This is a better story for Flux v2. More granular control over rollback behavior is also available within Helm Controller.

I will close the issue for now as it is stale. Flux v1 remains in maintenance mode.

We can provide support to Flux v1 users especially with respect to migrating to the new Flux version, which has some breaking changes but is also a total rewrite and also brings many improvements. I'm closing the issue but you are most welcome to write back on this issue, or open another issue. Thanks for using Flux.
