### ISSUE TITLE
fluxd is slow to terminate

### ISSUE THREAD

**Issue by foot** [fluxcd/flux#863]
On minikube + osx.

Maybe this issue isn't so high priority if it doesn't happen to anyone else.

Use case: While onboarding and configuring fluxd for the first time it takes at least one restart, perhaps more to get the configuration correct. This takes 30 seconds which is a bit slow and users can get a bit frustrated in the UI.

**Comment by foot** [comment]
More details:

- It disconnects from flux-svc
- It moves into the terminating state according to kubectl, but then sits there for 30s.

```
kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS        RESTARTS   AGE
kube-system   kube-addon-manager-minikube             1/1       Running       0          4m
kube-system   kube-dns-6fc954457d-b2rfd               3/3       Running       0          4m
kube-system   kubernetes-dashboard-b92nn              1/1       Running       0          4m
kube-system   weave-flux-agent-754895b668-79hpv       0/1       Terminating   0          3m
kube-system   weave-flux-memcached-67984b4c46-sr67m   1/1       Running       0          3m
```

**Comment by foot** [comment]
This is the version served up the launch-gen on fdww.

**Comment by squaremo** [comment]
It's not terminating when asked with `TERM`, so it sits around for 30s until Kubernetes loses patience and uses `KILL`. We do have code to respect the first signal and gracefully terminate -- but it apparently doesn't work.

#866 fixes that problem at least for when the daemon is waiting to be able to clone the git repo, which is the typical state while onboarding.

**Comment by kingdonb** [comment]
I will close the issue for now as it is stale. Flux v1 remains in maintenance mode.

We can provide support to Flux v1 users especially with respect to migrating to the new Flux version, Flux v2, which has some breaking changes but is also a total rewrite and also brings many improvements. I'm closing the issue but you are most welcome to write back on this issue, or open another issue. Thanks for using Flux.
