### ISSUE TITLE
Incorrect commit message when there's an ignored resource due to be updated

### ISSUE THREAD

**Issue by samb1729** [fluxcd/flux#894]
When an automated release happens (that is to say actual changes made in the repo), if there's an ignored resource that _would_ have been updated had it not been ignored, it'll still be included in the commit message.

How I think this can happen:
1. User has resource A running image `foo:1`, and resource B running image `bar:1`, both automated
2. User ignores resource B using `fluxctl` or weave deploy
3. New image `bar:2` released
4. Automation loop detects this image but it's eventually not applied because of the ignore annotation. At this point the erroneous calculation is hidden because no commit is created.
5. New image `foo:2` released
6. Automation loop calculates a change to both A and B, but only A is changed because of B is ignored.
7. The commit message is built from the calculated change, instead of what's actually changed in the yamls, so it says something like `Automated release of new images foo:2, and bar:2` which is wrong.

[Concrete example](https://github.com/weaveworks/service-conf/commit/03f70077d81b5e4d648eb2afcb8a0d0dbef1d86e)

**Comment by kingdonb** [comment]
At this time, we hope you have already begun migration away from Flux v1 / legacy over to the [current version of Flux](https://github.com/fluxcd/flux2).

We hope you've been able to upgrade to Flux v2, and note that Flux v1 remains in maintenance mode. Bugs with Flux v1 can be addressed as long as it remains in maintenance, according to the plan laid out in the [Flux Migration Timetable](https://fluxcd.io/docs/migration/timetable/). 👍 

Thanks for using Flux.
