### ISSUE TITLE
Deployment does not highlight any departure from a tag filter

### ISSUE THREAD

**Issue by rbruggem** [fluxcd/flux#901]
Human error can cause the deployment of the wrong image unintentionally.
It would be nice if flux would highlight any departure from a particular tag filter, for instance `master-*`.

**Comment by kingdonb** [comment]
Not sure how this can be implemented based on the description provided.

Flux either enforces the policy (and remediates any departure from policy by setting the image back to which one is appropriately selected by the given policy) or it is in non-automated mode (and remediates any departure to the value written in the git repository, setting the pod image back to whatever is written in the git repos without respect to any policy.)

Flux v2 has a whole new approach to image reflection and automation: https://toolkit.fluxcd.io/components/image/controller/ 

We hope you will upgrade to Flux v2 and help us verify the 100% feature parity, by letting us know if Flux v2 has any regression or departure from the optimal manifestation of your particular use cases. The redesigned Flux should be at or above feature parity for any given use case, with many improvements across the board for common uses of Flux.

Thanks for your report!
