### ISSUE TITLE
Serialise the various lock annotations in a single `lock` annotation

### ISSUE THREAD

**Issue by dlespiau** [fluxcd/flux#905]
At the moment we have 3 annotations for locking:

```
"flux.weave.works/locked": "true"
"flux.weave.works/locked_msg": "this is locked because reasons: $link_to_issue"
"flux.weave.works/locked_user": "Foo Bar <foo@weave.works>"
```

A common pattern is to serialise a json object in an annotation.  If we wanted to add the timestamp of the lock operation for instance, we wouldn't have to create another `locked_timestamp` annotation.

A potentially good way to do it would be to define a new annotation, say `flux.weave.works/lock`, which could look like `{ "locked": true, "msg": "...", "user": { "email": "...." } }` and have code to migrate the old style to the new one. If we always migrate first, we may be able to remove the code checking for `locked`, `locked_msg`, `locked_user`.

**Comment by sambooo** [comment]
From https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/:
> The metadata in an annotation can be small or large, structured or unstructured, ...

I don't think we need to serialise JSON for this, we can just store a yaml map as the value of the annotation.
