### ISSUE TITLE
Integration test in test/bin/test-flux has rotted

### ISSUE THREAD

**Issue by jpellizzari** [fluxcd/flux#919]
Repro steps:
1. Run `make integration-test`
2. Wait for it to time out

Expected:
It finishes

Actual:
It times out. Pod logs show `git clone: fatal: Could not read from remote repository.`

Root cause:
After #892, ssh config is written loaded into the container image from disk. In the integration test, we mount the `known_hosts` file to the `/root/.ssh` directory:
https://github.com/weaveworks/flux/blob/master/test/flux-deploy-all.yaml#L86

This overwrites the directory and nukes the ssh_config, which contains the location of the identity file mounted at /etc/fluxd/ssh/identity: https://github.com/weaveworks/flux/blob/master/docker/ssh_config

Setting `StrictHostKeyChecking no` and removing the `volumeMount` works around the issue, but that won't work long term.

Kubernetes issue: https://github.com/kubernetes/kubernetes/issues/51165
Possible working configuration (although it is a slightly different use case): https://github.com/dshulyak/kubernetes.github.io/commit/d58ba7b075bb4848349a2c920caaa08ff3773d70

**Comment by jpellizzari** [comment]
The fix should be to figure out how to mount the `known_hosts` file without writing over the entire `/root/.ssh` directory.

**Comment by squaremo** [comment]
https://github.com/weaveworks/flux/pull/921 fixes that initial problem; there are others though, so it's not complete.

**Comment by ncabatoff** [comment]
I gave up trying to get this working without making substantial changes, so I rewrote it in Go, see [flux-tester](http://github.com/ncabatoff/flux-tester) for details.  I'm open to merging it back into this repo but I'm operating under the assumption that if you had wanted it done this way you would've done so.

**Comment by jpellizzari** [comment]
I did have the bash one working in this branch: https://github.com/weaveworks/flux/tree/824-parse-list

**Comment by kingdonb** [comment]
This was removed a while ago, in 58f8d0adfcb0cb5176d240c7abec5a622e17085a
