### ISSUE TITLE
Document how to use with H(orizontal)P(od)A(utoscaler)

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#924]
HPAs modify the replicas of a Deployment; this will fight Flux unless you leave the replicas field out of the manifest (hat tip to @stefanprodan for figuring this out).

**Comment by kingdonb** [comment]
This is fixed via #1688 and #1686

https://fluxcd.io/legacy/flux/faq/#how-can-i-prevent-flux-overriding-the-replicas-when-using-hpa

The same information is mentioned in the current version of Flux docs, but it is under a different heading:

https://fluxcd.io/docs/faq/#what-is-a-kustomization-reconciliation
