### ISSUE TITLE
Document troubleshooting CI pipelines

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#925]
In particular:

 - why does my Travis-CI pipeline keep getting run (A: might be because it builds tags by default, including the tag flux updates; see https://docs.travis-ci.com/user/customizing-the-build/#Safelisting-or-blocklisting-branches for a remedy)

**Comment by squaremo** [comment]
- how to stop CI from building in a feedback loop: developer commits code change -> CI build -> new image -> flux commits config change -> CI build -> ...

**Comment by kingdonb** [comment]
https://fluxcd.io/legacy/flux/faq/#why-does-my-ci-pipeline-keep-getting-triggered
