### ISSUE TITLE
Idea: Add sentry error reporting to flux

### ISSUE THREAD

**Issue by leth** [fluxcd/flux#964]
Users may on occasion experience errors, but do not always have the time or inclination to report them to us.
Automated error reporting would capture errors which might normally go unreported, helping us to spot errors in the wild, and hopefully fix them!

We've added sentry error reporting to the [launcher](https://github.com/weaveworks/launcher) project.

**Comment by sambooo** [comment]
If this is added it should be explicitly opt-in when using standalone Flux, imo. We shouldn't default to exporting potentially sensitive errors without the users' informed consent.

**Comment by kingdonb** [comment]
I am a fan of Sentry and would merge this if it was submitted as a PR.

However, I do not currently have the time to implement it on my own without outside help. Closing.

Flux v1 is in Maintenance Mode.
