### ISSUE TITLE
Work with GCP repositories

### ISSUE THREAD

**Issue by bricef** [fluxcd/flux#986]
Some users wish to use Flux with their [GCP source code repositories](https://cloud.google.com/source-repositories/). This is made difficult because GCP only accepts HTTPS connections.

This _might_ work if we added the username/password pair in the url, but is not desirable.

In addition, the username and password from google need to be created using an interactive OAuth flow with their `gcloud` command line sdk.

It may be possible to sort this out directly by talking to the GCP source API.

**Comment by bricef** [comment]
## Possible workaround
GCP source repository can be used to [mirror repositories from Github and Bitbucket](https://cloud.google.com/source-repositories/docs/connecting-hosted-repositories). Flux will work with either of these services, so it would be possible to make it work using mirroring and with Flux acting on the other repsitory.

**Comment by jantoebes** [comment]
You can still use the ssh url/authentication @bricef and add the authentication key to the gcp repository?

**Comment by kingdonb** [comment]
Flux v1 is in maintenance mode now, and is not adding any new features unless they are critical.

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.
